/* Working Mate — English (reference + fallback for all languages) */
window.I18N = window.I18N || {};
window.I18N.en = {
  /* ───────── 首页 HOME ───────── */
  "home.nav.capability": "Capabilities",
  "home.nav.features": "All Features",
  "home.nav.workflow": "Workflow",
  "home.nav.models": "Models",
  "home.nav.pricing": "Pricing",
  "home.nav.console": "Console",
  "home.nav.login": "Sign in",

  "home.hero1.eyebrow": "v1.4 released · Local-first multi-model AI Agent",
  "home.hero1.h1": "Make AI <span class=\"glow\">actually work</span><br>instead of just chatting",
  "home.hero1.sub": "Local Ollama and cloud LLMs on one scheduler; node-based workflows chain scripts, storyboards, video and music into a single pipeline. Four-layer memory learns you over time, your data stays on-device, and it runs offline.",
  "home.hero1.stat1": "Models supported",
  "home.hero1.stat2": "Data shared",
  "home.hero1.stat3": "Self-evolving memory",
  "home.hero1.cta1": "Free download · Free tier",
  "home.hero1.cta2": "See workflow demo",

  "home.hero2.eyebrow": "Workflow · Node canvas",
  "home.hero2.h1": "Drag &amp; drop<br>to build an <span class=\"glow\">AI pipeline</span>",
  "home.hero2.sub": "Script → storyboard → video shots → background music, all in one run. Preview every step, re-run a single node, and drop in custom cards or local assets.",
  "home.hero2.stat1": "Domain experts",
  "home.hero2.stat2": "Ready templates",
  "home.hero2.stat3": "Drag &amp; use",
  "home.hero2.cta1": "Open workflow",
  "home.hero2.cta2": "Watch 60s demo",

  "home.hero3.eyebrow": "v1.4 · Limited launch offer",
  "home.hero3.h1": "Mid-year sale<br>use it <span class=\"glow\">forever</span> for $0",
  "home.hero3.sub": "The free tier is yours forever with unlimited local models. Paid tiers unlock longer memory, flagship models and cloud generation quota.",
  "home.hero3.stat1": "Starting · Free",
  "home.hero3.stat2": "Standard",
  "home.hero3.stat3": "Team · Planned",
  "home.hero3.cta1": "Download now",
  "home.hero3.cta2": "See changelog",

  "home.float.assist": "AI Assistant",
  "home.float.service": "Human support",
  "home.float.sales": "Sales",

  "home.cap.tag": "Capability",
  "home.cap.h2": "One client, your whole AI workspace",
  "home.cap.c1t": "Local + cloud hybrid routing",
  "home.cap.c1d": "Use Ollama locally when offline, switch to cloud flagships automatically when online. Swap models mid-conversation.",
  "home.cap.c2t": "17 domain experts collaborate",
  "home.cap.c2d": "Give it a goal and AdminAgent splits subtasks, assigns the right expert, and merges the results.",
  "home.cap.c3t": "Four-layer memory",
  "home.cap.c3d": "Resident facts, session archive, skill library, and user profile.",
  "home.cap.c4t": "Skills auto-crystallize",
  "home.cap.c4d": "Flows that work get extracted into reusable skills automatically.",
  "home.cap.c5t": "Real file work",
  "home.cap.c5d": "Read/write docs and spreadsheets, run scripts, drive windows.",

  "home.feat.tag": "All Features",
  "home.feat.h2": "All features, click to see details",
  "home.feat.p": "Every card opens a full page: what it does, how to use it, and the technical highlights.",

  "home.wf.tag": "Workflow",
  "home.wf.h2": "Drag repetitive flows into a pipeline",
  "home.wf.i1t": "Free drag &amp; connect",
  "home.wf.i1d": "Organize flows like building blocks; change one step without redoing the rest.",
  "home.wf.i2t": "Preview every step",
  "home.wf.i2d": "Text, images, video, audio — click a node to see it.",
  "home.wf.i3t": "One-click templates",
  "home.wf.i3d": "AI shorts / music singles / concept art — ready-made flows built in.",
  "home.wf.memtag": "Memory",
  "home.wf.memh2": "It doesn't start from zero every time",
  "home.wf.mem.i1t": "No context loss on topic switch",
  "home.wf.mem.i1d": "Pick up last week's requests this week.",
  "home.wf.mem.i2t": "Flows turn into skills",
  "home.wf.mem.i2d": "The same job takes one sentence the second time.",

  "home.mem.l1t": "Resident memory",
  "home.mem.l1d": "The most critical facts and preferences, injected every turn.",
  "home.mem.l2t": "Session archive",
  "home.mem.l2d": "All history, retrieved by keyword hit count.",
  "home.mem.l3t": "Skill library",
  "home.mem.l3d": "Working flows auto-crystallize for reuse.",
  "home.mem.l4t": "User profile",
  "home.mem.l4d": "Communication style and domain knowledge accumulate over time.",

  "home.models.tag": "Models",
  "home.models.h2": "Pretty much every model you'd want",
  "home.models.m1": "Ollama local",
  "home.models.m2": "DeepSeek V4 Pro / Flash",
  "home.models.m3": "Qwen3.8 Max",
  "home.models.m4": "GLM 5.3",
  "home.models.m5": "Kimi K3",
  "home.models.m6": "Doubao Seed",
  "home.models.m7": "MiniMax M3",
  "home.models.m8": "SiliconFlow",
  "home.models.m9": "Alibaba Bailian",
  "home.models.m10": "Kling",
  "home.models.m11": "Suno music",
  "home.models.m12": "OpenRouter all",

  "home.price.tag": "Pricing",
  "home.price.h2": "Start free, upgrade when you need more",
  "home.price.free.name": "Free",
  "home.price.free.li1": "Unlimited local models",
  "home.price.free.li2": "Free OpenRouter models included",
  "home.price.free.li3": "Basic chat and file operations",
  "home.price.free.li4": "Contains ads · Community support",
  "home.price.free.cta": "Free download",
  "home.price.std.flag": "Most popular",
  "home.price.std.name": "Standard",
  "home.price.std.li1": "Value lineup: DeepSeek V4 Flash & friends",
  "home.price.std.li2": "Smart routing + context compression",
  "home.price.std.li3": "Vision and multimodal input",
  "home.price.std.li4": "Ad-free",
  "home.price.std.cta": "Upgrade to Standard",
  "home.price.pro.name": "Pro",
  "home.price.pro.li1": "Flagship Chinese lineup unlocked",
  "home.price.pro.li2": "Dual-channel failover (primary + fallback)",
  "home.price.pro.li3": "AI video / music generation",
  "home.price.pro.li4": "Bring your own API key",
  "home.price.pro.cta": "Upgrade to Pro",
  "home.price.ult.flag": "Coming soon",
  "home.price.ult.name": "Ultimate",
  "home.price.ult.li1": "Engineering-grade CAD (true B-rep solids)",
  "home.price.ult.li2": "STEP / DXF / STL export",
  "home.price.ult.li3": "Self-researched, cross-validated dimensions",
  "home.price.ult.li4": "Larger context and higher limits",
  "home.price.ult.cta": "Get Ultra",

  "home.faq.h2": "FAQ",
  "home.faq.q1": "Does it work offline?",
  "home.faq.a1": "Yes. Local Ollama models run fully offline — chat, file ops and workflow orchestration need no network.",
  "home.faq.q2": "Is my data uploaded?",
  "home.faq.a2": "No. Chat history, knowledge base and memory all stay on your machine.",
  "home.faq.q3": "What are the Free tier limits?",
  "home.faq.a3": "Free gives you all local capabilities and basic tools with an ad slot; cloud flagship models and AI video/music generation are paid.",
  "home.faq.q4": "Which systems are supported?",
  "home.faq.a4": "Windows and macOS. Mobile (Android / iOS / HarmonyOS) is planned.",

  "home.cta.h2": "Let AI start working now",
  "home.cta.p": "The free tier is forever, installs in a minute, no credit card needed.",
  "home.cta.btn": "Free download Working Mate",

  "home.foot.copy": "© 2026 Working Mate · Local-first AI workspace",
  "home.foot.privacy": "Privacy",
  "home.foot.terms": "Terms",
  "home.foot.refunds": "Refunds",

  /* ───────── 功能页共享 UI (FEAT-UI) ───────── */
  "feat.nav.features": "Features",
  "feat.nav.workflow": "Workflow",
  "feat.nav.models": "Models",
  "feat.nav.pricing": "Pricing",
  "feat.nav.download": "Free download",
  "feat.foot.copy": "© 2026 Working Mate · Local-first AI workspace",
  "feat.foot.features": "Features",
  "feat.foot.privacy": "Privacy",
  "feat.foot.terms": "Terms",
  "feat.foot.refunds": "Refunds",
  "feat.tpl.back": "Back to all features",
  "feat.tpl.what": "What it does",
  "feat.tpl.how": "How to use",
  "feat.tpl.tech": "Technical highlights",
  "feat.tpl.shot": "Take a look",
  "feat.tpl.related": "Related features",
  "feat.tpl.end": "Give it a try",
  "feat.tpl.endP": "The free tier is forever; local features work out of the box, no credit card needed.",
  "feat.tpl.endBtn": "Free download Working Mate",
  "feat.tpl.view": "View details →",
  "feat.tpl.heroCta1": "Try free download",
  "feat.tpl.heroCta2": "See other features",

  /* ───────── 功能数据 (FEAT-DATA) ───────── */
  "feat.models.title": "Multi-Model Hybrid Routing",
  "feat.models.tag": "Multi-Model Router",
  "feat.models.sub": "78 built-in models plus 14 China-direct platforms, all behind one input box. Primary and fallback channels run side by side — if one wobbles, the request moves to the other; offline, local Ollama takes over.",
  "feat.models.fact0": "78 built-in models",
  "feat.models.fact1": "OpenRouter + 14 China-direct channels",
  "feat.models.fact2": "Dual-channel failover",
  "feat.models.fact3": "Region-locked models auto-skipped",
  "feat.models.grid": "60+ models · local / cloud unified entry",
  "feat.models.what0t": "One input box, every model",
  "feat.models.what0d": "No API notes, no tab juggling. DeepSeek, Qwen, GLM, Kimi, MiniMax, Doubao, Hunyuan, Ernie, Grok and the full OpenRouter catalogue sit in one dropdown — alongside whatever you have pulled in local Ollama.",
  "feat.models.what1t": "Primary + fallback, both live",
  "feat.models.what1d": "OpenRouter is the primary channel; Qiniu Cloud or any China-direct platform you add is the fallback. If a channel rate-limits, returns 5xx, has no key, or goes down entirely, the request is handed to the same class of model on the other channel — your conversation never breaks, you just see 'switched automatically'.",
  "feat.models.what2t": "Region-locked models detected and skipped",
  "feat.models.what2d": "Some billing regions cannot reach OpenAI, Anthropic or Google closed models. At startup the client probes once with minimal requests (cost ≈ $0) and caches the result; locked models are badged '🚫 region-locked' in the dropdown and skipped by auto-routing, so no time is wasted on calls that are certain to fail.",
  "feat.models.what3t": "14 China-direct platforms, preset",
  "feat.models.what3d": "SiliconFlow, Alibaba Bailian, DeepSeek official, Volcano Ark, Zhipu, Kimi, MiniMax, Tencent Hunyuan, ModelScope, 302.AI, DMXAPI, AIHubMix, NVIDIA NIM, StepFun. Pick one and the base URL fills itself in — paste your key and you are done, no doc-copying.",
  "feat.models.what4t": "Local first, works offline",
  "feat.models.what4d": "With Ollama connected the app runs fully offline: chat, file operations and workflow orchestration need no network, and nothing leaves your machine.",
  "feat.models.what5t": "Five plans × purpose matrix",
  "feat.models.what5d": "Free / Standard / Pro / Ultra / Max unlock different model pools; models are tagged general / reasoning / code / vision / music, so the system picks by task type — or you pin any model manually.",
  "feat.models.step0": "Settings → Cloud models: fill in the keys for the channels you want (OpenRouter, SiliconFlow, DeepSeek official…). Each key unlocks that platform.",
  "feat.models.step1": "For offline use, start local Ollama — the client discovers local models automatically.",
  "feat.models.step2": "Pick a model in the top dropdown, or leave it on Auto — models missing keys or region-locked are skipped for you.",
  "feat.models.step3": "Entries marked '· fallback' take over automatically when the primary channel fails.",
  "feat.models.tech0": "One cloud_client abstraction: local, cloud and every China-direct platform share a single call signature — adding a platform is one base_url plus a key.",
  "feat.models.tech1": "Dual-channel routing: when the same model id exists on both channels (DeepSeek V4 Pro, GLM 5.3, Kimi K3…), the channel is chosen dynamically by which key you configured, weighted by channel priority.",
  "feat.models.tech2": "Keys never cross channels: a Qiniu key is never sent to OpenRouter — this fix eliminated a whole class of fake '401, key expired' errors that were really just an unconfigured channel.",
  "feat.models.tech3": "429 splits rate-limit from insufficient balance: rate limits back off using Retry-After, empty balance stops immediately with a top-up prompt; a 403 region block switches straight to the fallback model.",
  "feat.models.shot": "One input, local and cloud connected",

  "feat.experts.title": "17 Domain Experts Collaborate",
  "feat.experts.tag": "Expert Team",
  "feat.experts.sub": "Give a goal, AdminAgent splits it into subtasks, assigns the right expert, and merges into one result. No prompt writing, no manual breakdown.",
  "feat.experts.fact0": "17 domain experts",
  "feat.experts.fact1": "Auto split / assign",
  "feat.experts.fact2": "≤10 tool calls / subtask",
  "feat.experts.fact3": "Auto-merged results",
  "feat.experts.grid": "17 domain experts · auto split / assign",
  "feat.experts.what0t": "Brief it in one sentence",
  "feat.experts.what0d": "Say \"turn this Excel's 3-month sales into a trend chart and write an analysis\" — it splits into read → clean → chart → analyze and assigns.",
  "feat.experts.what1t": "17 domain experts",
  "feat.experts.what1d": "Research, video shorts, image design, music, trading, actuarial, solo-business, software architecture, AI, prompting, full-stack Codex, office, code, writing, data science, ops, general.",
  "feat.experts.what2t": "AdminAgent does the split",
  "feat.experts.what2d": "The主控 agent reads your goal → builds a subtask list (with dependencies) → dispatches each to the right expert.",
  "feat.experts.what3t": "Each expert carries its own model groups",
  "feat.experts.what3d": "Every expert binds reasoning / general / code model groups, plus image / video / music generation models where relevant. Model groups recompute when you change channel or plan, so an expert never stalls because its model became unavailable.",
  "feat.experts.what4t": "Specialist agent lineup (Max plan)",
  "feat.experts.what4d": "Deep research, autonomous coding, self-researching CAD modeling, short-drama storyboarding and music each get a dedicated model and workflow — large-context reasoning for research, code-specialist models for programming, top-tier reasoning for modeling.",
  "feat.experts.what5t": "Auto re-fit when a region blocks a model",
  "feat.experts.what5d": "If a bound flagship model is unavailable in your region, the system swaps in an available model of the same class and logs it, instead of erroring out.",
  "feat.experts.step0": "Turn on \"Agent Mode\" at the top.",
  "feat.experts.step1": "Describe your goal (the more specific, the better); no manual breakdown.",
  "feat.experts.step2": "The agent shows a subtask list first; confirm to start.",
  "feat.experts.step3": "You can emergency-stop anytime, and watch each subtask's status and artifacts.",
  "feat.experts.tech0": "Split and execution share one multi-model degrade chain; rate-limits won't crash the whole task.",
  "feat.experts.tech1": "A failed subtask only skips its downstream; other branches keep running.",
  "feat.experts.tech2": "Cross-space calls are capped (prevent loops) so experts can't ping-pong forever.",
  "feat.experts.tech3": "Failed parse of the split throws the real error instead of silently returning empty.",
  "feat.experts.shot": "Goal → subtasks → expert execution",

  "feat.memory.title": "Four-Layer Memory System",
  "feat.memory.tag": "Memory",
  "feat.memory.sub": "It does not start from zero every time. Key facts, past sessions, proven workflows, and your preferences all settle into four memory layers — and long chats roll up earlier turns into summaries, saving tokens without losing the thread.",
  "feat.memory.fact0": "4 memory layers",
  "feat.memory.fact1": "Chinese n-gram search",
  "feat.memory.fact2": "Rolling compression 4x+",
  "feat.memory.fact3": "Local SQLite storage",
  "feat.memory.grid": "4 memory layers · Chinese n-gram search",
  "feat.memory.what0t": "L1 Resident memory",
  "feat.memory.what0d": "The most important facts and preferences injected every turn. A capacity cap forces it to keep only the most valuable few.",
  "feat.memory.what1t": "L2 Session archive",
  "feat.memory.what1d": "All past sessions stored locally, recalled by keyword hit count, injected only when needed — no resident budget spent.",
  "feat.memory.what2t": "L3 Skill library",
  "feat.memory.what2d": "Proven flows auto-extract into reusable skills — the second time, one sentence replays the whole action.",
  "feat.memory.what3t": "L4 User profile",
  "feat.memory.what3d": "Communication style, domain knowledge, habits accumulate so replies feel more like talking to you.",
  "feat.memory.what4t": "Rolling context compression",
  "feat.memory.what4d": "Recent turns stay verbatim for coherence, earlier turns fold into an incremental summary. Measured: a 5,975-token conversation compressed to 1,401 tokens (4.3x) with nothing important lost.",
  "feat.memory.what5t": "No thread drops when topics change",
  "feat.memory.what5d": "Something you discussed last week is still there this week; switch topics and come back, the context is intact.",
  "feat.memory.step0": "Just chat normally; no manual \"remember.\"",
  "feat.memory.step1": "Sidebar \"Memory Files\" shows current L1 resident and L4 profile.",
  "feat.memory.step2": "\"Memory Cleanup\" clears one layer or deletes a session.",
  "feat.memory.step3": "To make it remember a hard rule, just state it in chat — it's judged a long-term fact.",
  "feat.memory.tech0": "Chinese uses 2-4 char n-gram with English tokenization to fix low whole-string LIKE hit rates.",
  "feat.memory.tech1": "L2 scores by hit count; auto-degrades to plain table + LIKE when SQLite FTS5 is unavailable.",
  "feat.memory.tech2": "Lightweight summaries skip the LLM, concatenating first/last turns to control cost.",
  "feat.memory.tech3": "Rolling compression keeps the last K turns verbatim plus incremental summaries of older turns, recycling the oldest content as the model's context window fills.",
  "feat.memory.shot": "Memory files, always inspectable & clearable",

  "feat.skills.title": "Skills Auto-Crystallize",
  "feat.skills.tag": "Self-Evolving Skills",
  "feat.skills.sub": "A flow you ran gets auto-extracted into a reusable skill in the library. Next time, one sentence reproduces the whole action.",
  "feat.skills.fact0": "Auto-extract flows",
  "feat.skills.fact1": "Central skill library",
  "feat.skills.fact2": "Local storage",
  "feat.skills.fact3": "Reusable & shareable",
  "feat.skills.grid": "Auto-extract flows · central skill library",
  "feat.skills.what0t": "Run once, becomes a skill",
  "feat.skills.what0d": "One complete flow (read → process → output) that works gets auto-extracted into a structured reusable skill.",
  "feat.skills.what1t": "Next time, one sentence",
  "feat.skills.what1d": "Just say \"do it like last time\"; it matches from the library and executes, no re-describing steps.",
  "feat.skills.what2t": "Skill library visualized",
  "feat.skills.what2d": "Sidebar \"Skill Library\" to browse, search, enable or delete existing skills.",
  "feat.skills.what3t": "Wired to four-layer memory",
  "feat.skills.what3d": "Skills belong to L3, sharing the same memory system with workflows and experts.",
  "feat.skills.what4t": "Failures don't pollute the library",
  "feat.skills.what4d": "Only flows that truly work get crystallized; half-failed ones aren't saved as skills.",
  "feat.skills.what5t": "Local storage",
  "feat.skills.what5d": "The skill library lives on your machine, not uploaded to the cloud.",
  "feat.skills.step0": "Let the agent finish a multi-step job as usual.",
  "feat.skills.step1": "On success, the system auto-extracts and stores the skill.",
  "feat.skills.step2": "Open the sidebar \"Skill Library\" to confirm (rename, delete).",
  "feat.skills.step3": "Next time reference the skill directly, or let the agent auto-match.",
  "feat.skills.tech0": "Skill extraction shares the same node/step model with the workflow engine.",
  "feat.skills.tech1": "Skills are stored as local files for easy backup and migration.",
  "feat.skills.tech2": "Separated from L1/L2 memory to avoid skill text crowding the resident budget.",
  "feat.skills.shot": "Skill library: crystallized on success",

  "feat.workflow.title": "Node-Based Workflow Canvas",
  "feat.workflow.tag": "Workflow Canvas",
  "feat.workflow.sub": "Chain AI like building blocks: drag nodes, connect, run. Each step previews, re-runs and edits its prompt individually — prompts you can write yourself or let AI write for you.",
  "feat.workflow.fact0": "10 node types",
  "feat.workflow.fact1": "Drag + auto-connect + auto-layout",
  "feat.workflow.fact2": "Single-node rerun",
  "feat.workflow.fact3": "Prompt DIY or AI-written",
  "feat.workflow.grid": "10 node types · drag + auto-connect + auto-layout",
  "feat.workflow.what0t": "10 nodes, full coverage",
  "feat.workflow.what0d": "LLM text, storyboard, AI image, AI video, AI music, video compose, tool node, text card, local image, local music.",
  "feat.workflow.what1t": "Drag + connect",
  "feat.workflow.what1d": "Drag from the left library onto the canvas, hold a node's right edge to its target to connect; or \"⚡ Auto Connect\" wires by type logic at once.",
  "feat.workflow.what2t": "Auto layout",
  "feat.workflow.what2d": "\"⌗ Auto Layout\" arranges by dependency into layers; one click reorders scattered nodes.",
  "feat.workflow.what3t": "Preview every step",
  "feat.workflow.what3d": "Click any node and the right panel shows its text / image / video / audio artifact with a player.",
  "feat.workflow.what4t": "Prompts fully DIY",
  "feat.workflow.what4d": "Every text param is a multi-line editor; supports {{node}} placeholders referencing upstream artifacts.",
  "feat.workflow.what5t": "🪄 AI writes prompts for you",
  "feat.workflow.what5d": "Give one-line intent, AI writes a pro prompt by node type (storyboard artist / art director / music producer each has a template); still editable after.",
  "feat.workflow.what6t": "Templates run instantly",
  "feat.workflow.what6d": "Built-in AI shorts, music singles, concept-art flows — change a theme and run.",
  "feat.workflow.what7t": "Reliability analysis",
  "feat.workflow.what7d": "\"🛡 Reliability\" checks missing params, missing keys, broken links, cycles, with a score and fix tips.",
  "feat.workflow.step0": "Open sidebar \"Workflow\", drag nodes in (or \"Load Template\").",
  "feat.workflow.step1": "Connect: hold a node's right edge to the target; lazy users click \"⚡ Auto Connect\".",
  "feat.workflow.step2": "Click a node, set its prompt to this task (write or 🪄 AI write).",
  "feat.workflow.step3": "\"▶ Run Workflow\" runs the full flow; a failed node won't block other branches.",
  "feat.workflow.step4": "Save canvas as JSON; \"Save / Open JSON\" for reuse and sharing.",
  "feat.workflow.tech0": "Nodes are flat dict + deps; engine runs topologically in series, failed branches auto-skip downstream.",
  "feat.workflow.tech1": "Placeholders reference upstream artifacts, support nth item of a list (e.g. storyboard shot 1).",
  "feat.workflow.tech2": "Params normalized by type (duration→int, instrumental→bool) to avoid cloud type errors.",
  "feat.workflow.tech3": "LLM node return values get error-flag detection, preventing error text flowing downstream as script.",
  "feat.workflow.shot": "Node canvas: drag, connect, per-node preview",

  "feat.media.title": "AI Media Factory",
  "feat.media.tag": "AI Media Studio",
  "feat.media.sub": "From one theme to a finished clip: script → storyboard → AI video shots → background music → subtitles → compose, all built into the client — no hopping between sites.",
  "feat.media.fact0": "Script / storyboard / video / music",
  "feat.media.fact1": "Subtitles + GIF",
  "feat.media.fact2": "Vertical 9:16",
  "feat.media.fact3": "Auto-archived",
  "feat.media.grid": "Script / storyboard / video / music · subtitles + GIF",
  "feat.media.what0t": "Script generation",
  "feat.media.what0d": "Give a theme, get a 60s three-shot micro-drama script with auto-cut image prompts per shot.",
  "feat.media.what1t": "Storyboard split",
  "feat.media.what1d": "Auto-extract each shot description into a structured list, fed one by one to video nodes.",
  "feat.media.what2t": "AI video shots",
  "feat.media.what2d": "Call text-to-video to generate each shot, vertical 9:16, adjustable duration, single-shot rerun.",
  "feat.media.what3t": "Background music",
  "feat.media.what3d": "Generate an instrumental theme by script mood, or let AI write a full song with lyrics.",
  "feat.media.what4t": "AI image",
  "feat.media.what4d": "Cinematic concept art, cover images, storyboard refs, selectable ratios.",
  "feat.media.what5t": "Subtitles & GIF",
  "feat.media.what5d": "Auto subtitle files, or export clips as GIFs.",
  "feat.media.what6t": "Video compose",
  "feat.media.what6d": "Compose multiple shots in order into one finished clip.",
  "feat.media.what7t": "Local assets insertable",
  "feat.media.what7d": "Your own images and music can drop into the workflow as refs or score, mixed with AI output.",
  "feat.media.step0": "Workflow → Load \"🎬 AI Short (3 shots + music)\" template.",
  "feat.media.step1": "Change the theme to this task (e.g. \"daily life of a working dragon\").",
  "feat.media.step2": "Click the script node, write or 🪄 AI write; confirm then run.",
  "feat.media.step3": "Preview per node: script & storyboard first, then generated shot video & music.",
  "feat.media.step4": "Compose node outputs the clip; artifacts auto-land in the task archive folder.",
  "feat.media.tech0": "Video / music / image connect to Kling, Suno, image models via a unified tool registry.",
  "feat.media.tech1": "Media nodes bill per use; UI shows cost clearly (free tier can practice flows with local).",
  "feat.media.tech2": "Shot count, ratio, duration all editable; shot prompt supports hard override of upstream.",
  "feat.media.tech3": "Artifact paths auto-backfill to nodes; next rerun reuses directly.",
  "feat.media.shot": "Script → storyboard → shots → music",

  "feat.modules.title": "Six Industry Scenario Modules",
  "feat.modules.tag": "Scenarios",
  "feat.modules.sub": "Research, video, image, finance, software, growth — six ready-to-use scenario entries, each preset with experts, tools and quick cards; click in and go.",
  "feat.modules.fact0": "6 scenarios",
  "feat.modules.fact1": "Preset quick cards",
  "feat.modules.fact2": "Multi-language",
  "feat.modules.fact3": "Local / cloud",
  "feat.modules.grid": "6 scenarios · preset quick-start cards",
  "feat.modules.what0t": "Research",
  "feat.modules.what0d": "Paper search, material整理, structured summary & comparison — great for reviews and proposals.",
  "feat.modules.what1t": "Video & image creation",
  "feat.modules.what1d": "Short-script to clip, concept & cover design, wired to creation experts.",
  "feat.modules.what2t": "Finance & investment",
  "feat.modules.what2d": "Market data, company info, long/short thesis & risk — wired to trader / actuary.",
  "feat.modules.what3t": "Software & code",
  "feat.modules.what3d": "Requirement breakdown, code gen, debugging, quick script runs — wired to architect / full-stack Codex.",
  "feat.modules.what4t": "Growth & marketing",
  "feat.modules.what4d": "Topics, copy, campaign planning, growth experiment design.",
  "feat.modules.what5t": "Every module has quick cards",
  "feat.modules.what5d": "No prompt from scratch; click a card to use a ready task template.",
  "feat.modules.step0": "Sidebar \"NAVIGATION\" pick a scenario (research / video / image / finance / software / growth).",
  "feat.modules.step1": "Click a quick card in the scenario, or just describe the need.",
  "feat.modules.step2": "For cross-scenario, a project space gathers artifacts from several scenarios.",
  "feat.modules.tech0": "Scenario cards are just \"task template + expert + tool\" combos, all defined locally, editable.",
  "feat.modules.tech1": "Scenarios share one tool registry and memory system; artifacts interoperate.",
  "feat.modules.tech2": "UI supports 10 languages; scenario card copy follows the switch.",
  "feat.modules.shot": "Scenario cards: click and start working",

  "feat.spaces.title": "Project Spaces & Task Center",
  "feat.spaces.tag": "Projects & Tasks",
  "feat.spaces.sub": "One goal, one space; multiple tasks in parallel without mixing; all artifacts, logs and context archived in the space, resume anytime.",
  "feat.spaces.fact0": "Parallel tasks",
  "feat.spaces.fact1": "Space-level context isolation",
  "feat.spaces.fact2": "Auto-archived",
  "feat.spaces.fact3": "Kanban progress",
  "feat.spaces.grid": "Parallel tasks · space-level context isolation",
  "feat.spaces.what0t": "Project space",
  "feat.spaces.what0d": "Open a space per project; its goals, attachments, artifacts and chat history are stored separately, never polluted by others.",
  "feat.spaces.what1t": "Parallel tasks",
  "feat.spaces.what1d": "Run multiple subtasks in one space, each on its own progress.",
  "feat.spaces.what2t": "Task center kanban",
  "feat.spaces.what2d": "All tasks in one board: status, time, artifacts, failure reasons at a glance.",
  "feat.spaces.what3t": "Context bus",
  "feat.spaces.what3d": "Spaces can reference each other's artifacts within limits; call caps prevent circular dependency.",
  "feat.spaces.what4t": "Artifact archive",
  "feat.spaces.what4d": "Generated files, images, video, tables auto-land in the space folder — no hunting.",
  "feat.spaces.what5t": "Resume anytime",
  "feat.spaces.what5d": "Close and reopen the client; the space and progress remain.",
  "feat.spaces.step0": "Sidebar \"Project Spaces\" → New space, state the goal and attach reference files.",
  "feat.spaces.step1": "Hand the goal to the agent; it splits into parallel subtasks.",
  "feat.spaces.step2": "\"Task Center\" shows overall progress and each task's artifacts.",
  "feat.spaces.step3": "When done, grab all artifacts from the space folder; iterate in the same space.",
  "feat.spaces.tech0": "Spaces pass artifact refs via a context bus; cross-space calls capped to prevent loops.",
  "feat.spaces.tech1": "Task state and artifact paths persist; restart doesn't lose them.",
  "feat.spaces.tech2": "Each space's execution log is kept separately for easy step tracing.",
  "feat.spaces.shot": "Project space: goal, tasks, artifacts in one place",

  "feat.task_center.title": "Task Center",
  "feat.task_center.tag": "Task Center",
  "feat.task_center.sub": "All tasks in one kanban: who's running, which step, how long, what it produced, why it failed — clear at a glance.",
  "feat.task_center.fact0": "Central board",
  "feat.task_center.fact1": "Real-time status",
  "feat.task_center.fact2": "Failure traceable",
  "feat.task_center.fact3": "One-click open",
  "feat.task_center.grid": "Central board · real-time status refresh",
  "feat.task_center.what0t": "One screen, all",
  "feat.task_center.what0d": "Whether triggered by chat, split by agent, or run on schedule — all funnel into one list.",
  "feat.task_center.what1t": "Real-time status",
  "feat.task_center.what1d": "Queued / running / done / failed / skipped — status changes refresh instantly.",
  "feat.task_center.what2t": "Failures make sense",
  "feat.task_center.what2d": "Failure isn't just \"error\" — it gives the specific step and reason (missing key, rate-limit, file not found…).",
  "feat.task_center.what3t": "Artifact direct",
  "feat.task_center.what3d": "Open a task to open its file, image, video, or table.",
  "feat.task_center.what4t": "Pairs with workflow",
  "feat.task_center.what4d": "Each workflow node's result also lands in the task log for easy step tracing.",
  "feat.task_center.step0": "Sidebar \"Task Center\" to view all tasks.",
  "feat.task_center.step1": "Click a task for details: steps, time, artifacts, log.",
  "feat.task_center.step2": "Failed tasks can be traced then rerun that step.",
  "feat.task_center.tech0": "Two-level task/step structure; step-level logs tool name, params, time, result.",
  "feat.task_center.tech1": "Execution and UI threads separated; long tasks don't freeze the UI; thread crash auto-resets button state.",
  "feat.task_center.shot": "Task center: status, time, artifacts",

  "feat.automation.title": "Automation & Scheduled Tasks",
  "feat.automation.tag": "Automation",
  "feat.automation.sub": "Let AI work on your rhythm: tidy news each morning, summarize data weekly, remind you on time — it runs even when you're not watching.",
  "feat.automation.fact0": "Scheduled / periodic",
  "feat.automation.fact1": "Local scheduler",
  "feat.automation.fact2": "History logged",
  "feat.automation.fact3": "Failures visible",
  "feat.automation.grid": "Scheduled / periodic · local scheduler",
  "feat.automation.what0t": "One sentence to create",
  "feat.automation.what0d": "\"Tidy yesterday's industry news into a summary at 9am daily\" — said, and an automation exists.",
  "feat.automation.what1t": "Periodic & one-shot",
  "feat.automation.what1d": "Daily, weekly, monthly, or run once at a set time.",
  "feat.automation.what2t": "Local scheduler",
  "feat.automation.what2d": "Scheduling and data stay on-device, not uploaded.",
  "feat.automation.what3t": "Execution history",
  "feat.automation.what3d": "How many runs, each result, any failure — all recorded.",
  "feat.automation.what4t": "Pausable & deletable",
  "feat.automation.what4d": "Pause or delete anytime you don't want it.",
  "feat.automation.step0": "Sidebar \"Automation\" → New, write what to do.",
  "feat.automation.step1": "Set time & frequency (daily / weekly / once at a time).",
  "feat.automation.step2": "Save, then view next run time and history in the list.",
  "feat.automation.tech0": "Automation def and run state persist separately; scheduling survives restart.",
  "feat.automation.tech1": "Each run logged independently to judge content vs environment issues.",
  "feat.automation.shot": "Work automatically on your rhythm",

  "feat.gui.title": "GUI Automation",
  "feat.gui.tag": "Computer Control",
  "feat.gui.sub": "Let AI drive other programs on your machine: click buttons, fill forms, open menus — even old software with no API gets automated.",
  "feat.gui.fact0": "Mouse & keyboard sim",
  "feat.gui.fact1": "Capability check first",
  "feat.gui.fact2": "Confirm per action",
  "feat.gui.fact3": "Toggle anytime",
  "feat.gui.grid": "Mouse & keyboard sim · capability check first",
  "feat.gui.what0t": "Operate UI like a human",
  "feat.gui.what0d": "AI \"sees\" the current window, then decides where to click and what to type, advancing step by step.",
  "feat.gui.what1t": "Capability check before start",
  "feat.gui.what1d": "The system checks if the environment supports it first; if not, tells you why instead of failing silently.",
  "feat.gui.what2t": "Confirm before acting",
  "feat.gui.what2d": "By default every key action asks; only auto-confirm mode skips the prompts.",
  "feat.gui.what3t": "Risky actions still blocked",
  "feat.gui.what3d": "Destructive ops like delete/overwrite aren't released by auto-confirm.",
  "feat.gui.what4t": "Toggle anytime",
  "feat.gui.what4d": "One click off; AI immediately loses mouse/keyboard control.",
  "feat.gui.step0": "Settings → Enable \"GUI Automation\", pass the capability check first.",
  "feat.gui.step1": "Describe the operation (the more specific, the better).",
  "feat.gui.step2": "Confirm each key action as prompted.",
  "feat.gui.step3": "Turn the switch off when done.",
  "feat.gui.tech0": "Capability check runs and caches on enable, avoiding mid-run \"environment unsupported.\"",
  "feat.gui.tech1": "Operation granularity configurable; default per-action confirm.",
  "feat.gui.tech2": "Wired to auto-confirm: only explicit auto-confirm skips the prompt.",
  "feat.gui.shot": "Old software with no API gets automated too",

  "feat.safety.title": "Safety Guardrails: Auto-Confirm & Emergency Stop",
  "feat.safety.tag": "Safety",
  "feat.safety.sub": "Grant the power that should be granted, block what must be blocked. Writes can confirm per step or auto-confirm for speed — but risky actions are always blocked, deletes always go to recycle bin.",
  "feat.safety.fact0": "Levels: WARNING / BLOCKED",
  "feat.safety.fact1": "Auto-confirm mode",
  "feat.safety.fact2": "One-click stop",
  "feat.safety.fact3": "Deletes → recycle bin",
  "feat.safety.grid": "Levels: WARNING / BLOCKED · auto-confirm mode",
  "feat.safety.what0t": "Per-step confirm by default",
  "feat.safety.what0d": "Every write, data change or command first pops a window; executes only on your yes.",
  "feat.safety.what1t": "Auto-confirm (speed mode)",
  "feat.safety.what1d": "After trust, enable it; routine writes stop prompting, run straight through — good for verified repeat flows.",
  "feat.safety.what2t": "Risky still blocked",
  "feat.safety.what2d": "BLOCKED-level destructive actions aren't released by auto-confirm; always need your nod.",
  "feat.safety.what3t": "Deletes → recycle bin",
  "feat.safety.what3d": "AI deletes go to recycle bin by default, not wiped — recoverable if mistaken.",
  "feat.safety.what4t": "One-click emergency stop",
  "feat.safety.what4d": "Spot something wrong mid-chain? Emergency stop ends the running task immediately.",
  "feat.safety.what5t": "Tool allow/deny lists",
  "feat.safety.what5d": "Callable tools limited to the allowlist; denylist tools are unreachable in any case.",
  "feat.safety.step0": "Default is \"confirm every action\" — nothing to set.",
  "feat.safety.step1": "Enable \"Auto-Confirm\" once trust is enough; it asks once on enable.",
  "feat.safety.step2": "Disable anytime from the top bar, back to per-step confirm.",
  "feat.safety.step3": "Mid-run, click \"Stop\" to emergency-stop the current task.",
  "feat.safety.tech0": "Actions graded by risk: WARNING can be auto-confirmed, BLOCKED always blocked.",
  "feat.safety.tech1": "Tool calls use allow + deny lists; ≤10 calls per subtask.",
  "feat.safety.tech2": "Deletes uniformly go through recycle-bin backup path for recoverability.",
  "feat.safety.shot": "Grant the power, block what must be blocked",

  "feat.files.title": "Real File Work",
  "feat.files.tag": "Real File Work",
  "feat.files.sub": "It doesn't just chat: read your docs and sheets, edit content, generate new files, run scripts, batch process — then hand you the file.",
  "feat.files.fact0": "Read/write Office / sheets",
  "feat.files.fact1": "Run scripts",
  "feat.files.fact2": "Batch process",
  "feat.files.fact3": "Drag / paste images",
  "feat.files.grid": "Read/write Office / sheets · run scripts",
  "feat.files.what0t": "Understands your files",
  "feat.files.what0d": "Drop in Word, Excel, PPT, PDF, images; it reads and works on the content.",
  "feat.files.what1t": "Same format after edit",
  "feat.files.what1d": "Edits in-place and saves as the original format — not text you copy back yourself.",
  "feat.files.what2t": "Generate new files",
  "feat.files.what2d": "Sheets, reports, lists, charts — directly produce openable files.",
  "feat.files.what3t": "Run scripts",
  "feat.files.what3d": "Run scripts for batch when needed; output flows back into chat.",
  "feat.files.what4t": "Drag & paste",
  "feat.files.what4d": "Drop a file into the input to become context; clipboard images Ctrl+V become attachments.",
  "feat.files.what5t": "Artifact archive",
  "feat.files.what5d": "Generated files land in the task folder for easy pickup.",
  "feat.files.step0": "Drop a file into the input (or Ctrl+V paste an image).",
  "feat.files.step1": "Say what to do: \"summarize this sheet by month and chart the trend.\"",
  "feat.files.step2": "AI hands you a new file when done; open and use.",
  "feat.files.tech0": "File read/write goes through a unified tool layer, shared with workflow nodes.",
  "feat.files.tech1": "Large files are structurally parsed before processing, avoiding stuffing the whole doc into context.",
  "feat.files.tech2": "Generated artifact paths backfill for later reference and reprocessing.",
  "feat.files.shot": "Drop in, edited, hand you back a file",

  "feat.i18n.title": "Multi-Language Interface",
  "feat.i18n.tag": "i18n",
  "feat.i18n.sub": "The UI supports 10 languages with real-time switching — instant, no restart. Handy for overseas users or team collaboration.",
  "feat.i18n.fact0": "10 languages",
  "feat.i18n.fact1": "Real-time switch",
  "feat.i18n.fact2": "UI + scenario cards",
  "feat.i18n.fact3": "Extensible",
  "feat.i18n.grid": "10 languages · real-time switch",
  "feat.i18n.what0t": "10 languages",
  "feat.i18n.what0d": "简体中文, English, 日本語, 한국어, Deutsch, Français, Español, Português, Русский, العربية.",
  "feat.i18n.what1t": "Switch takes effect instantly",
  "feat.i18n.what1d": "Change language in Settings; UI text updates immediately, no client restart.",
  "feat.i18n.what2t": "Full coverage",
  "feat.i18n.what2d": "Main UI, settings, workflow canvas, scenario card copy all share one multilingual layer.",
  "feat.i18n.what3t": "Translations extensible",
  "feat.i18n.what3d": "Language resources live in separate files; adding a language is just one more copy.",
  "feat.i18n.step0": "Settings → UI Language, pick a language.",
  "feat.i18n.step1": "If prompted to restart, restart once for full effect.",
  "feat.i18n.tech0": "All UI text is fetched via a runtime translation function, avoiding hard-coding Chinese at import.",
  "feat.i18n.tech1": "Language resources are separate files for easy review and addition.",
  "feat.i18n.shot": "",

  "feat.privacy.title": "Local-First & Privacy",
  "feat.privacy.tag": "Local First",
  "feat.privacy.sub": "Conversations, memory, knowledge base, skills and artifacts all default to your own computer. Works fully offline; cloud is only for models you actively choose.",
  "feat.privacy.fact0": "0 data out (local mode)",
  "feat.privacy.fact1": "Offline usable",
  "feat.privacy.fact2": "All on-device",
  "feat.privacy.fact3": "Local DB",
  "feat.privacy.grid": "0 data out (local) · offline usable",
  "feat.privacy.what0t": "Data stays on-device",
  "feat.privacy.what0d": "Chat history, four-layer memory, skill library, project artifacts all stored as local files / local DB.",
  "feat.privacy.what1t": "Offline usable",
  "feat.privacy.what1d": "With local models, chat, file ops and workflow orchestration need no network at all.",
  "feat.privacy.what2t": "Cloud is your choice",
  "feat.privacy.what2d": "Only when you choose cloud models or cloud generation does related content go to the provider.",
  "feat.privacy.what3t": "One-click cleanup",
  "feat.privacy.what3d": "\"Memory Cleanup\" can clear a memory layer or delete a session — gone for real.",
  "feat.privacy.what4t": "No account needed",
  "feat.privacy.what4d": "Free tier doesn't force registration; local features work out of the box.",
  "feat.privacy.step0": "For full offline, just use local models.",
  "feat.privacy.step1": "To clear records: sidebar \"Memory Cleanup\".",
  "feat.privacy.step2": "Worried a chat is sensitive? Just don't pick a cloud model.",
  "feat.privacy.tech0": "Local storage uses SQLite and local dirs, no self-built cloud service.",
  "feat.privacy.tech1": "Cloud calls only go through your configured provider key, directly to the API.",
  "feat.privacy.tech2": "Memory layers are each clearable, avoiding \"clear one wipes all.\"",
  "feat.privacy.shot": "All on-device, runs offline",

  /* ───────── 功能页 engineering ───────── */
  "feat.engineering.title": "Engineering Drawing",
  "feat.engineering.tag": "Engineering Drawing",
  "feat.engineering.sub": "Describe what you need in the chat on the left; AI generates runnable plotting code and renders a live preview on the right. One click exports an Origin LabTalk script for publication-ready figures.",
  "feat.engineering.grid": "Chat-to-plot · Origin script export",
  "feat.engineering.fact0": "Chat-to-plot",
  "feat.engineering.fact1": "One-click Origin script export",
  "feat.engineering.fact2": "Local execution, zero upload",
  "feat.engineering.fact3": "Professional engineering charts",
  "feat.engineering.what0t": "Plot by chatting",
  "feat.engineering.what0d": "Describe the chart you need in the chat box — shear force, bending moment, Bode plot, error bars — and the AI generates code that renders instantly in the preview pane.",
  "feat.engineering.what1t": "Fully transparent code",
  "feat.engineering.what1d": "Every generation is readable Python code: parameters, units and formulas are all visible, and you can tweak and re-run.",
  "feat.engineering.what2t": "Local rendering, no data leaves your machine",
  "feat.engineering.what2d": "Plotting code runs on your computer (numpy / matplotlib / scipy); raw data never needs to be uploaded to any cloud.",
  "feat.engineering.what3t": "One-click Origin script export",
  "feat.engineering.what3d": "Once the preview looks right, convert the solution into an Origin LabTalk script (.ogs) and open it directly in licensed Origin.",
  "feat.engineering.what4t": "Many chart types",
  "feat.engineering.what4d": "Line, bar, scatter, error bars, dual y-axis, polar, 3D surfaces — every chart engineers use day to day.",
  "feat.engineering.what5t": "Context-aware revisions",
  "feat.engineering.what5d": "\"Make the line red\", \"use a log scale on y\" — just keep talking; it remembers what it drew last turn.",
  "feat.engineering.step0": "Open the panel from the sidebar: 📐 Engineering Drawing.",
  "feat.engineering.step1": "Type your request, e.g. \"Plot the shear force and bending moment diagrams of a cantilever beam under uniform load\".",
  "feat.engineering.step2": "AI generates code and runs it locally; the preview pane shows the figure immediately.",
  "feat.engineering.step3": "When satisfied, choose Export Script → Origin and save the .ogs file.",
  "feat.engineering.tech0": "A Qiniu cloud code model generates the plotting code, auto-picked by tier to keep costs down.",
  "feat.engineering.tech1": "Local sandboxed execution: only numpy / matplotlib / scipy preloaded, all exceptions captured and shown in chat.",
  "feat.engineering.tech2": "Off-screen Agg rendering — no pop-up windows, no focus stealing; figures saved locally as soon as they are drawn.",
  "feat.engineering.tech3": "Export uses a second model call to faithfully convert the Python solution into LabTalk / MATLAB / COMSOL code.",
  "feat.engineering.shot": "Chat to plot, live preview on the right",

  /* ───────── 功能页 modeling ───────── */
  "feat.modeling.title": "Modeling Assistant",
  "feat.modeling.tag": "Modeling Assistant",
  "feat.modeling.sub": "A math-modeling-competition-grade assistant: assumptions → equations → code → result plots, all in one flow. Export a MATLAB script so advisors or teammates can reproduce it in one click.",
  "feat.modeling.grid": "Assume → model → solve → plot",
  "feat.modeling.fact0": "Assume → model → solve → plot",
  "feat.modeling.fact1": "scipy numerical solving",
  "feat.modeling.fact2": "MATLAB script export",
  "feat.modeling.fact3": "Competition-style output",
  "feat.modeling.what0t": "The complete modeling workflow",
  "feat.modeling.what0d": "Up to 5 lines of assumptions and approach first, then runnable solving code, then a figure with a short interpretation — exactly the skeleton of a competition paper.",
  "feat.modeling.what1t": "Equations, fitting, optimization all covered",
  "feat.modeling.what1d": "ODEs (solve_ivp), least-squares fitting, linear programming, Monte Carlo simulation and other common methods are supported.",
  "feat.modeling.what2t": "Instant visualization",
  "feat.modeling.what2d": "Results are plotted automatically: convergence curves, phase diagrams, parameter sensitivity — inspect model behavior at a glance.",
  "feat.modeling.what3t": "One-click MATLAB script export",
  "feat.modeling.what3d": "Export the finalized solution as an .m script to reproduce in MATLAB, or hand it to courses and teammates that require MATLAB.",
  "feat.modeling.what4t": "History kept, no drift",
  "feat.modeling.what4d": "Multi-turn context is preserved: change constraints or swap the objective function and just keep talking.",
  "feat.modeling.what5t": "Parameters with units",
  "feat.modeling.what5d": "Generated code annotates parameters with physical dimensions — no more \"what is 0.5?\".",
  "feat.modeling.step0": "Open the panel from the sidebar: 🧮 Modeling Assistant.",
  "feat.modeling.step1": "Describe the problem, e.g. \"Predict population growth with a logistic model and fit its parameters\".",
  "feat.modeling.step2": "Read the approach, wait for the result plot on the right; keep asking to refine.",
  "feat.modeling.step3": "Export Script → MATLAB and save the .m file to reproduce.",
  "feat.modeling.tech0": "The local runtime ships the full numpy / scipy / matplotlib stack for complete numerical capability.",
  "feat.modeling.tech1": "solve_ivp, least_squares and friends are available out of the box — no hand-rolled solvers needed.",
  "feat.modeling.tech2": "Reuses the app's multi-model fallback chain; rate limits trigger automatic switching.",
  "feat.modeling.tech3": "Code-execution exceptions are fully captured and reported; a bad model never crashes the app.",
  "feat.modeling.shot": "Assumptions → solve → result plot",

  /* ───────── 功能页 simulation ───────── */
  "feat.simulation.title": "Physics Simulation",
  "feat.simulation.tag": "Physics Simulation",
  "feat.simulation.sub": "Describe a physical process and the AI builds a numerical model and simulates it: pendulums, vibration, heat transfer, waves, circuits… Result curves appear on the spot, and a COMSOL modeling script can be exported for further refinement.",
  "feat.simulation.grid": "ODE/PDE simulation · live curves",
  "feat.simulation.fact0": "ODE/PDE numerical simulation",
  "feat.simulation.fact1": "Real-time result preview",
  "feat.simulation.fact2": "COMSOL script export",
  "feat.simulation.fact3": "Quantities & units labeled",
  "feat.simulation.what0t": "From description to numerical model",
  "feat.simulation.what0d": "Name the scenario — large-angle pendulum, cantilever vibration, 1-D heat transfer — and the AI sets up equations, discretizes and solves them numerically.",
  "feat.simulation.what1t": "Instant curves and field plots",
  "feat.simulation.what1d": "How quantities evolve in time or space is plotted on the spot: angle-time, temperature fields, waveforms, all visible immediately.",
  "feat.simulation.what2t": "Quantities and units included",
  "feat.simulation.what2d": "Axes are labeled with quantities and units, parameters come with dimensions — results can go straight into a report.",
  "feat.simulation.what3t": "One-click COMSOL script export",
  "feat.simulation.what3d": "When you need serious FEM, export the solution as a COMSOL Java API script (.java) and keep refining the model in COMSOL.",
  "feat.simulation.what4t": "Parameter sweep comparisons",
  "feat.simulation.what4d": "\"Triple the damping and run again\" — re-run the same model with new parameters and compare curves at a glance.",
  "feat.simulation.what5t": "Local compute, zero upload",
  "feat.simulation.what5d": "Simulations run on your computer; models and data never leave the machine.",
  "feat.simulation.step0": "Open the panel from the sidebar: ⚛ Physics Simulation.",
  "feat.simulation.step1": "Describe the process and desired output, e.g. \"large-angle pendulum, plot angle vs. time\".",
  "feat.simulation.step2": "Wait for the preview to render, then tweak parameters or switch scenarios by chatting.",
  "feat.simulation.step3": "Export Script → COMSOL and save the .java modeling code.",
  "feat.simulation.tech0": "ODEs use scipy solve_ivp (RK45); simple cases automatically fall back to hand-rolled Euler / RK4 with numpy.",
  "feat.simulation.tech1": "Off-screen Agg rendering; simulation PNGs are saved locally for instant access.",
  "feat.simulation.tech2": "System prompts enforce output format and a library whitelist, maximizing executable-code success rate.",
  "feat.simulation.tech3": "COMSOL export uses a second model pass covering geometry → physics → mesh → solve → post-processing.",
  "feat.simulation.shot": "Numerical simulation, curves on the spot",
  "feat.models.what6t": "Model status at a glance",
  "feat.models.what6d": "Every entry carries a badge: '🔒 needs OpenRouter key' tells you which key is missing, '🚫 region-locked' tells you this region cannot use it. Available models sort first, ones needing keys sink to the bottom — no trial-and-error clicking.",
  "feat.models.what7t": "Switch mid-conversation",
  "feat.models.what7d": "Change models halfway through a chat without losing context — literally swapping the brain mid-thought.",
  "feat.models.step4": "Offline it falls back to local models; back online it returns to cloud with no manual step.",
  "feat.models.tech4": "At startup the OpenRouter public catalogue (400+ models) is fetched in the background to refresh prices and context windows — fetching needs no key.",
  "feat.models.tech5": "Model metadata carries context window, price and minimum plan; auto-routing scores by category match + plan level + price, preferring the cheaper model at equal capability.",
  "feat.memory.what6t": "Memory you can inspect and clear",
  "feat.memory.what6d": "Open 'Memory files' in the sidebar any time; if it remembered something wrong, clear or correct it.",
  "feat.memory.tech4": "Every layer has a character cap, so stale content can never drown out what matters.",
  "feat.routing.tag": "Smart Routing & Cost Control",
  "feat.routing.title": "Smart routing and cost control",
  "feat.routing.sub": "Large models bill by token, and what drains your balance is rarely the question you typed — it is the long context re-sent every single turn. Three defences — sticky model choice, prefix caching, rolling compression — keep the bill minimal.",
  "feat.routing.fact0": "Three token-saving defences",
  "feat.routing.fact1": "Context compression 4x+",
  "feat.routing.fact2": "Cached prefix billed at ~1/10",
  "feat.routing.fact3": "Usage and spend traceable",
  "feat.routing.what0t": "Defence 1: sticky model choice",
  "feat.routing.what0d": "Every model switch invalidates the provider-side prefix cache, so the entire context is re-billed at full price. Auto-routing is therefore sticky — the same task class keeps the same model, upgrading only when context approaches the window limit.",
  "feat.routing.what1t": "Defence 2: prompt prefix caching",
  "feat.routing.what1d": "System prompts, expert personas and tool descriptions that repeat every turn are marked as cacheable. Cache hits bill that input at roughly one tenth of the price — the longer the chat and the bigger the prefix, the more you save.",
  "feat.routing.what2t": "Defence 3: rolling context compression",
  "feat.routing.what2d": "Recent turns stay verbatim for continuity; older turns fold into an incremental summary. Measured 4.3x compression (5,975 → 1,401 tokens) with no semantic loss.",
  "feat.routing.what3t": "Model chosen by task type",
  "feat.routing.what3d": "Coding goes to code models, image understanding to vision models, long-form reasoning to large-window reasoning models. Auto-routing scores on category match, plan level and price — cheapest wins at equal capability.",
  "feat.routing.what4t": "Rate-limit back-off, not brute force",
  "feat.routing.what4d": "On a rate limit it reads Retry-After and backs off in two stages (8s, then 30s to let the window roll) instead of hammering retries; only after repeated failure does it downgrade the model — so quota is not burned on retries.",
  "feat.routing.what5t": "Automatic failover on failure",
  "feat.routing.what5d": "Channel 5xx, timeout, empty balance and region blocks each have their own policy: switch models when possible, otherwise tell you exactly why — never fail silently and never double-bill.",
  "feat.routing.what6t": "Spend you can see",
  "feat.routing.what6d": "Every call logs model, input/output tokens and estimated cost, so you can reconcile against your provider bill and know where the money went.",
  "feat.routing.step0": "Nothing to set up: auto-routing already does stickiness and compression.",
  "feat.routing.step1": "To save more, run everyday tasks on a lower plan model and keep flagship models for modeling and deep research.",
  "feat.routing.step2": "No need to prune long chats — rolling compression folds early turns automatically.",
  "feat.routing.step3": "Check the current plan and model pool in settings to confirm auto-routing uses the tier you expect.",
  "feat.routing.tech0": "Rolling context = last K turns verbatim + incremental summaries of older turns; summarising uses turn stitching rather than an extra LLM call, so it costs nothing extra.",
  "feat.routing.tech1": "Budget trimming reclaims the oldest content according to remaining window space, so a request can never overflow the model's context window.",
  "feat.routing.tech2": "Prompt caching attaches cache_control to the system prefix for OpenRouter / Claude-style gateways; other gateways ignore the field harmlessly.",
  "feat.routing.tech3": "The stickiness rule only asks whether the current model still fits the context; if it fits, the model is not changed — the KV-cache loss from switching costs far more than any unit-price difference.",
  "feat.routing.tech4": "Token estimation uses character counts with a Chinese/English differential (≈1.5 chars per token for Chinese, ≈4 for English) — no extra tokenizer call needed.",
  "feat.routing.shot": "Same work, smaller bill",
  "feat.channels.tag": "Providers & Region",
  "feat.channels.title": "Model channels and region awareness",
  "feat.channels.sub": "China-direct, not region-locked, one key for many models. 14 platform presets, dual-channel failover and region probing mean 'this model won't run' never needs debugging again.",
  "feat.channels.fact0": "14 China-direct presets",
  "feat.channels.fact1": "Dual-channel failover",
  "feat.channels.fact2": "Region locks detected automatically",
  "feat.channels.fact3": "Keys never leak across channels",
  "feat.channels.what0t": "Why multiple channels at all",
  "feat.channels.what0d": "Overseas aggregators block some vendors' closed models by billing region — on the same platform some models work and others return 403. China-direct official and compliant aggregator platforms have no such issue, but each covers only its own catalogue. Together they make the most robust setup.",
  "feat.channels.what1t": "14 China-direct presets",
  "feat.channels.what1d": "SiliconFlow, Alibaba Bailian, DeepSeek official, Volcano Ark, Zhipu BigModel, Moonshot Kimi, MiniMax, Tencent Hunyuan, ModelScope, 302.AI, DMXAPI, AIHubMix, NVIDIA NIM, StepFun. All OpenAI-protocol compatible; picking a platform fills in its base URL.",
  "feat.channels.what2t": "Primary + fallback, both live",
  "feat.channels.what2d": "With OpenRouter as primary, your China keys ride along as fallback, and vice versa. If one channel wobbles, a same-class model on the other picks up the request without breaking the conversation.",
  "feat.channels.what3t": "Region probing (automatic, free)",
  "feat.channels.what3d": "At startup each catalogue model gets one minimal request (max_tokens=1, cost ≈ $0) to measure what is region-blocked; results are cached and reused. Change the key and it re-probes — one probe per key, not per launch.",
  "feat.channels.what4t": "Blocked models are labelled",
  "feat.channels.what4d": "Blocked models are badged '🚫 region-locked' and sink to the bottom; auto-routing skips them entirely. You never pick one only to discover it does not run.",
  "feat.channels.what5t": "Models without keys speak up",
  "feat.channels.what5d": "If a platform key is missing, its models show '🔒 needs X key' — telling you exactly which key to add, instead of a vague authentication failure.",
  "feat.channels.what6t": "Switch platform, change no code",
  "feat.channels.what6d": "All channels share one call protocol and one model index; switching is a dropdown change, while workflows, experts and skills keep working untouched.",
  "feat.channels.step0": "Settings → Cloud models, choose a platform in the provider dropdown (e.g. SiliconFlow).",
  "feat.channels.step1": "The dialog pre-fills that platform's base URL; paste your key. The model field accepts any model id from that platform.",
  "feat.channels.step2": "Verify and save, then restart — the platform's models appear in the top dropdown.",
  "feat.channels.step3": "For dual-channel failover, add keys for two platforms; primary and fallback are assembled automatically.",
  "feat.channels.tech0": "One capability table holds every channel (label, base_url, signup URL, sample models) — adding a platform takes under ten lines.",
  "feat.channels.tech1": "Probe results are stored against a key fingerprint, so startup never re-probes the same key (a full probe takes about three minutes); a new key invalidates instantly.",
  "feat.channels.tech2": "Judgement is per model, not per vendor: open-weight models from the same vendor often remain reachable, so anything that actually passes is allowed.",
  "feat.channels.tech3": "Request headers adapt per channel: some platforms use an api-key header instead of Bearer, and the client switches transparently.",
  "feat.channels.tech4": "All channels share the same unified 429 / 5xx / 403 classification and degradation policy, so behaviour stays predictable.",
  "feat.channels.shot": "Channel status at a glance",
  "feat.cad3d.tag": "3D & CAD Modeling",
  "feat.cad3d.title": "3D modeling and CAD output",
  "feat.cad3d.sub": "One sentence produces a 3D model: concept-level Blender for quick sketches, engineering-level true CAD producing B-rep solids with STEP / DXF / OBJ export for industrial pipelines. It researches its own dimensions online and cross-validates them before building.",
  "feat.cad3d.fact0": "Self-researched + cross-validated dimensions",
  "feat.cad3d.fact1": "Concept / engineering dual kernel",
  "feat.cad3d.fact2": "B-rep solids · STEP / DXF export",
  "feat.cad3d.fact3": "All entries behind one button",
  "feat.cad3d.what0t": "It researches dimensions instead of guessing",
  "feat.cad3d.what0d": "Ask for 'a Boeing 737-800 fuselage' and it searches the real dimensions online — and it does not trust a single page: the same parameter is queried in several phrasings (Chinese and English), results from independent sources are aggregated, the median becomes the consensus value, and confidence (high / medium / low / conflict) is recorded.",
  "feat.cad3d.what1t": "Cross-validation you can inspect",
  "feat.cad3d.what1d": "Every key dimension shows its sources and verdict: how many sources support it, the agreed value and whether they contradict each other. The research report is saved to disk so it can ship alongside the model.",
  "feat.cad3d.what2t": "Concept level: quick Blender / bpy sketches",
  "feat.cad3d.what2d": "Generates a bpy script, runs it headless, exports STL and renders a preview. Available on every plan — ideal for 'let me see roughly what it looks like'.",
  "feat.cad3d.what3t": "Engineering level: true CAD kernel (B-rep)",
  "feat.cad3d.what3d": "The CAD kernel produces genuine B-rep solids — fillets, chamfers, boolean operations, holes — exported as STEP (the universal CAD interchange format) and DXF (2D drawings). Unlocked on Ultra and Max plans.",
  "feat.cad3d.what4t": "Modeling precision: one button",
  "feat.cad3d.what4d": "Pressing '3D modeling' opens every entry point: build now, precision (auto / concept / engineering), FreeCAD loft modeling, import a mesh, kernel paths. Auto upgrades smoothly as your plan and installed kernels allow.",
  "feat.cad3d.what5t": "Work from an existing model",
  "feat.cad3d.what5d": "Import STL / OBJ / GLB straight into the following steps (simulation, engineering drawings, product rendering) instead of starting from scratch.",
  "feat.cad3d.what6t": "Missing kernels offer to install",
  "feat.cad3d.what6d": "Choosing engineering level without the kernel installed prompts to install it (domestic mirror, isolated directory, your existing Python untouched) and lands on engineering level once finished.",
  "feat.cad3d.what7t": "Prompt constraints that prevent junk",
  "feat.cad3d.what7d": "System prompts force key dimensions to be declared as variables first, secondary positions computed from those variables (no magic numbers), plus volume and surface area self-checks — fewer 'looks right but measures wrong' outcomes.",
  "feat.cad3d.step0": "Open engineering mode → modeling and describe the part or object in the input box (the more specific the better, e.g. '60×40×8 plate, R5 corners, central φ10 through hole').",
  "feat.cad3d.step1": "Press '3D modeling' → choose precision: 'auto' for daily work, 'engineering' for industrial delivery.",
  "feat.cad3d.step2": "It researches parameters (showing the cross-validation report), generates the script, runs it headless, and renders previews and solid files on the right.",
  "feat.cad3d.step3": "Export STEP / DXF / STL when satisfied, or press 'Import mesh' to feed the geometry into the simulation panel.",
  "feat.cad3d.tech0": "Dual-kernel dispatch: concept level via bpy (headless Blender), engineering level via CadQuery / OpenCASCADE (true B-rep), routed by precision and plan.",
  "feat.cad3d.tech1": "Multi-source aggregation: 2–3 differently phrased queries (Chinese/English) → spec extraction per independent source → median-based robust consensus → 8% relative tolerance for agreement, single-source marked low, disagreement marked conflict.",
  "feat.cad3d.tech2": "Kernel discovery finds portable Blender / FreeCAD installs automatically and asks for a path when absent; kernel installation uses a domestic mirror into an isolated site directory.",
  "feat.cad3d.tech3": "Scripts run in an isolated subprocess with a timeout, so a bad model cannot freeze the client — errors stream back to the chat area verbatim.",
  "feat.cad3d.tech4": "Export formats follow the purpose: STEP for CAD interchange, DXF for drawings, STL / OBJ for 3D printing and mesh simulation.",
  "feat.cad3d.shot": "One sentence → a real B-rep solid",
  "feat.membership.tag": "Plans & Usage",
  "feat.membership.title": "Plans and usage",
  "feat.membership.sub": "Five plans map to different model pools and capability limits: Free runs local, Standard covers the value lineup, Pro opens the flagship Chinese models, Ultra adds engineering-grade CAD, and Max has no ceiling. New users get 3,000 credits to try every model; paid tiers unlock with a subscription or licence.",
  "feat.membership.fact0": "5 plans",
  "feat.membership.fact1": "3,000 welcome credits",
  "feat.membership.fact2": "Max has no ceiling",
  "feat.membership.fact3": "Specialist agents on Max only",
  "feat.membership.what0t": "Free: local first, zero cost",
  "feat.membership.what0d": "Run local models via Ollama — chat, file operations, workflows and skills all work; you can also attach free OpenRouter models to improve the experience. Data never leaves your machine.",
  "feat.membership.what1t": "Standard: the value lineup",
  "feat.membership.what1d": "DeepSeek V4 Flash, Qwen3.8 Flash, GLM 4.6, Doubao Seed Lite — fast and cheap workhorses with vision support, covering the vast majority of daily tasks.",
  "feat.membership.what2t": "Pro: flagship Chinese lineup",
  "feat.membership.what2d": "Unlocks DeepSeek V4 Pro, GLM 5.3, Kimi K3, Qwen3.8 Max and more — long-context reasoning, complex coding, and large vision models included.",
  "feat.membership.what3t": "Ultra: engineering-grade capability",
  "feat.membership.what3d": "On top of Pro, unlocks engineering-level CAD modeling (true B-rep with STEP / DXF export), larger context windows and higher call limits.",
  "feat.membership.what4t": "Max: no ceiling",
  "feat.membership.what4d": "No ceiling on cloud messages — credits are metered as you go (top up any time or auto-charge a linked card). Specialist agents — deep research, autonomous coding, self-researching CAD, short-drama storyboarding — are exclusive to this tier. Your 3,000 welcome credits work here too.",
  "feat.membership.what5t": "Tiers unlock by subscription",
  "feat.membership.what5d": "The tier dropdown in Settings shows each plan's state: locked tiers carry a 🔒 and cannot be selected, so you never switch by accident. Once your subscription or licence key lands, that tier unlocks on the spot — model pool, capability gates (CAD, specialist agents) and model count all refresh, with no reinstall or re-login.",
  "feat.membership.what6t": "Credits you can watch",
  "feat.membership.what6d": "Your balance lives in the status bar and ticks down the moment each call finishes, at that model's published rate — which is shown right next to the model name. Daily check-in adds 100 credits (15 times for new accounts). When the balance bottoms out the app returns to Free mode and offers a top-up: no silent downgrade, no hidden charges.",
  "feat.membership.step0": "Settings → Plan and usage to compare the five tiers and see your current one.",
  "feat.membership.step1": "Pick a plan and save; enter an activation code if you have one, or use credit.",
  "feat.membership.step2": "The model dropdown refreshes immediately with the models your new plan unlocks.",
  "feat.membership.step3": "Switch back to Free whenever you like — chat history and local data are unaffected.",
  "feat.membership.tech0": "The plan is a single source of truth: plan → model pool → capability gates → UI copy all derive from one config, eliminating 'changed the plan but the UI did not move' inconsistencies.",
  "feat.membership.tech1": "Capability gating works at two levels: models unlock by min_tier, while engineering CAD and specialist agents are judged by plan.",
  "feat.membership.tech2": "Quota checks run on both client and server — the client intercepts early, the server has the final say.",
  "feat.membership.tech3": "A plan change triggers model-pool recomputation and dropdown repaint with no app restart.",
  "feat.membership.shot": "Five plans, clear boundaries",
  "feat.experts.what6t": "Tool calls have boundaries",
  "feat.experts.what6d": "Each subtask is capped at 10 rounds of tool calls with whitelist and blacklist limits, so a task can neither run forever nor reach dangerous tools.",
  "feat.experts.what7t": "One consolidated deliverable",
  "feat.experts.what7d": "When all subtasks finish they are merged automatically into one usable result, instead of leaving you a pile of fragments.",
  "feat.routing.grid": "Three token-saving defences · Context compression 4x+",
  "feat.channels.grid": "14 China-direct presets · mainland auto-prefers domestic models",
  "feat.cad3d.grid": "Self-researched + cross-validated dimensions · Concept / engineering dual kernel",
  "feat.membership.grid": "5 plans · 3,000 welcome credits · daily check-in",
  "home.models.m13": "14 China-direct channels",
  "home.models.m14": "Region-locked models auto-skipped",
  "home.price.max.name": "Max",
  "home.price.max.li1": "3,000 welcome credits · no monthly cap, pay as you go",
  "home.price.max.li2": "Daily check-in: 100 credits",
  "home.price.max.li3": "Specialist agents: research / coding / CAD",
  "home.price.max.li4": "Storyboarding and music agents",
  "home.price.max.cta": "Get Max",
  "home.faq.q5": "Will some models be unavailable in my region?",
  "home.faq.a5": "Some closed models from overseas vendors are limited by billing region. The app probes this automatically at startup, badges affected models as region-locked, and routes around them. Fourteen China-direct platforms (SiliconFlow, Alibaba Bailian, DeepSeek official and more) are built in — not region-locked, one key for many models.",
  "home.faq.q6": "Can I use my own API key?",
  "home.faq.a6": "Yes, and it is encouraged. Any OpenAI-compatible platform works: SiliconFlow, Alibaba Bailian, DeepSeek official, Volcano Ark, Zhipu, Kimi, MiniMax, ModelScope, OpenRouter and more. Pick the platform and the base URL fills itself in; paste your key and you are running on your own quota. Add two platforms and they fail over automatically.",
  "home.price.free.li0": "3,000 welcome credits — try every model",
  "home.price.std.li0": "800 credits every month",
  "home.price.pro.li0": "3,000 credits every month",
  "home.price.ult.li0": "10,000 credits every month",
  "home.shots.tag": "Real Interface",
  "home.shots.h2": "Not mockups — the real interface",
  "home.shots.p": "Every image below is a direct in-app screenshot: no touch-ups, no placeholders. The features are real, and so is the UI.",
  "home.shots.s1t": "Main window · multi-model routing chat",
  "home.shots.s1d": "Drop in one sentence and it picks the best expert and model for the job. Session history and capability nav on the left, live credit balance bottom-right.",
  "home.shots.s2t": "Workflow canvas · drag into a pipeline",
  "home.shots.s2d": "Script → shots → video → music. Wire it once, run the whole chain; every node previews on its own.",
  "home.shots.s3t": "Project Space · an AI PM dispatches the work",
  "home.shots.s3d": "Set a goal — it breaks the work down, assigns experts, and keeps every artifact and status inside the space.",
  "home.shots.s4t": "Engineering Mode · plots / modeling / simulation",
  "home.shots.s4d": "Three tabs — engineering plots, math modeling, physics simulation — with one-click script or image export.",
  "home.shots.s5t": "Scheduled tasks · automation templates",
  "home.shots.s5d": "Daily digest, weekly report and interview-prep templates work out of the box, scheduled entirely on your machine.",
  "home.shots.s6t": "Task Center · cross-session progress board",
  "home.shots.s6d": "Double-click a card to jump back into that session — the AI tracks every task across sessions.",
  "home.shots.s7t": "Industry scenario · trip budget analysis",
  "home.shots.s7d": "Fuel, lodging and tickets itemized into price tables with sourcing notes.",
  "home.wf.shotcap": "The real canvas: drag nodes, tune parameters on the right, preview node by node",
  "home.nav.shots": "Screenshots",
};
