/* Working Mate — 日本語 */
window.I18N = window.I18N || {};
window.I18N.ja = {
  "home.nav.capability": "機能",
  "home.nav.features": "すべての機能",
  "home.nav.workflow": "ワークフロー",
  "home.nav.models": "モデル",
  "home.nav.pricing": "料金",
  "home.nav.console": "コンソール",
  "home.nav.login": "ログイン",

  "home.hero1.eyebrow": "v1.4 リリース · ローカル主体のマルチモデル AI エージェント",
  "home.hero1.h1": "AI に<span class=\"glow\">本気で働かせる</span><br>ただ話すだけじゃない",
  "home.hero1.sub": "ローカルの Ollama とクラウドの大規模モデルを一元管理。ノード式ワークフローが脚本・絵コンテ・動画・BGM を一つの流れに。4層メモリが使うほどあなたを理解し、データは手元に残り、オフラインでも動きます。",
  "home.hero1.stat1": "対応モデル",
  "home.hero1.stat2": "外部送信データ",
  "home.hero1.stat3": "自己進化する記憶",
  "home.hero1.cta1": "無料ダウンロード・無料版",
  "home.hero1.cta2": "ワークフローを見る",

  "home.hero2.eyebrow": "ワークフロー・ノードキャンバス",
  "home.hero2.h1": "ドラッグするだけで<br><span class=\"glow\">AI パイプライン</span>を構築",
  "home.hero2.sub": "脚本→絵コンテ→動画ショット→BGM まで一気に実行。各ステップをプレビュー・単ノード再実行でき、カスタムカードやローカル素材も挿入可能。",
  "home.hero2.stat1": "分野の専門家",
  "home.hero2.stat2": "すぐ使えるテンプレ",
  "home.hero2.stat3": "ドラッグで即実行",
  "home.hero2.cta1": "ワークフローを開く",
  "home.hero2.cta2": "60秒デモを見る",

  "home.hero3.eyebrow": "v1.4・期間限定ローンチ特典",
  "home.hero3.h1": "夏の大セール<br>$0 で<span class=\"glow\">永久</span>使える",
  "home.hero3.sub": "無料版は永久に利用可能でローカルモデルは無制限。有料プランでより長い記憶・フラッグシップモデル・クラウド生成枠を解放。",
  "home.hero3.stat1": "起点・無料",
  "home.hero3.stat2": "スタンダード",
  "home.hero3.stat3": "チーム・構想中",
  "home.hero3.cta1": "今すぐダウンロード",
  "home.hero3.cta2": "更新履歴を見る",

  "home.float.assist": "AI アシスタント",
  "home.float.service": "有人サポート",
  "home.float.sales": "営業窓口",

  "home.cap.tag": "Capabilities",
  "home.cap.h2": "一つのクライアントに、AI ワークスペース全体を",
  "home.cap.c1t": "ローカル＋クラウド ハイブリッドルーティング",
  "home.cap.c1d": "オフライン時は Ollama ローカル、オンライン時は自動でクラウド旗艦モデルに。会話中でも自由にモデルを切り替え。",
  "home.cap.c2t": "17 人の分野専門家が協働",
  "home.cap.c2d": "目標を渡すと AdminAgent がサブタスクを分解し、適切な専門家に割り当て、結果を統合。",
  "home.cap.c3t": "4層メモリ",
  "home.cap.c3d": "常駐事実・セッションアーカイブ・スキル庫・ユーザー像。",
  "home.cap.c4t": "スキルが自動蓄積",
  "home.cap.c4d": "成功したフローは自動で再利用可能なスキルに抽出。",
  "home.cap.c5t": "本物のファイル操作",
  "home.cap.c5d": "ドキュメントや表の読み書き、スクリプト実行、ウィンドウ操作。",

  "home.feat.tag": "All Features",
  "home.feat.h2": "すべての機能、クリックで詳細表示",
  "home.feat.p": "どのカードも詳細ページを開きます。何ができるか、使い方、技術の要点を。",

  "home.wf.tag": "Workflow",
  "home.wf.h2": "繰り返す流れを、ドラッグでパイプラインに",
  "home.wf.i1t": "自由なドラッグ＆接続",
  "home.wf.i1d": "ブロックのように流れを組み、一箇所変えても作り直し不要。",
  "home.wf.i2t": "各ステップを即プレビュー",
  "home.wf.i2d": "テキスト・画像・動画・音声を、ノードをクリックするだけで確認。",
  "home.wf.i3t": "ワンクリックテンプレ",
  "home.wf.i3d": "AI ショート／楽曲／コンセプト画は最初から組み込み。",
  "home.wf.memtag": "Memory",
  "home.wf.memh2": "毎回ゼロから始めない",
  "home.wf.mem.i1t": "話題を変えても途切れない",
  "home.wf.mem.i1d": "先週頼んだ要件を今週もそのまま続けられる。",
  "home.wf.mem.i2t": "フローがスキルになる",
  "home.wf.mem.i2d": "同じ作業は二回目から一文で済む。",

  "home.mem.l1t": "常駐メモリ",
  "home.mem.l1d": "最も重要な事実と好みを毎ターン注入。容量上限で価値ある数件だけを保持。",
  "home.mem.l2t": "セッションアーカイブ",
  "home.mem.l2d": "全履歴をローカル保存し、キーワード命中数で検索。",
  "home.mem.l3t": "スキル庫",
  "home.mem.l3d": "成功したフローが自動で蓄積・再利用される。",
  "home.mem.l4t": "ユーザー像",
  "home.mem.l4d": "話し方や分野知識が長く蓄積し、あなたらしい返答に。",

  "home.models.tag": "Models",
  "home.models.h2": "使いたいモデルはだいたい揃っています",
  "home.models.m1": "Ollama ローカル",
  "home.models.m2": "DeepSeek V4",
  "home.models.m3": "Qwen3.8 Max",
  "home.models.m4": "GLM 5.3",
  "home.models.m5": "Kimi K3",
  "home.models.m6": "Doubao Seed",
  "home.models.m7": "Claude Opus / Sonnet",
  "home.models.m8": "GPT-5.6",
  "home.models.m9": "Gemini",
  "home.models.m10": "Kling",
  "home.models.m11": "Suno 楽曲",
  "home.models.m12": "OpenRouter 全量",

  "home.price.tag": "Pricing",
  "home.price.h2": "まず無料で、必要ならアップグレード",
  "home.price.free.name": "無料",
  "home.price.free.li1": "ローカルモデル無制限",
  "home.price.free.li2": "基本チャット＆ファイル操作",
  "home.price.free.li3": "広告あり",
  "home.price.free.li4": "コミュニティサポート",
  "home.price.free.cta": "無料ダウンロード",
  "home.price.std.flag": "最も人気",
  "home.price.std.name": "スタンダード",
  "home.price.std.li1": "より長い文脈＆記憶",
  "home.price.std.li2": "コスパ重視のクラウドモデル",
  "home.price.std.li3": "広告なし",
  "home.price.std.li4": "ワークフロー全機能",
  "home.price.std.cta": "スタンダードへ",
  "home.price.pro.name": "プロ",
  "home.price.pro.li1": "全フラッグシップモデル",
  "home.price.pro.li2": "AI 動画／楽曲生成",
  "home.price.pro.li3": "複数専門家協働",
  "home.price.pro.li4": "優先サポート",
  "home.price.pro.cta": "プロへ",
  "home.price.ult.flag": "近日公開",
  "home.price.ult.name": "アルティメット",
  "home.price.ult.li1": "超大文脈",
  "home.price.ult.li2": "専用最上位モデル",
  "home.price.ult.li3": "チーム協働（構想中）",
  "home.price.ult.li4": "—",
  "home.price.ult.cta": "近日公開",

  "home.faq.h2": "よくある質問",
  "home.faq.q1": "オフラインでも使えますか？",
  "home.faq.a1": "はい。ローカル Ollama モデルは完全オフラインで動き、チャット・ファイル操作・ワークフロー編成はネットに依存しません。",
  "home.faq.q2": "データはアップロードされますか？",
  "home.faq.a2": "いいえ。会話履歴・ナレッジ・記憶はすべて手元の端末に残ります。",
  "home.faq.q3": "無料版の制限は？",
  "home.faq.a3": "無料版は全ローカル機能と基本ツールを広告付きで利用可能。クラウド旗艦モデルや AI 動画／楽曲生成は有料です。",
  "home.faq.q4": "対応OSは？",
  "home.faq.a4": "Windows と macOS。モバイル（Android / iOS / HarmonyOS）は構想中。",

  "home.cta.h2": "今すぐ AI に働かせよう",
  "home.cta.p": "無料版は永久に利用可能、1分でインストール、クレジットカード不要。",
  "home.cta.btn": "Working Mate を無料ダウンロード",

  "home.foot.copy": "© 2026 Working Mate・ローカル主体の AI ワークスペース",
  "home.foot.privacy": "プライバシー",
  "home.foot.terms": "規約",
  "home.foot.refunds": "返金",

  "feat.nav.features": "機能",
  "feat.nav.workflow": "ワークフロー",
  "feat.nav.models": "モデル",
  "feat.nav.pricing": "料金",
  "feat.nav.download": "無料ダウンロード",
  "feat.foot.copy": "© 2026 Working Mate・ローカル主体の AI ワークスペース",
  "feat.foot.features": "機能",
  "feat.foot.privacy": "プライバシー",
  "feat.foot.terms": "規約",
  "feat.foot.refunds": "返金",
  "feat.tpl.back": "機能一覧へ戻る",
  "feat.tpl.what": "できること",
  "feat.tpl.how": "使い方",
  "feat.tpl.tech": "技術の要点",
  "feat.tpl.shot": "見てみる",
  "feat.tpl.related": "関連機能",
  "feat.tpl.end": "試してみよう",
  "feat.tpl.endP": "無料版は永久に利用可能。ローカル機能はそのまま使え、クレジットカード不要。",
  "feat.tpl.endBtn": "Working Mate を無料ダウンロード",
  "feat.tpl.view": "詳細を見る →",
  "feat.tpl.heroCta1": "無料ダウンロードを試す",
  "feat.tpl.heroCta2": "他の機能を見る",

  "feat.models.title": "マルチモデル ハイブリッドルーティング",
  "feat.models.tag": "Multi-Model Router",
  "feat.models.sub": "ローカル Ollama とクラウド旗艦を一つの入力欄に。オフライン時はローカル、オンライン時はクラウドへ自動切替。再起動も設定もなしに会話中でモデルを交換。",
  "feat.models.fact0": "60+ モデル",
  "feat.models.fact1": "ローカル／クラウド統合",
  "feat.models.fact2": "自動フォールバック",
  "feat.models.fact3": "データ送出 0（ローカル）",
  "feat.models.grid": "60+ モデル・ローカル／クラウド統合入口",
  "feat.models.what0t": "一つの入力、全モデル",
  "feat.models.what0d": "API 管理もタブ散らかしも不要。DeepSeek、Qwen、GLM、Kimi、Doubao、GPT、Claude、Gemini、OpenRouter が一つのドロップダウンに。",
  "feat.models.what1t": "ローカル優先、オフライン可",
  "feat.models.what1d": "Ollama を繋げば完全オフライン。チャット・ファイル操作・ワークフロー編成はネット不要でデータは外に出ない。",
  "feat.models.what2t": "3段階モデル戦略",
  "feat.models.what2d": "スタンダード／プロ／フラッグシップをワンクリック切替。システムがタスクごとに最強コスパを自動選択、または手動指定。",
  "feat.models.what3t": "マルチモデル自動降格",
  "feat.models.what3d": "制限または 5xx 時は次の候補へ自動。残高不足や認証失敗のみ停止して明確に通知。暗黙の失敗なし。",
  "feat.models.what4t": "専門家がモデル群を保有",
  "feat.models.what4d": "17 人の専門家が各々 推理／汎用／コード のモデル群を束ね、コーダーはコード、ライターは文章モデルを。",
  "feat.models.what5t": "同一セッションで即交換",
  "feat.models.what5d": "途中でモデルを変えても文脈維持。「その場で頭脳を交換」が本当に。",
  "feat.models.step0": "設定 → モデルと実行環境でティアを選択（スタンダード／プロ／フラッグシップ）。",
  "feat.models.step1": "オフラインならローカル Ollama を起動。クライアントが自動検出。",
  "feat.models.step2": "上部ドロップダウンでモデルを選ぶか、「自動ルーティング」に任せる。",
  "feat.models.step3": "オフラインはローカルに、オンラインはクラウドに自動復帰。手動不要。",
  "feat.models.tech0": "統一 cloud_client 抽象層。ローカル／クラウドで同一呼び出し署名。",
  "feat.models.tech1": "429 は「制限」と「残高不足」を区別。制限は Retry-After で一度再試行、残高不足は即停止してチャージを促す。",
  "feat.models.tech2": "フォールバック連鎖は制限／5xx のみ切替。認証エラーは切替えず（無駄な課金回避）。",
  "feat.models.tech3": "モデルは「ティア×用途」で索引。専門家がモデル群を直接参照。",
  "feat.models.shot": "一つの入力、ローカルとクラウドを接続",

  "feat.experts.title": "17 人の分野専門家が協働",
  "feat.experts.tag": "Expert Team",
  "feat.experts.sub": "目標を渡すと AdminAgent がサブタスクを分解し、適切な専門家に割り当て、一つの結果に統合。プロンプトも分解も不要。",
  "feat.experts.fact0": "17 人の専門家",
  "feat.experts.fact1": "自動分解／割当",
  "feat.experts.fact2": "サブタスク当たり≤10回呼出",
  "feat.experts.fact3": "結果を自動統合",
  "feat.experts.grid": "17 人の専門家・自動分解／割当",
  "feat.experts.what0t": "一文で指示",
  "feat.experts.what0d": "「このExcelの3ヶ月売上をトレンド図にして分析を書いて」と言えば、読取→整形→図→分析に分解して割当。",
  "feat.experts.what1t": "17 人の専門家",
  "feat.experts.what1d": "研究・動画ショート・画像デザイン・音楽・トレード・保険数理・一人企業・ソフト架構・AI・プロンプト・フルスタックCodex・オフィス・コード・ライティング・データサイエンス・運用・汎用。",
  "feat.experts.what2t": "AdminAgent が分解",
  "feat.experts.what2d": "主制御エージェントが目標を読み→サブタスク一覧（依存付き）を生成→各専門家へ Dispatch。",
  "feat.experts.what3t": "専門家がモデル群を保有",
  "feat.experts.what3d": "各専門家が 推理／汎用／コード のモデル群と画像／動画／音楽の生成モデルを束ねる。",
  "feat.experts.what4t": "ツール呼出に境界",
  "feat.experts.what4d": "サブタスク当たり最大10回。許可／拒否リストで無限実行や危険呼出を防止。",
  "feat.experts.what5t": "一つの成果に統合",
  "feat.experts.what5d": "全サブタスク完了後、自動で一つの使える出力に統合。バラバラの断片ではなく。",
  "feat.experts.step0": "上部の「エージェントモード」をオン。",
  "feat.experts.step1": "目標を具体的に記述。自分で分解不要。",
  "feat.experts.step2": "エージェントが先にサブタスク一覧を提示。確認して開始。",
  "feat.experts.step3": "実行中いつでも緊急停止でき、各サブタスクの状態と成果を確認可能。",
  "feat.experts.tech0": "分解と実行が同一マルチモデル降格連鎖を共有。制限で全体崩壊しない。",
  "feat.experts.tech1": "失敗したサブタスクは依存先のみスキップ。他分枝は継続。",
  "feat.experts.tech2": "空間間呼出に上限（ループ防止）で専門家間の相互派遣を防止。",
  "feat.experts.tech3": "分解結果の解析失敗は本当の理由を投げ、空を黙示しない。",
  "feat.experts.shot": "目標 → サブタスク → 専門家実行",

  "feat.memory.title": "4層メモリシステム",
  "feat.memory.tag": "Memory",
  "feat.memory.sub": "毎回ゼロから始めない。重要事実・過去セッション・実証済フロー・好みと話し方が4層のメモリに沈殿。使うほどあなたを理解する。",
  "feat.memory.fact0": "4層メモリ",
  "feat.memory.fact1": "中国語 n-gram 検索",
  "feat.memory.fact2": "ローカル SQLite",
  "feat.memory.fact3": "容量上限で絞込",
  "feat.memory.grid": "4層メモリ・中国語 n-gram 検索",
  "feat.memory.what0t": "L1 常駐メモリ",
  "feat.memory.what0d": "最も重要な事実と好みを毎ターン注入。容量上限で価値ある数件だけ保持を強制。",
  "feat.memory.what1t": "L2 セッションアーカイブ",
  "feat.memory.what1d": "全履歴をローカル保存。キーワード命中数で関連数件を検索し、必要時のみ注入。",
  "feat.memory.what2t": "L3 スキル庫",
  "feat.memory.what2d": "実証済フローが自動で再利用スキルに。二回目は一文で再現。",
  "feat.memory.what3t": "L4 ユーザー像",
  "feat.memory.what3d": "話し方・分野知識・習慣が長く蓄積し、あなたらしい返答に。",
  "feat.memory.what4t": "話題を変えても途切れない",
  "feat.memory.what4d": "先週の要件を今週も継続。別話題を往復しても文脈を覚えている。",
  "feat.memory.what5t": "メモリは確認・削除可能",
  "feat.memory.what5d": "サイドバー「メモリファイル」は常に閲覧可。誤りは消去や修正が可能。",
  "feat.memory.step0": "普通にチャットするだけ。手動で「覚えて」不要。",
  "feat.memory.step1": "サイドバー「メモリファイル」で現在の L1 常駐と L4 像を表示。",
  "feat.memory.step2": "「メモリクリーンアップ」で層単位の消去やセッション削除。",
  "feat.memory.step3": "硬いルールを覚えさせたいなら会話で述べるだけで長期事実に。",
  "feat.memory.tech0": "中国語は2〜4文字 n-gram と英単語分割で全文LIKEの低命中を解決。",
  "feat.memory.tech1": "L2 は命中数で採点。SQLite FTS5 不可時は通常表＋LIKEに自動降格。",
  "feat.memory.tech2": "軽量要約はLLMを呼ばず首尾ターン結合でコスト抑制。",
  "feat.memory.tech3": "各層に文字上限があり、古い内容で溢れないよう保護。",
  "feat.memory.shot": "メモリファイルはいつでも確認・削除可",

  "feat.skills.title": "スキルの自動蓄積",
  "feat.skills.tag": "Self-Evolving Skills",
  "feat.skills.sub": "実行したフローが自動で再利用可能なスキルとしてスキル庫に抽出される。次回は一文で全体を再現。",
  "feat.skills.fact0": "フローを自動抽出",
  "feat.skills.fact1": "中央スキル庫",
  "feat.skills.fact2": "ローカル保存",
  "feat.skills.fact3": "再利用・共有可",
  "feat.skills.grid": "フローを自動抽出・中央スキル庫",
  "feat.skills.what0t": "一回実行でスキルに",
  "feat.skills.what0d": "一連の操作（読取→処理→出力）が成功すると構造化スキルとして自動抽出。",
  "feat.skills.what1t": "次回は一文で",
  "feat.skills.what1d": "「前回のようにして」と言うだけで庫から一致して実行。手順再記述不要。",
  "feat.skills.what2t": "スキル庫を可視化",
  "feat.skills.what2d": "サイドバー「スキル庫」で閲覧・検索・有効化・削除。",
  "feat.skills.what3t": "4層メモリと連動",
  "feat.skills.what3d": "スキルはL3に属し、ワークフロー・専門家と同一メモリを共有。",
  "feat.skills.what4t": "失敗は汚さない",
  "feat.skills.what4d": "本当に成功したフローのみ蓄積。途中失敗はスキルに記録されない。",
  "feat.skills.what5t": "ローカル保存",
  "feat.skills.what5d": "スキル庫は手元の端末に保存されクラウドへ上げない。",
  "feat.skills.step0": "いつも通りエージェントに複数ステップの作業を完了させる。",
  "feat.skills.step1": "成功後にシステムが自動抽出して格納。",
  "feat.skills.step2": "サイドバー「スキル庫」で新規スキルを確認（改名・削除可）。",
  "feat.skills.step3": "次回はスキルを直接参照、またはエージェントに自動一致させる。",
  "feat.skills.tech0": "スキル抽出はワークフローエンジンと同一ノード／ステップモデルを共有。",
  "feat.skills.tech1": "スキルはローカルファイルとして保存しBackup・移行容易。",
  "feat.skills.tech2": "L1/L2 記憶から分離し、スキル文が常駐予算を圧迫しないよう。",
  "feat.skills.shot": "スキル庫：成功時に蓄積",

  "feat.workflow.title": "ノード式ワークフローキャンバス",
  "feat.workflow.tag": "Workflow Canvas",
  "feat.workflow.sub": "ブロックのように AI を繋いで流れを作る。ドラッグ・接続・実行。各ステップを個別にプレビュー・再実行・プロンプト編集。プロンプトは自分で書いても AI に書かせても。",
  "feat.workflow.fact0": "10 種ノード",
  "feat.workflow.fact1": "ドラッグ＋自動接続＋自動配置",
  "feat.workflow.fact2": "単ノード再実行",
  "feat.workflow.fact3": "プロンプト手書き／AI代筆",
  "feat.workflow.grid": "10 種ノード・ドラッグ＋自動接続＋自動配置",
  "feat.workflow.what0t": "10 ノードで全工程",
  "feat.workflow.what0d": "LLMテキスト・絵コンテ・AI画像・AI動画・AI楽曲・動画合成・ツールノード・テキストカード・ローカル画像・ローカル楽曲。",
  "feat.workflow.what1t": "ドラッグ＋接続",
  "feat.workflow.what1d": "左ライブラリからキャンバスへドラッグし、ノード右端をターゲットへ引っ張って接続。または「⚡ 自動接続」で型ロジック通り一括接続。",
  "feat.workflow.what2t": "自動配置",
  "feat.workflow.what2d": "「⌗ 自動配置」が依存関係で階層配置。散らばりもワンクリックで整列。",
  "feat.workflow.what3t": "各ステップ即プレビュー",
  "feat.workflow.what3d": "ノードをクリックすると右パネルにテキスト／画像／動画／音声の成果をプレイヤー付で表示。",
  "feat.workflow.what4t": "プロンプト完全DIY",
  "feat.workflow.what4d": "各テキスト參数は複数行エディタ。{{ノード名}} で上流成果を参照可。",
  "feat.workflow.what5t": "🪄 AI がプロンプト代筆",
  "feat.workflow.what5d": "一文の意図で AI がノード型別に専門プロンプトを生成（絵コンテ師／アートディレクター／音楽プロデューサー各専用テンプレ）。生成後も手修正可。",
  "feat.workflow.what6t": "テンプレで即実行",
  "feat.workflow.what6d": "内蔵の AIショート／楽曲／コンセプト画はテーマを変えて実行。",
  "feat.workflow.what7t": "信頼性分析",
  "feat.workflow.what7d": "「🛡 信頼性」が欠落パラメータ・欠キー・切断・ループをチェックし採点と修正提示。",
  "feat.workflow.step0": "サイドバー「ワークフロー」を開き、左からノードをドラッグ（または「テンプレ読込」）。",
  "feat.workflow.step1": "接続：ノード右端をターゲットへ。面倒なら「⚡ 自動接続」。",
  "feat.workflow.step2": "ノードをクリックし、このタスクのプロンプトを設定（手書きまたは🪄 AI）。",
  "feat.workflow.step3": "「▶ ワークフロー実行」で全実行。失敗ノードは他分枝をブロックせず。",
  "feat.workflow.step4": "キャンバスをJSON保存。「保存／読込JSON」で再利用・共有。",
  "feat.workflow.tech0": "ノードはフラットdict＋deps。エンジンがトポロジカルに直列実行、失敗分枝は下流自動スキップ。",
  "feat.workflow.tech1": "プレースホルダは上流成果を参照し、リスト第N項（例：絵コンテ第1カット）を取得可。",
  "feat.workflow.tech2": "パラメタは型で正規化（秒数→int、インスト含む→bool）でクラウド型エラー回避。",
  "feat.workflow.tech3": "LLMノード戻り値にエラーフラグ検出で、エラー文が脚本として下流へ流れるのを防止。",
  "feat.workflow.shot": "ノードキャンバス：ドラッグ・接続・ノード別プレビュー",

  "feat.media.title": "AI メディアファクトリー",
  "feat.media.tag": "AI Media Studio",
  "feat.media.sub": "一つのテーマから完成クリップへ：脚本→絵コンテ→AI動画ショット→BGM→字幕→合成、すべてクライアント内組込。サイトを行ったり来たり不要。",
  "feat.media.fact0": "脚本／絵コンテ／動画／楽曲",
  "feat.media.fact1": "字幕＋GIF",
  "feat.media.fact2": "縦 9:16",
  "feat.media.fact3": "自動アーカイブ",
  "feat.media.grid": "脚本／絵コンテ／動画／楽曲・字幕＋GIF",
  "feat.media.what0t": "脚本生成",
  "feat.media.what0d": "テーマを渡すと60秒3カットのミクロドラマ脚本と、各カットの画像プロンプトを自動切出。",
  "feat.media.what1t": "絵コンテ分解",
  "feat.media.what1d": "脚本のカット記述を構造リストに自動抽出し、動画ノードへ順次投入。",
  "feat.media.what2t": "AI 動画ショット",
  "feat.media.what2d": "文→動画で各カット生成。縦9:16、秒数可変、単カット再実行可。",
  "feat.media.what3t": "背景音楽",
  "feat.media.what3d": "脚本のムードでインストゥルメンタル主題を生成、またはAIに歌詞付き楽曲を作成。",
  "feat.media.what4t": "AI 画像",
  "feat.media.what4d": "映画的コンセプト画・表紙・絵コンテ参考画、比率選択可。",
  "feat.media.what5t": "字幕＆GIF",
  "feat.media.what5d": "字幕ファイルを自動生成、またはクリップをGIF出力。",
  "feat.media.what6t": "動画合成",
  "feat.media.what6d": "複数カットを順に一つのクリップに合成出力。",
  "feat.media.what7t": "ローカル素材挿入可",
  "feat.media.what7d": "自身の画像や楽曲をワークフローに参考／楽曲として投入しAI成果と混合。",
  "feat.media.step0": "ワークフロー → 「🎬 AIショート（3カット＋楽曲）」テンプレ読込。",
  "feat.media.step1": "テーマをこのタスクに変更（例「働く龍の日常」）。",
  "feat.media.step2": "脚本ノードをクリックし手書きまたは🪄 AI。確認して実行。",
  "feat.media.step3": "ノード別プレビュー：先に脚本と絵コンテ、次に生成ショット動画と楽曲。",
  "feat.media.step4": "合成ノードがクリップ出力。成果はタスク保管フォルダへ自動配置。",
  "feat.media.tech0": "動画／楽曲／画像は可灵・Suno・画像モデルに統一ツールレジストリ経由。",
  "feat.media.tech1": "メディアノードは従量課金。UIにコストを明記（無料版はローカルで練習可）。",
  "feat.media.tech2": "カット数・比率・秒数は編集可。カットプロンプトは上流の上書きをサポート。",
  "feat.media.tech3": "成果パスをノードへ自動還填。次回再実行は直接再利用。",
  "feat.media.shot": "脚本 → 絵コンテ → ショット → 楽曲",

  "feat.modules.title": "6 業界シナリオモジュール",
  "feat.modules.tag": "Scenarios",
  "feat.modules.sub": "研究・動画・画像・金融・ソフト・成長——6つのすぐ使えるシナリオ入口。各々専門家・ツール・クイックカードを事前設定。クリックで開始。",
  "feat.modules.fact0": "6 シナリオ",
  "feat.modules.fact1": "事前クイックカード",
  "feat.modules.fact2": "多言語",
  "feat.modules.fact3": "ローカル／クラウド",
  "feat.modules.grid": "6 シナリオ・事前クイック開始カード",
  "feat.modules.what0t": "研究",
  "feat.modules.what0d": "論文検索・資料整理・構造化要約と比較。レビューや提案に最適。",
  "feat.modules.what1t": "動画＆画像作成",
  "feat.modules.what1d": "ショート脚本からクリップ、コンセプト＆表紙デザイン。作成専門家と接続。",
  "feat.modules.what2t": "金融＆投資",
  "feat.modules.what2d": "相場データ・企業情報・ロング／ショート根拠とリスク。トレーダー／保険数理と接続。",
  "feat.modules.what3t": "ソフト＆コード",
  "feat.modules.what3d": "要件分解・コード生成・デバッグ・手軽なスクリプト実行。架構者／フルスタックCodexと接続。",
  "feat.modules.what4t": "成長＆マーケ",
  "feat.modules.what4d": "ネタ・コピー・キャンペーン企画・成長実験設計。",
  "feat.modules.what5t": "各モジュールにクイックカード",
  "feat.modules.what5d": "プロンプトをゼロから書かず、カードを押すだけで既製タスクテンプレを使用。",
  "feat.modules.step0": "サイドバー「NAVIGATION」でシナリオ選択（研究／動画／画像／金融／ソフト／成長）。",
  "feat.modules.step1": "シナリオ内のクイックカードをクリック、または要件を記述。",
  "feat.modules.step2": "跨シナリオならプロジェクト空間が複数シナリオの成果を一つに集約。",
  "feat.modules.tech0": "シナリオカードは「タスクテンプレ＋専門家＋ツール」の組合せ。全部ローカル定義で編集可。",
  "feat.modules.tech1": "シナリオは同一ツールレジストリと記憶を共有。成果が相互運用。",
  "feat.modules.tech2": "UIは10言語対応。シナリオカード文案が切替に追従。",
  "feat.modules.shot": "シナリオカード：クリックで作業開始",

  "feat.spaces.title": "プロジェクト空間＆タスクセンター",
  "feat.spaces.tag": "Projects & Tasks",
  "feat.spaces.sub": "一つの目標に一つの空間。複数タスクを並行し混ざらない。全成果・ログ・文脈を空間に保管し、いつでも再開。",
  "feat.spaces.fact0": "並行タスク",
  "feat.spaces.fact1": "空間レベル文脈分離",
  "feat.spaces.fact2": "自動保管",
  "feat.spaces.fact3": "かんばん進捗",
  "feat.spaces.grid": "並行タスク・空間レベル文脈分離",
  "feat.spaces.what0t": "プロジェクト空間",
  "feat.spaces.what0d": "プロジェクトごとに空間を開く。目標・添付・成果・チャット履歴は別保管され他に汚されない。",
  "feat.spaces.what1t": "並行タスク",
  "feat.spaces.what1d": "一つの空間で複数サブタスクを並行。各々が独自の進捗。",
  "feat.spaces.what2t": "タスクセンターかんばん",
  "feat.spaces.what2d": "全タスクを一つの盤面に。状態・時間・成果・失敗理由が一目で。",
  "feat.spaces.what3t": "文脈バス",
  "feat.spaces.what3d": "空間間で限度内に成果を相互参照。呼出上限で循環依存を防止。",
  "feat.spaces.what4t": "成果保管",
  "feat.spaces.what4d": "生成ファイル・画像・動画・表が空間フォルダへ自動配置。探さなくて済む。",
  "feat.spaces.what5t": "いつでも再開",
  "feat.spaces.what5d": "クライアントを閉じて開いても空間と進捗は残る。",
  "feat.spaces.step0": "サイドバー「プロジェクト空間」→ 新規空間。目標を記述し参考ファイルを添付。",
  "feat.spaces.step1": "目標をエージェントへ。並行サブタスクに分解。",
  "feat.spaces.step2": "「タスクセンター」で全体進捗と各タスクの成果を表示。",
  "feat.spaces.step3": "完了後は空間フォルダから全成果を取得。続けるなら同じ空間で。",
  "feat.spaces.tech0": "空間間は文脈バスで成果参照を渡す。跨空間呼出に上限でループ防止。",
  "feat.spaces.tech1": "タスク状態と成果パスは永続化。再起動で消失しない。",
  "feat.spaces.tech2": "各空間の実行ログを別保存しステップ追跡容易。",
  "feat.spaces.shot": "プロジェクト空間：目標・タスク・成果を一処に",

  "feat.task_center.title": "タスクセンター",
  "feat.task_center.tag": "Task Center",
  "feat.task_center.sub": "全タスクを一つのかんばんに。誰が実行中、どのステップ、どれだけかかった、何を産出、なぜ失敗——一目で。",
  "feat.task_center.fact0": "中央盤面",
  "feat.task_center.fact1": "状態リアルタイム",
  "feat.task_center.fact2": "失敗原因可朔",
  "feat.task_center.fact3": "ワンクリック開封",
  "feat.task_center.grid": "中央盤面・状態リアルタイム更新",
  "feat.task_center.what0t": "一画面で全部",
  "feat.task_center.what0d": "チャット起点・エージェント分解・定期実行を問わず、すべて一つの一覧に。",
  "feat.task_center.what1t": "リアルタイム状態",
  "feat.task_center.what1d": "待機中／実行中／完了／失敗／スキップ。状態変化を即刷新。",
  "feat.task_center.what2t": "失敗が分かる",
  "feat.task_center.what2d": "失敗は単なる「エラー」ではなく、具体的ステップと理由（欠キー・制限・ファイル不存在…）を提示。",
  "feat.task_center.what3t": "成果直結",
  "feat.task_center.what3d": "タスクを開くと産出ファイル・画像・動画・表を開く。",
  "feat.task_center.what4t": "ワークフローと連携",
  "feat.task_center.what4d": "ワークフロー各ノードの結果もタスクログに残りステップ追跡容易。",
  "feat.task_center.step0": "サイドバー「タスクセンター」で全タスク表示。",
  "feat.task_center.step1": "タスクをクリックし詳細：ステップ・時間・成果・ログ。",
  "feat.task_center.step2": "失敗タスクは原因を突き止めそのステップを再実行。",
  "feat.task_center.tech0": "タスク／ステップの2階層。ステップ級でツール名・パラメタ・時間・結果を記録。",
  "feat.task_center.tech1": "実行とUIスレッド分離。長タスクでUI停止せず、スレッド異常終了時はボタン状態を自動復帰。",
  "feat.task_center.shot": "タスクセンター：状態・時間・成果",

  "feat.automation.title": "自動化＆定期タスク",
  "feat.automation.tag": "Automation",
  "feat.automation.sub": "AI にあなたのリズムで働かせる。毎朝ニュースを整理、毎週データを集計、時間通りに通知——見てなくても動く。",
  "feat.automation.fact0": "定期／周期実行",
  "feat.automation.fact1": "ローカルスケジューラ",
  "feat.automation.fact2": "履歴記録",
  "feat.automation.fact3": "失敗可視",
  "feat.automation.grid": "定期／周期実行・ローカルスケジューラ",
  "feat.automation.what0t": "一文で作成",
  "feat.automation.what0d": "「毎朝9時に昨日の業界ニュースを要約して」と言うだけで自動化ができる。",
  "feat.automation.what1t": "周期と一回両対応",
  "feat.automation.what1d": "毎日・毎週・毎月、または指定時刻に一度だけ。",
  "feat.automation.what2t": "ローカルスケジュール",
  "feat.automation.what2d": "スケジュールとデータは手元に留まりアップロードされない。",
  "feat.automation.what3t": "実行履歴",
  "feat.automation.what3d": "何回実行、各結果、失敗の有無を記録。",
  "feat.automation.what4t": "一時停止＆削除可",
  "feat.automation.what4d": "不要ならいつでも一時停止または削除。",
  "feat.automation.step0": "サイドバー「自動化」→ 新規。何をするかを記述。",
  "feat.automation.step1": "時間と頻度を設定（毎日／毎週／指定時刻一度）。",
  "feat.automation.step2": "保存後、一覧で次回実行時刻と履歴を表示。",
  "feat.automation.tech0": "自動化定義と実行状態を別永続化。再起動後もスケジュール維持。",
  "feat.automation.tech1": "各実行を独立記録し、内容か環境かの判別を容易に。",
  "feat.automation.shot": "あなたのリズムで自動的に働く",

  "feat.gui.title": "GUI 自動化",
  "feat.gui.tag": "Computer Control",
  "feat.gui.sub": "AI に手元の他プログラムを操作させる。ボタンをクリックし、フォームを埋め、メニューを開く——APIのない古いソフトも自動化。",
  "feat.gui.fact0": "マウス＆キーボード模拟",
  "feat.gui.fact1": "事前能力検出",
  "feat.gui.fact2": "操作ごと確認",
  "feat.gui.fact3": "いつでも切替",
  "feat.gui.grid": "マウス＆キーボード模拟・事前能力検出",
  "feat.gui.what0t": "人間のようにUI操作",
  "feat.gui.what0d": "AI が現在の窓を見て、どこをクリックし何を入力するか決め一歩ずつ進行。",
  "feat.gui.what1t": "開始前に能力検出",
  "feat.gui.what1d": "システムが先に環境対応を確認。非対応なら黙って失敗せず理由を通知。",
  "feat.gui.what2t": "操作前に確認",
  "feat.gui.what2d": "既定で重要操作ごとに問い合わせ。自動確認モードのみプロンプトをスキップ。",
  "feat.gui.what3t": "危険動作も遮断",
  "feat.gui.what3d": "削除／上書き等の破壊的動作は自動確認でも解放されない。",
  "feat.gui.what4t": "いつでも切替",
  "feat.gui.what4d": "ワンクリックでオフ。AI は即座にマウス／キーボード制御を失う。",
  "feat.gui.step0": "設定 → 「GUI自動化」を有効化。まず能力検出を通過。",
  "feat.gui.step1": "行う操作を記述（具体的なほど良い）。",
  "feat.gui.step2": "促された重要動作を都度確認。",
  "feat.gui.step3": "完了後にスイッチをオフ。",
  "feat.gui.tech0": "能力検出は有効時に実行・キャッシュし、途中で環境非対応になるのを防止。",
  "feat.gui.tech1": "操作粒度は設定可。既定は都度確認。",
  "feat.gui.tech2": "自動確認と連動。明示的な自動確認のみプロンプトをスキップ。",
  "feat.gui.shot": "APIのない古いソフトも自動化",

  "feat.safety.title": "安全ガードレール：自動確認＆緊急停止",
  "feat.safety.tag": "Safety",
  "feat.safety.sub": "与えるべき権限は与え、遮断すべきは遮断。書込はステップごと確認、または自動確認で高速化——でも危険動作は常に遮断、削除は必ずごみ箱へ。",
  "feat.safety.fact0": "レベル：WARNING／BLOCKED",
  "feat.safety.fact1": "自動確認モード",
  "feat.safety.fact2": "ワンクリック停止",
  "feat.safety.fact3": "削除→ごみ箱",
  "feat.safety.grid": "レベル：WARNING／BLOCKED・自動確認モード",
  "feat.safety.what0t": "既定はステップごと確認",
  "feat.safety.what0d": "書込・データ変更・コマンドは毎回ポップアップ。あなたの「はい」のみ実行。",
  "feat.safety.what1t": "自動確認（高速モード）",
  "feat.safety.what1d": "信頼後は有効化。通常書込はプロンプトを止めて一直線。検証済み反復フローに向く。",
  "feat.safety.what2t": "危険は依然遮断",
  "feat.safety.what2d": "BLOCKED 級の破壊的動作は自動確認でも解放されず、常にあなたの了承が必要。",
  "feat.safety.what3t": "削除→ごみ箱",
  "feat.safety.what3d": "AI の削除は既定でごみ箱へ。消されず誤っても復元可。",
  "feat.safety.what4t": "ワンクリック緊急停止",
  "feat.safety.what4d": "実行中に何かおかしければ緊急停止で実行中タスクを即終了。",
  "feat.safety.what5t": "ツール許可／拒否リスト",
  "feat.safety.what5d": "呼出可能ツールを許可リストに限定。拒否リストはいかなる場合も呼出不能。",
  "feat.safety.step0": "既定は「操作ごと確認」。設定不要。",
  "feat.safety.step1": "信頼が十分なら「自動確認」を有効化。有効化時に一度確認。",
  "feat.safety.step2": "上部バーからいつでも無効化しステップごと確認へ。",
  "feat.safety.step3": "実行中は「停止」で現在のタスクを緊急停止。",
  "feat.safety.tech0": "動作をリスクで格付け。WARNING は自動確認可、BLOCKED は常に遮断。",
  "feat.safety.tech1": "ツール呼出は許可＋拒否リストの二重制限。サブタスク当たり≤10回。",
  "feat.safety.tech2": "削除は一律ごみ箱バックアップ経路で復元性を確保。",
  "feat.safety.shot": "権限は与え、遮断すべきは遮断",

  "feat.files.title": "本物のファイル操作",
  "feat.files.tag": "Real File Work",
  "feat.files.sub": "ただ話すだけでない。ドキュメントや表を読み、内容を編集し、新ファイルを生成し、スクリプトを実行し、一括処理——そしてファイルを渡す。",
  "feat.files.fact0": "Office／表の読書",
  "feat.files.fact1": "スクリプト実行",
  "feat.files.fact2": "一括処理",
  "feat.files.fact3": "画像ドラッグ／貼付",
  "feat.files.grid": "Office／表の読書・スクリプト実行",
  "feat.files.what0t": "ファイルを理解",
  "feat.files.what0d": "Word・Excel・PPT・PDF・画像を放り込めば内容を読んで作業。",
  "feat.files.what1t": "編集後も同じ形式",
  "feat.files.what1d": "元形式で編集・別名保存。自分でコピー戻すテキストではない。",
  "feat.files.what2t": "新ファイル生成",
  "feat.files.what2d": "表・報告・リスト・図表を直接開けるファイルに出力。",
  "feat.files.what3t": "スクリプト実行",
  "feat.files.what3d": "一括でスクリプト実行。出力はチャットへ還流。",
  "feat.files.what4t": "ドラッグ＆貼付",
  "feat.files.what4d": "ファイルを入力へドロップで文脈に。クリップボード画像はCtrl+Vで添付に。",
  "feat.files.what5t": "成果保管",
  "feat.files.what5d": "生成ファイルはタスクフォルダへ。取り出し容易。",
  "feat.files.step0": "ファイルを入力へドロップ（または画像をCtrl+V貼付）。",
  "feat.files.step1": "「この表を月ごとに集計しトレンド図を」と指示。",
  "feat.files.step2": "AI が完了時に新ファイルを渡す。開いて使用。",
  "feat.files.tech0": "ファイル読書は統一ツール層を通りワークフローノードと共有。",
  "feat.files.tech1": "大きなファイルは先に構造解析し全文を文脈へ詰め込まない。",
  "feat.files.tech2": "生成成果パスを還填し後日参照と再処理を容易に。",
  "feat.files.shot": "放り込み、編集、ファイルを返す",

  "feat.i18n.title": "多言語インターフェース",
  "feat.i18n.tag": "i18n",
  "feat.i18n.sub": "UI は10言語をリアルタイム切替。即時で再起動不要。海外ユーザーやチーム協働に便利。",
  "feat.i18n.fact0": "10 言語",
  "feat.i18n.fact1": "リアルタイム切替",
  "feat.i18n.fact2": "UI＋シナリオカード",
  "feat.i18n.fact3": "拡張可能",
  "feat.i18n.grid": "10 言語・リアルタイム切替",
  "feat.i18n.what0t": "10 言語",
  "feat.i18n.what0d": "简体中文、English、日本語、한국어、Deutsch、Français、Español、Português、Русский、العربية。",
  "feat.i18n.what1t": "切替は即時反映",
  "feat.i18n.what1d": "設定で言語を変えるとUI文案が即更新。再起動不要。",
  "feat.i18n.what2t": "網羅",
  "feat.i18n.what2d": "メインUI・設定・ワークフローキャンバス・シナリオカード文案が同一多言語層を共有。",
  "feat.i18n.what3t": "翻訳拡張可能",
  "feat.i18n.what3d": "言語資源は別ファイル。言語追加は一つ書くだけ。",
  "feat.i18n.step0": "設定 → UI言語で言語を選択。",
  "feat.i18n.step1": "再起動を促されたら一度再起動で全体反映。",
  "feat.i18n.tech0": "全UI文案は実行時翻訳関数で取得し、インポート時に中国語を固化しない。",
  "feat.i18n.tech1": "言語資源は別ファイルで校閲と追加が容易。",
  "feat.i18n.shot": "",

  "feat.privacy.title": "ローカル主体＆プライバシー",
  "feat.privacy.tag": "Local First",
  "feat.privacy.sub": "会話・記憶・ナレッジ・スキル・成果はすべて既定で自身の端末。完全オフラインで動き、クラウドはあなたが能動的に選んだモデルのみ。",
  "feat.privacy.fact0": "データ送出 0（ローカル）",
  "feat.privacy.fact1": "オフライン可",
  "feat.privacy.fact2": "全て端末内",
  "feat.privacy.fact3": "ローカルDB",
  "feat.privacy.grid": "データ送出 0（ローカル）・オフライン可",
  "feat.privacy.what0t": "データは端末に留まる",
  "feat.privacy.what0d": "会話履歴・4層記憶・スキル庫・プロジェクト成果はローカルファイル／DBに保存。",
  "feat.privacy.what1t": "オフライン可",
  "feat.privacy.what1d": "ローカルモデルがあればチャット・ファイル操作・ワークフロー編成はネット不要。",
  "feat.privacy.what2t": "クラウドはあなたの選択",
  "feat.privacy.what2d": "クラウドモデルやクラウド生成を選んだ時のみ関連内容が提供元へ。",
  "feat.privacy.what3t": "ワンクリッククリーン",
  "feat.privacy.what3d": "「メモリクリーンアップ」で層単位の消去やセッション削除。本当に消える。",
  "feat.privacy.what4t": "アカウント不要",
  "feat.privacy.what4d": "無料版は登録を強制せず。ローカル機能はすぐ使える。",
  "feat.privacy.step0": "完全オフラインならローカルモデルのみ使用。",
  "feat.privacy.step1": "記録を消すにはサイドバー「メモリクリーンアップ」。",
  "feat.privacy.step2": "あるチャットが敏感ならクラウドモデルを選ばないだけ。",
  "feat.privacy.tech0": "ローカル保存はSQLiteとローカルディレクトリ。自築クラウド不要。",
  "feat.privacy.tech1": "クラウド呼出は設定した提供元キー経由で直接APIへ。",
  "feat.privacy.tech2": "記憶層は各々消去可。「一つ消すと全部消える」を防止。",
  "feat.privacy.shot": "全て端末内、オフラインで動く",
  "home.price.free.li0": "新規登録で3000クレジット（全モデルお試し可）",
  "home.price.std.li0": "毎月800クレジット付き",
  "home.price.pro.li0": "毎月3000クレジット付き",
  "home.price.ult.li0": "毎月10000クレジット付き",
  "home.price.max.li1": "新規3000クレジット · 月上限なしの従量制",
  "feat.membership.grid": "5プラン · 新規3000クレジット · 毎日チェックイン",
  "feat.channels.grid": "国内直連14プリセット · 中国本土では国産モデルを優先",
  "feat.membership.sub": "5つのプランはモデルプールと能力の境界が異なります。無料版はローカル、標準版はコスパ重視、プロ版は国産フラッグシップ、Ultraはエンジニアリング級CAD、Maxは上限なし。新規登録で3000クレジット（全モデルお試し可）。有料プランはサブスクまたはライセンスで解放。",
  "feat.membership.fact1": "新規3000クレジット",
  "feat.membership.what4d": "クラウド呼び出しに月上限なし。クレジットは従量で実扣（いつでもチャージ可、カード自動課金も可）。専攻Agent（深度研究・自律コーディング・自走CAD・縦型ドラマ絵コンテ）はこのプラン限定。新規3000クレジットもこのプランで使えます。",
  "feat.membership.what5t": "プランはサブスクで解放",
  "feat.membership.what5d": "設定のプラン選択には各プランの状態が表示されます。未購読のプランには 🔒 が付き、選択できません（誤切替防止）。購読またはライセンスキーを入力すると即座に解放され、モデルプール・能力ゲート（CAD・専攻Agent）・モデル数が同期更新されます。再インストールも再ログインも不要です。",
  "feat.membership.what6t": "クレジットが見える",
  "feat.membership.what6d": "残高はステータスバーに常駐し、呼び出しが終わるたびにそのモデルの公開レートで即座に減ります（レートはモデル名のすぐ横に表示）。毎日チェックインで100クレジット（新規は15回）。残高が底を打つと自動で無料版に戻り、チャージを促します — 無言のダウングレードも隠れた課金もありません。",
  "home.price.max.li2": "毎日チェックインで100クレジット",
};
