/* Working Mate — Deutsch */
window.I18N = window.I18N || {};
window.I18N.de = {
  /* ───────── 首页 HOME ───────── */
  "home.nav.capability": "Funktionen",
  "home.nav.features": "Alle Funktionen",
  "home.nav.workflow": "Workflow",
  "home.nav.models": "Modelle",
  "home.nav.pricing": "Preise",
  "home.nav.console": "Konsole",
  "home.nav.login": "Anmelden",

  "home.hero1.eyebrow": "v1.4 veröffentlicht · Lokaler Multi-Modell-KI-Agent",
  "home.hero1.h1": "Lass die KI <span class=\"glow\">wirklich arbeiten</span><br>statt nur zu plaudern",
  "home.hero1.sub": "Lokales Ollama und Cloud-LLMs unter einem Scheduler; knotenbasierte Workflows verketten Skripte, Storyboards, Video und Musik zu einer Pipeline. Die vierstufige Memory lernt dich über die Zeit, deine Daten bleiben auf dem Gerät, und es läuft offline.",
  "home.hero1.stat1": "Unterstützte Modelle",
  "home.hero1.stat2": "Geteilte Daten",
  "home.hero1.stat3": "Selbstlernende Memory",
  "home.hero1.cta1": "Kostenlos herunterladen · Free-Tier",
  "home.hero1.cta2": "Workflow-Demo ansehen",

  "home.hero2.eyebrow": "Workflow · Knoten-Canvas",
  "home.hero2.h1": "Drag &amp; drop<br>um eine <span class=\"glow\">KI-Pipeline</span> zu bauen",
  "home.hero2.sub": "Skript → Storyboard → Videoclips → Hintergrundmusik, alles in einem Lauf. Jeden Schritt vorschauen, einen einzelnen Knoten erneut ausführen und eigene Karten oder lokale Assets einfügen.",
  "home.hero2.stat1": "Domain-Experten",
  "home.hero2.stat2": "Fertige Vorlagen",
  "home.hero2.stat3": "Ziehen & nutzen",
  "home.hero2.cta1": "Workflow öffnen",
  "home.hero2.cta2": "60s-Demo ansehen",

  "home.hero3.eyebrow": "v1.4 · Begrenztes Einführungsangebot",
  "home.hero3.h1": "Sommeraktion<br>nutze es <span class=\"glow\">für immer</span> für 0 $",
  "home.hero3.sub": "Das Free-Tier ist für immer mit unbegrenzten lokalen Modellen. Bezahlte Stufen schalten längere Memory, Flaggschiff-Modelle und Cloud-Generierungskontingent frei.",
  "home.hero3.stat1": "Start · Kostenlos",
  "home.hero3.stat2": "Standard",
  "home.hero3.stat3": "Team · Geplant",
  "home.hero3.cta1": "Jetzt herunterladen",
  "home.hero3.cta2": "Changelog ansehen",

  "home.float.assist": "KI-Assistent",
  "home.float.service": "Menschlicher Support",
  "home.float.sales": "Vertrieb",

  "home.cap.tag": "Funktion",
  "home.cap.h2": "Ein Client, dein ganzer KI-Arbeitsplatz",
  "home.cap.c1t": "Lokal + Cloud Hybrid-Routing",
  "home.cap.c1d": "Nutze Ollama lokal im Offline-Modus, schalte automatisch auf Cloud-Flaggschiffe um, wenn online. Modellwechsel mitten im Gespräch.",
  "home.cap.c2t": "17 Domain-Experten arbeiten zusammen",
  "home.cap.c2d": "Gib ein Ziel vor, AdminAgent teilt Unteraufgaben auf, weist den richtigen Experten zu und führt die Ergebnisse zusammen.",
  "home.cap.c3t": "Vierstufige Memory",
  "home.cap.c3d": "Residente Fakten, Sitzungsarchiv, Skill-Bibliothek und Nutzerprofil.",
  "home.cap.c4t": "Skills kristallisieren automatisch",
  "home.cap.c4d": "Funktionierende Flows werden automatisch zu wiederverwendbaren Skills extrahiert.",
  "home.cap.c5t": "Echte Dateiarbeit",
  "home.cap.c5d": "Docs und Tabellen lesen/schreiben, Skripte ausführen, Windows steuern.",

  "home.feat.tag": "Alle Funktionen",
  "home.feat.h2": "Alle Funktionen, zum Detail klicken",
  "home.feat.p": "Jede Karte öffnet eine volle Seite: was sie tut, wie man sie nutzt und die technischen Highlights.",

  "home.wf.tag": "Workflow",
  "home.wf.h2": "Wiederholte Flows in eine Pipeline ziehen",
  "home.wf.i1t": "Frei ziehen & verbinden",
  "home.wf.i1d": "Organisiere Flows wie Bausteine; ändere einen Schritt, ohne den Rest neu zu machen.",
  "home.wf.i2t": "Jeden Schritt vorschauen",
  "home.wf.i2d": "Text, Bilder, Video, Audio — klick einen Knoten an, um ihn zu sehen.",
  "home.wf.i3t": "Vorlagen mit einem Klick",
  "home.wf.i3d": "KI-Shorts / Musik-Singles / Concept-Art — fertige Flows eingebaut.",
  "home.wf.memtag": "Memory",
  "home.wf.memh2": "Es fängt nicht jedes Mal bei null an",
  "home.wf.mem.i1t": "Kein Kontextverlust beim Themenwechsel",
  "home.wf.mem.i1d": "Nimm diese Woche Anfragen von letzter Woche auf.",
  "home.wf.mem.i2t": "Flows werden zu Skills",
  "home.wf.mem.i2d": "Dieselbe Aufgabe dauert das zweite Mal nur einen Satz.",

  "home.mem.l1t": "Residente Memory",
  "home.mem.l1d": "Die wichtigsten Fakten und Präferenzen, jede Runde injiziert.",
  "home.mem.l2t": "Sitzungsarchiv",
  "home.mem.l2d": "Alle Historie, abgerufen nach Trefferzahl von Stichwörtern.",
  "home.mem.l3t": "Skill-Bibliothek",
  "home.mem.l3d": "Bewährte Flows kristallisieren automatisch zur Wiederverwendung.",
  "home.mem.l4t": "Nutzerprofil",
  "home.mem.l4d": "Kommunikationsstil und Domain-Wissen wachsen über die Zeit.",

  "home.models.tag": "Modelle",
  "home.models.h2": "So ziemlich jedes Modell, das du willst",
  "home.models.m1": "Ollama lokal",
  "home.models.m2": "DeepSeek V4",
  "home.models.m3": "Qwen3.8 Max",
  "home.models.m4": "GLM 5.3",
  "home.models.m5": "Kimi K3",
  "home.models.m6": "Doubao Seed",
  "home.models.m7": "Claude Opus / Sonnet",
  "home.models.m8": "GPT-5.6",
  "home.models.m9": "Gemini",
  "home.models.m10": "Kling",
  "home.models.m11": "Suno music",
  "home.models.m12": "OpenRouter alle",

  "home.price.tag": "Preise",
  "home.price.h2": "Kostenlos starten, upgraden wenn du mehr brauchst",
  "home.price.free.name": "Kostenlos",
  "home.price.free.li1": "Unbegrenzte lokale Modelle",
  "home.price.free.li2": "Basis-Chat & Datei-Ops",
  "home.price.free.li3": "Werbung enthalten",
  "home.price.free.li4": "Community-Support",
  "home.price.free.cta": "Kostenlos herunterladen",
  "home.price.std.flag": "Am beliebtesten",
  "home.price.std.name": "Standard",
  "home.price.std.li1": "Längerer Kontext & Memory",
  "home.price.std.li2": "Kostengünstige Cloud-Modelle",
  "home.price.std.li3": "Werbefrei",
  "home.price.std.li4": "Volle Workflow-Funktionen",
  "home.price.std.cta": "Auf Standard upgraden",
  "home.price.pro.name": "Pro",
  "home.price.pro.li1": "Alle Flaggschiff-Modelle",
  "home.price.pro.li2": "KI-Video-/Musik-Generierung",
  "home.price.pro.li3": "Multi-Experten-Kollaboration",
  "home.price.pro.li4": "Prioritäts-Support",
  "home.price.pro.cta": "Auf Pro upgraden",
  "home.price.ult.flag": "Bald verfügbar",
  "home.price.ult.name": "Ultimate",
  "home.price.ult.li1": "Riesiger Kontext",
  "home.price.ult.li2": "Exklusive Top-Modelle",
  "home.price.ult.li3": "Team-Kollab (geplant)",
  "home.price.ult.li4": "—",
  "home.price.ult.cta": "Bald verfügbar",

  "home.faq.h2": "FAQ",
  "home.faq.q1": "Funktioniert es offline?",
  "home.faq.a1": "Ja. Lokale Ollama-Modelle laufen vollständig offline — Chat, Datei-Ops und Workflow-Orchestrierung brauchen kein Netz.",
  "home.faq.q2": "Werden meine Daten hochgeladen?",
  "home.faq.a2": "Nein. Chatverlauf, Wissensbasis und Memory bleiben auf deinem Rechner.",
  "home.faq.q3": "Was sind die Free-Tier-Limits?",
  "home.faq.a3": "Free gibt alle lokalen Fähigkeiten und Basis-Tools mit einem Werbeplatz; Cloud-Flaggschiff-Modelle und KI-Video/Musik-Generierung sind kostenpflichtig.",
  "home.faq.q4": "Welche Systeme werden unterstützt?",
  "home.faq.a4": "Windows und macOS. Mobile (Android / iOS / HarmonyOS) ist geplant.",

  "home.cta.h2": "Lass die KI jetzt arbeiten",
  "home.cta.p": "Das Free-Tier ist für immer, installiert in einer Minute, keine Kreditkarte nötig.",
  "home.cta.btn": "Working Mate kostenlos herunterladen",

  "home.foot.copy": "© 2026 Working Mate · Lokaler KI-Arbeitsplatz",
  "home.foot.privacy": "Datenschutz",
  "home.foot.terms": "AGB",
  "home.foot.refunds": "Rückerstattung",

  /* ───────── 功能页共享 UI (FEAT-UI) ───────── */
  "feat.nav.features": "Funktionen",
  "feat.nav.workflow": "Workflow",
  "feat.nav.models": "Modelle",
  "feat.nav.pricing": "Preise",
  "feat.nav.download": "Kostenlos herunterladen",
  "feat.foot.copy": "© 2026 Working Mate · Lokaler KI-Arbeitsplatz",
  "feat.foot.features": "Funktionen",
  "feat.foot.privacy": "Datenschutz",
  "feat.foot.terms": "AGB",
  "feat.foot.refunds": "Rückerstattung",
  "feat.tpl.back": "Zurück zu allen Funktionen",
  "feat.tpl.what": "Was es tut",
  "feat.tpl.how": "Anwendung",
  "feat.tpl.tech": "Technische Highlights",
  "feat.tpl.shot": "Schau rein",
  "feat.tpl.related": "Verwandte Funktionen",
  "feat.tpl.end": "Probier es aus",
  "feat.tpl.endP": "Das Free-Tier ist für immer; lokale Funktionen laufen out-of-the-box, keine Kreditkarte nötig.",
  "feat.tpl.endBtn": "Working Mate kostenlos herunterladen",
  "feat.tpl.view": "Mehr erfahren →",
  "feat.tpl.heroCta1": "Kostenlos-Download testen",
  "feat.tpl.heroCta2": "Weitere Funktionen ansehen",

  /* ───────── 功能数据 (FEAT-DATA) ───────── */
  "feat.models.title": "Multi-Modell Hybrid-Routing",
  "feat.models.tag": "Multi-Modell-Router",
  "feat.models.sub": "Lokales Ollama und Cloud-Flaggschiffe in einer Chat-Box: automatisch auf lokal wechseln wenn offline, automatisch auf Cloud wenn online; Modellwechsel mitten im Gespräch ohne Neustart oder Config.",
  "feat.models.fact0": "60+ Modelle",
  "feat.models.fact1": "Lokal / Cloud vereint",
  "feat.models.fact2": "Auto-Fallback",
  "feat.models.fact3": "0 Daten raus (lokal)",
  "feat.models.grid": "60+ Modelle · lokaler / Cloud-Einstiegspunkt",
  "feat.models.what0t": "Eine Eingabe, jedes Modell",
  "feat.models.what0d": "Kein API-Gefrickel, kein Tab-Chaos. DeepSeek, Qwen, GLM, Kimi, Doubao, GPT, Claude, Gemini, OpenRouter — alles in einem Dropdown.",
  "feat.models.what1t": "Lokal zuerst, läuft offline",
  "feat.models.what1d": "Ollama einstecken und voll offline gehen: Chat, Datei-Ops und Workflow-Orchestrierung brauchen kein Netz, Daten verlassen nie die Maschine.",
  "feat.models.what2t": "Drei-Stufen-Modellstrategie",
  "feat.models.what2d": "Standard / Pro / Flaggschiff mit einem Klick umschalten; das System wählt automatisch das beste Preis-Leistungs-Verhältnis pro Aufgabe, oder du wählst manuell.",
  "feat.models.what3t": "Multi-Modell Auto-Degrade",
  "feat.models.what3d": "Bei Rate-Limit oder 5xx springt es automatisch zum nächsten Kandidaten; stoppt und meldet klar erst bei unzureichendem Guthaben oder Auth-Fehler — nie still.",
  "feat.models.what4t": "Experten bringen Modellgruppen",
  "feat.models.what4d": "17 Domain-Experten binden je eine Reasoning-/General-/Code-Modellgruppe, sodass Coder Code-Modelle und Schreiber Schreib-Modelle nutzen.",
  "feat.models.what5t": "Live in einer Sitzung tauschen",
  "feat.models.what5d": "Modellwechsel mitten im Chat ohne Kontextverlust — wirklich „Gehirn spontan wechseln“.",
  "feat.models.step0": "Einstellungen → Modelle & Runtime, wähle eine Stufe (Standard / Pro / Flaggschiff).",
  "feat.models.step1": "Für Offline-Nutzung lokales Ollama einschalten; der Client entdeckt lokale Modelle automatisch.",
  "feat.models.step2": "Modell im Dropdown oben wählen, oder einfach „Auto Router“ nutzen.",
  "feat.models.step3": "Offline fällt auf lokal zurück; online stellt Cloud wieder her — keine manuelle Eingriff.",
  "feat.models.tech0": "Einheitliche cloud_client-Abstraktion; lokal / Cloud teilen eine Call-Signatur.",
  "feat.models.tech1": "429 unterscheidet „Rate-Limit“ vs „Guthaben unzureichend“: einmal retry bei Limit, stopp und Top-up-Aufforderung bei Guthaben.",
  "feat.models.tech2": "Multi-Modell-Fallback-Kette: wechselt nur bei Rate-Limit / 5xx; nie bei Auth-Fehlern (vermeidet sinnlose Retries).",
  "feat.models.tech3": "Modelle indexiert nach Stufe × Zweck; Experten referenzieren Modellgruppen direkt.",
  "feat.models.shot": "Eine Eingabe, lokal und Cloud verbunden",

  "feat.experts.title": "17 Domain-Experten arbeiten zusammen",
  "feat.experts.tag": "Experten-Team",
  "feat.experts.sub": "Gib ein Ziel vor, AdminAgent teilt es in Unteraufgaben auf, weist den richtigen Experten zu und führt zu einem Ergebnis zusammen. Kein Prompt-Schreiben, kein manuelles Aufteilen.",
  "feat.experts.fact0": "17 Domain-Experten",
  "feat.experts.fact1": "Auto teilen / zuweisen",
  "feat.experts.fact2": "≤10 Tool-Calls / Unteraufgabe",
  "feat.experts.fact3": "Auto zusammengeführt",
  "feat.experts.grid": "17 Domain-Experten · auto teilen / zuweisen",
  "feat.experts.what0t": "In einem Satz briefen",
  "feat.experts.what0d": "Sag „mach aus dem 3-Monats-Umsatz dieser Excel eine Trendcharts und schreib eine Analyse“ — es teilt in lesen → bereinigen → chart → analysieren auf und weist zu.",
  "feat.experts.what1t": "17 Domain-Experten",
  "feat.experts.what1d": "Forschung, Video-Shorts, Bilddesign, Musik, Trading, Aktuariat, Solo-Business, Software-Architektur, KI, Prompting, Full-Stack Codex, Office, Code, Schreiben, Data Science, Ops, General.",
  "feat.experts.what2t": "AdminAgent macht die Aufteilung",
  "feat.experts.what2d": "Der Hauptagent liest dein Ziel → baut eine Unteraufgabenliste (mit Abhängigkeiten) → schickt jede an den richtigen Experten.",
  "feat.experts.what3t": "Experten bringen Modellgruppen",
  "feat.experts.what3d": "Jeder Experte bindet eine Reasoning-/General-/Code-Modellgruppe und bindet Generierungsmodelle für Bild / Video / Musik.",
  "feat.experts.what4t": "Tool-Calls bleiben begrenzt",
  "feat.experts.what4d": "Bis zu 10 Tool-Calls pro Unteraufgabe, mit Erlaub-/Verbotslisten, verhindern Kontrollverlust oder gefährliche Calls.",
  "feat.experts.what5t": "Zu einer Lieferung zusammengeführt",
  "feat.experts.what5d": "Wenn alle Unteraufgaben fertig sind, werden Ergebnisse automatisch zu einer nutzbaren Ausgabe gemergt, nicht verstreute Fetzen.",
  "feat.experts.step0": "Oben „Agent-Modus“ einschalten.",
  "feat.experts.step1": "Beschreibe dein Ziel (je spezifischer, desto besser); kein manuelles Aufteilen.",
  "feat.experts.step2": "Der Agent zeigt erst eine Unteraufgabenliste; bestätigen zum Start.",
  "feat.experts.step3": "Du kannst jederzeit Notstopp machen und Status und Artefakte jeder Unteraufgabe sehen.",
  "feat.experts.tech0": "Aufteilung und Ausführung teilen eine Multi-Modell-Degrade-Kette; Rate-Limits crashen nicht die ganze Aufgabe.",
  "feat.experts.tech1": "Eine fehlgeschlagene Unteraufgabe überspringt nur ihren Downstream; andere Zweige laufen weiter.",
  "feat.experts.tech2": "Cross-Space-Calls sind gedeckelt (verhindert Schleifen), damit Experten nicht ewig ping-pong spielen.",
  "feat.experts.tech3": "Fehlparse der Aufteilung wirft den echten Fehler statt still leer zurückzugeben.",
  "feat.experts.shot": "Ziel → Unteraufgaben → Experten-Ausführung",

  "feat.memory.title": "Vierstufiges Memory-System",
  "feat.memory.tag": "Memory",
  "feat.memory.sub": "Es fängt nicht jedes Mal bei null an. Schlüsselfakten, vergangene Sitzungen, bewährte Flows, deine Präferenzen und dein Stil setzen sich in vier Memory-Schichten — je mehr du es nutzt, desto besser kennt es dich.",
  "feat.memory.fact0": "4 Memory-Schichten",
  "feat.memory.fact1": "Chinesische n-gram-Suche",
  "feat.memory.fact2": "Lokales SQLite",
  "feat.memory.fact3": "Kapazität gedeckelt",
  "feat.memory.grid": "4 Memory-Schichten · chinesische n-gram-Suche",
  "feat.memory.what0t": "L1 Residente Memory",
  "feat.memory.what0d": "Die wichtigsten Fakten und Präferenzen, jede Runde injiziert. Ein Kapazitätsdeckel zwingt, nur die wertvollsten zu behalten.",
  "feat.memory.what1t": "L2 Sitzungsarchiv",
  "feat.memory.what1d": "Alle vergangenen Sitzungen lokal gespeichert, per Trefferzahl von Stichwörtern abgerufen, nur bei Bedarf injiziert — kein residentes Budget verbraucht.",
  "feat.memory.what2t": "L3 Skill-Bibliothek",
  "feat.memory.what2d": "Bewährte Flows extrahieren sich auto in wiederverwendbare Skills — das zweite Mal spielt ein Satz die ganze Aktion ab.",
  "feat.memory.what3t": "L4 Nutzerprofil",
  "feat.memory.what3d": "Kommunikationsstil, Domain-Wissen, Gewohnheiten wachsen, sodass Antworten mehr wie du klingen.",
  "feat.memory.what4t": "Thema wechseln ohne Fadenverlust",
  "feat.memory.what4d": "Bedarfe von letzter Woche bleiben erhalten; weg und zurück, es erinnert sich noch an den Kontext.",
  "feat.memory.what5t": "Memory sichtbar & löschbar",
  "feat.memory.what5d": "Die Sidebar „Memory-Dateien“ ist immer einsehbar; falsche Einträge können gelöscht oder korrigiert werden.",
  "feat.memory.step0": "Einfach normal chatten; kein manuelles „merke“.",
  "feat.memory.step1": "Sidebar „Memory-Dateien“ zeigt aktuelles L1 resident und L4 Profil.",
  "feat.memory.step2": "„Memory-Aufräumen“ löscht eine Schicht oder eine Sitzung.",
  "feat.memory.step3": "Um eine harte Regel zu merken, einfach im Chat aussprechen — als langfristiger Fakt gewertet.",
  "feat.memory.tech0": "Chinesisch nutzt 2-4-Zeichen n-gram mit englischer Tokenisierung, um niedrige LIKE-Treffer auf Ganzzahl zu fixen.",
  "feat.memory.tech1": "L2 scored nach Trefferzahl; auto-Degrade auf einfache Tabelle + LIKE wenn SQLite FTS5 fehlt.",
  "feat.memory.tech2": "Leichte Zusammenfassungen überspringen das LLM, konkatenieren erste/letzte Runden zur Kostenkontrolle.",
  "feat.memory.tech3": "Jede Schicht hat ein Zeichen-Limit, schützt Memory vor veraltetem Überlauf.",
  "feat.memory.shot": "Memory-Dateien, immer einsehbar & löschbar",

  "feat.skills.title": "Skills kristallisieren automatisch",
  "feat.skills.tag": "Selbstevolvierende Skills",
  "feat.skills.sub": "Ein ausgeführter Flow wird auto in einen wiederverwendbaren Skill der Bibliothek extrahiert. Nächstes Mal reproduziert ein Satz die ganze Aktion.",
  "feat.skills.fact0": "Flows auto extrahieren",
  "feat.skills.fact1": "Zentrale Skill-Bibliothek",
  "feat.skills.fact2": "Lokale Speicherung",
  "feat.skills.fact3": "Wiederverwendbar & teilbar",
  "feat.skills.grid": "Flows auto extrahieren · zentrale Skill-Bibliothek",
  "feat.skills.what0t": "Einmal laufen, wird zum Skill",
  "feat.skills.what0d": "Ein kompletter Flow (lesen → verarbeiten → ausgeben), der funktioniert, wird auto in einen strukturierten wiederverwendbaren Skill extrahiert.",
  "feat.skills.what1t": "Nächstes Mal, ein Satz",
  "feat.skills.what1d": "Sag einfach „mach wie letztes Mal“; es matched aus der Bibliothek und führt aus, ohne Schritte neu zu beschreiben.",
  "feat.skills.what2t": "Skill-Bibliothek visualisiert",
  "feat.skills.what2d": "Sidebar „Skill-Bibliothek“ zum Stöbern, Suchen, Aktivieren oder Löschen vorhandener Skills.",
  "feat.skills.what3t": "An vierstufige Memory gekoppelt",
  "feat.skills.what3d": "Skills gehören zu L3, teilen dasselbe Memory-System mit Workflows und Experten.",
  "feat.skills.what4t": "Fehler verschmutzen die Bibliothek nicht",
  "feat.skills.what4d": "Nur wirklich funktionierende Flows kristallisieren; halb fehlgeschlagene werden nicht als Skill gespeichert.",
  "feat.skills.what5t": "Lokale Speicherung",
  "feat.skills.what5d": "Die Skill-Bibliothek liegt auf deiner Maschine, nicht in der Cloud.",
  "feat.skills.step0": "Lass den Agent wie gewohnt einen Mehr-Schritt-Job beenden.",
  "feat.skills.step1": "Bei Erfolg extrahiert und speichert das System den Skill auto.",
  "feat.skills.step2": "Öffne die Sidebar „Skill-Bibliothek“ zum Bestätigen (umbenennen, löschen).",
  "feat.skills.step3": "Nächstes Mal direkt den Skill referenzieren, oder Agent auto-matchen lassen.",
  "feat.skills.tech0": "Skill-Extraktion teilt dasselbe Knoten/Schritt-Modell mit der Workflow-Engine.",
  "feat.skills.tech1": "Skills als lokale Dateien gespeichert für einfache Sicherung und Migration.",
  "feat.skills.tech2": "Getrennt von L1/L2-Memory, damit Skill-Text das residente Budget nicht verdrängt.",
  "feat.skills.shot": "Skill-Bibliothek: beim Erfolg kristallisiert",

  "feat.workflow.title": "Knotenbasierter Workflow-Canvas",
  "feat.workflow.tag": "Workflow-Canvas",
  "feat.workflow.sub": "Kette KI wie Bausteine: Knoten ziehen, verbinden, laufen. Jeder Schritt vorschauen, einzeln neu ausführen und sein Prompt individuell editieren — Prompts, die du selbst schreibst oder die KI schreiben lässt.",
  "feat.workflow.fact0": "10 Knotentypen",
  "feat.workflow.fact1": "Ziehen + auto-verbinden + auto-layout",
  "feat.workflow.fact2": "Einzelknoten-Neustart",
  "feat.workflow.fact3": "Prompt DIY oder KI-geschrieben",
  "feat.workflow.grid": "10 Knotentypen · ziehen + auto-verbinden + auto-layout",
  "feat.workflow.what0t": "10 Knoten, volle Abdeckung",
  "feat.workflow.what0d": "LLM-Text, Storyboard, KI-Bild, KI-Video, KI-Musik, Video-Compose, Tool-Knoten, Textkarte, lokales Bild, lokale Musik.",
  "feat.workflow.what1t": "Ziehen + verbinden",
  "feat.workflow.what1d": "Aus der linken Bibliothek auf den Canvas ziehen, den rechten Rand eines Knotens zur Ziel halten zum Verbinden; oder „⚡ Auto Connect“ verkabelt auf einmal per Typ-Logik.",
  "feat.workflow.what2t": "Auto-Layout",
  "feat.workflow.what2d": "„⌗ Auto Layout“ ordnet nach Abhängigkeit in Schichten; ein Klick sortiert verstreute Knoten.",
  "feat.workflow.what3t": "Jeden Schritt vorschauen",
  "feat.workflow.what3d": "Klick einen Knoten, das rechte Panel zeigt sein Text-/Bild-/Video-/Audio-Artefakt mit Player.",
  "feat.workflow.what4t": "Prompts voll DIY",
  "feat.workflow.what4d": "Jeder Textparam ist ein Multi-Zeilen-Editor; unterstützt {{node}}-Platzhalter für Upstream-Artefakte.",
  "feat.workflow.what5t": "🪄 KI schreibt Prompts für dich",
  "feat.workflow.what5d": "Ein-Zeilen-Intent, KI schreibt pro Knotentyp einen Pro-Prompt (Storyboard-Künstler / Art-Direktor / Musikproduzent haben je Vorlage); danach noch editierbar.",
  "feat.workflow.what6t": "Vorlagen sofort lauffähig",
  "feat.workflow.what6d": "Eingebaute KI-Shorts, Musik-Singles, Concept-Art-Flows — Theme ändern und laufen.",
  "feat.workflow.what7t": "Zuverlässigkeitsanalyse",
  "feat.workflow.what7d": "„🛡 Zuverlässigkeit“ prüft fehlende Params, fehlende Keys, tote Links, Zyklen, mit Score und Fix-Tipps.",
  "feat.workflow.step0": "Sidebar „Workflow“ öffnen, Knoten ziehen (oder „Vorlage laden“).",
  "feat.workflow.step1": "Verbinden: rechten Rand eines Knotens zur Ziel halten; Faule klicken „⚡ Auto Connect“.",
  "feat.workflow.step2": "Knoten klicken, sein Prompt für diese Aufgabe setzen (schreiben oder 🪄 KI schreiben).",
  "feat.workflow.step3": "„▶ Workflow ausführen“ läuft den vollen Flow; ein fehlernder Knoten blockt andere Zweige nicht.",
  "feat.workflow.step4": "Canvas als JSON speichern; „Speichern / Öffnen JSON“ für Wiederverwendung und Teilen.",
  "feat.workflow.tech0": "Knoten sind flaches dict + deps; Engine läuft topologisch seriell, fehlernde Zweige überspringen Downstream auto.",
  "feat.workflow.tech1": "Platzhalter referenzieren Upstream-Artefakte, unterstützen n-tes Element einer Liste (z.B. Storyboard Shot 1).",
  "feat.workflow.tech2": "Params nach Typ normalisiert (dauer→int, instrumental→bool) gegen Cloud-Typfehler.",
  "feat.workflow.tech3": "LLM-Knoten-Rückgaben haben Fehler-Flag-Erkennung, verhindern, dass Fehlertext als Script downstream fließt.",
  "feat.workflow.shot": "Knoten-Canvas: ziehen, verbinden, pro Knoten Vorschau",

  "feat.media.title": "KI-Medienfabrik",
  "feat.media.tag": "KI-Medienstudio",
  "feat.media.sub": "Von einem Theme zu einem fertigen Clip: Skript → Storyboard → KI-Videoshots → Hintergrundmusik → Untertitel → Compose, alles im Client eingebaut — kein Hin-und-her zwischen Seiten.",
  "feat.media.fact0": "Skript / Storyboard / Video / Musik",
  "feat.media.fact1": "Untertitel + GIF",
  "feat.media.fact2": "Vertikal 9:16",
  "feat.media.fact3": "Auto-archiviert",
  "feat.media.grid": "Skript / Storyboard / Video / Musik · Untertitel + GIF",
  "feat.media.what0t": "Skriptgenerierung",
  "feat.media.what0d": "Gib ein Theme, bekomme ein 60s Micro-Drama-Skript mit 3 Shots und auto-geschnittenen Bild-Prompts pro Shot.",
  "feat.media.what1t": "Storyboard-Split",
  "feat.media.what1d": "Jede Shot-Beschreibung auto in eine strukturierte Liste extrahiert, einzeln an Video-Knoten gefüttert.",
  "feat.media.what2t": "KI-Videoshots",
  "feat.media.what2d": "Text-zu-Video pro Shot, vertikal 9:16, Dauer justierbar, Einzel-Shot-Neustart.",
  "feat.media.what3t": "Hintergrundmusik",
  "feat.media.what3d": "Ein Instrumental-Theme nach Skript-Laune generieren, oder KI schreibt vollen Song mit Lyrics.",
  "feat.media.what4t": "KI-Bild",
  "feat.media.what4d": "Kino-Concept-Art, Cover-Bilder, Storyboard-Refs, wählbare Ratios.",
  "feat.media.what5t": "Untertitel & GIF",
  "feat.media.what5d": "Auto-Untertiteldateien, oder Clips als GIF exportieren.",
  "feat.media.what6t": "Video-Compose",
  "feat.media.what6d": "Mehrere Shots in Reihenfolge zu einem fertigen Clip zusammenfügen.",
  "feat.media.what7t": "Lokale Assets einfügbar",
  "feat.media.what7d": "Eigene Bilder und Musik können als Refs oder Score in den Workflow fallen, gemischt mit KI-Output.",
  "feat.media.step0": "Workflow → „🎬 KI-Short (3 Shots + Musik)“ Vorlage laden.",
  "feat.media.step1": "Theme auf diese Aufgabe ändern (z.B. „Alltag eines arbeitenden Drachen“).",
  "feat.media.step2": "Skript-Knoten klicken, schreiben oder 🪄 KI schreiben; bestätigen dann laufen.",
  "feat.media.step3": "Pro Knoten vorschauen: zuerst Skript & Storyboard, dann Shot-Video & Musik.",
  "feat.media.step4": "Compose-Knoten gibt Clip aus; Artefakte landen auto im Task-Archivordner.",
  "feat.media.tech0": "Video / Musik / Bild via einheitliches Tool-Registry an Kling, Suno, Bildmodelle angebunden.",
  "feat.media.tech1": "Media-Knoten pro Nutzung abgerechnet; UI zeigt Kosten klar (Free kann Flows lokal üben).",
  "feat.media.tech2": "Shot-Zahl, Ratio, Dauer alle editierbar; Shot-Prompt unterstützt Hart-Override des Upstream.",
  "feat.media.tech3": "Artefaktpfade auto zurückgefüllt in Knoten; nächster Lauf nutzt direkt wieder.",
  "feat.media.shot": "Skript → Storyboard → Shots → Musik",

  "feat.modules.title": "Sechs Branchen-Szenario-Module",
  "feat.modules.tag": "Szenarien",
  "feat.modules.sub": "Forschung, Video, Bild, Finanzen, Software, Growth — sechs fertige Szenario-Einstiege, je vorkonfiguriert mit Experten, Tools und Quick-Karten; rein und los.",
  "feat.modules.fact0": "6 Szenarien",
  "feat.modules.fact1": "Vorkonfig. Quick-Karten",
  "feat.modules.fact2": "Mehrsprachig",
  "feat.modules.fact3": "Lokal / cloud",
  "feat.modules.grid": "6 Szenarien · vorkonfig. Schnellstart-Karten",
  "feat.modules.what0t": "Forschung",
  "feat.modules.what0d": "Paper-Suche, Material-Aufbereitung, strukturierte Zusammenfassung & Vergleich — top für Reviews und Proposals.",
  "feat.modules.what1t": "Video- & Bildkreation",
  "feat.modules.what1d": "Kurz-Script zu Clip, Concept- & Cover-Design, an Kreations-Experten gekoppelt.",
  "feat.modules.what2t": "Finanzen & Investment",
  "feat.modules.what2d": "Marktdaten, Firmeninfos, Long/Short-These & Risiko — an Trader / Aktuar gekoppelt.",
  "feat.modules.what3t": "Software & Code",
  "feat.modules.what3d": "Anforderungsaufteilung, Code-Gen, Debug, schnelle Script-Läufe — an Architekt / Full-Stack Codex gekoppelt.",
  "feat.modules.what4t": "Growth & Marketing",
  "feat.modules.what4d": "Topics, Copy, Kampagnenplanung, Growth-Experiment-Design.",
  "feat.modules.what5t": "Jedes Modul hat Quick-Karten",
  "feat.modules.what5d": "Kein Prompt from scratch; Karte klicken für fertige Task-Vorlage.",
  "feat.modules.step0": "Sidebar „NAVIGATION“ Szenario wählen (forschung / video / bild / finanzen / software / growth).",
  "feat.modules.step1": "Quick-Karte im Szenario klicken, oder Bedarf einfach beschreiben.",
  "feat.modules.step2": "Bei Cross-Szenario sammelt ein Projekt-Space Artefakte mehrerer Szenarien.",
  "feat.modules.tech0": "Szenario-Karten sind nur „Task-Vorlage + Experte + Tool“ Combos, lokal definiert, editierbar.",
  "feat.modules.tech1": "Szenarien teilen ein Tool-Registry und Memory-System; Artefakte interoperieren.",
  "feat.modules.tech2": "UI unterstützt 10 Sprachen; Szenario-Karten-Copy folgt dem Switch.",
  "feat.modules.shot": "Szenario-Karten: klicken und losarbeiten",

  "feat.spaces.title": "Projekt-Spaces & Task-Center",
  "feat.spaces.tag": "Projekte & Tasks",
  "feat.spaces.sub": "Ein Ziel, ein Space; mehrere Tasks parallel ohne Vermischung; alle Artefakte, Logs und Kontext im Space archiviert, jederzeit fortsetzen.",
  "feat.spaces.fact0": "Parallele Tasks",
  "feat.spaces.fact1": "Space-Level Kontext-Isolation",
  "feat.spaces.fact2": "Auto-archiviert",
  "feat.spaces.fact3": "Kanban-Fortschritt",
  "feat.spaces.grid": "Parallele Tasks · Space-Level Kontext-Isolation",
  "feat.spaces.what0t": "Projekt-Space",
  "feat.spaces.what0d": "Pro Projekt einen Space öffnen; Ziele, Anhänge, Artefakte und Chat-Historie separat gespeichert, nie von anderen verschmutzt.",
  "feat.spaces.what1t": "Parallele Tasks",
  "feat.spaces.what1d": "Mehrere Unteraufgaben in einem Space laufen lassen, jede mit eigenem Fortschritt.",
  "feat.spaces.what2t": "Task-Center Kanban",
  "feat.spaces.what2d": "Alle Tasks in einem Board: Status, Zeit, Artefakte, Fehlergründe auf einen Blick.",
  "feat.spaces.what3t": "Context-Bus",
  "feat.spaces.what3d": "Spaces können Artefakte der anderen im Rahmen referenzieren; Call-Decksel verhindern zirkuläre Abhängigkeit.",
  "feat.spaces.what4t": "Artefakt-Archiv",
  "feat.spaces.what4d": "Generierte Dateien, Bilder, Video, Tabellen landen auto im Space-Ordner — kein Suchen.",
  "feat.spaces.what5t": "Jederzeit fortsetzen",
  "feat.spaces.what5d": "Client schließen und neu öffnen; Space und Fortschritt bleiben.",
  "feat.spaces.step0": "Sidebar „Projekt-Spaces“ → Neuer Space, Ziel nennen und Ref-Dateien anhängen.",
  "feat.spaces.step1": "Ziel an Agent geben; der teilt in parallele Unteraufgaben.",
  "feat.spaces.step2": "„Task-Center“ zeigt Gesamtfortschritt und Artefakte jeder Task.",
  "feat.spaces.step3": "Wenn fertig, alle Artefakte aus Space-Ordner holen; im selben Space iterieren.",
  "feat.spaces.tech0": "Spaces geben Artefakt-Refs über Context-Bus; Cross-Space-Calls gedeckelt gegen Schleifen.",
  "feat.spaces.tech1": "Task-State und Artefaktpfade persistieren; Restart verliert sie nicht.",
  "feat.spaces.tech2": "Jedes Space-Ausführungslog separat geführt für einfachen Step-Trace.",
  "feat.spaces.shot": "Projekt-Space: Ziel, Tasks, Artefakte an einem Ort",

  "feat.task_center.title": "Task-Center",
  "feat.task_center.tag": "Task-Center",
  "feat.task_center.sub": "Alle Tasks in einem Kanban: wer läuft, welcher Schritt, wie lang, was produziert, warum fehlgeschlagen — klar auf einen Blick.",
  "feat.task_center.fact0": "Zentrales Board",
  "feat.task_center.fact1": "Echtzeit-Status",
  "feat.task_center.fact2": "Fehler tracebar",
  "feat.task_center.fact3": "Ein-Klick öffnen",
  "feat.task_center.grid": "Zentrales Board · Echtzeit-Status-Refresh",
  "feat.task_center.what0t": "Ein Screen, alles",
  "feat.task_center.what0d": "Ob per Chat getriggert, von Agent geteilt oder per Schedule — alles läuft in eine Liste.",
  "feat.task_center.what1t": "Echtzeit-Status",
  "feat.task_center.what1d": "Queue / laufend / done / failed / skipped — Statuswechsel refresh sofort.",
  "feat.task_center.what2t": "Fehler ergeben Sinn",
  "feat.task_center.what2d": "Fehler ist nicht nur „error“ — er gibt spezifischen Schritt und Grund (fehlender Key, Rate-Limit, Datei nicht gefunden…).",
  "feat.task_center.what3t": "Artefakt direkt",
  "feat.task_center.what3d": "Task öffnen öffnet seine Datei, Bild, Video oder Tabelle.",
  "feat.task_center.what4t": "Paart mit Workflow",
  "feat.task_center.what4d": "Jedes Workflow-Knoten-Ergebnis landet auch im Task-Log für einfachen Step-Trace.",
  "feat.task_center.step0": "Sidebar „Task-Center“ alle Tasks ansehen.",
  "feat.task_center.step1": "Task klicken für Details: Schritte, Zeit, Artefakte, Log.",
  "feat.task_center.step2": "Fehlgeschlagene Tasks tracebar dann diesen Schritt neu laufen.",
  "feat.task_center.tech0": "Zwei-Stufen Task/Schritt-Struktur; Step-Log nennt Tool, Params, Zeit, Ergebnis.",
  "feat.task_center.tech1": "Ausführungs- und UI-Thread getrennt; lange Tasks frieren UI nicht ein; Thread-Crash resettet Button-State auto.",
  "feat.task_center.shot": "Task-Center: Status, Zeit, Artefakte",

  "feat.automation.title": "Automatisierung & geplante Tasks",
  "feat.automation.tag": "Automatisierung",
  "feat.automation.sub": "Lass die KI in deinem Rhythmus arbeiten: morgens News aufräumen, wöchentlich Daten zusammenfassen, pünktlich erinnern — läuft, auch wenn du nicht guckst.",
  "feat.automation.fact0": "Geplant / periodisch",
  "feat.automation.fact1": "Lokaler Scheduler",
  "feat.automation.fact2": "Historie geloggt",
  "feat.automation.fact3": "Fehler sichtbar",
  "feat.automation.grid": "Geplant / periodisch · lokaler Scheduler",
  "feat.automation.what0t": "In einem Satz erstellen",
  "feat.automation.what0d": "„Räum die Branchennews von gestern täglich um 9 Uhr zu einer Zusammenfassung“ — gesagt, existiert eine Automation.",
  "feat.automation.what1t": "Periodisch & einmalig",
  "feat.automation.what1d": "Täglich, wöchentlich, monatlich, oder einmal zu festgelegter Zeit.",
  "feat.automation.what2t": "Lokaler Scheduler",
  "feat.automation.what2d": "Planung und Daten bleiben auf dem Gerät, nicht hochgeladen.",
  "feat.automation.what3t": "Ausführungshistorie",
  "feat.automation.what3d": "Wie viele Läufe, jedes Ergebnis, jeder Fehler — alles aufgezeichnet.",
  "feat.automation.what4t": "Pausier- & löschbar",
  "feat.automation.what4d": "Pausieren oder löschen, wann immer du es nicht willst.",
  "feat.automation.step0": "Sidebar „Automatisierung“ → Neu, schreiben was zu tun.",
  "feat.automation.step1": "Zeit & Frequenz setzen (täglich / wöchentlich / einmal zu Zeit).",
  "feat.automation.step2": "Speichern, dann nächsten Lauf und Historie in Liste sehen.",
  "feat.automation.tech0": "Automation-Def und Run-State persistieren separat; Planung übersteht Restart.",
  "feat.automation.tech1": "Jeder Lauf unabhängig geloggt, um Inhalt vs. Umgebung zu beurteilen.",
  "feat.automation.shot": "Arbeite automatisch in deinem Rhythmus",

  "feat.gui.title": "GUI-Automatisierung",
  "feat.gui.tag": "Computersteuerung",
  "feat.gui.sub": "Lass die KI andere Programme auf deiner Maschine steuern: Buttons klicken, Formulare füllen, Menüs öffnen — selbst alte Software ohne API wird automatisiert.",
  "feat.gui.fact0": "Maus- & Tastatursim",
  "feat.gui.fact1": "Fähigkeitscheck zuerst",
  "feat.gui.fact2": "Pro Aktion bestätigen",
  "feat.gui.fact3": "Jederzeit umschaltbar",
  "feat.gui.grid": "Maus- & Tastatursim · Fähigkeitscheck zuerst",
  "feat.gui.what0t": "UI wie ein Mensch bedienen",
  "feat.gui.what0d": "KI „sieht“ das aktuelle Fenster, entscheidet dann wo klicken und was tippen, schreitet Schritt für Schritt voran.",
  "feat.gui.what1t": "Fähigkeitscheck vor Start",
  "feat.gui.what1d": "System prüft zuerst, ob Umgebung es unterstützt; sonst sagt es warum, statt still zu scheitern.",
  "feat.gui.what2t": "Vor Aktion bestätigen",
  "feat.gui.what2d": "Standard fragt jede Schlüsselaktion; nur Auto-Confirm-Modus überspringt Prompts.",
  "feat.gui.what3t": "Risikoreiche Aktionen bleiben blockiert",
  "feat.gui.what3d": "Destruktive Ops wie löschen/überschreiben werden von Auto-Confirm nicht freigegeben.",
  "feat.gui.what4t": "Jederzeit umschaltbar",
  "feat.gui.what4d": "Ein Klick aus; KI verliert sofort Maus/Tastatur-Kontrolle.",
  "feat.gui.step0": "Einstellungen → „GUI-Automatisierung“ aktivieren, zuerst Fähigkeitscheck bestehen.",
  "feat.gui.step1": "Operation beschreiben (je spezifischer, desto besser).",
  "feat.gui.step2": "Jede Schlüsselaktion wie gebeten bestätigen.",
  "feat.gui.step3": "Schalter aus, wenn fertig.",
  "feat.gui.tech0": "Fähigkeitscheck läuft und cached bei Aktivierung, vermeidet mitten-drin „Umgebung nicht unterstützt“.",
  "feat.gui.tech1": "Operations-Granularität konfigurierbar; default pro Aktion bestätigen.",
  "feat.gui.tech2": "Gekoppelt an Auto-Confirm: nur explizites Auto-Confirm überspringt Prompt.",
  "feat.gui.shot": "Alte Software ohne API wird auch automatisiert",

  "feat.safety.title": "Sicherheits-Guardrails: Auto-Confirm & Notstopp",
  "feat.safety.tag": "Sicherheit",
  "feat.safety.sub": "Gewähre die Macht, die gewährt werden soll, blockiere was blockiert werden muss. Schreibvorgänge können pro Schritt bestätigen oder für Tempo auto-bestätigen — aber risikoreiche Aktionen sind immer blockiert, Löschungen gehen immer in den Papierkorb.",
  "feat.safety.fact0": "Stufen: WARNING / BLOCKED",
  "feat.safety.fact1": "Auto-Confirm-Modus",
  "feat.safety.fact2": "Ein-Klick Stopp",
  "feat.safety.fact3": "Löschungen → Papierkorb",
  "feat.safety.grid": "Stufen: WARNING / BLOCKED · Auto-Confirm-Modus",
  "feat.safety.what0t": "Standard pro Schritt bestätigen",
  "feat.safety.what0d": "Jeder Schreib-, Daten- oder Command-Popup zuerst; ausführen nur bei deinem Ja.",
  "feat.safety.what1t": "Auto-Confirm (Tempo-Modus)",
  "feat.safety.what1d": "Nach Vertrauen aktivieren; Routine-Schreibs hören auf zu fragen, laufen durch — gut für verifizierte Repeat-Flows.",
  "feat.safety.what2t": "Risiko bleibt blockiert",
  "feat.safety.what2d": "BLOCKED-level destruktive Aktionen werden von Auto-Confirm nicht freigegeben; brauchen immer dein Nicken.",
  "feat.safety.what3t": "Löschungen → Papierkorb",
  "feat.safety.what3d": "KI-Löschungen gehen default in Papierkorb, nicht gewiped — bei Fehler wiederherstellbar.",
  "feat.safety.what4t": "Ein-Klick Notstopp",
  "feat.safety.what4d": "Mitten in Kette was Falsches gesehen? Notstopp beendet laufende Task sofort.",
  "feat.safety.what5t": "Tool Erlaub-/Verbotslisten",
  "feat.safety.what5d": "Aufrufbare Tools auf Whitelist begrenzt; Blacklist-Tools in jedem Fall unerreichbar.",
  "feat.safety.step0": "Default „jede Aktion bestätigen“ — nichts zu setzen.",
  "feat.safety.step1": "„Auto-Confirm“ aktivieren, sobald Vertrauen reicht; fragt einmal bei Aktivierung.",
  "feat.safety.step2": "Jederzeit von Top-Bar deaktivieren, zurück zu pro-Schritt-Bestätigung.",
  "feat.safety.step3": "Im Lauf „Stop“ klicken für Notstopp der aktuellen Task.",
  "feat.safety.tech0": "Aktionen nach Risiko gestuft: WARNING auto-confirmbar, BLOCKED immer blockiert.",
  "feat.safety.tech1": "Tool-Calls nutzen Erlaub + Verbot Listen; ≤10 Calls pro Unteraufgabe.",
  "feat.safety.tech2": "Löschungen einheitlich über Papierkorb-Backup-Pfad für Wiederherstellbarkeit.",
  "feat.safety.shot": "Gewähre die Macht, blockiere was blockiert werden muss",

  "feat.files.title": "Echte Dateiarbeit",
  "feat.files.tag": "Echte Dateiarbeit",
  "feat.files.sub": "Es plaudert nicht nur: liest deine Docs und Sheets, editiert Inhalt, generiert neue Dateien, läuft Skripte, Batch-Verarbeitung — dann reicht es dir die Datei.",
  "feat.files.fact0": "Liest/schreibt Office / Sheets",
  "feat.files.fact1": "Skripte ausführen",
  "feat.files.fact2": "Batch-Verarbeitung",
  "feat.files.fact3": "Bilder ziehen / einfügen",
  "feat.files.grid": "Liest/schreibt Office / Sheets · Skripte ausführen",
  "feat.files.what0t": "Versteht deine Dateien",
  "feat.files.what0d": "Word, Excel, PPT, PDF, Bilder reinwerfen; es liest und arbeitet am Inhalt.",
  "feat.files.what1t": "Gleiches Format nach Edit",
  "feat.files.what1d": "Editiert an Ort und Stelle und speichert im Originalformat — nicht Text, den du zurückkopierst.",
  "feat.files.what2t": "Neue Dateien generieren",
  "feat.files.what2d": "Sheets, Reports, Listen, Charts — direkt offene Dateien produzieren.",
  "feat.files.what3t": "Skripte ausführen",
  "feat.files.what3d": "Skripte für Batch bei Bedarf laufen; Output fließt zurück in Chat.",
  "feat.files.what4t": "Ziehen & einfügen",
  "feat.files.what4d": "Datei in Eingabe fallen lassen als Kontext; Clipboard-Bilder Ctrl+V werden Anhänge.",
  "feat.files.what5t": "Artefakt-Archiv",
  "feat.files.what5d": "Generierte Dateien landen im Task-Ordner zum leichten Abholen.",
  "feat.files.step0": "Datei in Eingabe fallen (oder Ctrl+V Bild einfügen).",
  "feat.files.step1": "Sag was zu tun: „fass diese Sheet nach Monat zusammen und chart die Trend“.",
  "feat.files.step2": "KI reicht neue Datei wenn fertig; öffnen und nutzen.",
  "feat.files.tech0": "Datei lesen/schreiben über einheitliche Tool-Layer, mit Workflow-Knoten geteilt.",
  "feat.files.tech1": "Große Dateien strukturell geparst vor Verarbeitung, vermeidet ganzes Doc in Kontext zu stopfen.",
  "feat.files.tech2": "Generierte Artefaktpfade zurückgefüllt für spätere Referenz und Reprocessing.",
  "feat.files.shot": "Rein, editiert, dir Datei zurück",

  "feat.i18n.title": "Mehrsprachige Oberfläche",
  "feat.i18n.tag": "i18n",
  "feat.i18n.sub": "Die UI unterstützt 10 Sprachen mit Echtzeit-Switch — instant, kein Neustart. Praktisch für Auslandnutzer oder Team-Kollab.",
  "feat.i18n.fact0": "10 Sprachen",
  "feat.i18n.fact1": "Echtzeit-Switch",
  "feat.i18n.fact2": "UI + Szenario-Karten",
  "feat.i18n.fact3": "Erweiterbar",
  "feat.i18n.grid": "10 Sprachen · Echtzeit-Switch",
  "feat.i18n.what0t": "10 Sprachen",
  "feat.i18n.what0d": "简体中文, English, 日本語, 한국어, Deutsch, Français, Español, Português, Русский, العربية.",
  "feat.i18n.what1t": "Switch wirkt sofort",
  "feat.i18n.what1d": "Sprache in Einstellungen ändern; UI-Text aktualisiert sofort, kein Client-Neustart.",
  "feat.i18n.what2t": "Volle Abdeckung",
  "feat.i18n.what2d": "Main-UI, Einstellungen, Workflow-Canvas, Szenario-Karten-Copy teilen eine mehrsprachige Schicht.",
  "feat.i18n.what3t": "Übersetzungen erweiterbar",
  "feat.i18n.what3d": "Sprachressourcen in separaten Dateien; Sprache hinzufügen ist nur eine Kopie mehr.",
  "feat.i18n.step0": "Einstellungen → UI-Sprache, Sprache wählen.",
  "feat.i18n.step1": "Wenn Neustart verlangt, einmal neu starten für volle Wirkung.",
  "feat.i18n.tech0": "Aller UI-Text über runtime-Übersetzungsfunktion geholt, vermeidet Hartcodierung Chinesisch beim Import.",
  "feat.i18n.tech1": "Sprachressourcen sind separate Dateien für einfache Review und Ergänzung.",
  "feat.i18n.shot": "",

  "feat.privacy.title": "Local-First & Datenschutz",
  "feat.privacy.tag": "Local First",
  "feat.privacy.sub": "Gespräche, Memory, Wissensbasis, Skills und Artefakte standardmäßig auf deinem eigenen Rechner. Läuft voll offline; Cloud nur für Modelle, die du aktiv wählst.",
  "feat.privacy.fact0": "0 Daten raus (lokaler Modus)",
  "feat.privacy.fact1": "Offline nutzbar",
  "feat.privacy.fact2": "Alles on-device",
  "feat.privacy.fact3": "Lokale DB",
  "feat.privacy.grid": "0 Daten raus (lokal) · offline nutzbar",
  "feat.privacy.what0t": "Daten bleiben on-device",
  "feat.privacy.what0d": "Chatverlauf, vierstufige Memory, Skill-Bibliothek, Projekt-Artefakte alle als lokale Dateien / lokale DB gespeichert.",
  "feat.privacy.what1t": "Offline nutzbar",
  "feat.privacy.what1d": "Mit lokalen Modellen brauchen Chat, Datei-Ops und Workflow-Orchestrierung kein Netz.",
  "feat.privacy.what2t": "Cloud ist deine Wahl",
  "feat.privacy.what2d": "Nur wenn du Cloud-Modelle oder Cloud-Generierung wählst, geht Inhalt zum Anbieter.",
  "feat.privacy.what3t": "Ein-Klick Aufräumen",
  "feat.privacy.what3d": "„Memory-Aufräumen“ kann eine Memory-Schicht löschen oder eine Sitzung löschen — weg für real.",
  "feat.privacy.what4t": "Kein Account nötig",
  "feat.privacy.what4d": "Free-Tier erzwingt keine Registrierung; lokale Funktionen laufen out-of-the-box.",
  "feat.privacy.step0": "Für voll offline einfach lokale Modelle nutzen.",
  "feat.privacy.step1": "Zum Löschen: Sidebar „Memory-Aufräumen“.",
  "feat.privacy.step2": "Chat wirkt sensitiv? Einfach kein Cloud-Modell wählen.",
  "feat.privacy.tech0": "Lokale Speicherung nutzt SQLite und lokale Dir, kein eigener Cloud-Service.",
  "feat.privacy.tech1": "Cloud-Calls gehen nur über deinen konfigurierten Provider-Key, direkt zur API.",
  "feat.privacy.tech2": "Memory-Schichten je löschbar, vermeidet „eine löschen = alles weg“.",
  "feat.privacy.shot": "Alles on-device, läuft offline",
  "home.price.free.li0": "3.000 Guthaben gratis (alle Modelle testen)",
  "home.price.std.li0": "800 Guthaben pro Monat",
  "home.price.pro.li0": "3.000 Guthaben pro Monat",
  "home.price.ult.li0": "10.000 Guthaben pro Monat",
  "home.price.max.li1": "3.000 Guthaben gratis · kein Monatslimit, nutzungsbasiert",
  "feat.membership.grid": "5 Tarife · 3.000 Guthaben gratis · täglich einchecken",
  "feat.channels.grid": "14 China-Direkt-Presets · Festland bevorzugt eigene Modelle",
  "feat.membership.sub": "Fünf Tarife, fünf Grenzen: Gratis läuft lokal, Standard deckt die Preis-Leistungs-Riege ab, Pro öffnet die chinesischen Flaggschiff-Modelle, Ultra ergänzt CAD auf Engineering-Niveau, Max kennt keine Obergrenze. Neue Nutzer erhalten 3.000 Guthaben zum Ausprobieren; kostenpflichtige Tarife werden per Abo oder Lizenz freigeschaltet.",
  "feat.membership.fact1": "3.000 Guthaben gratis",
  "feat.membership.what4d": "Kein Monatslimit für Cloud-Aufrufe — Guthaben wird nutzungsbasiert abgezogen (jederzeit aufladen oder Karte automatisch belasten). Spezial-Agenten (Deep Research, autonomes Coding, selbstrecherchierendes CAD, Kurzdrama-Storyboard) gibt es nur in diesem Tarif. Die 3.000 Startguthaben gelten auch hier.",
  "feat.membership.what5t": "Tarife werden per Abo freigeschaltet",
  "feat.membership.what5d": "Das Tarif-Menü in den Einstellungen zeigt den Status jeder Stufe: nicht abonnierte Tarife tragen ein 🔒 und sind nicht auswählbar — ein versehentliches Umschalten ist ausgeschlossen. Sobald Abo oder Lizenzschlüssel eintrifft, wird die Stufe sofort freigeschaltet; Modellpool, Funktionsfreigaben (CAD, Spezial-Agenten) und Modellanzahl aktualisieren sich ohne Neuinstallation oder erneutes Anmelden.",
  "feat.membership.what6t": "Guthaben zum Mitverfolgen",
  "feat.membership.what6d": "Ihr Guthaben steht in der Statusleiste und sinkt in dem Moment, in dem ein Aufruf endet — zum veröffentlichten Satz des Modells, der direkt neben dem Modellnamen steht. Tägliches Einchecken bringt 100 Guthaben (15-mal für neue Konten). Ist das Guthaben aufgebraucht, kehrt die App in den Gratis-Modus zurück und bietet ein Aufladen an: kein stilles Downgrade, keine versteckten Kosten.",
  "home.price.max.li2": "Täglich einchecken: 100 Guthaben",
  "home.shots.tag": "Echte Oberfläche",
  "home.shots.h2": "Keine Renderings — die echte Oberfläche",
  "home.shots.p": "Jedes Bild unten ist ein direkter Screenshot aus der App: keine Retusche, keine Platzhalter. Die Funktionen sind echt, die Oberfläche auch.",
  "home.shots.s1t": "Hauptfenster · Multi-Modell-Routing-Chat",
  "home.shots.s1d": "Ein Satz genügt – die App wählt den passenden Experten und das passende Modell. Links Verlauf und Navigation, unten rechts das Guthaben in Echtzeit.",
  "home.shots.s2t": "Workflow-Canvas · per Drag zur Pipeline",
  "home.shots.s2d": "Skript → Storyboard → Video → Musik. Einmal verbinden, komplett durchlaufen lassen; jeder Knoten lässt sich einzeln ansehen.",
  "home.shots.s3t": "Projektbereich · ein KI-Projektleiter verteilt die Arbeit",
  "home.shots.s3d": "Ziel setzen – die App zerlegt die Arbeit, weist Experten zu und behält Ergebnisse und Status im Bereich.",
  "home.shots.s4t": "Engineering-Modus · Diagramme / Modellierung / Simulation",
  "home.shots.s4d": "Drei Tabs – technische Diagramme, mathematische Modellierung, physikalische Simulation – mit Skript- oder Bildexport.",
  "home.shots.s5t": "Geplante Aufgaben · Automatisierungsvorlagen",
  "home.shots.s5d": "Tagesdigest, Wochenbericht und Vorlagen zur Interviewvorbereitung sind sofort nutzbar – geplant wird rein lokal.",
  "home.shots.s6t": "Task-Center · Fortschrittsboard über Sitzungen hinweg",
  "home.shots.s6d": "Doppelklick auf eine Karte springt in die Sitzung – die KI verfolgt jede Aufgabe sitzungsübergreifend.",
  "home.shots.s7t": "Branchenszenario · Reisebudget-Analyse",
  "home.shots.s7d": "Kraftstoff, Unterkunft und Tickets als Preistabellen aufgeschlüsselt, mit Quellenangaben.",
  "home.wf.shotcap": "Der echte Canvas: Knoten ziehen, Parameter rechts anpassen, Knoten für Knoten ansehen",
  "home.nav.shots": "Screenshots",
};
