/* Working Mate — Français */
window.I18N = window.I18N || {};
window.I18N.fr = {
  /* ───────── 首页 HOME ───────── */
  "home.nav.capability": "Capacités",
  "home.nav.features": "Toutes les fonctionnalités",
  "home.nav.workflow": "Workflow",
  "home.nav.models": "Modèles",
  "home.nav.pricing": "Tarifs",
  "home.nav.console": "Console",
  "home.nav.login": "Se connecter",

  "home.hero1.eyebrow": "v1.4 disponible · Agent IA multimodèle local-first",
  "home.hero1.h1": "Faites travailler l'IA <span class=\"glow\">pour de vrai</span><br>au lieu de simplement discuter",
  "home.hero1.sub": "Ollama local et LLM cloud sur un même ordonnanceur ; les workflows en nœuds enchaînent scripts, storyboards, vidéo et musique dans un seul pipeline. La mémoire à quatre couches apprend de vous, vos données restent sur l'appareil et tout fonctionne hors ligne.",
  "home.hero1.stat1": "Modèles pris en charge",
  "home.hero1.stat2": "Données partagées",
  "home.hero1.stat3": "Mémoire auto-évolutive",
  "home.hero1.cta1": "Téléchargement gratuit · Offre gratuite",
  "home.hero1.cta2": "Voir la démo du workflow",

  "home.hero2.eyebrow": "Workflow · Canevas de nœuds",
  "home.hero2.h1": "Glissez-déposez<br>pour construire un <span class=\"glow\">pipeline IA</span>",
  "home.hero2.sub": "Script → storyboard → plans vidéo → musique de fond, le tout en une exécution. Prévisualisez chaque étape, relancez un nœud seul et insérez des cartes personnalisées ou des ressources locales.",
  "home.hero2.stat1": "Experts métier",
  "home.hero2.stat2": "Modèles prêts",
  "home.hero2.stat3": "Glisser et utiliser",
  "home.hero2.cta1": "Ouvrir le workflow",
  "home.hero2.cta2": "Voir la démo 60s",

  "home.hero3.eyebrow": "v1.4 · Offre de lancement limitée",
  "home.hero3.h1": "Promo mi-année<br>utilisez-le <span class=\"glow\">pour toujours</span> à 0 $",
  "home.hero3.sub": "L'offre gratuite est à vous pour toujours avec des modèles locaux illimités. Les offres payantes débloquent une mémoire plus longue, les modèles phares et le quota de génération cloud.",
  "home.hero3.stat1": "Départ · Gratuit",
  "home.hero3.stat2": "Standard",
  "home.hero3.stat3": "Équipe · Prévu",
  "home.hero3.cta1": "Télécharger maintenant",
  "home.hero3.cta2": "Voir le journal des changements",

  "home.float.assist": "Assistant IA",
  "home.float.service": "Support humain",
  "home.float.sales": "Ventes",

  "home.cap.tag": "Capacité",
  "home.cap.h2": "Un seul client, tout votre espace de travail IA",
  "home.cap.c1t": "Routage hybride local + cloud",
  "home.cap.c1d": "Utilisez Ollama local hors ligne, basculez automatiquement vers les modèles phares cloud en ligne. Changez de modèle en pleine conversation.",
  "home.cap.c2t": "17 experts métier collaborent",
  "home.cap.c2d": "Donnez un objectif et AdminAgent divise les sous-tâches, attribue le bon expert et fusionne les résultats.",
  "home.cap.c3t": "Mémoire à quatre couches",
  "home.cap.c3d": "Faits résidents, archive de session, bibliothèque de compétences et profil utilisateur.",
  "home.cap.c4t": "Les compétences se cristallisent automatiquement",
  "home.cap.c4d": "Les flux qui fonctionnent sont extraits automatiquement en compétences réutilisables.",
  "home.cap.c5t": "Vraie manipulation de fichiers",
  "home.cap.c5d": "Lire/écrire docs et tableurs, exécuter des scripts, piloter Windows.",

  "home.feat.tag": "Toutes les fonctionnalités",
  "home.feat.h2": "Toutes les fonctionnalités, cliquez pour les détails",
  "home.feat.p": "Chaque carte ouvre une page complète : ce qu'elle fait, comment l'utiliser et les points techniques.",

  "home.wf.tag": "Workflow",
  "home.wf.h2": "Transformez les flux répétitifs en pipeline",
  "home.wf.i1t": "Glissez et connectez librement",
  "home.wf.i1d": "Organisez les flux comme des blocs ; changez une étape sans refaire le reste.",
  "home.wf.i2t": "Prévisualisez chaque étape",
  "home.wf.i2d": "Texte, images, vidéo, audio — cliquez un nœud pour le voir.",
  "home.wf.i3t": "Modèles en un clic",
  "home.wf.i3d": "Shorts IA / singles musicaux / concept art — flux prêts intégrés.",
  "home.wf.memtag": "Mémoire",
  "home.wf.memh2": "Il ne repart pas de zéro à chaque fois",
  "home.wf.mem.i1t": "Pas de perte de contexte au changement de sujet",
  "home.wf.mem.i1d": "Reprenez cette semaine les demandes de la semaine dernière.",
  "home.wf.mem.i2t": "Les flux deviennent des compétences",
  "home.wf.mem.i2d": "La même tâche ne prend qu'une phrase la deuxième fois.",

  "home.mem.l1t": "Mémoire résidente",
  "home.mem.l1d": "Les faits et préférences les plus critiques, injectés à chaque tour.",
  "home.mem.l2t": "Archive de session",
  "home.mem.l2d": "Tout l'historique, retrouvé par nombre de correspondances de mots-clés.",
  "home.mem.l3t": "Bibliothèque de compétences",
  "home.mem.l3d": "Les flux éprouvés se cristallisent automatiquement pour réutilisation.",
  "home.mem.l4t": "Profil utilisateur",
  "home.mem.l4d": "Le style de communication et les connaissances métier s'accumulent avec le temps.",

  "home.models.tag": "Modèles",
  "home.models.h2": "À peu près tous les modèles que vous voulez",
  "home.models.m1": "Ollama local",
  "home.models.m2": "DeepSeek V4",
  "home.models.m3": "Qwen3.8 Max",
  "home.models.m4": "GLM 5.3",
  "home.models.m5": "Kimi K3",
  "home.models.m6": "Doubao Seed",
  "home.models.m7": "Claude Opus / Sonnet",
  "home.models.m8": "GPT-5.6",
  "home.models.m9": "Gemini",
  "home.models.m10": "Kling",
  "home.models.m11": "Suno music",
  "home.models.m12": "OpenRouter tous",

  "home.price.tag": "Tarifs",
  "home.price.h2": "Commencez gratuit, passez à la suite quand vous en avez besoin",
  "home.price.free.name": "Gratuit",
  "home.price.free.li1": "Modèles locaux illimités",
  "home.price.free.li2": "Chat et opérations fichiers de base",
  "home.price.free.li3": "Publicités incluses",
  "home.price.free.li4": "Support communautaire",
  "home.price.free.cta": "Téléchargement gratuit",
  "home.price.std.flag": "Le plus populaire",
  "home.price.std.name": "Standard",
  "home.price.std.li1": "Contexte et mémoire plus longs",
  "home.price.std.li2": "Modèles cloud rentables",
  "home.price.std.li3": "Sans publicité",
  "home.price.std.li4": "Fonctionnalités workflow complètes",
  "home.price.std.cta": "Passer au Standard",
  "home.price.pro.name": "Pro",
  "home.price.pro.li1": "Tous les modèles phares",
  "home.price.pro.li2": "Génération vidéo / musique IA",
  "home.price.pro.li3": "Collaboration multi-experts",
  "home.price.pro.li4": "Support prioritaire",
  "home.price.pro.cta": "Passer au Pro",
  "home.price.ult.flag": "Bientôt disponible",
  "home.price.ult.name": "Ultimate",
  "home.price.ult.li1": "Contexte immense",
  "home.price.ult.li2": "Modèles haut de gamme exclusifs",
  "home.price.ult.li3": "Collab équipe (prévue)",
  "home.price.ult.li4": "—",
  "home.price.ult.cta": "Bientôt disponible",

  "home.faq.h2": "FAQ",
  "home.faq.q1": "Fonctionne-t-il hors ligne ?",
  "home.faq.a1": "Oui. Les modèles Ollama locaux tournent entièrement hors ligne — chat, opérations fichiers et orchestration de workflow ne nécessitent aucun réseau.",
  "home.faq.q2": "Mes données sont-elles envoyées ?",
  "home.faq.a2": "Non. L'historique de chat, la base de connaissances et la mémoire restent sur votre machine.",
  "home.faq.q3": "Quelles sont les limites de l'offre Gratuite ?",
  "home.faq.a3": "Le gratuit donne toutes les capacités locales et les outils de base avec un emplacement publicitaire ; les modèles phares cloud et la génération vidéo/musique IA sont payants.",
  "home.faq.q4": "Quels systèmes sont pris en charge ?",
  "home.faq.a4": "Windows et macOS. Mobile (Android / iOS / HarmonyOS) est prévu.",

  "home.cta.h2": "Laissez l'IA commencer à travailler maintenant",
  "home.cta.p": "L'offre gratuite est pour toujours, s'installe en une minute, aucune carte bancaire requise.",
  "home.cta.btn": "Télécharger gratuitement Working Mate",

  "home.foot.copy": "© 2026 Working Mate · Espace de travail IA local-first",
  "home.foot.privacy": "Confidentialité",
  "home.foot.terms": "Conditions",
  "home.foot.refunds": "Remboursements",

  /* ───────── 功能页共享 UI (FEAT-UI) ───────── */
  "feat.nav.features": "Fonctionnalités",
  "feat.nav.workflow": "Workflow",
  "feat.nav.models": "Modèles",
  "feat.nav.pricing": "Tarifs",
  "feat.nav.download": "Téléchargement gratuit",
  "feat.foot.copy": "© 2026 Working Mate · Espace de travail IA local-first",
  "feat.foot.features": "Fonctionnalités",
  "feat.foot.privacy": "Confidentialité",
  "feat.foot.terms": "Conditions",
  "feat.foot.refunds": "Remboursements",
  "feat.tpl.back": "Retour à toutes les fonctionnalités",
  "feat.tpl.what": "Ce qu'il fait",
  "feat.tpl.how": "Comment l'utiliser",
  "feat.tpl.tech": "Points techniques",
  "feat.tpl.shot": "Jetez un œil",
  "feat.tpl.related": "Fonctionnalités liées",
  "feat.tpl.end": "Essayez-le",
  "feat.tpl.endP": "L'offre gratuite est pour toujours ; les fonctionnalités locales marchent d'emblée, aucune carte bancaire requise.",
  "feat.tpl.endBtn": "Télécharger gratuitement Working Mate",
  "feat.tpl.view": "Voir le détail →",
  "feat.tpl.heroCta1": "Essayer le téléchargement gratuit",
  "feat.tpl.heroCta2": "Voir d'autres fonctionnalités",

  /* ───────── 功能数据 (FEAT-DATA) ───────── */
  "feat.models.title": "Routage hybride multimodèle",
  "feat.models.tag": "Routeur multimodèle",
  "feat.models.sub": "Ollama local et modèles phares cloud dans une même boîte de chat : bascule auto vers local hors ligne, auto vers cloud en ligne ; changez de modèle en pleine conversation sans redémarrer ni reconfigurer.",
  "feat.models.fact0": "60+ modèles",
  "feat.models.fact1": "Local / cloud unifié",
  "feat.models.fact2": "Repli auto",
  "feat.models.fact3": "0 donnée sortie (local)",
  "feat.models.grid": "60+ modèles · entrée unifiée local / cloud",
  "feat.models.what0t": "Une saisie, tous les modèles",
  "feat.models.what0d": "Pas de jonglerie avec les API, pas d'onglets éparpillés. DeepSeek, Qwen, GLM, Kimi, Doubao, GPT, Claude, Gemini, OpenRouter — tous dans un menu déroulant.",
  "feat.models.what1t": "Local d'abord, hors ligne",
  "feat.models.what1d": "Branchez Ollama et passez entièrement hors ligne : chat, opérations fichiers et orchestration de workflow ne nécessitent aucun réseau, les données ne quittent jamais la machine.",
  "feat.models.what2t": "Stratégie modèle à trois niveaux",
  "feat.models.what2d": "Standard / Pro / Phare en un clic ; le système choisit automatiquement le meilleur rapport qualité-prix par tâche, ou vous choisissez manuellement.",
  "feat.models.what3t": "Dégradation auto multimodèle",
  "feat.models.what3d": "En cas de limite de débit ou 5xx, il passe automatiquement au candidat suivant ; ne s'arrête et n'erre clairement qu'en cas de solde insuffisant ou d'échec d'auth — jamais en silence.",
  "feat.models.what4t": "Les experts apportent des groupes de modèles",
  "feat.models.what4d": "Les 17 experts métier lient chacun un groupe modèle raisonnement / général / code, ainsi les codeurs usent de modèles code et les rédacteurs de modèles rédaction.",
  "feat.models.what5t": "Échangez en direct dans une session",
  "feat.models.what5d": "Changez de modèle en plein chat sans perdre le contexte — vraiment « changez de cerveau à la volée ».",
  "feat.models.step0": "Réglages → Modèles et exécution, choisissez un niveau (Standard / Pro / Phare).",
  "feat.models.step1": "Pour un usage hors ligne, activez Ollama local ; le client découvre les modèles locaux automatiquement.",
  "feat.models.step2": "Choisissez un modèle dans le menu du haut, ou utilisez simplement « Routeur auto » pour le laisser choisir.",
  "feat.models.step3": "Hors ligne il revient au local ; en ligne il restaure le cloud — aucune intervention manuelle.",
  "feat.models.tech0": "Abstraction cloud_client unifiée ; local / cloud partagent une même signature d'appel.",
  "feat.models.tech1": "429 distingue « limite de débit » vs « solde insuffisant » : retry une fois sur limite, arrêt et invite de recharge sur solde.",
  "feat.models.tech2": "Chaîne de repli multimodèle : bascule seulement sur limite / 5xx ; jamais sur erreurs d'auth (évite les retries inutiles).",
  "feat.models.tech3": "Modèles indexés par niveau × usage ; les experts référencent directement les groupes de modèles.",
  "feat.models.shot": "Une saisie, local et cloud connectés",

  "feat.experts.title": "17 experts métier collaborent",
  "feat.experts.tag": "Équipe d'experts",
  "feat.experts.sub": "Donnez un objectif, AdminAgent le divise en sous-tâches, attribue le bon expert et fusionne en un seul résultat. Pas d'écriture de prompt, pas de découpage manuel.",
  "feat.experts.fact0": "17 experts métier",
  "feat.experts.fact1": "Division / attribution auto",
  "feat.experts.fact2": "≤10 appels outil / sous-tâche",
  "feat.experts.fact3": "Résultats fusionnés auto",
  "feat.experts.grid": "17 experts métier · division / attribution auto",
  "feat.experts.what0t": "Briefez en une phrase",
  "feat.experts.what0d": "Dites « transforme les ventes sur 3 mois de ce Excel en graphe de tendance et écris une analyse » — il divise en lire → nettoyer → graphe → analyser et attribue.",
  "feat.experts.what1t": "17 experts métier",
  "feat.experts.what1d": "Recherche, shorts vidéo, design image, musique, trading, actuariat, solo-business, architecture logicielle, IA, prompting, Codex full-stack, bureau, code, rédaction, data science, ops, général.",
  "feat.experts.what2t": "AdminAgent fait la division",
  "feat.experts.what2d": "L'agent maître lit votre objectif → construit une liste de sous-tâches (avec dépendances) → envoie chacune au bon expert.",
  "feat.experts.what3t": "Les experts apportent des groupes de modèles",
  "feat.experts.what3d": "Chaque expert lie un groupe modèle raisonnement / général / code, et lie des modèles de génération sur image / vidéo / musique.",
  "feat.experts.what4t": "Les appels outils restent bornés",
  "feat.experts.what4d": "Jusqu'à 10 appels outils par sous-tâche, avec listes autoriser/refuser, évitant les appels incontrôlés ou dangereux.",
  "feat.experts.what5t": "Fusionnés en une seule livraison",
  "feat.experts.what5d": "Quand toutes les sous-tâches finissent, les résultats fusionnent automatiquement en une sortie utilisable, pas des fragments éparpillés.",
  "feat.experts.step0": "Activez « Mode Agent » en haut.",
  "feat.experts.step1": "Décrivez votre objectif (plus précis = mieux) ; pas de découpage manuel.",
  "feat.experts.step2": "L'agent affiche d'abord une liste de sous-tâches ; confirmez pour démarrer.",
  "feat.experts.step3": "Vous pouvez arrêter d'urgence à tout moment et suivre le statut et les artefacts de chaque sous-tâche.",
  "feat.experts.tech0": "Division et exécution partagent une même chaîne de dégradation multimodèle ; les limites de débit ne plantent pas toute la tâche.",
  "feat.experts.tech1": "Une sous-tâche échouée ne saute que ses aval ; les autres branches continuent.",
  "feat.experts.tech2": "Les appels inter-espaces sont plafonnés (évite les boucles) pour que les experts ne se renvoient pas à l'infini.",
  "feat.experts.tech3": "L'échec d'analyse de la division lève la vraie erreur au lieu de renvoyer silencieusement vide.",
  "feat.experts.shot": "Objectif → sous-tâches → exécution expert",

  "feat.memory.title": "Système de mémoire à quatre couches",
  "feat.memory.tag": "Mémoire",
  "feat.memory.sub": "Il ne repart pas de zéro à chaque fois. Faits clés, sessions passées, flux éprouvés, vos préférences et votre style s'installent dans quatre couches de mémoire — plus vous l'utilisez, plus il vous connaît.",
  "feat.memory.fact0": "4 couches de mémoire",
  "feat.memory.fact1": "Recherche n-gram chinois",
  "feat.memory.fact2": "SQLite local",
  "feat.memory.fact3": "Capacité plafonnée",
  "feat.memory.grid": "4 couches de mémoire · recherche n-gram chinois",
  "feat.memory.what0t": "L1 Mémoire résidente",
  "feat.memory.what0d": "Les faits et préférences les plus importants injectés à chaque tour. Un plafond de capacité force à ne garder que les plus précieux.",
  "feat.memory.what1t": "L2 Archive de session",
  "feat.memory.what1d": "Toutes les sessions passées stockées localement, rappelées par nombre de correspondances de mots-clés, injectées seulement si besoin — pas de budget résident dépensé.",
  "feat.memory.what2t": "L3 Bibliothèque de compétences",
  "feat.memory.what2d": "Les flux éprouvés s'extraient auto en compétences réutilisables — la deuxième fois, une phrase rejoue toute l'action.",
  "feat.memory.what3t": "L4 Profil utilisateur",
  "feat.memory.what3d": "Style de communication, connaissances métier, habitudes s'accumulent pour que les réponses ressemblent plus à vous.",
  "feat.memory.what4t": "Changez de sujet sans perdre le fil",
  "feat.memory.what4d": "Les besoins de la semaine dernière perdurent ; partez et revenez, il se souvient encore du contexte.",
  "feat.memory.what5t": "Mémoire visible et effaçable",
  "feat.memory.what5d": "Le panneau latéral « Fichiers mémoire » est toujours inspectable ; les entrées erronées peuvent être effacées ou corrigées.",
  "feat.memory.step0": "Discutez normalement ; pas de « souviens-toi » manuel.",
  "feat.memory.step1": "Le panneau « Fichiers mémoire » montre le résident L1 et le profil L4 actuels.",
  "feat.memory.step2": "« Nettoyage mémoire » efface une couche ou supprime une session.",
  "feat.memory.step3": "Pour lui faire mémoriser une règle stricte, énoncez-la simplement dans le chat — jugée fait à long terme.",
  "feat.memory.tech0": "Le chinois utilise n-gram 2-4 car avec tokenisation anglais pour corriger le faible taux de correspondance LIKE sur chaîne entière.",
  "feat.memory.tech1": "L2 score par nombre de correspondances ; dégrade auto en table simple + LIKE si SQLite FTS5 indisponible.",
  "feat.memory.tech2": "Les résumés légers sautent le LLM, concaténant premier/dernier tours pour contrôler le coût.",
  "feat.memory.tech3": "Chaque couche a un plafond de caractères, protégeant la mémoire du débordement périmé.",
  "feat.memory.shot": "Fichiers mémoire, toujours inspectables et effaçables",

  "feat.skills.title": "Les compétences se cristallisent automatiquement",
  "feat.skills.tag": "Compétences auto-évolutives",
  "feat.skills.sub": "Un flux que vous avez exécuté est extrait auto en une compétence réutilisable de la bibliothèque. La prochaine fois, une phrase reproduit toute l'action.",
  "feat.skills.fact0": "Extraction auto des flux",
  "feat.skills.fact1": "Bibliothèque centrale de compétences",
  "feat.skills.fact2": "Stockage local",
  "feat.skills.fact3": "Réutilisable et partageable",
  "feat.skills.grid": "Extraction auto des flux · bibliothèque centrale",
  "feat.skills.what0t": "Exécutez une fois, devient compétence",
  "feat.skills.what0d": "Un flux complet (lire → traiter → sortir) qui fonctionne est extrait auto en compétence structurée réutilisable.",
  "feat.skills.what1t": "La prochaine fois, une phrase",
  "feat.skills.what1d": "Dites simplement « fais comme la dernière fois » ; il correspond depuis la bibliothèque et exécute, sans redécrire les étapes.",
  "feat.skills.what2t": "Bibliothèque de compétences visualisée",
  "feat.skills.what2d": "Panneau « Bibliothèque de compétences » pour parcourir, chercher, activer ou supprimer les compétences existantes.",
  "feat.skills.what3t": "Câblé à la mémoire à quatre couches",
  "feat.skills.what3d": "Les compétences appartiennent à L3, partageant le même système de mémoire avec workflows et experts.",
  "feat.skills.what4t": "Les échecs ne polluent pas la bibliothèque",
  "feat.skills.what4d": "Seuls les flux vraiment fonctionnels se cristallisent ; les à moitié échoués ne sont pas enregistrés comme compétences.",
  "feat.skills.what5t": "Stockage local",
  "feat.skills.what5d": "La bibliothèque de compétences vit sur votre machine, pas envoyée au cloud.",
  "feat.skills.step0": "Laissez l'agent finir un travail multi-étapes comme d'habitude.",
  "feat.skills.step1": "En cas de succès, le système extrait et stocke auto la compétence.",
  "feat.skills.step2": "Ouvrez le panneau « Bibliothèque de compétences » pour confirmer (renommer, supprimer).",
  "feat.skills.step3": "La prochaine fois référencez la compétence directement, ou laissez l'agent l'associer auto.",
  "feat.skills.tech0": "L'extraction de compétence partage le même modèle nœud/étape avec le moteur de workflow.",
  "feat.skills.tech1": "Les compétences sont stockées comme fichiers locaux pour sauvegarde et migration faciles.",
  "feat.skills.tech2": "Séparées de la mémoire L1/L2 pour éviter que le texte de compétence encombre le budget résident.",
  "feat.skills.shot": "Bibliothèque de compétences : cristallisée au succès",

  "feat.workflow.title": "Canevas de workflow en nœuds",
  "feat.workflow.tag": "Canevas de workflow",
  "feat.workflow.sub": "Enchaînez l'IA comme des blocs : glissez des nœuds, connectez, exécutez. Chaque étape prévisualise, relance et édite son prompt individuellement — des prompts que vous pouvez écrire vous-même ou laisser l'IA écrire.",
  "feat.workflow.fact0": "10 types de nœuds",
  "feat.workflow.fact1": "Glisser + auto-connecter + auto-disposition",
  "feat.workflow.fact2": "Relance d'un nœud seul",
  "feat.workflow.fact3": "Prompt DIY ou écrit par IA",
  "feat.workflow.grid": "10 types de nœuds · glisser + auto-connecter + auto-disposition",
  "feat.workflow.what0t": "10 nœuds, couverture totale",
  "feat.workflow.what0d": "Texte LLM, storyboard, image IA, vidéo IA, musique IA, composition vidéo, nœud outil, carte texte, image locale, musique locale.",
  "feat.workflow.what1t": "Glisser + connecter",
  "feat.workflow.what1d": "Glissez depuis la bibliothèque de gauche sur le canevas, maintenez le bord droit d'un nœud vers sa cible pour connecter ; ou « ⚡ Auto Connect » câble d'un coup par logique de type.",
  "feat.workflow.what2t": "Auto-disposition",
  "feat.workflow.what2d": "« ⌗ Auto Disposition » arrange par dépendance en couches ; un clic réordonne les nœuds éparpillés.",
  "feat.workflow.what3t": "Prévisualisez chaque étape",
  "feat.workflow.what3d": "Cliquez n'importe quel nœud et le panneau droit montre son artefact texte / image / vidéo / audio avec lecteur.",
  "feat.workflow.what4t": "Prompts entièrement DIY",
  "feat.workflow.what4d": "Chaque paramètre texte est un éditeur multi-lignes ; supporte les espaces réservés {{node}} référençant les artefacts amont.",
  "feat.workflow.what5t": "🪄 L'IA écrit les prompts pour vous",
  "feat.workflow.what5d": "Donnez une intention d'une ligne, l'IA écrit un prompt pro par type de nœud (artiste storyboard / directeur artistique / producteur musique ont chacun un modèle) ; encore éditable après.",
  "feat.workflow.what6t": "Modèles exécutés instantanément",
  "feat.workflow.what6d": "Shorts IA, singles musicaux, flux concept-art intégrés — changez un thème et exécutez.",
  "feat.workflow.what7t": "Analyse de fiabilité",
  "feat.workflow.what7d": "« 🛡 Fiabilité » vérifie paramètres manquants, clés manquantes, liens cassés, cycles, avec score et conseils de correction.",
  "feat.workflow.step0": "Ouvrez le panneau « Workflow », glissez des nœuds (ou « Charger modèle »).",
  "feat.workflow.step1": "Connectez : maintenez le bord droit d'un nœud vers la cible ; les paresseux cliquent « ⚡ Auto Connect ».",
  "feat.workflow.step2": "Cliquez un nœud, réglez son prompt pour cette tâche (écrire ou 🪄 IA écrit).",
  "feat.workflow.step3": "« ▶ Exécuter le workflow » lance le flux complet ; un nœud échoué ne bloque pas les autres branches.",
  "feat.workflow.step4": "Sauvegardez le canevas en JSON ; « Sauver / Ouvrir JSON » pour réutilisation et partage.",
  "feat.workflow.tech0": "Les nœuds sont dict plat + deps ; le moteur exécute topologiquement en série, les branches échouées sautent auto l'aval.",
  "feat.workflow.tech1": "Les espaces réservés référencent les artefacts amont, supportent le nième élément d'une liste (ex. plan shot 1).",
  "feat.workflow.tech2": "Params normalisés par type (durée→int, instrumental→bool) pour éviter les erreurs de type cloud.",
  "feat.workflow.tech3": "Les valeurs de retour du nœud LLM ont détection d'erreur, empêchant le texte d'erreur de couler en aval comme script.",
  "feat.workflow.shot": "Canevas de nœuds : glisser, connecter, prévisualiser par nœud",

  "feat.media.title": "Usine média IA",
  "feat.media.tag": "Studio média IA",
  "feat.media.sub": "D'un thème à une clip finie : script → storyboard → plans vidéo IA → musique de fond → sous-titres → composition, tout intégré au client — pas besoin de sauter de site en site.",
  "feat.media.fact0": "Script / storyboard / vidéo / musique",
  "feat.media.fact1": "Sous-titres + GIF",
  "feat.media.fact2": "Vertical 9:16",
  "feat.media.fact3": "Auto-archivé",
  "feat.media.grid": "Script / storyboard / vidéo / musique · sous-titres + GIF",
  "feat.media.what0t": "Génération de script",
  "feat.media.what0d": "Donnez un thème, obtenez un script de micro-drama 60s trois plans avec prompts image auto-découpés par plan.",
  "feat.media.what1t": "Découpage storyboard",
  "feat.media.what1d": "Extraite auto chaque description de plan en liste structurée, envoyée une à une aux nœuds vidéo.",
  "feat.media.what2t": "Plans vidéo IA",
  "feat.media.what2d": "Appelez texte-vers-vidéo pour générer chaque plan, vertical 9:16, durée ajustable, relance d'un plan seul.",
  "feat.media.what3t": "Musique de fond",
  "feat.media.what3d": "Générez un thème instrumental selon l'humeur du script, ou laissez l'IA écrire une chanson complète avec paroles.",
  "feat.media.what4t": "Image IA",
  "feat.media.what4d": "Concept art cinématographique, images de couverture, refs storyboard, ratios sélectionnables.",
  "feat.media.what5t": "Sous-titres et GIF",
  "feat.media.what5d": "Fichiers de sous-titres auto, ou exportez les clips en GIF.",
  "feat.media.what6t": "Composition vidéo",
  "feat.media.what6d": "Composez plusieurs plans dans l'ordre en une seule clip finie.",
  "feat.media.what7t": "Ressources locales insérables",
  "feat.media.what7d": "Vos propres images et musiques peuvent tomber dans le workflow comme refs ou score, mélangées à la sortie IA.",
  "feat.media.step0": "Workflow → Chargez le modèle « 🎬 Short IA (3 plans + musique) ».",
  "feat.media.step1": "Changez le thème pour cette tâche (ex. « la vie quotidienne d'un dragon qui travaille »).",
  "feat.media.step2": "Cliquez le nœud script, écrivez ou 🪄 IA écrit ; confirmez puis exécutez.",
  "feat.media.step3": "Prévisualisez par nœud : script et storyboard d'abord, puis plans vidéo et musique générés.",
  "feat.media.step4": "Le nœud composition sort la clip ; les artefacts atterrissent auto dans le dossier d'archive de tâche.",
  "feat.media.tech0": "Vidéo / musique / image connectés à Kling, Suno, modèles image via un registre d'outils unifié.",
  "feat.media.tech1": "Les nœuds média facturent à l'usage ; l'UI montre le coût clairement (le gratuit peut pratiquer les flux en local).",
  "feat.media.tech2": "Nombre de plans, ratio, durée tous éditables ; le prompt de plan supporte le remplacement dur de l'amont.",
  "feat.media.tech3": "Les chemins d'artefacts auto-renseignés aux nœuds ; la prochaine relance réutilise directement.",
  "feat.media.shot": "Script → storyboard → plans → musique",

  "feat.modules.title": "Six modules de scénarios métier",
  "feat.modules.tag": "Scénarios",
  "feat.modules.sub": "Recherche, vidéo, image, finance, logiciel, growth — six entrées de scénario prêtes à l'emploi, chacune pré-réglée avec experts, outils et cartes rapides ; cliquez et partez.",
  "feat.modules.fact0": "6 scénarios",
  "feat.modules.fact1": "Cartes rapides pré-réglées",
  "feat.modules.fact2": "Multilingue",
  "feat.modules.fact3": "Local / cloud",
  "feat.modules.grid": "6 scénarios · cartes de démarrage rapide pré-réglées",
  "feat.modules.what0t": "Recherche",
  "feat.modules.what0d": "Recherche de papiers, organisation de matériel, résumé structuré et comparaison — idéal pour revues et propositions.",
  "feat.modules.what1t": "Création vidéo et image",
  "feat.modules.what1d": "Script court vers clip, design concept et couverture, câblé aux experts de création.",
  "feat.modules.what2t": "Finance et investissement",
  "feat.modules.what2d": "Données de marché, infos entreprise, thèse long/short et risque — câblé au trader / actuaire.",
  "feat.modules.what3t": "Logiciel et code",
  "feat.modules.what3d": "Découpage de besoin, génération de code, debug, exécution de scripts rapides — câblé à l'architecte / Codex full-stack.",
  "feat.modules.what4t": "Growth et marketing",
  "feat.modules.what4d": "Sujets, copy, planification de campagne, conception d'expériences growth.",
  "feat.modules.what5t": "Chaque module a des cartes rapides",
  "feat.modules.what5d": "Pas de prompt from scratch ; cliquez une carte pour utiliser un modèle de tâche prêt.",
  "feat.modules.step0": "Panneau « NAVIGATION » choisissez un scénario (recherche / vidéo / image / finance / logiciel / growth).",
  "feat.modules.step1": "Cliquez une carte rapide dans le scénario, ou décrivez simplement le besoin.",
  "feat.modules.step2": "Pour cross-scénario, un espace projet rassemble les artefacts de plusieurs scénarios.",
  "feat.modules.tech0": "Les cartes scénario sont juste des combos « modèle de tâche + expert + outil », tous définis localement, éditables.",
  "feat.modules.tech1": "Les scénarios partagent un registre d'outils et un système de mémoire ; les artefacts interopèrent.",
  "feat.modules.tech2": "L'UI supporte 10 langues ; le copy des cartes scénario suit le switch.",
  "feat.modules.shot": "Cartes scénario : cliquez et commencez à travailler",

  "feat.spaces.title": "Espaces projet & centre de tâches",
  "feat.spaces.tag": "Projets & tâches",
  "feat.spaces.sub": "Un objectif, un espace ; plusieurs tâches en parallèle sans mélange ; tous les artefacts, logs et contexte archivés dans l'espace, reprenez à tout moment.",
  "feat.spaces.fact0": "Tâches parallèles",
  "feat.spaces.fact1": "Isolement de contexte au niveau espace",
  "feat.spaces.fact2": "Auto-archivé",
  "feat.spaces.fact3": "Progression kanban",
  "feat.spaces.grid": "Tâches parallèles · isolement de contexte au niveau espace",
  "feat.spaces.what0t": "Espace projet",
  "feat.spaces.what0d": "Ouvrez un espace par projet ; ses objectifs, pièces jointes, artefacts et historique de chat sont stockés séparément, jamais pollués par d'autres.",
  "feat.spaces.what1t": "Tâches parallèles",
  "feat.spaces.what1d": "Exécutez plusieurs sous-tâches dans un espace, chacune sur sa propre progression.",
  "feat.spaces.what2t": "Centre de tâches kanban",
  "feat.spaces.what2d": "Toutes les tâches en un tableau : statut, temps, artefacts, raisons d'échec d'un coup d'œil.",
  "feat.spaces.what3t": "Bus de contexte",
  "feat.spaces.what3d": "Les espaces peuvent référencer les artefacts des autres dans la limite ; les plafonds d'appel évitent la dépendance circulaire.",
  "feat.spaces.what4t": "Archive d'artefacts",
  "feat.spaces.what4d": "Fichiers, images, vidéo, tableurs générés atterrissent auto dans le dossier d'espace — pas de chasse.",
  "feat.spaces.what5t": "Reprenez à tout moment",
  "feat.spaces.what5d": "Fermez et rouvrez le client ; l'espace et la progression restent.",
  "feat.spaces.step0": "Panneau « Espaces projet » → Nouvel espace, énoncez l'objectif et attachez les fichiers de référence.",
  "feat.spaces.step1": "Confiez l'objectif à l'agent ; il divise en sous-tâches parallèles.",
  "feat.spaces.step2": "« Centre de tâches » montre la progression globale et les artefacts de chaque tâche.",
  "feat.spaces.step3": "Une fois fait, récupérez tous les artefacts du dossier d'espace ; itérez dans le même espace.",
  "feat.spaces.tech0": "Les espaces passent les refs d'artefacts via un bus de contexte ; appels inter-espaces plafonnés pour éviter les boucles.",
  "feat.spaces.tech1": "L'état de tâche et les chemins d'artefacts persistent ; le redémarrage ne les perd pas.",
  "feat.spaces.tech2": "Le journal d'exécution de chaque espace est gardé séparément pour traçage d'étape facile.",
  "feat.spaces.shot": "Espace projet : objectif, tâches, artefacts en un lieu",

  "feat.task_center.title": "Centre de tâches",
  "feat.task_center.tag": "Centre de tâches",
  "feat.task_center.sub": "Toutes les tâches en un kanban : qui tourne, quelle étape, combien de temps, qu'a-t-il produit, pourquoi a-t-il échoué — clair d'un coup d'œil.",
  "feat.task_center.fact0": "Tableau central",
  "feat.task_center.fact1": "Statut temps réel",
  "feat.task_center.fact2": "Échec traçable",
  "feat.task_center.fact3": "Ouverture en un clic",
  "feat.task_center.grid": "Tableau central · rafraîchissement statut temps réel",
  "feat.task_center.what0t": "Un écran, tout",
  "feat.task_center.what0d": "Déclenché par chat, divisé par agent, ou exécuté sur planning — tout converge dans une liste.",
  "feat.task_center.what1t": "Statut temps réel",
  "feat.task_center.what1d": "En file / en cours / fait / échoué / sauté — les changements de statut rafraîchissent instantanément.",
  "feat.task_center.what2t": "Les échecs ont un sens",
  "feat.task_center.what2d": "L'échec n'est pas juste « erreur » — il donne l'étape et la raison spécifiques (clé manquante, limite de débit, fichier introuvable…).",
  "feat.task_center.what3t": "Artefact direct",
  "feat.task_center.what3d": "Ouvrez une tâche pour ouvrir son fichier, image, vidéo ou tableur.",
  "feat.task_center.what4t": "Paire avec workflow",
  "feat.task_center.what4d": "Le résultat de chaque nœud de workflow atterrit aussi dans le log de tâche pour traçage d'étape facile.",
  "feat.task_center.step0": "Panneau « Centre de tâches » pour voir toutes les tâches.",
  "feat.task_center.step1": "Cliquez une tâche pour détails : étapes, temps, artefacts, log.",
  "feat.task_center.step2": "Les tâches échouées peuvent être tracées puis relancées à cette étape.",
  "feat.task_center.tech0": "Structure tâche/étape à deux niveaux ; le log d'étape nomme outil, params, temps, résultat.",
  "feat.task_center.tech1": "Exécution et thread UI séparés ; les tâches longues ne gèlent pas l'UI ; crash de thread réinitialise auto l'état du bouton.",
  "feat.task_center.shot": "Centre de tâches : statut, temps, artefacts",

  "feat.automation.title": "Automatisation & tâches planifiées",
  "feat.automation.tag": "Automatisation",
  "feat.automation.sub": "Laissez l'IA travailler à votre rythme : actualités rangées chaque matin, données résumées chaque semaine, rappels à l'heure — ça tourne même quand vous ne regardez pas.",
  "feat.automation.fact0": "Planifié / périodique",
  "feat.automation.fact1": "Planificateur local",
  "feat.automation.fact2": "Historique journalisé",
  "feat.automation.fact3": "Échecs visibles",
  "feat.automation.grid": "Planifié / périodique · planificateur local",
  "feat.automation.what0t": "Créez en une phrase",
  "feat.automation.what0d": "« Range les actualités secteur d'hier en résumé à 9h chaque jour » — dit, et une automation existe.",
  "feat.automation.what1t": "Périodique et unique",
  "feat.automation.what1d": "Quotidien, hebdomadaire, mensuel, ou exécuté une fois à une heure fixe.",
  "feat.automation.what2t": "Planificateur local",
  "feat.automation.what2d": "Planification et données restent sur l'appareil, pas envoyées.",
  "feat.automation.what3t": "Historique d'exécution",
  "feat.automation.what3d": "Combien d'exécutions, chaque résultat, tout échec — tout enregistré.",
  "feat.automation.what4t": "Pausable et supprimable",
  "feat.automation.what4d": "Pause ou supprimez à tout moment que vous ne le voulez plus.",
  "feat.automation.step0": "Panneau « Automatisation » → Nouveau, écrivez quoi faire.",
  "feat.automation.step1": "Réglez heure et fréquence (quotidien / hebdomadaire / une fois à une heure).",
  "feat.automation.step2": "Sauvez, puis voyez prochaine exécution et historique dans la liste.",
  "feat.automation.tech0": "Déf et état d'exécution d'automation persistent séparément ; la planification survit au redémarrage.",
  "feat.automation.tech1": "Chaque exécution journalisée indépendamment pour juger contenu vs environnement.",
  "feat.automation.shot": "Travaillez automatiquement à votre rythme",

  "feat.gui.title": "Automatisation GUI",
  "feat.gui.tag": "Contrôle ordinateur",
  "feat.gui.sub": "Laissez l'IA piloter d'autres programmes sur votre machine : cliquer des boutons, remplir des formulaires, ouvrir des menus — même un vieux logiciel sans API est automatisé.",
  "feat.gui.fact0": "Simulation souris & clavier",
  "feat.gui.fact1": "Vérification capacité d'abord",
  "feat.gui.fact2": "Confirmer par action",
  "feat.gui.fact3": "Bascule à tout moment",
  "feat.gui.grid": "Simulation souris & clavier · vérification capacité d'abord",
  "feat.gui.what0t": "Opérez l'UI comme un humain",
  "feat.gui.what0d": "L'IA « voit » la fenêtre courante, puis décide où cliquer et quoi taper, avançant pas à pas.",
  "feat.gui.what1t": "Vérification capacité avant départ",
  "feat.gui.what1d": "Le système vérifie d'abord si l'environnement le supporte ; sinon, dit pourquoi au lieu d'échouer en silence.",
  "feat.gui.what2t": "Confirmer avant d'agir",
  "feat.gui.what2d": "Par défaut chaque action clé demande ; seul le mode auto-confirm saute les invites.",
  "feat.gui.what3t": "Les actions risquées restent bloquées",
  "feat.gui.what3d": "Les opérations destructives comme supprimer/écraser ne sont pas libérées par auto-confirm.",
  "feat.gui.what4t": "Bascule à tout moment",
  "feat.gui.what4d": "Un clic pour couper ; l'IA perd immédiatement le contrôle souris/clavier.",
  "feat.gui.step0": "Réglages → Activez « Automatisation GUI », passez la vérification capacité d'abord.",
  "feat.gui.step1": "Décrivez l'opération (plus précis = mieux).",
  "feat.gui.step2": "Confirmez chaque action clé comme invité.",
  "feat.gui.step3": "Coupez l'interrupteur quand fini.",
  "feat.gui.tech0": "La vérification capacité tourne et met en cache à l'activation, évitant « environnement non supporté » en cours.",
  "feat.gui.tech1": "Granularité d'opération configurable ; confirm par action par défaut.",
  "feat.gui.tech2": "Câblé à auto-confirm : seul auto-confirm explicite saute l'invite.",
  "feat.gui.shot": "Un vieux logiciel sans API est aussi automatisé",

  "feat.safety.title": "Garde-fous de sécurité : auto-confirm & arrêt d'urgence",
  "feat.safety.tag": "Sécurité",
  "feat.safety.sub": "Accordez le pouvoir qui doit l'être, bloquez ce qui doit l'être. Les écritures peuvent confirmer par étape ou auto-confirmer pour la vitesse — mais les actions risquées sont toujours bloquées, les suppressions vont toujours à la corbeille.",
  "feat.safety.fact0": "Niveaux : WARNING / BLOCKED",
  "feat.safety.fact1": "Mode auto-confirm",
  "feat.safety.fact2": "Arrêt en un clic",
  "feat.safety.fact3": "Suppressions → corbeille",
  "feat.safety.grid": "Niveaux : WARNING / BLOCKED · mode auto-confirm",
  "feat.safety.what0t": "Confirmer par étape par défaut",
  "feat.safety.what0d": "Chaque écriture, changement de donnée ou commande pop d'abord une fenêtre ; exécute seulement sur votre oui.",
  "feat.safety.what1t": "Auto-confirm (mode vitesse)",
  "feat.safety.what1d": "Après confiance, activez-le ; les écritures de routine arrêtent de demander, passent directement — bon pour les flux répétés vérifiés.",
  "feat.safety.what2t": "Risqué reste bloqué",
  "feat.safety.what2d": "Les actions destructives de niveau BLOCKED ne sont pas libérées par auto-confirm ; ont toujours besoin de votre accord.",
  "feat.safety.what3t": "Suppressions → corbeille",
  "feat.safety.what3d": "Les suppressions IA vont à la corbeille par défaut, pas effacées — récupérables en cas d'erreur.",
  "feat.safety.what4t": "Arrêt d'urgence en un clic",
  "feat.safety.what4d": "Voyez quelque chose de mal en cours de chaîne ? L'arrêt d'urgence termine la tâche en cours immédiatement.",
  "feat.safety.what5t": "Listes outils autoriser/refuser",
  "feat.safety.what5d": "Les outils appelables limités à la liste blanche ; les outils de liste noire sont inaccessibles dans tous les cas.",
  "feat.safety.step0": "Par défaut « confirmer chaque action » — rien à régler.",
  "feat.safety.step1": "Activez « Auto-Confirm » une fois la confiance suffisante ; il demande une fois à l'activation.",
  "feat.safety.step2": "Désactivez à tout moment depuis la barre du haut, retour à confirm par étape.",
  "feat.safety.step3": "En cours, cliquez « Stop » pour arrêter d'urgence la tâche courante.",
  "feat.safety.tech0": "Actions gradées par risque : WARNING peut être auto-confirmé, BLOCKED toujours bloqué.",
  "feat.safety.tech1": "Appels outils utilisent listes autoriser + refuser ; ≤10 appels par sous-tâche.",
  "feat.safety.tech2": "Suppressions uniformément passent par chemin sauvegarde corbeille pour récupérabilité.",
  "feat.safety.shot": "Accordez le pouvoir, bloquez ce qui doit l'être",

  "feat.files.title": "Vraie manipulation de fichiers",
  "feat.files.tag": "Vraie manipulation de fichiers",
  "feat.files.sub": "Il ne discute pas seulement : lit vos docs et tableurs, édite le contenu, génère de nouveaux fichiers, exécute des scripts, traite par lot — puis vous tend le fichier.",
  "feat.files.fact0": "Lit/écrit Office / tableurs",
  "feat.files.fact1": "Exécute des scripts",
  "feat.files.fact2": "Traitement par lot",
  "feat.files.fact3": "Glissez / collez images",
  "feat.files.grid": "Lit/écrit Office / tableurs · exécute des scripts",
  "feat.files.what0t": "Comprend vos fichiers",
  "feat.files.what0d": "Déposez Word, Excel, PPT, PDF, images ; il lit et travaille sur le contenu.",
  "feat.files.what1t": "Même format après édition",
  "feat.files.what1d": "Édite en place et sauve au format d'origine — pas un texte que vous recopiez.",
  "feat.files.what2t": "Génère de nouveaux fichiers",
  "feat.files.what2d": "Tableurs, rapports, listes, graphes — produit directement des fichiers ouvrables.",
  "feat.files.what3t": "Exécute des scripts",
  "feat.files.what3d": "Exécute des scripts pour lot si besoin ; la sortie revient dans le chat.",
  "feat.files.what4t": "Glissez et collez",
  "feat.files.what4d": "Déposez un fichier dans la saisie pour devenir contexte ; images presse-papiers Ctrl+V deviennent pièces jointes.",
  "feat.files.what5t": "Archive d'artefacts",
  "feat.files.what5d": "Les fichiers générés atterrissent dans le dossier de tâche pour ramassage facile.",
  "feat.files.step0": "Déposez un fichier dans la saisie (ou Ctrl+V collez une image).",
  "feat.files.step1": "Dites quoi faire : « résume cette feuille par mois et graphe la tendance ».",
  "feat.files.step2": "L'IA vous tend un nouveau fichier quand fini ; ouvrez et utilisez.",
  "feat.files.tech0": "Lecture/écriture fichier passe par une couche outil unifiée, partagée avec les nœuds de workflow.",
  "feat.files.tech1": "Les gros fichiers sont analysés structurellement avant traitement, évitant de bourrer tout le doc dans le contexte.",
  "feat.files.tech2": "Les chemins d'artefacts générés se renseignent en retour pour référence et retraitement ultérieurs.",
  "feat.files.shot": "Déposez, édité, vous rend un fichier",

  "feat.i18n.title": "Interface multilingue",
  "feat.i18n.tag": "i18n",
  "feat.i18n.sub": "L'UI supporte 10 langues avec switch en temps réel — instantané, sans redémarrage. Pratique pour les utilisateurs outre-mer ou la collaboration en équipe.",
  "feat.i18n.fact0": "10 langues",
  "feat.i18n.fact1": "Switch temps réel",
  "feat.i18n.fact2": "UI + cartes scénario",
  "feat.i18n.fact3": "Extensible",
  "feat.i18n.grid": "10 langues · switch temps réel",
  "feat.i18n.what0t": "10 langues",
  "feat.i18n.what0d": "简体中文, English, 日本語, 한국어, Deutsch, Français, Español, Português, Русский, العربية.",
  "feat.i18n.what1t": "Le switch prend effet instantanément",
  "feat.i18n.what1d": "Changez la langue dans Réglages ; le texte UI se met à jour immédiatement, sans redémarrage client.",
  "feat.i18n.what2t": "Couverture totale",
  "feat.i18n.what2d": "UI principale, réglages, canevas workflow, copy des cartes scénario partagent une même couche multilingue.",
  "feat.i18n.what3t": "Traductions extensibles",
  "feat.i18n.what3d": "Les ressources langue vivent dans des fichiers séparés ; ajouter une langue n'est qu'une copie de plus.",
  "feat.i18n.step0": "Réglages → Langue UI, choisissez une langue.",
  "feat.i18n.step1": "Si invité à redémarrer, redémarrez une fois pour plein effet.",
  "feat.i18n.tech0": "Tout le texte UI est récupéré via une fonction de traduction runtime, évitant le codage en dur du chinois à l'import.",
  "feat.i18n.tech1": "Les ressources langue sont des fichiers séparés pour revue et ajout faciles.",
  "feat.i18n.shot": "",

  "feat.privacy.title": "Local-first & confidentialité",
  "feat.privacy.tag": "Local first",
  "feat.privacy.sub": "Conversations, mémoire, base de connaissances, compétences et artefacts par défaut sur votre propre ordinateur. Fonctionne entièrement hors ligne ; le cloud est seulement pour les modèles que vous choisissez activement.",
  "feat.privacy.fact0": "0 donnée sortie (mode local)",
  "feat.privacy.fact1": "Utilisable hors ligne",
  "feat.privacy.fact2": "Tout sur l'appareil",
  "feat.privacy.fact3": "DB locale",
  "feat.privacy.grid": "0 donnée sortie (local) · utilisable hors ligne",
  "feat.privacy.what0t": "Les données restent sur l'appareil",
  "feat.privacy.what0d": "Historique de chat, mémoire à quatre couches, bibliothèque de compétences, artefacts de projet tous stockés comme fichiers locaux / DB locale.",
  "feat.privacy.what1t": "Utilisable hors ligne",
  "feat.privacy.what1d": "Avec modèles locaux, chat, opérations fichiers et orchestration workflow ne nécessitent aucun réseau.",
  "feat.privacy.what2t": "Le cloud est votre choix",
  "feat.privacy.what2d": "Seulement quand vous choisissez modèles cloud ou génération cloud le contenu lié va au fournisseur.",
  "feat.privacy.what3t": "Nettoyage en un clic",
  "feat.privacy.what3d": "« Nettoyage mémoire » peut effacer une couche de mémoire ou supprimer une session — parti pour de vrai.",
  "feat.privacy.what4t": "Pas de compte requis",
  "feat.privacy.what4d": "Le gratuit n'oblige pas l'enregistrement ; les fonctionnalités locales marchent d'emblée.",
  "feat.privacy.step0": "Pour tout hors ligne, utilisez simplement des modèles locaux.",
  "feat.privacy.step1": "Pour effacer les enregistrements : panneau « Nettoyage mémoire ».",
  "feat.privacy.step2": "Un chat vous semble sensible ? Ne choisissez juste pas de modèle cloud.",
  "feat.privacy.tech0": "Le stockage local utilise SQLite et dossiers locaux, pas de service cloud auto-construit.",
  "feat.privacy.tech1": "Les appels cloud passent seulement par votre clé fournisseur configurée, directement à l'API.",
  "feat.privacy.tech2": "Les couches de mémoire sont chacune effaçables, évitant « effacer une efface tout ».",
  "feat.privacy.shot": "Tout sur l'appareil, tourne hors ligne"
};
