/* Working Mate — 한국어 */
window.I18N = window.I18N || {};
window.I18N.ko = {
  "home.nav.capability": "기능",
  "home.nav.features": "전체 기능",
  "home.nav.workflow": "워크플로",
  "home.nav.models": "모델",
  "home.nav.pricing": "가격",
  "home.nav.console": "콘솔",
  "home.nav.login": "로그인",

  "home.hero1.eyebrow": "v1.4 출시 · 로컬 우선 멀티모델 AI 에이전트",
  "home.hero1.h1": "AI가 진짜로 <span class=\"glow\">일하게</span><br>그냥 대화만 하는 게 아니라",
  "home.hero1.sub": "로컬 Ollama와 클라우드 대형 모델을 하나로 스케줄링. 노드 방식 워크플로가 대본·콘티·영상·배경음악을 한 파이프라인으로 연결합니다. 4계층 기억이 쓸수록 당신을 이해하고, 데이터는 내 PC에 남으며 오프라인도 됩니다.",
  "home.hero1.stat1": "연동 모델",
  "home.hero1.stat2": "외부 전송 데이터",
  "home.hero1.stat3": "자체 진화 기억",
  "home.hero1.cta1": "무료 다운로드 · 무료판",
  "home.hero1.cta2": "워크플로 데모 보기",

  "home.hero2.eyebrow": "워크플로 · 노드 캔버스",
  "home.hero2.h1": "끌어다 놓기만 하면<br><span class=\"glow\">AI 파이프라인</span> 완성",
  "home.hero2.sub": "대본→콘티→영상 샷→배경음악까지 한 번에. 매 단계 미리보기, 단일 노드 재실행, 사용자 카드와 로컬 자료 삽입 지원.",
  "home.hero2.stat1": "분야 전문가",
  "home.hero2.stat2": "즉시 템플릿",
  "home.hero2.stat3": "끌어다 사용",
  "home.hero2.cta1": "워크플로 열기",
  "home.hero2.cta2": "60초 데모 보기",

  "home.hero3.eyebrow": "v1.4 · 한정 론칭 혜택",
  "home.hero3.h1": "여름 대할인<br>$0 으로 <span class=\"glow\">영구</span> 사용",
  "home.hero3.sub": "무료판은 영구 사용, 로컬 모델 무제한. 유료 등급은 더 긴 기억, 플래그십 모델, 클라우드 생성 할당량을 잠금 해제합니다.",
  "home.hero3.stat1": "시작 · 무료",
  "home.hero3.stat2": "스탠다드",
  "home.hero3.stat3": "팀 · 예정",
  "home.hero3.cta1": "지금 다운로드",
  "home.hero3.cta2": "변경 로그 보기",

  "home.float.assist": "AI 어시스턴트",
  "home.float.service": "인간 상담",
  "home.float.sales": "영업 문의",

  "home.cap.tag": "Capability",
  "home.cap.h2": "하나의 클라이언트에 AI 작업공간 전체를",
  "home.cap.c1t": "로컬 + 클라우드 하이브리드 라우팅",
  "home.cap.c1d": "오프라인일 땐 Ollama 로컬, 온라인일 땐 클라우드 플래그십으로 자동 전환. 대화 중에도 모델 자유 교체.",
  "home.cap.c2t": "17명 분야 전문가 협업",
  "home.cap.c2d": "목표를 주면 AdminAgent가 하위 작업을 나누고 알맞은 전문가에 배정해 결과를 합칩니다.",
  "home.cap.c3t": "4계층 기억",
  "home.cap.c3d": "상주 사실·세션 보관·스킬 라이브러리·사용자 프로필.",
  "home.cap.c4t": "스킬 자동 정착",
  "home.cap.c4d": "성공한 흐름이 자동으로 재사용 가능한 스킬로 추출됩니다.",
  "home.cap.c5t": "진짜 파일 작업",
  "home.cap.c5d": "문서·스프레드시트 읽기/쓰기, 스크립트 실행, 창 조작.",

  "home.feat.tag": "All Features",
  "home.feat.h2": "전체 기능, 클릭하면 상세히",
  "home.feat.p": "모든 카드가 전체 페이지를 엽니다. 무엇을 하는지, 어떻게 쓰는지, 기술 하이라이트를.",

  "home.wf.tag": "Workflow",
  "home.wf.h2": "반복 흐름을 파이프라인으로",
  "home.wf.i1t": "자유 드래그 & 연결",
  "home.wf.i1d": "블록처럼 흐름을 구성, 한 단계만 바꿔도 처음부터 안 해도 됨.",
  "home.wf.i2t": "매 단계 즉시 미리보기",
  "home.wf.i2d": "텍스트·이미지·영상·오디오, 노드를 클릭하면 바로 보임.",
  "home.wf.i3t": "원클릭 템플릿",
  "home.wf.i3d": "AI 쇼츠 / 음악 싱글 / 콘셉트 아트 — 내장 완료.",
  "home.wf.memtag": "Memory",
  "home.wf.memh2": "매번 처음부터 시작하지 않음",
  "home.wf.mem.i1t": "주제를 바꿔도 끊기지 않음",
  "home.wf.mem.i1d": "지난주 요청을 이번 주에 이어갑니다.",
  "home.wf.mem.i2t": "흐름이 스킬이 됨",
  "home.wf.mem.i2d": "같은 작업은 두 번째엔 한 문장이면 충분.",

  "home.mem.l1t": "상주 기억",
  "home.mem.l1d": "가장 중요한 사실과 선호를 매 턴 주입. 용량 한도로 가치 있는 몇 개만 유지.",
  "home.mem.l2t": "세션 보관",
  "home.mem.l2d": "전체 기록을 로컬 저장, 키워드 적중 수로 검색.",
  "home.mem.l3t": "스킬 라이브러리",
  "home.mem.l3d": "성공한 흐름이 자동 정착되어 재사용.",
  "home.mem.l4t": "사용자 프로필",
  "home.mem.l4d": "말투와 도메인 지식이 누적되어 당신답게.",

  "home.models.tag": "Models",
  "home.models.h2": "쓰고 싶은 모델은 다 있습니다",
  "home.models.m1": "Ollama 로컬",
  "home.models.m2": "DeepSeek V4",
  "home.models.m3": "Qwen3.8 Max",
  "home.models.m4": "GLM 5.3",
  "home.models.m5": "Kimi K3",
  "home.models.m6": "Doubao Seed",
  "home.models.m7": "Claude Opus / Sonnet",
  "home.models.m8": "GPT-5.6",
  "home.models.m9": "Gemini",
  "home.models.m10": "Kling",
  "home.models.m11": "Suno 음악",
  "home.models.m12": "OpenRouter 전체",

  "home.price.tag": "Pricing",
  "home.price.h2": "먼저 무료로, 더 필요하면 업그레이드",
  "home.price.free.name": "무료",
  "home.price.free.li1": "로컬 모델 무제한",
  "home.price.free.li2": "기본 대화 & 파일 작업",
  "home.price.free.li3": "광고 포함",
  "home.price.free.li4": "커뮤니티 지원",
  "home.price.free.cta": "무료 다운로드",
  "home.price.std.flag": "가장 인기",
  "home.price.std.name": "스탠다드",
  "home.price.std.li1": "더 긴 문맥 & 기억",
  "home.price.std.li2": "가성비 클라우드 모델",
  "home.price.std.li3": "광고 없음",
  "home.price.std.li4": "워크플로 전 기능",
  "home.price.std.cta": "스탠다드로 업그레이드",
  "home.price.pro.name": "프로",
  "home.price.pro.li1": "모든 플래그십 모델",
  "home.price.pro.li2": "AI 영상 / 음악 생성",
  "home.price.pro.li3": "다중 전문가 협업",
  "home.price.pro.li4": "우선 지원",
  "home.price.pro.cta": "프로로 업그레이드",
  "home.price.ult.flag": "출시 예정",
  "home.price.ult.name": "얼티밋",
  "home.price.ult.li1": "초대형 문맥",
  "home.price.ult.li2": "독점 최상위 모델",
  "home.price.ult.li3": "팀 협업 (예정)",
  "home.price.ult.li4": "—",
  "home.price.ult.cta": "출시 예정",

  "home.faq.h2": "자주 묻는 질문",
  "home.faq.q1": "오프라인에서도 되나요?",
  "home.faq.a1": "됩니다. 로컬 Ollama 모델은 완전 오프라인, 대화·파일 작업·워크플로 편성이 네트워크 불필요.",
  "home.faq.q2": "내 데이터가 업로드되나요?",
  "home.faq.a2": "아니요. 대화 기록·지식베이스·기억은 모두 내 PC에 남습니다.",
  "home.faq.q3": "무료판 제한은?",
  "home.faq.a3": "무료판은 모든 로컬 기능과 기본 도구를 광고 포함 제공. 클라우드 플래그십 모델, AI 영상/음악 생성은 유료.",
  "home.faq.q4": "어떤 시스템 지원?",
  "home.faq.a4": "Windows와 macOS. 모바일(Android / iOS / HarmonyOS)은 예정.",

  "home.cta.h2": "지금 AI가 일하게 하세요",
  "home.cta.p": "무료판은 영구, 1분 설치, 신용카드 불필요.",
  "home.cta.btn": "Working Mate 무료 다운로드",

  "home.foot.copy": "© 2026 Working Mate · 로컬 우선 AI 작업공간",
  "home.foot.privacy": "개인정보",
  "home.foot.terms": "약관",
  "home.foot.refunds": "환불",

  "feat.nav.features": "기능",
  "feat.nav.workflow": "워크플로",
  "feat.nav.models": "모델",
  "feat.nav.pricing": "가격",
  "feat.nav.download": "무료 다운로드",
  "feat.foot.copy": "© 2026 Working Mate · 로컬 우선 AI 작업공간",
  "feat.foot.features": "기능",
  "feat.foot.privacy": "개인정보",
  "feat.foot.terms": "약관",
  "feat.foot.refunds": "환불",
  "feat.tpl.back": "전체 기능으로 돌아가기",
  "feat.tpl.what": "할 수 있는 일",
  "feat.tpl.how": "사용 방법",
  "feat.tpl.tech": "기술 하이라이트",
  "feat.tpl.shot": "잠깐 보기",
  "feat.tpl.related": "관련 기능",
  "feat.tpl.end": "한 번 써보기",
  "feat.tpl.endP": "무료판은 영구, 로컬 기능은 바로 쓰고 신용카드 불필요.",
  "feat.tpl.endBtn": "Working Mate 무료 다운로드",
  "feat.tpl.view": "자세히 보기 →",
  "feat.tpl.heroCta1": "무료 다운로드 체험",
  "feat.tpl.heroCta2": "다른 기능 보기",

  "feat.models.title": "멀티모델 하이브리드 라우팅",
  "feat.models.tag": "Multi-Model Router",
  "feat.models.sub": "로컬 Ollama와 클라우드 플래그십이 한 입력창에. 오프라인이면 로컬, 온라인이면 클라우드로 자동 전환. 재시작·설정 없이 대화 중 모델 교체.",
  "feat.models.fact0": "60+ 모델",
  "feat.models.fact1": "로컬 / 클라우드 통합",
  "feat.models.fact2": "자동 폴백",
  "feat.models.fact3": "데이터 유출 0(로컬)",
  "feat.models.grid": "60+ 모델 · 로컬 / 클라우드 통합 입구",
  "feat.models.what0t": "하나의 입력, 모든 모델",
  "feat.models.what0d": "API 지정도 탭 낭비도 없음. DeepSeek, Qwen, GLM, Kimi, Doubao, GPT, Claude, Gemini, OpenRouter가 한 드롭다운에.",
  "feat.models.what1t": "로컬 우선, 오프라인 가능",
  "feat.models.what1d": "Ollama 연결 시 완전 오프라인. 대화·파일 작업·워크플로가 네트워크 불필요, 데이터는 외부로 나가지 않음.",
  "feat.models.what2t": "3단계 모델 전략",
  "feat.models.what2d": "스탠다드/프로/플래그십 원클릭 전환. 시스템이 작업별 최고 가성비를 자동 선택하거나 수동 지정.",
  "feat.models.what3t": "멀티모델 자동 강등",
  "feat.models.what3d": "제한이나 5xx면 다음 후보로 자동. 잔액 부족이나 인증 실패만 정지하고 명확히 알림. 조용한 실패 없음.",
  "feat.models.what4t": "전문가가 모델 그룹 보유",
  "feat.models.what4d": "17명 전문가가 각각 추론/범용/코드 모델 그룹을 묶어 코더는 코드, 라이터는 글 모델 사용.",
  "feat.models.what5t": "동일 세션에서 즉시 교체",
  "feat.models.what5d": "도중에 모델 바꿔도 문맥 유지. 진짜 '그 자리에서 머리 교체'.",
  "feat.models.step0": "설정 → 모델 및 실행 환경에서 등급 선택(스탠다드/프로/플래그십).",
  "feat.models.step1": "오프라인은 로컬 Ollama 켜기. 클라이언트가 자동 발견.",
  "feat.models.step2": "상단 드롭다운에서 모델 선택 또는 '자동 라우팅'에 맡기기.",
  "feat.models.step3": "오프라인은 로컬, 온라인은 클라우드로 자동 복귀. 수동 불필요.",
  "feat.models.tech0": "통합 cloud_client 추상화. 로컬/클라우드 동일 호출 시그니처.",
  "feat.models.tech1": "429는 '제한'과 '잔액 부족' 구분. 제한은 Retry-After로 한 번 재시도, 잔액 부족은 즉시 정지 후 충전 유도.",
  "feat.models.tech2": "폴백 체인은 제한/5xx만 전환. 인증 오류는 전환하지 않음(헛된 과금 방지).",
  "feat.models.tech3": "모델은 '등급 × 용도'로 색인. 전문가가 모델 그룹 직접 참조.",
  "feat.models.shot": "하나의 입력, 로컬과 클라우드 연결",

  "feat.experts.title": "17명 분야 전문가 협업",
  "feat.experts.tag": "Expert Team",
  "feat.experts.sub": "목표를 주면 AdminAgent가 하위 작업을 나누고 알맞은 전문가에 배정해 하나의 결과로 합칩니다. 프롬프트도 직접 나눌 필요도 없음.",
  "feat.experts.fact0": "17명 전문가",
  "feat.experts.fact1": "자동 분해 / 배정",
  "feat.experts.fact2": "하위 작업당 ≤10회 호출",
  "feat.experts.fact3": "자동 병합 결과",
  "feat.experts.grid": "17명 전문가 · 자동 분해 / 배정",
  "feat.experts.what0t": "한 문장으로 지시",
  "feat.experts.what0d": "'이 엑셀의 3개월 판매를 추세 그래프로 만들고 분석 써줘'라 하면 읽기→정리→도표→분석으로 나눠 배정.",
  "feat.experts.what1t": "17명 전문가",
  "feat.experts.what1d": "연구·영상 쇼츠·이미지 디자인·음악·트레이딩·계리·1인 기업·소프트 아키텍처·AI·프롬프트·풀스택 Codex·오피스·코드·글쓰기·데이터 사이언스·운영·범용.",
  "feat.experts.what2t": "AdminAgent가 분해",
  "feat.experts.what2d": "주제 제어 에이전트가 목표를 읽고 → 하위 작업 목록(의존성 포함) 생성 → 각 전문가에 디스패치.",
  "feat.experts.what3t": "전문가가 모델 그룹 보유",
  "feat.experts.what3d": "각 전문가가 추론/범용/코드 모델 그룹과 이미지/영상/음악 생성 모델을 묶음.",
  "feat.experts.what4t": "도구 호출에 경계",
  "feat.experts.what4d": "하위 작업당 최대 10회. 허용/거부 목록으로 무한 실행이나 위험 호출 방지.",
  "feat.experts.what5t": "하나의 결과로 병합",
  "feat.experts.what5d": "모든 하위 작업 완료 후 자동으로 쓸 수 있는 하나의 출력으로 병합. 조각 아님.",
  "feat.experts.step0": "상단 '에이전트 모드' 켜기.",
  "feat.experts.step1": "목표 구체적으로 기술. 직접 나눌 필요 없음.",
  "feat.experts.step2": "에이전트가 먼저 하위 작업 목록 제시. 확인 후 시작.",
  "feat.experts.step3": "실행 중 언제든 긴급 정지, 각 하위 작업 상태와 산출물 확인 가능.",
  "feat.experts.tech0": "분해와 실행이 동일 멀티모델 강등 체인 공유. 제한으로 전체 붕괴 안 됨.",
  "feat.experts.tech1": "실패한 하위 작업은 의존 하류만 건너뜀. 다른 분기는 계속.",
  "feat.experts.tech2": "공간 간 호출에 상한(루프 방지)으로 전문가 상호 파견 방지.",
  "feat.experts.tech3": "분해 결과 파싱 실패는 진짜 이유 던지며 조용히 빈 값 안 돌림.",
  "feat.experts.shot": "목표 → 하위 작업 → 전문가 실행",

  "feat.memory.title": "4계층 기억 시스템",
  "feat.memory.tag": "Memory",
  "feat.memory.sub": "매번 처음부터 시작하지 않음. 핵심 사실·지난 세션·검증된 흐름·선호와 말투가 4계층 기억에 가라앉음. 쓸수록 당신을 이해.",
  "feat.memory.fact0": "4계층 기억",
  "feat.memory.fact1": "중국어 n-gram 검색",
  "feat.memory.fact2": "로컬 SQLite",
  "feat.memory.fact3": "용량 상한 필터",
  "feat.memory.grid": "4계층 기억 · 중국어 n-gram 검색",
  "feat.memory.what0t": "L1 상주 기억",
  "feat.memory.what0d": "가장 중요한 사실과 선호를 매 턴 주입. 용량 한도로 가치 있는 몇 개만 유지 강제.",
  "feat.memory.what1t": "L2 세션 보관",
  "feat.memory.what1d": "전체 기록을 로컬 저장, 키워드 적중 수로 관련 몇 개 검색해 필요 시에만 주입.",
  "feat.memory.what2t": "L3 스킬 라이브러리",
  "feat.memory.what2d": "검증된 흐름이 자동으로 재사용 스킬로. 두 번째는 한 문장이면 재현.",
  "feat.memory.what3t": "L4 사용자 프로필",
  "feat.memory.what3d": "말투·도메인 지식·습관이 누적되어 당신답게.",
  "feat.memory.what4t": "주제 바꿔도 끊기지 않음",
  "feat.memory.what4d": "지난주 요청을 이번 주에 이어감. 다른 주제 왕복해도 문맥 기억.",
  "feat.memory.what5t": "기억은 확인·삭제 가능",
  "feat.memory.what5d": "사이드바 '기억 파일'은 항상 열람. 틀리면 지우거나 정정 가능.",
  "feat.memory.step0": "그냥 대화하면 됨. 수동 '기억해' 불필요.",
  "feat.memory.step1": "사이드바 '기억 파일'에서 현재 L1 상주와 L4 프로필 표시.",
  "feat.memory.step2": "'기억 정리'로 계층 단위 삭제나 세션 삭제.",
  "feat.memory.step3": "딱딱한 규칙을 기억시키려면 대화에서 말하면 장기 사실로 판단.",
  "feat.memory.tech0": "중국어는 2~4자 n-gram과 영단어 토큰화로 전체 문자열 LIKE 저조 해결.",
  "feat.memory.tech1": "L2는 적중 수 채점. SQLite FTS5 없으면 일반 표 + LIKE로 자동 강등.",
  "feat.memory.tech2": "경량 요약은 LLM 안 부르고 첫/끝 턴 연결로 비용 통제.",
  "feat.memory.tech3": "각 계층에 문자 한도 있어 오래된 내용으로 넘치지 않게 보호.",
  "feat.memory.shot": "기억 파일은 언제든 확인·삭제 가능",

  "feat.skills.title": "스킬 자동 정착",
  "feat.skills.tag": "Self-Evolving Skills",
  "feat.skills.sub": "실행한 흐름이 자동으로 재사용 가능한 스킬로 스킬 라이브러리에 추출됩니다. 다음엔 한 문장이면 전체 재현.",
  "feat.skills.fact0": "흐름 자동 추출",
  "feat.skills.fact1": "중앙 스킬 라이브러리",
  "feat.skills.fact2": "로컬 저장",
  "feat.skills.fact3": "재사용·공유 가능",
  "feat.skills.grid": "흐름 자동 추출 · 중앙 스킬 라이브러리",
  "feat.skills.what0t": "한 번 실행이 스킬로",
  "feat.skills.what0d": "완료된 흐름(읽기→처리→출력)이 성공하면 구조화된 재사용 스킬로 자동 추출.",
  "feat.skills.what1t": "다음엔 한 문장",
  "feat.skills.what1d": "'지난번처럼 해줘'라 하면 라이브러리에서 매칭해 실행. 단계 재기술 불필요.",
  "feat.skills.what2t": "스킬 라이브러리 시각화",
  "feat.skills.what2d": "사이드바 '스킬 라이브러리'에서 탐색·검색·활성화·삭제.",
  "feat.skills.what3t": "4계층 기억과 연결",
  "feat.skills.what3d": "스킬은 L3 소속, 워크플로·전문가와 동일 기억 공유.",
  "feat.skills.what4t": "실패는 오염 안 함",
  "feat.skills.what4d": "진짜 성공한 흐름만 정착. 중도 실패는 스킬로 기록 안 됨.",
  "feat.skills.what5t": "로컬 저장",
  "feat.skills.what5d": "스킬 라이브러리는 내 PC에, 클라우드로 안 올라감.",
  "feat.skills.step0": "평소처럼 에이전트에 다단계 작업 완료시키기.",
  "feat.skills.step1": "성공 시 시스템이 자동 추출해 저장.",
  "feat.skills.step2": "사이드바 '스킬 라이브러리'에서 신규 스킬 확인(이름 변경·삭제 가능).",
  "feat.skills.step3": "다음엔 스킬 직접 참조하거나 에이전트가 자동 매칭.",
  "feat.skills.tech0": "스킬 추출은 워크플로 엔진과 동일 노드/단계 모델 공유.",
  "feat.skills.tech1": "스킬은 로컬 파일로 저장해 백업·이전 쉬움.",
  "feat.skills.tech2": "L1/L2 기억과 분리해 스킬 텍스트가 상주 예산 점유 못하게.",
  "feat.skills.shot": "스킬 라이브러리: 성공 시 정착",

  "feat.workflow.title": "노드 방식 워크플로 캔버스",
  "feat.workflow.tag": "Workflow Canvas",
  "feat.workflow.sub": "블록처럼 AI를 연결해 흐름을 만듦. 드래그·연결·실행. 각 단계를 개별 미리보기·재실행·프롬프트 편집. 프롬프트는 직접 써도 AI가 써주도 됨.",
  "feat.workflow.fact0": "10종 노드",
  "feat.workflow.fact1": "드래그 + 자동 연결 + 자동 배치",
  "feat.workflow.fact2": "단일 노드 재실행",
  "feat.workflow.fact3": "프롬프트 직접 / AI 작성",
  "feat.workflow.grid": "10종 노드 · 드래그 + 자동 연결 + 자동 배치",
  "feat.workflow.what0t": "10 노드로 전 과정",
  "feat.workflow.what0d": "LLM 텍스트·콘티·AI 이미지·AI 영상·AI 음악·영상 합성·도구 노드·텍스트 카드·로컬 이미지·로컬 음악.",
  "feat.workflow.what1t": "드래그 + 연결",
  "feat.workflow.what1d": "왼쪽 라이브러리에서 캔버스로 드래그, 노드 우측을 타깃으로 끌어 연결. 또는 '⚡ 자동 연결'로 형별 일괄.",
  "feat.workflow.what2t": "자동 배치",
  "feat.workflow.what2d": "'⌗ 자동 배치'가 의존성별 계층 배치. 흩어진 노드 한 번에 정렬.",
  "feat.workflow.what3t": "매 단계 즉시 미리보기",
  "feat.workflow.what3d": "노드 클릭 시 우측 패널에 텍스트/이미지/영상/오디오 산출물을 플레이어와 함께 표시.",
  "feat.workflow.what4t": "프롬프트 완전 DIY",
  "feat.workflow.what4d": "각 텍스트 매개변수는 여러 줄 편집기. {{노드명}}으로 상류 산출물 참조.",
  "feat.workflow.what5t": "🪄 AI가 프롬프트 작성",
  "feat.workflow.what5d": "한 줄 의도로 AI가 노드형별 전문 프롬프트 생성(콘티 작가/아트 디렉터/음악 프로듀서 전용 템플릿). 이후에도 수정 가능.",
  "feat.workflow.what6t": "템플릿 즉시 실행",
  "feat.workflow.what6d": "내장 AI 쇼츠/음악 싱글/콘셉트 아트는 테마 바꿔 실행.",
  "feat.workflow.what7t": "신뢰성 분석",
  "feat.workflow.what7d": "'🛡 신뢰성'이 누락 매개변수·누락 키·끊김·순환을 점검하고 점수와 수정 제안.",
  "feat.workflow.step0": "사이드바 '워크플로' 열고 왼쪽에서 노드 드래그(또는 '템플릿 불러오기').",
  "feat.workflow.step1": "연결: 노드 우측을 타깃으로. 귀찮으면 '⚡ 자동 연결'.",
  "feat.workflow.step2": "노드 클릭해 이 작업의 프롬프트 설정(직접 쓰기 또는 🪄 AI).",
  "feat.workflow.step3": "'▶ 워크플로 실행'으로 전체 실행. 실패 노드는 다른 분기 막지 않음.",
  "feat.workflow.step4": "캔버스를 JSON 저장. 'JSON 저장/열기'로 재사용·공유.",
  "feat.workflow.tech0": "노드는 플랫 dict + deps. 엔진이 위상 정렬로 직렬 실행, 실패 분기는 하류 자동 건너뜀.",
  "feat.workflow.tech1": "플레이스홀더는 상류 산출물 참조, 리스트 N번째 항(예: 콘티 1컷) 가져오기 지원.",
  "feat.workflow.tech2": "매개변수는 형별 정규화(초→int, 반주→bool)로 클라우드 형 오류 방지.",
  "feat.workflow.tech3": "LLM 노드 반환값에 오류 플래그 탐지로 오류 텍스트가 대본으로 하류 유입 방지.",
  "feat.workflow.shot": "노드 캔버스: 드래그·연결·노드별 미리보기",

  "feat.media.title": "AI 미디어 팩토리",
  "feat.media.tag": "AI Media Studio",
  "feat.media.sub": "하나의 주제에서 완성 클립까지: 대본→콘티→AI 영상 샷→배경음악→자막→합성, 모두 클라이언트 내장. 사이트 왕래 불필요.",
  "feat.media.fact0": "대본 / 콘티 / 영상 / 음악",
  "feat.media.fact1": "자막 + GIF",
  "feat.media.fact2": "세로 9:16",
  "feat.media.fact3": "자동 보관",
  "feat.media.grid": "대본 / 콘티 / 영상 / 음악 · 자막 + GIF",
  "feat.media.what0t": "대본 생성",
  "feat.media.what0d": "주제를 주면 60초 3컷 마이크로 드라마 대본과 각 컷 이미지 프롬프트 자동 분할.",
  "feat.media.what1t": "콘티 분해",
  "feat.media.what1d": "대본의 컷 설명을 구조 목록으로 자동 추출해 영상 노드에 순차 투입.",
  "feat.media.what2t": "AI 영상 샷",
  "feat.media.what2d": "텍스트→영상으로 각 컷 생성. 세로 9:16, 길이 조절, 단컷 재실행 가능.",
  "feat.media.what3t": "배경음악",
  "feat.media.what3d": "대본 분위기로 반주 주제곡 생성, 또는 AI가 가사 있는 곡 작성.",
  "feat.media.what4t": "AI 이미지",
  "feat.media.what4d": "영화적 콘셉트 아트·표지·콘티 참고도, 비율 선택 가능.",
  "feat.media.what5t": "자막 & GIF",
  "feat.media.what5d": "자막 파일 자동 생성, 또는 클립을 GIF로 내보내기.",
  "feat.media.what6t": "영상 합성",
  "feat.media.what6d": "여러 컷을 순서대로 하나의 클립로 합성 출력.",
  "feat.media.what7t": "로컬 자료 삽입 가능",
  "feat.media.what7d": "내 이미지와 음악을 워크플로에 참고/음악으로 넣어 AI 산출물과 혼합.",
  "feat.media.step0": "워크플로 → '🎬 AI 쇼츠(3컷 + 음악)' 템플릿 불러오기.",
  "feat.media.step1": "테마를 이 작업으로 변경(예 '일하는 용의 일상').",
  "feat.media.step2": "대본 노드 클릭, 직접 쓰기 또는 🪄 AI. 확인 후 실행.",
  "feat.media.step3": "노드별 미리보기: 먼저 대본과 콘티, 다음 생성 샷 영상과 음악.",
  "feat.media.step4": "합성 노드가 클립 출력. 산출물은 작업 보관 폴더에 자동 배치.",
  "feat.media.tech0": "영상/음악/이미지는 Kling·Suno·이미지 모델에 통합 도구 레지스트리 경유.",
  "feat.media.tech1": "미디어 노드는 건당 과금. UI에 비용 명시(무료판은 로컬로 연습 가능).",
  "feat.media.tech2": "컷 수·비율·길이 편집 가능. 컷 프롬프트는 상류 하드 오버라이드 지원.",
  "feat.media.tech3": "산출물 경로를 노드에 자동 채움. 다음 재실행은 직접 재사용.",
  "feat.media.shot": "대본 → 콘티 → 샷 → 음악",

  "feat.modules.title": "6대 산업 시나리오 모듈",
  "feat.modules.tag": "Scenarios",
  "feat.modules.sub": "연구·영상·이미지·금융·소프트·성장 — 바로 쓰는 6개 시나리오 입구. 각각 전문가·도구·퀵 카드 사전 설정. 클릭하면 시작.",
  "feat.modules.fact0": "6 시나리오",
  "feat.modules.fact1": "사전 퀵 카드",
  "feat.modules.fact2": "다국어",
  "feat.modules.fact3": "로컬 / 클라우드",
  "feat.modules.grid": "6 시나리오 · 사전 퀵 시작 카드",
  "feat.modules.what0t": "연구",
  "feat.modules.what0d": "논문 검색·자료 정리·구조화 요약과 비교. 리뷰와 제안에 적합.",
  "feat.modules.what1t": "영상 & 이미지 제작",
  "feat.modules.what1d": "쇼츠 대본에서 클립, 콘셉트&표지 디자인. 제작 전문가 연결.",
  "feat.modules.what2t": "금융 & 투자",
  "feat.modules.what2d": "시세 데이터·기업 정보·롱/숏 근거와 리스크. 트레이더/계리사 연결.",
  "feat.modules.what3t": "소프트 & 코드",
  "feat.modules.what3d": "요구 분해·코드 생성·디버깅·간편 스크립트 실행. 아키텍트/풀스택 Codex 연결.",
  "feat.modules.what4t": "성장 & 마케팅",
  "feat.modules.what4d": "주제·카피·캠페인 기획·성장 실험 설계.",
  "feat.modules.what5t": "각 모듈에 퀵 카드",
  "feat.modules.what5d": "프롬프트를 처음부터 안 써도, 카드 누르면 기성 작업 템플릿 사용.",
  "feat.modules.step0": "사이드바 'NAVIGATION'에서 시나리오 선택(연구/영상/이미지/금융/소프트/성장).",
  "feat.modules.step1": "시나리오 내 퀵 카드 클릭 또는 필요 기술.",
  "feat.modules.step2": "교차 시나리오면 프로젝트 공간이 여러 시나리오 산출물을 하나로 모음.",
  "feat.modules.tech0": "시나리오 카드는 '작업 템플릿 + 전문가 + 도구' 조합, 모두 로컬 정의로 편집 가능.",
  "feat.modules.tech1": "시나리오는 동일 도구 레지스트리와 기억 공유. 산출물 상호 운용.",
  "feat.modules.tech2": "UI는 10개 언어 지원. 시나리오 카드 문구가 전환 따름.",
  "feat.modules.shot": "시나리오 카드: 클릭하면 작업 시작",

  "feat.spaces.title": "프로젝트 공간 & 작업 센터",
  "feat.spaces.tag": "Projects & Tasks",
  "feat.spaces.sub": "하나의 목표에 하나의 공간. 여러 작업을 병렬로 섞이지 않게. 모든 산출물·로그·문맥을 공간에 보관, 언제든 재개.",
  "feat.spaces.fact0": "병렬 작업",
  "feat.spaces.fact1": "공간 단위 문맥 격리",
  "feat.spaces.fact2": "자동 보관",
  "feat.spaces.fact3": "칸반 진행",
  "feat.spaces.grid": "병렬 작업 · 공간 단위 문맥 격리",
  "feat.spaces.what0t": "프로젝트 공간",
  "feat.spaces.what0d": "프로젝트마다 공간 열기. 목표·첨부·산출물·대화 기록은 별도 저장되어 오염 안 됨.",
  "feat.spaces.what1t": "병렬 작업",
  "feat.spaces.what1d": "한 공간에서 여러 하위 작업을 각각 진행.",
  "feat.spaces.what2t": "작업 센터 칸반",
  "feat.spaces.what2d": "모든 작업을 한 보드에. 상태·시간·산출물·실패 이유 한눈에.",
  "feat.spaces.what3t": "문맥 버스",
  "feat.spaces.what3d": "공간 간에 한도 내 산출물 상호 참조. 호출 상한으로 순환 의존 방지.",
  "feat.spaces.what4t": "산출물 보관",
  "feat.spaces.what4d": "생성 파일·이미지·영상·표가 공간 폴더에 자동 배치. 찾지 않아도 됨.",
  "feat.spaces.what5t": "언제든 재개",
  "feat.spaces.what5d": "클라이언트 닫았다 열어도 공간과 진행은 남음.",
  "feat.spaces.step0": "사이드바 '프로젝트 공간' → 새 공간. 목표 기술하고 참고 파일 첨부.",
  "feat.spaces.step1": "목표를 에이전트에. 병렬 하위 작업으로 분해.",
  "feat.spaces.step2": "'작업 센터'에서 전체 진행과 각 작업 산출물 표시.",
  "feat.spaces.step3": "완료 후 공간 폴더에서 전체 산출물 가져감. 이어가려면 같은 공간에서.",
  "feat.spaces.tech0": "공간 간은 문맥 버스로 산출물 참조 전달. 교차 공간 호출에 상한으로 루프 방지.",
  "feat.spaces.tech1": "작업 상태와 산출물 경로 영속화. 재시작해도 소실 안 됨.",
  "feat.spaces.tech2": "각 공간 실행 로그 별도 보관으로 단계 추적 쉬움.",
  "feat.spaces.shot": "프로젝트 공간: 목표·작업·산출물 한곳에",

  "feat.task_center.title": "작업 센터",
  "feat.task_center.tag": "Task Center",
  "feat.task_center.sub": "모든 작업을 한 칸반에. 누가 실행 중, 어느 단계, 얼마나 걸렸고, 무엇을 산출했는지, 왜 실패했는지 — 한눈에.",
  "feat.task_center.fact0": "중앙 보드",
  "feat.task_center.fact1": "상태 실시간",
  "feat.task_center.fact2": "실패 추적 가능",
  "feat.task_center.fact3": "원클릭 열기",
  "feat.task_center.grid": "중앙 보드 · 상태 실시간 갱신",
  "feat.task_center.what0t": "한 화면에 전부",
  "feat.task_center.what0d": "대화 시작·에이전트 분해·정기 실행 가리지 않고 모두 한 목록으로.",
  "feat.task_center.what1t": "실시간 상태",
  "feat.task_center.what1d": "대기/실행/완료/실패/건너뜀. 상태 변화 즉시 갱신.",
  "feat.task_center.what2t": "실패를 알 수 있음",
  "feat.task_center.what2d": "실패는 단순 '오류'가 아니라 구체적 단계와 이유(누락 키·제한·파일 없음…) 제시.",
  "feat.task_center.what3t": "산출물 직접",
  "feat.task_center.what3d": "작업 열면 산출 파일·이미지·영상·표 열림.",
  "feat.task_center.what4t": "워크플로와 페어링",
  "feat.task_center.what4d": "워크플로 각 노드 결과도 작업 로그에 남아 단계 추적 쉬움.",
  "feat.task_center.step0": "사이드바 '작업 센터'에서 전체 작업 표시.",
  "feat.task_center.step1": "작업 클릭해 상세: 단계·시간·산출물·로그.",
  "feat.task_center.step2": "실패 작업은 원인 짚고 해당 단계 재실행.",
  "feat.task_center.tech0": "작업/단계 2계층 구조. 단계급으로 도구명·매개변수·시간·결과 기록.",
  "feat.task_center.tech1": "실행과 UI 스레드 분리. 긴 작업도 UI 안 멈춤, 스레드 비정상 종료 시 버튼 상태 자동 복귀.",
  "feat.task_center.shot": "작업 센터: 상태·시간·산출물",

  "feat.automation.title": "자동화 & 예약 작업",
  "feat.automation.tag": "Automation",
  "feat.automation.sub": "AI에 당신의 리듬으로 일시키기. 매일 아침 뉴스 정리, 매주 데이터 집계, 시간 맞춰 알림 — 보고 있지 않아도 돌아감.",
  "feat.automation.fact0": "예약 / 주기 실행",
  "feat.automation.fact1": "로컬 스케줄러",
  "feat.automation.fact2": "이력 기록",
  "feat.automation.fact3": "실패 표시",
  "feat.automation.grid": "예약 / 주기 실행 · 로컬 스케줄러",
  "feat.automation.what0t": "한 문장으로 생성",
  "feat.automation.what0d": "'매일 오전 9시에 어제 업계 뉴스를 요약해줘'라 하면 자동화 완성.",
  "feat.automation.what1t": "주기와 1회 모두",
  "feat.automation.what1d": "매일·매주·매월, 또는 지정 시각에 한 번.",
  "feat.automation.what2t": "로컬 스케줄",
  "feat.automation.what2d": "스케줄과 데이터는 내 PC에 남아 업로드 안 됨.",
  "feat.automation.what3t": "실행 이력",
  "feat.automation.what3d": "몇 번 실행, 각 결과, 실패 여부 기록.",
  "feat.automation.what4t": "일시정지 & 삭제 가능",
  "feat.automation.what4d": "원하지 않으면 언제든 일시정지 또는 삭제.",
  "feat.automation.step0": "사이드바 '자동화' → 새로 만들기. 할 일 기술.",
  "feat.automation.step1": "시간과 빈도 설정(매일/매주/지정 시각 1회).",
  "feat.automation.step2": "저장 후 목록에서 다음 실행 시각과 이력 표시.",
  "feat.automation.tech0": "자동화 정의와 실행 상태 별도 영속화. 재시작 후에도 스케줄 유지.",
  "feat.automation.tech1": "각 실행을 독립 기록해 내용인지 환경인지 판별 쉽게.",
  "feat.automation.shot": "당신의 리듬으로 자동으로 일하기",

  "feat.gui.title": "GUI 자동화",
  "feat.gui.tag": "Computer Control",
  "feat.gui.sub": "AI가 내 PC의 다른 프로그램을 조작. 버튼 클릭, 양식 채우기, 메뉴 열기 — API 없는 옛 소프트도 자동화.",
  "feat.gui.fact0": "마우스 & 키보드 시뮬",
  "feat.gui.fact1": "시작 전 능력 감지",
  "feat.gui.fact2": "동작마다 확인",
  "feat.gui.fact3": "언제든 전환",
  "feat.gui.grid": "마우스 & 키보드 시뮬 · 시작 전 능력 감지",
  "feat.gui.what0t": "사람처럼 UI 조작",
  "feat.gui.what0d": "AI가 현재 창을 '보고' 어디 클릭할지, 무엇 입력할지 결정해 단계 진행.",
  "feat.gui.what1t": "시작 전 능력 감지",
  "feat.gui.what1d": "시스템이 먼저 환경 지원 확인. 미지원이면 조용히 실패 않고 이유 알림.",
  "feat.gui.what2t": "행동 전 확인",
  "feat.gui.what2d": "기본으로 중요한 동작마다 묻기. 자동 확인 모드만 프롬프트 건너뜀.",
  "feat.gui.what3t": "위험 동작도 차단",
  "feat.gui.what3d": "삭제/덮어쓰기 등 파괴적 동작은 자동 확인으로도 해제 안 됨.",
  "feat.gui.what4t": "언제든 전환",
  "feat.gui.what4d": "한 번 클릭으로 OFF. AI가 즉시 마우스/키보드 제어 잃음.",
  "feat.gui.step0": "설정 → 'GUI 자동화' 활성화. 먼저 능력 감지 통과.",
  "feat.gui.step1": "수행할 동작 기술(구체할수록 좋음).",
  "feat.gui.step2": "프롬프트 따라 중요한 동작마다 확인.",
  "feat.gui.step3": "끝나면 스위치 OFF.",
  "feat.gui.tech0": "능력 감지는 활성화 시 실행·캐시해 중간에 환경 미지원 방지.",
  "feat.gui.tech1": "조작 세분도 설정 가능. 기본은 동작마다 확인.",
  "feat.gui.tech2": "자동 확인과 연동. 명시적 자동 확인만 프롬프트 건너뜀.",
  "feat.gui.shot": "API 없는 옛 소프트도 자동화",

  "feat.safety.title": "안전 가드레일: 자동 확인 & 긴급 정지",
  "feat.safety.tag": "Safety",
  "feat.safety.sub": "줄 권한은 주고, 막아야 할 것은 막음. 쓰기는 단계마다 확인하거나 자동 확인으로 빠르게 — 하지만 위험 동작은 항상 차단, 삭제는 항상 휴지통으로.",
  "feat.safety.fact0": "레벨: WARNING / BLOCKED",
  "feat.safety.fact1": "자동 확인 모드",
  "feat.safety.fact2": "원클릭 정지",
  "feat.safety.fact3": "삭제 → 휴지통",
  "feat.safety.grid": "레벨: WARNING / BLOCKED · 자동 확인 모드",
  "feat.safety.what0t": "기본은 단계마다 확인",
  "feat.safety.what0d": "쓰기·데이터 변경·명령은 매번 팝업. 당신의 '예'만 실행.",
  "feat.safety.what1t": "자동 확인(속도 모드)",
  "feat.safety.what1d": "신뢰 후 활성화. 일반 쓰기는 프롬프트 멈추고 직진. 검증된 반복 흐름에 적합.",
  "feat.safety.what2t": "위험은 여전히 차단",
  "feat.safety.what2d": "BLOCKED급 파괴적 동작은 자동 확인으로도 해제 안 됨, 항상 당신 승인 필요.",
  "feat.safety.what3t": "삭제 → 휴지통",
  "feat.safety.what3d": "AI 삭제는 기본 휴지통으로. 지워지지 않아 실수해도 복원 가능.",
  "feat.safety.what4t": "원클릭 긴급 정지",
  "feat.safety.what4d": "실행 중 뭔가 이상하면 긴급 정지로 현재 작업 즉시 종료.",
  "feat.safety.what5t": "도구 허용/거부 목록",
  "feat.safety.what5d": "호출 가능 도구를 허용 목록으로 한정. 거부 목록은 어떤 경우도 호출 불가.",
  "feat.safety.step0": "기본은 '동작마다 확인'. 설정 불필요.",
  "feat.safety.step1": "신뢰 충분하면 '자동 확인' 활성화. 활성화 시 한 번 확인.",
  "feat.safety.step2": "상단 바에서 언제든 비활성화해 단계마다 확인으로.",
  "feat.safety.step3": "실행 중 '정지'로 현재 작업 긴급 정지.",
  "feat.safety.tech0": "동작을 위험별 분류. WARNING은 자동 확인 가능, BLOCKED는 항상 차단.",
  "feat.safety.tech1": "도구 호출은 허용+거부 목록 이중 제한. 하위 작업당 ≤10회.",
  "feat.safety.tech2": "삭제는 일률 휴지통 백업 경로로 복원성 확보.",
  "feat.safety.shot": "권한은 주고 막아야 할 것은 막음",

  "feat.files.title": "진짜 파일 작업",
  "feat.files.tag": "Real File Work",
  "feat.files.sub": "그냥 대화만 하는 게 아님. 문서·표를 읽고, 내용 편집하고, 새 파일 생성하고, 스크립트 실행하고, 일괄 처리 — 그리고 파일 건넴.",
  "feat.files.fact0": "Office / 표 읽기쓰기",
  "feat.files.fact1": "스크립트 실행",
  "feat.files.fact2": "일괄 처리",
  "feat.files.fact3": "이미지 드래그 / 붙여넣기",
  "feat.files.grid": "Office / 표 읽기쓰기 · 스크립트 실행",
  "feat.files.what0t": "파일을 이해",
  "feat.files.what0d": "Word·Excel·PPT·PDF·이미지를 넣으면 내용을 읽고 작업.",
  "feat.files.what1t": "편집 후도 같은 형식",
  "feat.files.what1d": "원 형식으로 편집·다른 이름 저장. 직접 복사해 돌릴 텍스트 아님.",
  "feat.files.what2t": "새 파일 생성",
  "feat.files.what2d": "표·보고서·목록·차트를 바로 열리는 파일로 출력.",
  "feat.files.what3t": "스크립트 실행",
  "feat.files.what3d": "일괄로 스크립트 실행. 출력은 대화로 환류.",
  "feat.files.what4t": "드래그 & 붙여넣기",
  "feat.files.what4d": "파일을 입력에 드롭하면 문맥이 됨. 클립보드 이미지는 Ctrl+V로 첨부.",
  "feat.files.what5t": "산출물 보관",
  "feat.files.what5d": "생성 파일은 작업 폴더에. 가져가기 쉬움.",
  "feat.files.step0": "파일을 입력에 드롭(또는 이미지 Ctrl+V 붙여넣기).",
  "feat.files.step1": "'이 표를 월별 집계하고 추세 그래프 그려줘'라 지시.",
  "feat.files.step2": "AI가 완료 시 새 파일 건넴. 열어 사용.",
  "feat.files.tech0": "파일 읽기/쓰기는 통합 도구 계층 경유, 워크플로 노드와 공유.",
  "feat.files.tech1": "큰 파일은 먼저 구조 분석해 전체를 문맥에 집어넣지 않음.",
  "feat.files.tech2": "생성 산출물 경로 채움으로 후일 참조와 재처리 쉽게.",
  "feat.files.shot": "넣고, 편집하고, 파일 돌려받기",

  "feat.i18n.title": "다국어 인터페이스",
  "feat.i18n.tag": "i18n",
  "feat.i18n.sub": "UI는 10개 언어 실시간 전환. 즉시, 재시작 불필요. 해외 사용자나 팀 협업에 편리.",
  "feat.i18n.fact0": "10개 언어",
  "feat.i18n.fact1": "실시간 전환",
  "feat.i18n.fact2": "UI + 시나리오 카드",
  "feat.i18n.fact3": "확장 가능",
  "feat.i18n.grid": "10개 언어 · 실시간 전환",
  "feat.i18n.what0t": "10개 언어",
  "feat.i18n.what0d": "简体中文, English, 日本語, 한국어, Deutsch, Français, Español, Português, Русский, العربية.",
  "feat.i18n.what1t": "전환은 즉시 반영",
  "feat.i18n.what1d": "설정에서 언어 바꾸면 UI 문구 즉시 갱신. 재시작 불필요.",
  "feat.i18n.what2t": "전면 커버리지",
  "feat.i18n.what2d": "메인 UI·설정·워크플로 캔버스·시나리오 카드 문구가 동일 다국어 계층 공유.",
  "feat.i18n.what3t": "번역 확장 가능",
  "feat.i18n.what3d": "언어 자원은 별도 파일. 언어 추가는 하나 더 쓰기만 하면 됨.",
  "feat.i18n.step0": "설정 → UI 언어에서 언어 선택.",
  "feat.i18n.step1": "재시작을 권하면 한 번 재시작해 전체 반영.",
  "feat.i18n.tech0": "모든 UI 문구는 실행 시 번역 함수로 가져와 import 시 중국어 고정 회피.",
  "feat.i18n.tech1": "언어 자원은 별도 파일로 교정과 추가 쉬움.",
  "feat.i18n.shot": "",

  "feat.privacy.title": "로컬 우선 & 개인정보",
  "feat.privacy.tag": "Local First",
  "feat.privacy.sub": "대화·기억·지식베이스·스킬·산출물은 모두 기본값으로 당신 PC. 완전 오프라인으로 돌아가고, 클라우드는 당신이 능동적으로 고른 모델만.",
  "feat.privacy.fact0": "데이터 유출 0(로컬)",
  "feat.privacy.fact1": "오프라인 가능",
  "feat.privacy.fact2": "전부 기기 내",
  "feat.privacy.fact3": "로컬 DB",
  "feat.privacy.grid": "데이터 유출 0(로컬) · 오프라인 가능",
  "feat.privacy.what0t": "데이터는 기기에 머묾",
  "feat.privacy.what0d": "대화 기록·4계층 기억·스킬 라이브러리·프로젝트 산출물은 로컬 파일/DB에 저장.",
  "feat.privacy.what1t": "오프라인 가능",
  "feat.privacy.what1d": "로컬 모델 있으면 대화·파일 작업·워크플로 편성은 네트워크 불필요.",
  "feat.privacy.what2t": "클라우드는 당신 선택",
  "feat.privacy.what2d": "클라우드 모델이나 클라우드 생성을 고를 때만 관련 내용이 제공자로.",
  "feat.privacy.what3t": "원클릭 정리",
  "feat.privacy.what3d": "'기억 정리'로 계층 단위 삭제나 세션 삭제. 진짜로 사라짐.",
  "feat.privacy.what4t": "계정 불필요",
  "feat.privacy.what4d": "무료판은 가입 강제 안 함. 로컬 기능은 바로 씀.",
  "feat.privacy.step0": "완전 오프라인이면 로컬 모델만 사용.",
  "feat.privacy.step1": "기록 지우려면 사이드바 '기억 정리'.",
  "feat.privacy.step2": "어떤 대화가 민감하면 클라우드 모델 고르지 않으면 됨.",
  "feat.privacy.tech0": "로컬 저장은 SQLite와 로컬 디렉터리. 자체 클라우드 불필요.",
  "feat.privacy.tech1": "클라우드 호출은 설정한 제공자 키 경유로 직접 API.",
  "feat.privacy.tech2": "기억 계층은 각각 삭제 가능. '하나 지우면 전부 지워짐' 방지.",
  "feat.privacy.shot": "전부 기기 내, 오프라인으로 돌아감",
  "home.price.free.li0": "신규 가입 시 3,000 크레딧(모든 모델 체험)",
  "home.price.std.li0": "매월 800 크레딧 포함",
  "home.price.pro.li0": "매월 3,000 크레딧 포함",
  "home.price.ult.li0": "매월 10,000 크레딧 포함",
  "home.price.max.li1": "신규 3,000 크레딧 · 월 상한 없이 종량제",
  "feat.membership.grid": "5개 플랜 · 신규 3,000 크레딧 · 매일 출석",
  "feat.channels.grid": "중국 직결 14개 프리셋 · 중국 본토는 국산 모델 우선",
  "feat.membership.sub": "5개 플랜은 모델 풀과 기능 경계가 다릅니다. 무료판은 로컬, 스탠다드는 가성비, 프로는 국산 플래그십, 울트라는 엔지니어링급 CAD, 맥스는 무제한. 신규 가입 시 3,000 크레딧으로 모든 모델을 체험할 수 있고, 유료 등급은 구독/라이선스로 해제됩니다.",
  "feat.membership.fact1": "신규 3,000 크레딧",
  "feat.membership.what4d": "클라우드 호출에 월 상한 없음. 크레딧은 사용한 만큼 차감(언제든 충전, 카드 자동 결제 가능). 전공 Agent(심층 연구·자율 코딩·자가 CAD·숏드라마 스토리보드)는 이 등급 전용입니다. 신규 3,000 크레딧도 여기서 사용할 수 있습니다.",
  "feat.membership.what5t": "등급은 구독으로 해제",
  "feat.membership.what5d": "설정의 등급 드롭다운은 각 플랜 상태를 보여줍니다. 미구독 등급은 🔒가 붙고 선택할 수 없어 실수로 바뀌지 않습니다. 구독이나 라이선스 키가 들어오면 즉시 해제되고 모델 풀, 기능 게이트(CAD·전공 Agent), 모델 수가 함께 갱신됩니다. 재설치나 재로그인이 필요 없습니다.",
  "feat.membership.what6t": "크레딧이 보인다",
  "feat.membership.what6d": "잔액은 상태 표시줄에 상주하며 호출이 끝나는 즉시 해당 모델의 공개 요율로 차감됩니다(요율은 모델명 옆에 표시). 매일 출석 시 100 크레딧(신규 15회). 잔액이 바닥나면 앱이 자동으로 무료판으로 돌아가고 충전을 안내합니다 — 조용한 강등도, 숨은 과금도 없습니다.",
  "home.price.max.li2": "매일 출석 시 100 크레딧",
  "home.shots.tag": "실제 화면",
  "home.shots.h2": "렌더링이 아니라 진짜 화면입니다",
  "home.shots.p": "아래 이미지는 모두 앱 안에서 그대로 캡처한 실사입니다. 보정도, 임시 이미지도 없습니다. 기능도 UI도 진짜입니다.",
  "home.shots.s1t": "메인 화면 · 멀티 모델 라우팅 대화",
  "home.shots.s1d": "한 문장만 넣으면 가장 알맞은 전문가와 모델을 자동으로 고릅니다. 왼쪽은 대화 기록과 기능 내비게이션, 오른쪽 아래는 실시간 크레딧 잔액.",
  "home.shots.s2t": "워크플로 캔버스 · 드래그로 파이프라인 구성",
  "home.shots.s2d": "대본 → 스토리보드 → 영상 → 음악. 한 번 연결하면 한 번에 실행되고, 각 노드는 따로 미리 볼 수 있습니다.",
  "home.shots.s3t": "프로젝트 스페이스 · AI PM이 업무 배분",
  "home.shots.s3d": "목표를 정하면 자동으로 작업을 쪼개 전문가에게 배정하고, 산출물과 진행 상황은 스페이스에 남습니다.",
  "home.shots.s4t": "엔지니어링 모드 · 도면 / 모델링 / 시뮬레이션",
  "home.shots.s4d": "엔지니어링 도면, 수학 모델링, 물리 시뮬레이션 3개 탭. 스크립트나 이미지로 내보낼 수 있습니다.",
  "home.shots.s5t": "예약 작업 · 자동화 템플릿",
  "home.shots.s5d": "일일 요약, 주간 보고서, 면접 준비 알림 등 템플릿을 바로 쓸 수 있고 예약은 전부 로컬에서 돌아갑니다.",
  "home.shots.s6t": "작업 센터 · 세션 간 진행 보드",
  "home.shots.s6d": "카드를 더블클릭하면 해당 세션으로 돌아갑니다. AI는 세션을 넘나들며 각 작업의 진행 상황을 파악합니다.",
  "home.shots.s7t": "산업 시나리오 · 여행 예산 분석",
  "home.shots.s7d": "기름값, 숙박, 입장료를 항목별로 계산하고 가격표와 근거를 함께 제시합니다.",
  "home.wf.shotcap": "실제 캔버스: 노드를 끌고, 오른쪽에서 파라미터를 고치고, 노드별로 미리보기",
  "home.nav.shots": "실제 화면",
};
