/* Working Mate — Español */
window.I18N = window.I18N || {};
window.I18N.es = {
  /* ───────── 首页 HOME ───────── */
  "home.nav.capability": "Capacidades",
  "home.nav.features": "Todas las funciones",
  "home.nav.workflow": "Flujo de trabajo",
  "home.nav.models": "Modelos",
  "home.nav.pricing": "Precios",
  "home.nav.console": "Consola",
  "home.nav.login": "Iniciar sesión",

  "home.hero1.eyebrow": "v1.4 lanzado · Agente de IA multi-modelo local-first",
  "home.hero1.h1": "Haz que la IA <span class=\"glow\">trabaje de verdad</span><br>en vez de solo charlar",
  "home.hero1.sub": "Ollama local y LLM en la nube bajo un mismo planificador; los flujos por nodos encadenan guiones, storyboards, vídeo y música en una sola tubería. La memoria de cuatro capas aprende de ti con el tiempo, tus datos permanecen en el dispositivo y funciona sin conexión.",
  "home.hero1.stat1": "Modelos soportados",
  "home.hero1.stat2": "Datos compartidos",
  "home.hero1.stat3": "Memoria autoevolutiva",
  "home.hero1.cta1": "Descarga gratis · Nivel gratuito",
  "home.hero1.cta2": "Ver demo del flujo",

  "home.hero2.eyebrow": "Flujo de trabajo · Lienzo de nodos",
  "home.hero2.h1": "Arrastra y suelta<br>para construir una <span class=\"glow\">IA en tubería</span>",
  "home.hero2.sub": "Guión → storyboard → planos de vídeo → música de fondo, todo en una ejecución. Previsualiza cada paso, reejecuta un nodo solo e inserta tarjetas o assets locales personalizados.",
  "home.hero2.stat1": "Expertos de dominio",
  "home.hero2.stat2": "Plantillas listas",
  "home.hero2.stat3": "Arrastra y usa",
  "home.hero2.cta1": "Abrir flujo",
  "home.hero2.cta2": "Ver demo de 60s",

  "home.hero3.eyebrow": "v1.4 · Oferta limitada de lanzamiento",
  "home.hero3.h1": "Promo de mitad de año<br>úsalo <span class=\"glow\">para siempre</span> por $0",
  "home.hero3.sub": "El nivel gratuito es tuyo para siempre con modelos locales ilimitados. Los niveles de pago desbloquean memoria más larga, modelos estrella y cuota de generación en la nube.",
  "home.hero3.stat1": "Inicio · Gratis",
  "home.hero3.stat2": "Estándar",
  "home.hero3.stat3": "Equipo · Previsto",
  "home.hero3.cta1": "Descargar ahora",
  "home.hero3.cta2": "Ver registro de cambios",

  "home.float.assist": "Asistente IA",
  "home.float.service": "Soporte humano",
  "home.float.sales": "Ventas",

  "home.cap.tag": "Capacidad",
  "home.cap.h2": "Un solo cliente, todo tu espacio de trabajo IA",
  "home.cap.c1t": "Enrutado híbrido local + nube",
  "home.cap.c1d": "Usa Ollama local sin conexión, cambia automáticamente a modelos estrella en la nube cuando estás online. Cambia de modelo a mitad de conversación.",
  "home.cap.c2t": "17 expertos de dominio colaboran",
  "home.cap.c2d": "Dale un objetivo y AdminAgent divide las subtareas, asigna el experto adecuado y fusiona los resultados.",
  "home.cap.c3t": "Memoria de cuatro capas",
  "home.cap.c3d": "Hechos residentes, archivo de sesión, biblioteca de habilidades y perfil de usuario.",
  "home.cap.c4t": "Las habilidades se cristalizan solas",
  "home.cap.c4d": "Los flujos que funcionan se extraen automáticamente en habilidades reutilizables.",
  "home.cap.c5t": "Trabajo real con archivos",
  "home.cap.c5d": "Lee/escribe documentos y hojas, ejecuta scripts, controla Windows.",

  "home.feat.tag": "Todas las funciones",
  "home.feat.h2": "Todas las funciones, clic para ver detalles",
  "home.feat.p": "Cada tarjeta abre una página completa: qué hace, cómo usarla y los puntos técnicos.",

  "home.wf.tag": "Flujo de trabajo",
  "home.wf.h2": "Convierte flujos repetitivos en una tubería",
  "home.wf.i1t": "Arrastra y conecta libremente",
  "home.wf.i1d": "Organiza flujos como bloques; cambia un paso sin rehacer el resto.",
  "home.wf.i2t": "Previsualiza cada paso",
  "home.wf.i2d": "Texto, imágenes, vídeo, audio — haz clic en un nodo para verlo.",
  "home.wf.i3t": "Plantillas en un clic",
  "home.wf.i3d": "Shorts de IA / sencillos musicales / arte conceptual — flujos integrados listos.",
  "home.wf.memtag": "Memoria",
  "home.wf.memh2": "No empieza desde cero cada vez",
  "home.wf.mem.i1t": "Sin pérdida de contexto al cambiar de tema",
  "home.wf.mem.i1d": "Retoma esta semana las peticiones de la semana pasada.",
  "home.wf.mem.i2t": "Los flujos se vuelven habilidades",
  "home.wf.mem.i2d": "La misma tarea la segunda vez lleva una sola frase.",

  "home.mem.l1t": "Memoria residente",
  "home.mem.l1d": "Los hechos y preferencias más críticos, inyectados cada turno.",
  "home.mem.l2t": "Archivo de sesión",
  "home.mem.l2d": "Todo el historial, recuperado por número de aciertos de palabras clave.",
  "home.mem.l3t": "Biblioteca de habilidades",
  "home.mem.l3d": "Los flujos probados se cristalizan automáticamente para reutilización.",
  "home.mem.l4t": "Perfil de usuario",
  "home.mem.l4d": "El estilo de comunicación y los conocimientos de dominio se acumulan con el tiempo.",

  "home.models.tag": "Modelos",
  "home.models.h2": "Prácticamente cualquier modelo que quieras",
  "home.models.m1": "Ollama local",
  "home.models.m2": "DeepSeek V4",
  "home.models.m3": "Qwen3.8 Max",
  "home.models.m4": "GLM 5.3",
  "home.models.m5": "Kimi K3",
  "home.models.m6": "Doubao Seed",
  "home.models.m7": "Claude Opus / Sonnet",
  "home.models.m8": "GPT-5.6",
  "home.models.m9": "Gemini",
  "home.models.m10": "Kling",
  "home.models.m11": "Suno music",
  "home.models.m12": "OpenRouter todos",

  "home.price.tag": "Precios",
  "home.price.h2": "Empieza gratis, mejora cuando necesites más",
  "home.price.free.name": "Gratis",
  "home.price.free.li1": "Modelos locales ilimitados",
  "home.price.free.li2": "Chat y ops de archivos básicas",
  "home.price.free.li3": "Incluye anuncios",
  "home.price.free.li4": "Soporte de comunidad",
  "home.price.free.cta": "Descarga gratis",
  "home.price.std.flag": "Más popular",
  "home.price.std.name": "Estándar",
  "home.price.std.li1": "Contexto y memoria más largos",
  "home.price.std.li2": "Modelos en la nube económicos",
  "home.price.std.li3": "Sin anuncios",
  "home.price.std.li4": "Funciones de flujo completas",
  "home.price.std.cta": "Pasar a Estándar",
  "home.price.pro.name": "Pro",
  "home.price.pro.li1": "Todos los modelos estrella",
  "home.price.pro.li2": "Generación de vídeo / música IA",
  "home.price.pro.li3": "Colaboración multi-experto",
  "home.price.pro.li4": "Soporte prioritario",
  "home.price.pro.cta": "Pasar a Pro",
  "home.price.ult.flag": "Próximamente",
  "home.price.ult.name": "Ultimate",
  "home.price.ult.li1": "Contexto enorme",
  "home.price.ult.li2": "Modelos top exclusivos",
  "home.price.ult.li3": "Colab de equipo (previsto)",
  "home.price.ult.li4": "—",
  "home.price.ult.cta": "Próximamente",

  "home.faq.h2": "Preguntas frecuentes",
  "home.faq.q1": "¿Funciona sin conexión?",
  "home.faq.a1": "Sí. Los modelos locales de Ollama funcionan totalmente offline — chat, ops de archivos y orquestación de flujos no necesitan red.",
  "home.faq.q2": "¿Se suben mis datos?",
  "home.faq.a2": "No. El historial de chat, la base de conocimiento y la memoria se quedan en tu máquina.",
  "home.faq.q3": "¿Cuáles son los límites del nivel gratuito?",
  "home.faq.a3": "Lo gratis da todas las capacidades locales y herramientas básicas con un espacio de anuncio; los modelos estrella en la nube y la generación de vídeo/música IA son de pago.",
  "home.faq.q4": "¿Qué sistemas se soportan?",
  "home.faq.a4": "Windows y macOS. Móvil (Android / iOS / HarmonyOS) está previsto.",

  "home.cta.h2": "Deja que la IA empiece a trabajar ya",
  "home.cta.p": "El nivel gratuito es para siempre, se instala en un minuto, sin tarjeta de crédito.",
  "home.cta.btn": "Descarga Working Mate gratis",

  "home.foot.copy": "© 2026 Working Mate · Espacio de trabajo IA local-first",
  "home.foot.privacy": "Privacidad",
  "home.foot.terms": "Términos",
  "home.foot.refunds": "Reembolsos",

  /* ───────── 功能页共享 UI (FEAT-UI) ───────── */
  "feat.nav.features": "Funciones",
  "feat.nav.workflow": "Flujo de trabajo",
  "feat.nav.models": "Modelos",
  "feat.nav.pricing": "Precios",
  "feat.nav.download": "Descarga gratis",
  "feat.foot.copy": "© 2026 Working Mate · Espacio de trabajo IA local-first",
  "feat.foot.features": "Funciones",
  "feat.foot.privacy": "Privacidad",
  "feat.foot.terms": "Términos",
  "feat.foot.refunds": "Reembolsos",
  "feat.tpl.back": "Volver a todas las funciones",
  "feat.tpl.what": "Qué hace",
  "feat.tpl.how": "Cómo usar",
  "feat.tpl.tech": "Puntos técnicos",
  "feat.tpl.shot": "Echa un vistazo",
  "feat.tpl.related": "Funciones relacionadas",
  "feat.tpl.end": "Pruébalo",
  "feat.tpl.endP": "El nivel gratuito es para siempre; las funciones locales funcionan de fábrica, sin tarjeta de crédito.",
  "feat.tpl.endBtn": "Descarga Working Mate gratis",
  "feat.tpl.view": "Ver detalles →",
  "feat.tpl.heroCta1": "Probar descarga gratis",
  "feat.tpl.heroCta2": "Ver otras funciones",

  /* ───────── 功能数据 (FEAT-DATA) ───────── */
  "feat.models.title": "Enrutado híbrido multi-modelo",
  "feat.models.tag": "Enrutador multi-modelo",
  "feat.models.sub": "Ollama local y modelos estrella en la nube en un solo chat: cambio automático a local sin conexión, automático a nube online; cambia de modelo a mitad de conversación sin reiniciar ni reconfigurar.",
  "feat.models.fact0": "60+ modelos",
  "feat.models.fact1": "Local / nube unificado",
  "feat.models.fact2": "Fallback auto",
  "feat.models.fact3": "0 datos fuera (local)",
  "feat.models.grid": "60+ modelos · entrada unificada local / nube",
  "feat.models.what0t": "Una entrada, todos los modelos",
  "feat.models.what0d": "Sin lío de APIs, sin pestañas dispersas. DeepSeek, Qwen, GLM, Kimi, Doubao, GPT, Claude, Gemini, OpenRouter — todo en un desplegable.",
  "feat.models.what1t": "Local primero, funciona offline",
  "feat.models.what1d": "Conecta Ollama y pasa totalmente offline: chat, ops de archivos y orquestación de flujos no necesitan red, los datos nunca salen de la máquina.",
  "feat.models.what2t": "Estrategia de modelos en tres niveles",
  "feat.models.what2d": "Estándar / Pro / Estrella con un clic; el sistema elige automáticamente el mejor valor por tarea, o eliges manualmente.",
  "feat.models.what3t": "Degradado automático multi-modelo",
  "feat.models.what3d": "Ante límite de tasa o 5xx, salta automáticamente al siguiente candidato; solo se detiene y avisa claramente con saldo insuficiente o fallo de auth — nunca en silencio.",
  "feat.models.what4t": "Los expertos traen grupos de modelos",
  "feat.models.what4d": "Los 17 expertos de dominio enlazan cada uno un grupo de modelos razonamiento / general / código, así los coders usan modelos de código y los redactores modelos de escritura.",
  "feat.models.what5t": "Cambia en vivo en una sesión",
  "feat.models.what5d": "Cambia de modelo a mitad del chat sin perder contexto — de verdad «cambia de cerebro al vuelo».",
  "feat.models.step0": "Ajustes → Modelos y runtime, elige un nivel (Estándar / Pro / Estrella).",
  "feat.models.step1": "Para uso offline, activa Ollama local; el cliente descubre los modelos locales automáticamente.",
  "feat.models.step2": "Elige un modelo en el desplegable superior, o simplemente usa «Enrutador auto».",
  "feat.models.step3": "Offline cae a local; online restaura la nube — sin intervención manual.",
  "feat.models.tech0": "Abstracción cloud_client unificada; local / nube comparten una firma de llamada.",
  "feat.models.tech1": "429 distingue «límite» vs «saldo insuficiente»: reintenta una vez en límite, detiene y pide recarga en saldo.",
  "feat.models.tech2": "Cadena de fallback multi-modelo: cambia solo en límite / 5xx; nunca en errores de auth (evita reintentos inútiles).",
  "feat.models.tech3": "Modelos indexados por nivel × propósito; los expertos referencian grupos de modelos directamente.",
  "feat.models.shot": "Una entrada, local y nube conectados",

  "feat.experts.title": "17 expertos de dominio colaboran",
  "feat.experts.tag": "Equipo de expertos",
  "feat.experts.sub": "Dale un objetivo, AdminAgent lo divide en subtareas, asigna el experto adecuado y fusiona en un solo resultado. Sin escribir prompts, sin división manual.",
  "feat.experts.fact0": "17 expertos de dominio",
  "feat.experts.fact1": "División / asignación auto",
  "feat.experts.fact2": "≤10 llamadas herramienta / subtarea",
  "feat.experts.fact3": "Resultados auto-fusionados",
  "feat.experts.grid": "17 expertos de dominio · división / asignación auto",
  "feat.experts.what0t": "Descríbelo en una frase",
  "feat.experts.what0d": "Di «pasa las ventas de 3 meses de este Excel a un gráfico de tendencia y escribe un análisis» — divide en leer → limpiar → gráfico → analizar y asigna.",
  "feat.experts.what1t": "17 expertos de dominio",
  "feat.experts.what1d": "Investigación, shorts de vídeo, diseño de imagen, música, trading, actuaría, solo-negocio, arquitectura de software, IA, prompting, Codex full-stack, oficina, código, escritura, ciencia de datos, ops, general.",
  "feat.experts.what2t": "AdminAgent hace la división",
  "feat.experts.what2d": "El agente principal lee tu objetivo → construye una lista de subtareas (con dependencias) → despacha cada una al experto adecuado.",
  "feat.experts.what3t": "Los expertos traen grupos de modelos",
  "feat.experts.what3d": "Cada experto enlaza un grupo de modelos razonamiento / general / código, y enlaza modelos de generación en imagen / vídeo / música.",
  "feat.experts.what4t": "Las llamadas herramienta quedan acotadas",
  "feat.experts.what4d": "Hasta 10 llamadas herramienta por subtarea, con listas permitir/denegar, evitando llamadas descontroladas o peligrosas.",
  "feat.experts.what5t": "Fusionado en una entrega",
  "feat.experts.what5d": "Cuando terminan todas las subtareas, los resultados se fusionan solos en una salida útil, no fragmentos dispersos.",
  "feat.experts.step0": "Activa «Modo Agente» arriba.",
  "feat.experts.step1": "Describe tu objetivo (cuanto más concreto, mejor); sin división manual.",
  "feat.experts.step2": "El agente muestra primero una lista de subtareas; confirma para empezar.",
  "feat.experts.step3": "Puedes parar de emergencia en cualquier momento y ver el estado y artefactos de cada subtarea.",
  "feat.experts.tech0": "División y ejecución comparten una cadena de degradado multi-modelo; los límites no tumban toda la tarea.",
  "feat.experts.tech1": "Una subtarea fallida solo salta su downstream; las otras ramas siguen.",
  "feat.experts.tech2": "Las llamadas cross-space tienen tope (evita bucles) para que los expertos no se reboten por siempre.",
  "feat.experts.tech3": "El fallo al parsear la división lanza el error real en vez de devolver vacío en silencio.",
  "feat.experts.shot": "Objetivo → subtareas → ejecución experto",

  "feat.memory.title": "Sistema de memoria de cuatro capas",
  "feat.memory.tag": "Memoria",
  "feat.memory.sub": "No empieza desde cero cada vez. Hechos clave, sesiones pasadas, flujos probados, tus preferencias y estilo se asientan en cuatro capas de memoria — cuanto más lo usas, mejor te conoce.",
  "feat.memory.fact0": "4 capas de memoria",
  "feat.memory.fact1": "Búsqueda n-gram chino",
  "feat.memory.fact2": "SQLite local",
  "feat.memory.fact3": "Con tope de capacidad",
  "feat.memory.grid": "4 capas de memoria · búsqueda n-gram chino",
  "feat.memory.what0t": "L1 Memoria residente",
  "feat.memory.what0d": "Los hechos y preferencias más importantes inyectados cada turno. Un tope de capacidad fuerza a guardar solo los más valiosos.",
  "feat.memory.what1t": "L2 Archivo de sesión",
  "feat.memory.what1d": "Todas las sesiones pasadas guardadas localmente, recuperadas por número de aciertos de palabras clave, inyectadas solo cuando se necesita — sin gastar presupuesto residente.",
  "feat.memory.what2t": "L3 Biblioteca de habilidades",
  "feat.memory.what2d": "Los flujos probados se extraen solos en habilidades reutilizables — la segunda vez, una frase reproduce toda la acción.",
  "feat.memory.what3t": "L4 Perfil de usuario",
  "feat.memory.what3d": "El estilo de comunicación, los conocimientos de dominio y los hábitos se acumulan para que las respuestas se parezcan más a ti.",
  "feat.memory.what4t": "Cambia de tema sin perder el hilo",
  "feat.memory.what4d": "Las necesidades de la semana pasada perduran; te vas y vuelves, aún recuerda el contexto.",
  "feat.memory.what5t": "Memoria visible y borrable",
  "feat.memory.what5d": "El panel lateral «Archivos de memoria» siempre es inspectable; las entradas erróneas se pueden borrar o corregir.",
  "feat.memory.step0": "Solo charla con normalidad; sin «recuerda» manual.",
  "feat.memory.step1": "El panel «Archivos de memoria» muestra el residente L1 y el perfil L4 actuales.",
  "feat.memory.step2": "«Limpieza de memoria» borra una capa o elimina una sesión.",
  "feat.memory.step3": "Para que recuerde una regla estricta, simplemente enúnciala en el chat — se juzga como hecho a largo plazo.",
  "feat.memory.tech0": "El chino usa n-gram de 2-4 chars con tokenización inglesa para corregir el bajo acierto LIKE sobre cadena completa.",
  "feat.memory.tech1": "L2 puntúa por aciertos; degrada a tabla simple + LIKE si SQLite FTS5 no está disponible.",
  "feat.memory.tech2": "Los resúmenes ligeros saltan el LLM, concatenando primeros/últimos turnos para controlar coste.",
  "feat.memory.tech3": "Cada capa tiene tope de caracteres, protegiendo la memoria de desbordes obsoletos.",
  "feat.memory.shot": "Archivos de memoria, siempre inspectables y borrables",

  "feat.skills.title": "Las habilidades se cristalizan solas",
  "feat.skills.tag": "Habilidades autoevolutivas",
  "feat.skills.sub": "Un flujo que ejecutaste se extrae solo en una habilidad reutilizable de la biblioteca. La próxima vez, una frase reproduce toda la acción.",
  "feat.skills.fact0": "Extracción auto de flujos",
  "feat.skills.fact1": "Biblioteca central de habilidades",
  "feat.skills.fact2": "Almacenamiento local",
  "feat.skills.fact3": "Reutilizable y compartible",
  "feat.skills.grid": "Extracción auto de flujos · biblioteca central",
  "feat.skills.what0t": "Ejecuta una vez, se vuelve habilidad",
  "feat.skills.what0d": "Un flujo completo (leer → procesar → sacar) que funciona se extrae solo en una habilidad estructurada reutilizable.",
  "feat.skills.what1t": "La próxima vez, una frase",
  "feat.skills.what1d": "Di simplemente «hazlo como la última vez»; empareja desde la biblioteca y ejecuta, sin redescrir los pasos.",
  "feat.skills.what2t": "Biblioteca de habilidades visualizada",
  "feat.skills.what2d": "Panel lateral «Biblioteca de habilidades» para navegar, buscar, activar o borrar.",
  "feat.skills.what3t": "Cableado a la memoria de cuatro capas",
  "feat.skills.what3d": "Las habilidades pertenecen a L3, compartiendo el mismo sistema de memoria con flujos y expertos.",
  "feat.skills.what4t": "Los fallos no ensucian la biblioteca",
  "feat.skills.what4d": "Solo los flujos que de verdad funcionan se cristalizan; los a medias no se guardan como habilidades.",
  "feat.skills.what5t": "Almacenamiento local",
  "feat.skills.what5d": "La biblioteca de habilidades vive en tu máquina, no se sube a la nube.",
  "feat.skills.step0": "Deja que el agente termine un trabajo multi-paso como de costumbre.",
  "feat.skills.step1": "Al tener éxito, el sistema extrae y guarda la habilidad automáticamente.",
  "feat.skills.step2": "Abre el panel «Biblioteca de habilidades» para confirmar (renombrar, borrar).",
  "feat.skills.step3": "La próxima vez referencia la habilidad directamente, o deja que el agente empareje solo.",
  "feat.skills.tech0": "La extracción de habilidades comparte el mismo modelo nodo/paso con el motor de flujos.",
  "feat.skills.tech1": "Las habilidades se guardan como archivos locales para fácil respaldo y migración.",
  "feat.skills.tech2": "Separadas de la memoria L1/L2 para que el texto de habilidad no ocupe el presupuesto residente.",
  "feat.skills.shot": "Biblioteca de habilidades: cristalizada al éxito",

  "feat.workflow.title": "Lienzo de flujo por nodos",
  "feat.workflow.tag": "Lienzo de flujo",
  "feat.workflow.sub": "Encadena la IA como bloques: arrastra nodos, conecta, ejecuta. Cada paso previsualiza, reejecuta y edita su prompt individualmente — prompts que escribes tú o dejas que la IA escriba.",
  "feat.workflow.fact0": "10 tipos de nodos",
  "feat.workflow.fact1": "Arrastrar + auto-conectar + auto-layout",
  "feat.workflow.fact2": "Reejecutar un nodo solo",
  "feat.workflow.fact3": "Prompt DIY o escrito por IA",
  "feat.workflow.grid": "10 tipos de nodos · arrastrar + auto-conectar + auto-layout",
  "feat.workflow.what0t": "10 nodos, cobertura total",
  "feat.workflow.what0d": "Texto LLM, storyboard, imagen IA, vídeo IA, música IA, composición vídeo, nodo herramienta, tarjeta texto, imagen local, música local.",
  "feat.workflow.what1t": "Arrastrar + conectar",
  "feat.workflow.what1d": "Arrastra desde la biblioteca izquierda al lienzo, mantén el borde derecho de un nodo hacia su destino para conectar; o «⚡ Auto Connect» cablea de una vez por lógica de tipo.",
  "feat.workflow.what2t": "Auto-layout",
  "feat.workflow.what2d": "«⌗ Auto Layout» ordena por dependencia en capas; un clic reordena nodos dispersos.",
  "feat.workflow.what3t": "Previsualiza cada paso",
  "feat.workflow.what3d": "Haz clic en cualquier nodo y el panel derecho muestra su artefacto texto / imagen / vídeo / audio con reproductor.",
  "feat.workflow.what4t": "Prompts totalmente DIY",
  "feat.workflow.what4d": "Cada parámetro de texto es un editor multilínea; soporta marcadores {{node}} que referencian artefactos previos.",
  "feat.workflow.what5t": "🪄 La IA escribe los prompts por ti",
  "feat.workflow.what5d": "Da una intención de una línea, la IA escribe un prompt pro por tipo de nodo (artista storyboard / director de arte / productor musical cada uno tiene plantilla); aún editable después.",
  "feat.workflow.what6t": "Plantillas corren al instante",
  "feat.workflow.what6d": "Shorts de IA, sencillos musicales, flujos de arte conceptual integrados — cambia un tema y ejecuta.",
  "feat.workflow.what7t": "Análisis de fiabilidad",
  "feat.workflow.what7d": "«🛡 Fiabilidad» comprueba parámetros faltantes, claves faltantes, enlaces rotos, ciclos, con puntuación y tips de arreglo.",
  "feat.workflow.step0": "Abre el panel «Flujo», arrastra nodos (o «Cargar plantilla»).",
  "feat.workflow.step1": "Conecta: mantén el borde derecho de un nodo hacia el destino; los vagos clican «⚡ Auto Connect».",
  "feat.workflow.step2": "Haz clic en un nodo, pon su prompt para esta tarea (escribe o 🪄 IA escribe).",
  "feat.workflow.step3": "«▶ Ejecutar flujo» corre todo el flujo; un nodo fallido no bloquea otras ramas.",
  "feat.workflow.step4": "Guarda el lienzo como JSON; «Guardar / Abrir JSON» para reutilizar y compartir.",
  "feat.workflow.tech0": "Los nodos son dict plano + deps; el motor ejecuta topológicamente en serie, ramas fallidas saltan su downstream solas.",
  "feat.workflow.tech1": "Los marcadores referencian artefactos previos, soportan el enésimo elemento de una lista (p.ej. plan de storyboard 1).",
  "feat.workflow.tech2": "Parámetros normalizados por tipo (duración→int, instrumental→bool) contra errores de tipo en la nube.",
  "feat.workflow.tech3": "Los valores de retorno del nodo LLM tienen detección de error, evitando que el texto de error fluya río abajo como guion.",
  "feat.workflow.shot": "Lienzo de nodos: arrastra, conecta, previsualiza por nodo",

  "feat.media.title": "Fábrica de medios IA",
  "feat.media.tag": "Estudio de medios IA",
  "feat.media.sub": "De un tema a un clip terminado: guión → storyboard → planos de vídeo IA → música de fondo → subtítulos → composición, todo integrado en el cliente — sin saltar entre sitios.",
  "feat.media.fact0": "Guion / storyboard / vídeo / música",
  "feat.media.fact1": "Subtítulos + GIF",
  "feat.media.fact2": "Vertical 9:16",
  "feat.media.fact3": "Auto-archivado",
  "feat.media.grid": "Guion / storyboard / vídeo / música · subtítulos + GIF",
  "feat.media.what0t": "Generación de guion",
  "feat.media.what0d": "Da un tema, obtén un guion de micro-drama 60s con 3 planos e prompts de imagen recortados auto por plano.",
  "feat.media.what1t": "División de storyboard",
  "feat.media.what1d": "Extrae auto cada descripción de plano en una lista estructurada, alimentada una a una a los nodos de vídeo.",
  "feat.media.what2t": "Planos de vídeo IA",
  "feat.media.what2d": "Llama texto-a-vídeo para generar cada plano, vertical 9:16, duración ajustable, reejecución de un plano solo.",
  "feat.media.what3t": "Música de fondo",
  "feat.media.what3d": "Genera un tema instrumental según el tono del guion, o deja que la IA escriba una canción completa con letra.",
  "feat.media.what4t": "Imagen IA",
  "feat.media.what4d": "Arte conceptual cinematográfico, portadas, refs de storyboard, ratios seleccionables.",
  "feat.media.what5t": "Subtítulos y GIF",
  "feat.media.what5d": "Archivos de subtítulos auto, o exporta clips como GIF.",
  "feat.media.what6t": "Composición de vídeo",
  "feat.media.what6d": "Compone varios planos en orden en un clip terminado.",
  "feat.media.what7t": "Assets locales insertables",
  "feat.media.what7d": "Tus propias imágenes y música pueden caer en el flujo como refs o banda sonora, mezcladas con la salida IA.",
  "feat.media.step0": "Flujo → Carga plantilla «🎬 Short IA (3 planos + música)».",
  "feat.media.step1": "Cambia el tema a esta tarea (p.ej. «la vida diaria de un dragón trabajador»).",
  "feat.media.step2": "Haz clic en el nodo guion, escribe o 🪄 IA escribe; confirma y ejecuta.",
  "feat.media.step3": "Previsualiza por nodo: guion y storyboard primero, luego planos de vídeo y música.",
  "feat.media.step4": "El nodo composición saca el clip; los artefactos caen auto en la carpeta de archivo de tarea.",
  "feat.media.tech0": "Vídeo / música / imagen conectados a Kling, Suno, modelos de imagen vía un registro de herramientas unificado.",
  "feat.media.tech1": "Los nodos de medios facturan por uso; la UI muestra el coste claro (lo gratis puede practicar flujos en local).",
  "feat.media.tech2": "Número de planos, ratio, duración todos editables; el prompt de plano soporta override duro del upstream.",
  "feat.media.tech3": "Rutas de artefactos auto-rellenadas en los nodos; la próxima ejecución reusa directo.",
  "feat.media.shot": "Guion → storyboard → planos → música",

  "feat.modules.title": "Seis módulos de escenarios industriales",
  "feat.modules.tag": "Escenarios",
  "feat.modules.sub": "Investigación, vídeo, imagen, finanzas, software, growth — seis entradas de escenario listas, cada una preconfigurada con expertos, herramientas y tarjetas rápidas; entras y trabajas.",
  "feat.modules.fact0": "6 escenarios",
  "feat.modules.fact1": "Tarjetas rápidas preconfiguradas",
  "feat.modules.fact2": "Multilingüe",
  "feat.modules.fact3": "Local / nube",
  "feat.modules.grid": "6 escenarios · tarjetas de inicio rápido preconfiguradas",
  "feat.modules.what0t": "Investigación",
  "feat.modules.what0d": "Búsqueda de papers, organización de material, resumen estructurado y comparación — ideal para revisiones y propuestas.",
  "feat.modules.what1t": "Creación de vídeo e imagen",
  "feat.modules.what1d": "Guión corto a clip, diseño de concepto y portada, cableado a expertos de creación.",
  "feat.modules.what2t": "Finanzas e inversión",
  "feat.modules.what2d": "Datos de mercado, info de empresas, tesis long/short y riesgo — cableado a trader / actuario.",
  "feat.modules.what3t": "Software y código",
  "feat.modules.what3d": "Desglose de requisitos, gen de código, debug, ejecución de scripts rápidos — cableado a arquitecto / Codex full-stack.",
  "feat.modules.what4t": "Growth y marketing",
  "feat.modules.what4d": "Temas, copy, planificación de campañas, diseño de experimentos growth.",
  "feat.modules.what5t": "Cada módulo tiene tarjetas rápidas",
  "feat.modules.what5d": "Sin prompt from scratch; clica una tarjeta para usar una plantilla de tarea lista.",
  "feat.modules.step0": "Panel «NAVEGACIÓN» elige un escenario (investigación / vídeo / imagen / finanzas / software / growth).",
  "feat.modules.step1": "Clica una tarjeta rápida del escenario, o simplemente describe la necesidad.",
  "feat.modules.step2": "Para cross-escenario, un espacio de proyecto reúne artefactos de varios escenarios.",
  "feat.modules.tech0": "Las tarjetas de escenario son solo combos «plantilla de tarea + experto + herramienta», definidas localmente, editables.",
  "feat.modules.tech1": "Los escenarios comparten un registro de herramientas y un sistema de memoria; los artefactos interoperan.",
  "feat.modules.tech2": "La UI soporta 10 idiomas; el copy de las tarjetas de escenario sigue al switch.",
  "feat.modules.shot": "Tarjetas de escenario: clica y empieza a trabajar",

  "feat.spaces.title": "Espacios de proyecto y centro de tareas",
  "feat.spaces.tag": "Proyectos y tareas",
  "feat.spaces.sub": "Un objetivo, un espacio; varias tareas en paralelo sin mezclar; todos los artefactos, logs y contexto archivados en el espacio, retoma cuando quieras.",
  "feat.spaces.fact0": "Tareas en paralelo",
  "feat.spaces.fact1": "Aislamiento de contexto a nivel espacio",
  "feat.spaces.fact2": "Auto-archivado",
  "feat.spaces.fact3": "Progreso kanban",
  "feat.spaces.grid": "Tareas en paralelo · aislamiento de contexto a nivel espacio",
  "feat.spaces.what0t": "Espacio de proyecto",
  "feat.spaces.what0d": "Abre un espacio por proyecto; sus objetivos, adjuntos, artefactos e historial de chat se guardan por separado, nunca contaminados por otros.",
  "feat.spaces.what1t": "Tareas en paralelo",
  "feat.spaces.what1d": "Ejecuta varias subtareas en un espacio, cada una con su propio progreso.",
  "feat.spaces.what2t": "Centro de tareas kanban",
  "feat.spaces.what2d": "Todas las tareas en un tablero: estado, tiempo, artefactos, razones de fallo de un vistazo.",
  "feat.spaces.what3t": "Bus de contexto",
  "feat.spaces.what3d": "Los espacios pueden referenciar los artefactos de otros dentro de un límite; los topes de llamada evitan dependencia circular.",
  "feat.spaces.what4t": "Archivo de artefactos",
  "feat.spaces.what4d": "Archivos, imágenes, vídeo, tablas generados caen auto en la carpeta del espacio — sin buscar.",
  "feat.spaces.what5t": "Retoma cuando quieras",
  "feat.spaces.what5d": "Cierra y reabre el cliente; el espacio y el progreso permanecen.",
  "feat.spaces.step0": "Panel «Espacios de proyecto» → Nuevo espacio, enuncia el objetivo y adjunta archivos de referencia.",
  "feat.spaces.step1": "Entrega el objetivo al agente; divide en subtareas en paralelo.",
  "feat.spaces.step2": "«Centro de tareas» muestra el progreso global y los artefactos de cada tarea.",
  "feat.spaces.step3": "Cuando acabes, recoge todos los artefactos de la carpeta del espacio; itera en el mismo espacio.",
  "feat.spaces.tech0": "Los espacios pasan refs de artefactos vía un bus de contexto; llamadas cross-space con tope para evitar bucles.",
  "feat.spaces.tech1": "El estado de tarea y las rutas de artefactos persisten; el reinicio no los pierde.",
  "feat.spaces.tech2": "El log de ejecución de cada espacio se guarda por separado para trazar pasos fácilmente.",
  "feat.spaces.shot": "Espacio de proyecto: objetivo, tareas, artefactos en un sitio",

  "feat.task_center.title": "Centro de tareas",
  "feat.task_center.tag": "Centro de tareas",
  "feat.task_center.sub": "Todas las tareas en un kanban: quién corre, qué paso, cuánto tiempo, qué produjo, por qué falló — claro de un vistazo.",
  "feat.task_center.fact0": "Tablero central",
  "feat.task_center.fact1": "Estado en tiempo real",
  "feat.task_center.fact2": "Fallo rastreable",
  "feat.task_center.fact3": "Abrir en un clic",
  "feat.task_center.grid": "Tablero central · refresco de estado en tiempo real",
  "feat.task_center.what0t": "Una pantalla, todo",
  "feat.task_center.what0d": "Disparado por chat, dividido por agente o por agenda — todo converge en una lista.",
  "feat.task_center.what1t": "Estado en tiempo real",
  "feat.task_center.what1d": "En cola / corriendo / hecho / fallado / saltado — el cambio de estado refresca al instante.",
  "feat.task_center.what2t": "Los fallos tienen sentido",
  "feat.task_center.what2d": "El fallo no es solo «error» — da el paso y motivo específico (clave faltante, límite, archivo no encontrado…).",
  "feat.task_center.what3t": "Artefacto directo",
  "feat.task_center.what3d": "Abre una tarea para abrir su archivo, imagen, vídeo o tabla.",
  "feat.task_center.what4t": "Emparejado con flujo",
  "feat.task_center.what4d": "El resultado de cada nodo de flujo también cae en el log de tarea para trazar pasos.",
  "feat.task_center.step0": "Panel «Centro de tareas» para ver todas las tareas.",
  "feat.task_center.step1": "Clica una tarea para detalles: pasos, tiempo, artefactos, log.",
  "feat.task_center.step2": "Las tareas fallidas se rastrean y luego reejecutan ese paso.",
  "feat.task_center.tech0": "Estructura de dos niveles tarea/paso; el log de paso nombra herramienta, parámetros, tiempo, resultado.",
  "feat.task_center.tech1": "Hilo de ejecución y UI separados; tareas largas no congelan la UI; caída de hilo resetea estado de botón auto.",
  "feat.task_center.shot": "Centro de tareas: estado, tiempo, artefactos",

  "feat.automation.title": "Automatización y tareas programadas",
  "feat.automation.tag": "Automatización",
  "feat.automation.sub": "Deja que la IA trabaje a tu ritmo: ordena noticias cada mañana, resume datos semanalmente, recuerda a tiempo — corre incluso cuando no miras.",
  "feat.automation.fact0": "Programado / periódico",
  "feat.automation.fact1": "Planificador local",
  "feat.automation.fact2": "Historial registrado",
  "feat.automation.fact3": "Fallos visibles",
  "feat.automation.grid": "Programado / periódico · planificador local",
  "feat.automation.what0t": "Crear en una frase",
  "feat.automation.what0d": "«Ordena las noticias del sector de ayer en un resumen a las 9am diario» — dicho, existe una automatización.",
  "feat.automation.what1t": "Periódico y único",
  "feat.automation.what1d": "Diario, semanal, mensual, o ejecutar una vez a una hora fija.",
  "feat.automation.what2t": "Planificador local",
  "feat.automation.what2d": "La programación y los datos se quedan en el dispositivo, no se suben.",
  "feat.automation.what3t": "Historial de ejecución",
  "feat.automation.what3d": "Cuántas ejecuciones, cada resultado, cualquier fallo — todo registrado.",
  "feat.automation.what4t": "Pausable y borrable",
  "feat.automation.what4d": "Pausa o borra cuando no lo quieras.",
  "feat.automation.step0": "Panel «Automatización» → Nuevo, escribe qué hacer.",
  "feat.automation.step1": "Pon hora y frecuencia (diario / semanal / una vez a una hora).",
  "feat.automation.step2": "Guarda, luego ve próxima ejecución e historial en la lista.",
  "feat.automation.tech0": "Def de automatización y estado de ejecución persisten separados; la programación sobrevive al reinicio.",
  "feat.automation.tech1": "Cada ejecución registrada independientemente para juzgar contenido vs entorno.",
  "feat.automation.shot": "Trabaja automáticamente a tu ritmo",

  "feat.gui.title": "Automatización GUI",
  "feat.gui.tag": "Control de computadora",
  "feat.gui.sub": "Deja que la IA conduzca otros programas en tu máquina: clic en botones, rellena formularios, abre menús — hasta un software viejo sin API se automatiza.",
  "feat.gui.fact0": "Simulación de ratón y teclado",
  "feat.gui.fact1": "Chequeo de capacidad primero",
  "feat.gui.fact2": "Confirmar por acción",
  "feat.gui.fact3": "Conmutable en cualquier momento",
  "feat.gui.grid": "Simulación de ratón y teclado · chequeo de capacidad primero",
  "feat.gui.what0t": "Opera la UI como un humano",
  "feat.gui.what0d": "La IA «ve» la ventana actual, luego decide dónde clicar y qué teclear, avanzando paso a paso.",
  "feat.gui.what1t": "Chequeo de capacidad antes de empezar",
  "feat.gui.what1d": "El sistema chequea primero si el entorno lo soporta; si no, dice por qué en vez de fallar en silencio.",
  "feat.gui.what2t": "Confirmar antes de actuar",
  "feat.gui.what2d": "Por defecto cada acción clave pregunta; solo el modo auto-confirm salta los avisos.",
  "feat.gui.what3t": "Acciones arriesgadas siguen bloqueadas",
  "feat.gui.what3d": "Operaciones destructivas como borrar/sobrescribir no las libera auto-confirm.",
  "feat.gui.what4t": "Conmutable en cualquier momento",
  "feat.gui.what4d": "Un clic para apagar; la IA pierde al instante el control de ratón/teclado.",
  "feat.gui.step0": "Ajustes → Activa «Automatización GUI», pasa el chequeo de capacidad primero.",
  "feat.gui.step1": "Describe la operación (cuanto más concreto, mejor).",
  "feat.gui.step2": "Confirma cada acción clave como se pide.",
  "feat.gui.step3": "Apaga el interruptor al terminar.",
  "feat.gui.tech0": "El chequeo de capacidad corre y cachea al activar, evitando «entorno no soportado» a mitad.",
  "feat.gui.tech1": "Granularidad de operación configurable; confirmar por acción por defecto.",
  "feat.gui.tech2": "Cableado a auto-confirm: solo auto-confirm explícito salta el aviso.",
  "feat.gui.shot": "Un software viejo sin API también se automatiza",

  "feat.safety.title": "Barandillas de seguridad: auto-confirm y parada de emergencia",
  "feat.safety.tag": "Seguridad",
  "feat.safety.sub": "Otorga el poder que debe otorgarse, bloquea lo que debe bloquearse. Las escrituras pueden confirmar por paso o auto-confirmar por velocidad — pero acciones arriesgadas siempre bloqueadas, borrados siempre a la papelera.",
  "feat.safety.fact0": "Niveles: WARNING / BLOCKED",
  "feat.safety.fact1": "Modo auto-confirm",
  "feat.safety.fact2": "Parada en un clic",
  "feat.safety.fact3": "Borrados → papelera",
  "feat.safety.grid": "Niveles: WARNING / BLOCKED · modo auto-confirm",
  "feat.safety.what0t": "Confirmar por paso por defecto",
  "feat.safety.what0d": "Cada escritura, cambio de dato o comando abre ventana primero; ejecuta solo con tu sí.",
  "feat.safety.what1t": "Auto-confirm (modo velocidad)",
  "feat.safety.what1d": "Tras confianza, actívalo; escrituras rutinarias dejan de preguntar, pasan directo — bueno para flujos repetidos verificados.",
  "feat.safety.what2t": "Riesgo sigue bloqueado",
  "feat.safety.what2d": "Acciones destructivas de nivel BLOCKED no las libera auto-confirm; siempre necesitan tu visto bueno.",
  "feat.safety.what3t": "Borrados → papelera",
  "feat.safety.what3d": "Los borrados de IA van a la papelera por defecto, no se borran — recuperables si te equivocas.",
  "feat.safety.what4t": "Parada de emergencia en un clic",
  "feat.safety.what4d": "¿Ves algo mal a mitad de cadena? La parada de emergencia termina la tarea actual al instante.",
  "feat.safety.what5t": "Listas permitir/denegar de herramientas",
  "feat.safety.what5d": "Las herramientas llamables limitadas a la lista blanca; las de lista negra inalcanzables en todo caso.",
  "feat.safety.step0": "Por defecto «confirmar cada acción» — nada que ajustar.",
  "feat.safety.step1": "Activa «Auto-Confirm» cuando haya suficiente confianza; pregunta una vez al activar.",
  "feat.safety.step2": "Desactiva en cualquier momento desde la barra superior, vuelve a confirmar por paso.",
  "feat.safety.step3": "En curso, clica «Stop» para parada de emergencia de la tarea actual.",
  "feat.safety.tech0": "Acciones gradadas por riesgo: WARNING auto-confirmable, BLOCKED siempre bloqueado.",
  "feat.safety.tech1": "Llamadas herramienta usan listas permitir + denegar; ≤10 llamadas por subtarea.",
  "feat.safety.tech2": "Borrados uniformes vía ruta de respaldo de papelera para recuperabilidad.",
  "feat.safety.shot": "Otorga el poder, bloquea lo que debe bloquearse",

  "feat.files.title": "Trabajo real con archivos",
  "feat.files.tag": "Trabajo real con archivos",
  "feat.files.sub": "No solo charla: lee tus documentos y hojas, edita contenido, genera nuevos archivos, ejecuta scripts, procesa por lotes — luego te entrega el archivo.",
  "feat.files.fact0": "Lee/escribe Office / hojas",
  "feat.files.fact1": "Ejecuta scripts",
  "feat.files.fact2": "Proceso por lotes",
  "feat.files.fact3": "Arrastra / pega imágenes",
  "feat.files.grid": "Lee/escribe Office / hojas · ejecuta scripts",
  "feat.files.what0t": "Entiende tus archivos",
  "feat.files.what0d": "Suelta Word, Excel, PPT, PDF, imágenes; lee y trabaja sobre el contenido.",
  "feat.files.what1t": "Mismo formato tras editar",
  "feat.files.what1d": "Edita in situ y guarda en el formato original — no un texto que copias de vuelta.",
  "feat.files.what2t": "Genera nuevos archivos",
  "feat.files.what2d": "Hojas, informes, listas, gráficos — produce directamente archivos abribles.",
  "feat.files.what3t": "Ejecuta scripts",
  "feat.files.what3d": "Ejecuta scripts para lote cuando hace falta; la salida vuelve al chat.",
  "feat.files.what4t": "Arrastra y pega",
  "feat.files.what4d": "Suelta un archivo en el input para ser contexto; imágenes de portapapeles Ctrl+V se vuelven adjuntos.",
  "feat.files.what5t": "Archivo de artefactos",
  "feat.files.what5d": "Los archivos generados caen en la carpeta de tarea para fácil recogida.",
  "feat.files.step0": "Suelta un archivo en el input (o Ctrl+V pega imagen).",
  "feat.files.step1": "Di qué hacer: «resume esta hoja por mes y grafica la tendencia».",
  "feat.files.step2": "La IA te entrega un archivo nuevo al acabar; abre y usa.",
  "feat.files.tech0": "Lectura/escritura de archivos vía una capa de herramientas unificada, compartida con nodos de flujo.",
  "feat.files.tech1": "Archivos grandes se parsean estructuralmente antes de procesar, evitando meter el doc entero en el contexto.",
  "feat.files.tech2": "Rutas de artefactos generados se rellenan de vuelta para referencia y reprocesado.",
  "feat.files.shot": "Suelta, editado, te entrega un archivo",

  "feat.i18n.title": "Interfaz multilingüe",
  "feat.i18n.tag": "i18n",
  "feat.i18n.sub": "La UI soporta 10 idiomas con cambio en tiempo real — instantáneo, sin reiniciar. Útil para usuarios en el extranjero o trabajo en equipo.",
  "feat.i18n.fact0": "10 idiomas",
  "feat.i18n.fact1": "Cambio en tiempo real",
  "feat.i18n.fact2": "UI + tarjetas de escenario",
  "feat.i18n.fact3": "Extensible",
  "feat.i18n.grid": "10 idiomas · cambio en tiempo real",
  "feat.i18n.what0t": "10 idiomas",
  "feat.i18n.what0d": "简体中文, English, 日本語, 한국어, Deutsch, Français, Español, Português, Русский, العربية.",
  "feat.i18n.what1t": "El cambio surte efecto al instante",
  "feat.i18n.what1d": "Cambia el idioma en Ajustes; el texto de la UI se actualiza al momento, sin reiniciar el cliente.",
  "feat.i18n.what2t": "Cobertura total",
  "feat.i18n.what2d": "UI principal, ajustes, lienzo de flujo, copy de tarjetas de escenario comparten una misma capa multilingüe.",
  "feat.i18n.what3t": "Traducciones extensibles",
  "feat.i18n.what3d": "Los recursos de idioma viven en archivos separados; añadir un idioma es solo una copia más.",
  "feat.i18n.step0": "Ajustes → Idioma de UI, elige un idioma.",
  "feat.i18n.step1": "Si pide reiniciar, reinicia una vez para efecto completo.",
  "feat.i18n.tech0": "Todo el texto de UI se obtiene vía una función de traducción en runtime, evitando hardcodear chino al importar.",
  "feat.i18n.tech1": "Los recursos de idioma son archivos separados para fácil revisión y adición.",
  "feat.i18n.shot": "",

  "feat.privacy.title": "Local-first y privacidad",
  "feat.privacy.tag": "Local First",
  "feat.privacy.sub": "Conversaciones, memoria, base de conocimiento, habilidades y artefactos por defecto en tu propio computador. Funciona totalmente offline; la nube solo para modelos que elijas activamente.",
  "feat.privacy.fact0": "0 datos fuera (modo local)",
  "feat.privacy.fact1": "Usable offline",
  "feat.privacy.fact2": "Todo en el dispositivo",
  "feat.privacy.fact3": "DB local",
  "feat.privacy.grid": "0 datos fuera (local) · usable offline",
  "feat.privacy.what0t": "Los datos quedan en el dispositivo",
  "feat.privacy.what0d": "Historial de chat, memoria de cuatro capas, biblioteca de habilidades, artefactos de proyecto todos como archivos locales / DB local.",
  "feat.privacy.what1t": "Usable offline",
  "feat.privacy.what1d": "Con modelos locales, chat, ops de archivos y orquestación de flujos no necesitan red.",
  "feat.privacy.what2t": "La nube es tu elección",
  "feat.privacy.what2d": "Solo cuando eliges modelos en la nube o generación en la nube va el contenido al proveedor.",
  "feat.privacy.what3t": "Limpieza en un clic",
  "feat.privacy.what3d": "«Limpieza de memoria» puede borrar una capa de memoria o eliminar una sesión — borrado real.",
  "feat.privacy.what4t": "No requiere cuenta",
  "feat.privacy.what4d": "Lo gratis no fuerza registro; las funciones locales funcionan de fábrica.",
  "feat.privacy.step0": "Para todo offline, simplemente usa modelos locales.",
  "feat.privacy.step1": "Para borrar registros: panel «Limpieza de memoria».",
  "feat.privacy.step2": "¿Un chat te parece sensible? Simplemente no elijas modelo en la nube.",
  "feat.privacy.tech0": "El almacenamiento local usa SQLite y carpetas locales, sin servicio en la nube propio.",
  "feat.privacy.tech1": "Las llamadas en la nube solo van vía tu clave de proveedor configurada, directo a la API.",
  "feat.privacy.tech2": "Las capas de memoria son cada una borrables, evitando «borrar una borra todas».",
  "feat.privacy.shot": "Todo en el dispositivo, corre offline",
  "home.price.free.li0": "3.000 créditos de regalo (prueba todos los modelos)",
  "home.price.std.li0": "800 créditos al mes",
  "home.price.pro.li0": "3.000 créditos al mes",
  "home.price.ult.li0": "10.000 créditos al mes",
  "home.price.max.li1": "3.000 créditos de regalo · sin tope mensual, por uso",
  "feat.membership.grid": "5 planes · 3.000 créditos de regalo · registro diario",
  "feat.channels.grid": "14 presets directos de China · en China prioriza modelos nacionales",
  "feat.membership.sub": "Cinco planes con distintos conjuntos de modelos y límites: Gratis funciona en local, Estándar cubre la gama con mejor precio, Pro abre los modelos chinos de referencia, Ultra añade CAD de ingeniería y Max no tiene tope. Los nuevos usuarios reciben 3.000 créditos para probarlo todo; los planes de pago se activan con suscripción o licencia.",
  "feat.membership.fact1": "3.000 créditos de regalo",
  "feat.membership.what4d": "Sin tope mensual en llamadas a la nube: los créditos se descuentan por uso (recarga cuando quieras o cargo automático con tarjeta vinculada). Los agentes especializados —investigación profunda, programación autónoma, CAD auto-documentado, storyboard de miniseries— son exclusivos de este plan. Tus 3.000 créditos de regalo también sirven aquí.",
  "feat.membership.what5t": "Los planes se activan por suscripción",
  "feat.membership.what5d": "El desplegable de planes en Ajustes muestra el estado de cada uno: los planes sin suscripción llevan un 🔒 y no se pueden seleccionar, así no cambias por error. Cuando llega tu suscripción o clave de licencia, ese plan se desbloquea al instante: catálogo de modelos, accesos de capacidad (CAD, agentes especializados) y número de modelos se refrescan, sin reinstalar ni volver a iniciar sesión.",
  "feat.membership.what6t": "Créditos a la vista",
  "feat.membership.what6d": "Tu saldo vive en la barra de estado y baja en cuanto termina cada llamada, según la tarifa publicada del modelo, que aparece junto a su nombre. El registro diario suma 100 créditos (15 veces para cuentas nuevas). Cuando el saldo se agota, la app vuelve al modo gratuito y ofrece una recarga: sin degradación silenciosa ni cargos ocultos.",
  "home.price.max.li2": "Registro diario: 100 créditos",
  "home.shots.tag": "Interfaz real",
  "home.shots.h2": "No son renders: es la interfaz real",
  "home.shots.p": "Todas las imágenes de abajo son capturas directas de la aplicación: sin retoques ni imágenes de relleno. Las funciones son reales y la interfaz también.",
  "home.shots.s1t": "Ventana principal · chat con enrutado multimodelo",
  "home.shots.s1d": "Basta una frase: elige al experto y al modelo más adecuados. Historial y navegación a la izquierda, saldo de créditos en tiempo real abajo a la derecha.",
  "home.shots.s2t": "Lienzo de flujos · arrastra y monta un pipeline",
  "home.shots.s2d": "Guion → storyboard → vídeo → música. Conéctalo una vez y ejecuta toda la cadena; cada nodo se previsualiza por separado.",
  "home.shots.s3t": "Espacio de proyecto · un jefe de proyecto IA reparte el trabajo",
  "home.shots.s3d": "Define un objetivo y descompone las tareas, las asigna a expertos y guarda entregables y avance dentro del espacio.",
  "home.shots.s4t": "Modo ingeniería · gráficas / modelado / simulación",
  "home.shots.s4d": "Tres pestañas —gráficas de ingeniería, modelado matemático y simulación física— con exportación de script o imagen.",
  "home.shots.s5t": "Tareas programadas · plantillas de automatización",
  "home.shots.s5d": "Resumen diario, informe semanal y recordatorio de preparación de entrevistas, listos para usar y programados en local.",
  "home.shots.s6t": "Centro de tareas · panel de avance entre sesiones",
  "home.shots.s6d": "Haz doble clic en una tarjeta para volver a esa sesión: la IA sigue cada tarea entre sesiones.",
  "home.shots.s7t": "Escenario sectorial · análisis de presupuesto de viaje",
  "home.shots.s7d": "Combustible, alojamiento y entradas desglosados en tablas de precios con las fuentes.",
  "home.wf.shotcap": "El lienzo real: arrastra nodos, ajusta parámetros a la derecha y previsualiza nodo a nodo",
  "home.nav.shots": "Capturas",
};
