/* Working Mate — English (reference + fallback for all languages) */
window.I18N = window.I18N || {};
window.I18N.en = {
  /* ───────── 首页 HOME ───────── */
  "home.nav.capability": "Capabilities",
  "home.nav.features": "All Features",
  "home.nav.workflow": "Workflow",
  "home.nav.models": "Models",
  "home.nav.pricing": "Pricing",
  "home.nav.console": "Console",
  "home.nav.login": "Sign in",

  "home.hero1.eyebrow": "v1.4 released · Local-first multi-model AI Agent",
  "home.hero1.h1": "Make AI <span class=\"glow\">actually work</span><br>instead of just chatting",
  "home.hero1.sub": "Local Ollama and cloud LLMs on one scheduler; node-based workflows chain scripts, storyboards, video and music into a single pipeline. Four-layer memory learns you over time, your data stays on-device, and it runs offline.",
  "home.hero1.stat1": "Models supported",
  "home.hero1.stat2": "Data shared",
  "home.hero1.stat3": "Self-evolving memory",
  "home.hero1.cta1": "Free download · Free tier",
  "home.hero1.cta2": "See workflow demo",

  "home.hero2.eyebrow": "Workflow · Node canvas",
  "home.hero2.h1": "Drag &amp; drop<br>to build an <span class=\"glow\">AI pipeline</span>",
  "home.hero2.sub": "Script → storyboard → video shots → background music, all in one run. Preview every step, re-run a single node, and drop in custom cards or local assets.",
  "home.hero2.stat1": "Domain experts",
  "home.hero2.stat2": "Ready templates",
  "home.hero2.stat3": "Drag &amp; use",
  "home.hero2.cta1": "Open workflow",
  "home.hero2.cta2": "Watch 60s demo",

  "home.hero3.eyebrow": "v1.4 · Limited launch offer",
  "home.hero3.h1": "Mid-year sale<br>use it <span class=\"glow\">forever</span> for $0",
  "home.hero3.sub": "The free tier is yours forever with unlimited local models. Paid tiers unlock longer memory, flagship models and cloud generation quota.",
  "home.hero3.stat1": "Starting · Free",
  "home.hero3.stat2": "Standard",
  "home.hero3.stat3": "Team · Planned",
  "home.hero3.cta1": "Download now",
  "home.hero3.cta2": "See changelog",

  "home.float.assist": "AI Assistant",
  "home.float.service": "Human support",
  "home.float.sales": "Sales",

  "home.cap.tag": "Capability",
  "home.cap.h2": "One client, your whole AI workspace",
  "home.cap.c1t": "Local + cloud hybrid routing",
  "home.cap.c1d": "Use Ollama locally when offline, switch to cloud flagships automatically when online. Swap models mid-conversation.",
  "home.cap.c2t": "17 domain experts collaborate",
  "home.cap.c2d": "Give it a goal and AdminAgent splits subtasks, assigns the right expert, and merges the results.",
  "home.cap.c3t": "Four-layer memory",
  "home.cap.c3d": "Resident facts, session archive, skill library, and user profile.",
  "home.cap.c4t": "Skills auto-crystallize",
  "home.cap.c4d": "Flows that work get extracted into reusable skills automatically.",
  "home.cap.c5t": "Real file work",
  "home.cap.c5d": "Read/write docs and spreadsheets, run scripts, drive windows.",

  "home.feat.tag": "All Features",
  "home.feat.h2": "All features, click to see details",
  "home.feat.p": "Every card opens a full page: what it does, how to use it, and the technical highlights.",

  "home.wf.tag": "Workflow",
  "home.wf.h2": "Drag repetitive flows into a pipeline",
  "home.wf.i1t": "Free drag &amp; connect",
  "home.wf.i1d": "Organize flows like building blocks; change one step without redoing the rest.",
  "home.wf.i2t": "Preview every step",
  "home.wf.i2d": "Text, images, video, audio — click a node to see it.",
  "home.wf.i3t": "One-click templates",
  "home.wf.i3d": "AI shorts / music singles / concept art — ready-made flows built in.",
  "home.wf.memtag": "Memory",
  "home.wf.memh2": "It doesn't start from zero every time",
  "home.wf.mem.i1t": "No context loss on topic switch",
  "home.wf.mem.i1d": "Pick up last week's requests this week.",
  "home.wf.mem.i2t": "Flows turn into skills",
  "home.wf.mem.i2d": "The same job takes one sentence the second time.",

  "home.mem.l1t": "Resident memory",
  "home.mem.l1d": "The most critical facts and preferences, injected every turn.",
  "home.mem.l2t": "Session archive",
  "home.mem.l2d": "All history, retrieved by keyword hit count.",
  "home.mem.l3t": "Skill library",
  "home.mem.l3d": "Working flows auto-crystallize for reuse.",
  "home.mem.l4t": "User profile",
  "home.mem.l4d": "Communication style and domain knowledge accumulate over time.",

  "home.models.tag": "Models",
  "home.models.h2": "Pretty much every model you'd want",
  "home.models.m1": "Ollama local",
  "home.models.m2": "DeepSeek V4",
  "home.models.m3": "Qwen3.8 Max",
  "home.models.m4": "GLM 5.3",
  "home.models.m5": "Kimi K3",
  "home.models.m6": "Doubao Seed",
  "home.models.m7": "Claude Opus / Sonnet",
  "home.models.m8": "GPT-5.6",
  "home.models.m9": "Gemini",
  "home.models.m10": "Kling",
  "home.models.m11": "Suno music",
  "home.models.m12": "OpenRouter all",

  "home.price.tag": "Pricing",
  "home.price.h2": "Start free, upgrade when you need more",
  "home.price.free.name": "Free",
  "home.price.free.li1": "Unlimited local models",
  "home.price.free.li2": "Basic chat & file ops",
  "home.price.free.li3": "Ads included",
  "home.price.free.li4": "Community support",
  "home.price.free.cta": "Free download",
  "home.price.std.flag": "Most popular",
  "home.price.std.name": "Standard",
  "home.price.std.li1": "Longer context & memory",
  "home.price.std.li2": "Cost-effective cloud models",
  "home.price.std.li3": "Ad-free",
  "home.price.std.li4": "Full workflow features",
  "home.price.std.cta": "Upgrade to Standard",
  "home.price.pro.name": "Pro",
  "home.price.pro.li1": "All flagship models",
  "home.price.pro.li2": "AI video / music generation",
  "home.price.pro.li3": "Multi-expert collaboration",
  "home.price.pro.li4": "Priority support",
  "home.price.pro.cta": "Upgrade to Pro",
  "home.price.ult.flag": "Coming soon",
  "home.price.ult.name": "Ultimate",
  "home.price.ult.li1": "Huge context",
  "home.price.ult.li2": "Exclusive top models",
  "home.price.ult.li3": "Team collab (planned)",
  "home.price.ult.li4": "—",
  "home.price.ult.cta": "Coming soon",

  "home.faq.h2": "FAQ",
  "home.faq.q1": "Does it work offline?",
  "home.faq.a1": "Yes. Local Ollama models run fully offline — chat, file ops and workflow orchestration need no network.",
  "home.faq.q2": "Is my data uploaded?",
  "home.faq.a2": "No. Chat history, knowledge base and memory all stay on your machine.",
  "home.faq.q3": "What are the Free tier limits?",
  "home.faq.a3": "Free gives you all local capabilities and basic tools with an ad slot; cloud flagship models and AI video/music generation are paid.",
  "home.faq.q4": "Which systems are supported?",
  "home.faq.a4": "Windows and macOS. Mobile (Android / iOS / HarmonyOS) is planned.",

  "home.cta.h2": "Let AI start working now",
  "home.cta.p": "The free tier is forever, installs in a minute, no credit card needed.",
  "home.cta.btn": "Free download Working Mate",

  "home.foot.copy": "© 2026 Working Mate · Local-first AI workspace",
  "home.foot.privacy": "Privacy",
  "home.foot.terms": "Terms",
  "home.foot.refunds": "Refunds",

  /* ───────── 功能页共享 UI (FEAT-UI) ───────── */
  "feat.nav.features": "Features",
  "feat.nav.workflow": "Workflow",
  "feat.nav.models": "Models",
  "feat.nav.pricing": "Pricing",
  "feat.nav.download": "Free download",
  "feat.foot.copy": "© 2026 Working Mate · Local-first AI workspace",
  "feat.foot.features": "Features",
  "feat.foot.privacy": "Privacy",
  "feat.foot.terms": "Terms",
  "feat.foot.refunds": "Refunds",
  "feat.tpl.back": "Back to all features",
  "feat.tpl.what": "What it does",
  "feat.tpl.how": "How to use",
  "feat.tpl.tech": "Technical highlights",
  "feat.tpl.shot": "Take a look",
  "feat.tpl.related": "Related features",
  "feat.tpl.end": "Give it a try",
  "feat.tpl.endP": "The free tier is forever; local features work out of the box, no credit card needed.",
  "feat.tpl.endBtn": "Free download Working Mate",
  "feat.tpl.view": "View details →",
  "feat.tpl.heroCta1": "Try free download",
  "feat.tpl.heroCta2": "See other features",

  /* ───────── 功能数据 (FEAT-DATA) ───────── */
  "feat.models.title": "Multi-Model Hybrid Routing",
  "feat.models.tag": "Multi-Model Router",
  "feat.models.sub": "Local Ollama and cloud flagships live in one chat box: auto-switch to local when offline, auto-switch to cloud when online; swap models mid-conversation without restart or config.",
  "feat.models.fact0": "60+ models",
  "feat.models.fact1": "Local / cloud unified",
  "feat.models.fact2": "Auto fallback",
  "feat.models.fact3": "0 data out (local)",
  "feat.models.grid": "60+ models · local / cloud unified entry",
  "feat.models.what0t": "One input, every model",
  "feat.models.what0d": "No API juggling, no tab sprawl. DeepSeek, Qwen, GLM, Kimi, Doubao, GPT, Claude, Gemini, OpenRouter — all in one dropdown.",
  "feat.models.what1t": "Local first, runs offline",
  "feat.models.what1d": "Plug in Ollama and go fully offline: chat, file ops and workflow orchestration need no network, data never leaves the machine.",
  "feat.models.what2t": "Three-tier model strategy",
  "feat.models.what2d": "Standard / Pro / Flagship one-click switching; the system auto-picks the best value per task, or you pick manually.",
  "feat.models.what3t": "Multi-model auto-degrade",
  "feat.models.what3d": "On rate-limit or 5xx, it hops to the next candidate automatically; only stops and errors clearly on insufficient balance or auth failure — never silent.",
  "feat.models.what4t": "Experts bring model groups",
  "feat.models.what4d": "17 domain experts each bind a reasoning / general / code model group, so coders use code models and writers use writing models.",
  "feat.models.what5t": "Swap live in one session",
  "feat.models.what5d": "Change models mid-chat without losing context — truly \"swap brains on the fly.\"",
  "feat.models.step0": "Settings → Models & runtime, pick a tier (Standard / Pro / Flagship).",
  "feat.models.step1": "For offline use, turn on local Ollama; the client discovers local models automatically.",
  "feat.models.step2": "Pick a model in the top dropdown, or just use \"Auto Router\" to let it choose.",
  "feat.models.step3": "Offline it falls back to local; online it restores cloud — no manual intervention.",
  "feat.models.tech0": "Unified cloud_client abstraction; local / cloud share one call signature.",
  "feat.models.tech1": "429 distinguishes \"rate-limited\" vs \"insufficient balance\": retry once on rate-limit, stop and prompt top-up on balance.",
  "feat.models.tech2": "Multi-model fallback chain: switch only on rate-limit / 5xx; never switch on auth errors (avoid wasteful retries).",
  "feat.models.tech3": "Models indexed by tier × purpose; experts reference model groups directly.",
  "feat.models.shot": "One input, local and cloud connected",

  "feat.experts.title": "17 Domain Experts Collaborate",
  "feat.experts.tag": "Expert Team",
  "feat.experts.sub": "Give a goal, AdminAgent splits it into subtasks, assigns the right expert, and merges into one result. No prompt writing, no manual breakdown.",
  "feat.experts.fact0": "17 domain experts",
  "feat.experts.fact1": "Auto split / assign",
  "feat.experts.fact2": "≤10 tool calls / subtask",
  "feat.experts.fact3": "Auto-merged results",
  "feat.experts.grid": "17 domain experts · auto split / assign",
  "feat.experts.what0t": "Brief it in one sentence",
  "feat.experts.what0d": "Say \"turn this Excel's 3-month sales into a trend chart and write an analysis\" — it splits into read → clean → chart → analyze and assigns.",
  "feat.experts.what1t": "17 domain experts",
  "feat.experts.what1d": "Research, video shorts, image design, music, trading, actuarial, solo-business, software architecture, AI, prompting, full-stack Codex, office, code, writing, data science, ops, general.",
  "feat.experts.what2t": "AdminAgent does the split",
  "feat.experts.what2d": "The主控 agent reads your goal → builds a subtask list (with dependencies) → dispatches each to the right expert.",
  "feat.experts.what3t": "Experts bring model groups",
  "feat.experts.what3d": "Each expert binds a reasoning / general / code model group, and binds generation models on image / video / music.",
  "feat.experts.what4t": "Tool calls stay bounded",
  "feat.experts.what4d": "Up to 10 tool calls per subtask, with allow/deny lists, preventing runaway or dangerous calls.",
  "feat.experts.what5t": "Merged into one delivery",
  "feat.experts.what5d": "When all subtasks finish, results auto-merge into one usable output, not scattered fragments.",
  "feat.experts.step0": "Turn on \"Agent Mode\" at the top.",
  "feat.experts.step1": "Describe your goal (the more specific, the better); no manual breakdown.",
  "feat.experts.step2": "The agent shows a subtask list first; confirm to start.",
  "feat.experts.step3": "You can emergency-stop anytime, and watch each subtask's status and artifacts.",
  "feat.experts.tech0": "Split and execution share one multi-model degrade chain; rate-limits won't crash the whole task.",
  "feat.experts.tech1": "A failed subtask only skips its downstream; other branches keep running.",
  "feat.experts.tech2": "Cross-space calls are capped (prevent loops) so experts can't ping-pong forever.",
  "feat.experts.tech3": "Failed parse of the split throws the real error instead of silently returning empty.",
  "feat.experts.shot": "Goal → subtasks → expert execution",

  "feat.memory.title": "Four-Layer Memory System",
  "feat.memory.tag": "Memory",
  "feat.memory.sub": "It doesn't start from zero each time. Key facts, past sessions, proven flows, your preferences and style settle into four memory layers — the more you use it, the more it knows you.",
  "feat.memory.fact0": "4 memory layers",
  "feat.memory.fact1": "Chinese n-gram search",
  "feat.memory.fact2": "Local SQLite",
  "feat.memory.fact3": "Capacity-capped",
  "feat.memory.grid": "4 memory layers · Chinese n-gram search",
  "feat.memory.what0t": "L1 Resident memory",
  "feat.memory.what0d": "The most important facts and preferences injected every turn. A capacity cap forces it to keep only the most valuable few.",
  "feat.memory.what1t": "L2 Session archive",
  "feat.memory.what1d": "All past sessions stored locally, recalled by keyword hit count, injected only when needed — no resident budget spent.",
  "feat.memory.what2t": "L3 Skill library",
  "feat.memory.what2d": "Proven flows auto-extract into reusable skills — the second time, one sentence replays the whole action.",
  "feat.memory.what3t": "L4 User profile",
  "feat.memory.what3d": "Communication style, domain knowledge, habits accumulate so replies feel more like talking to you.",
  "feat.memory.what4t": "Switch topics without losing thread",
  "feat.memory.what4d": "Last week's needs carry over; jump away and back, it still remembers context.",
  "feat.memory.what5t": "Memory is viewable & clearable",
  "feat.memory.what5d": "The sidebar \"Memory Files\" is always inspectable; wrong entries can be cleared or corrected.",
  "feat.memory.step0": "Just chat normally; no manual \"remember.\"",
  "feat.memory.step1": "Sidebar \"Memory Files\" shows current L1 resident and L4 profile.",
  "feat.memory.step2": "\"Memory Cleanup\" clears one layer or deletes a session.",
  "feat.memory.step3": "To make it remember a hard rule, just state it in chat — it's judged a long-term fact.",
  "feat.memory.tech0": "Chinese uses 2-4 char n-gram with English tokenization to fix low whole-string LIKE hit rates.",
  "feat.memory.tech1": "L2 scores by hit count; auto-degrades to plain table + LIKE when SQLite FTS5 is unavailable.",
  "feat.memory.tech2": "Lightweight summaries skip the LLM, concatenating first/last turns to control cost.",
  "feat.memory.tech3": "Every layer has a char cap, protecting memory from stale overflow.",
  "feat.memory.shot": "Memory files, always inspectable & clearable",

  "feat.skills.title": "Skills Auto-Crystallize",
  "feat.skills.tag": "Self-Evolving Skills",
  "feat.skills.sub": "A flow you ran gets auto-extracted into a reusable skill in the library. Next time, one sentence reproduces the whole action.",
  "feat.skills.fact0": "Auto-extract flows",
  "feat.skills.fact1": "Central skill library",
  "feat.skills.fact2": "Local storage",
  "feat.skills.fact3": "Reusable & shareable",
  "feat.skills.grid": "Auto-extract flows · central skill library",
  "feat.skills.what0t": "Run once, becomes a skill",
  "feat.skills.what0d": "One complete flow (read → process → output) that works gets auto-extracted into a structured reusable skill.",
  "feat.skills.what1t": "Next time, one sentence",
  "feat.skills.what1d": "Just say \"do it like last time\"; it matches from the library and executes, no re-describing steps.",
  "feat.skills.what2t": "Skill library visualized",
  "feat.skills.what2d": "Sidebar \"Skill Library\" to browse, search, enable or delete existing skills.",
  "feat.skills.what3t": "Wired to four-layer memory",
  "feat.skills.what3d": "Skills belong to L3, sharing the same memory system with workflows and experts.",
  "feat.skills.what4t": "Failures don't pollute the library",
  "feat.skills.what4d": "Only flows that truly work get crystallized; half-failed ones aren't saved as skills.",
  "feat.skills.what5t": "Local storage",
  "feat.skills.what5d": "The skill library lives on your machine, not uploaded to the cloud.",
  "feat.skills.step0": "Let the agent finish a multi-step job as usual.",
  "feat.skills.step1": "On success, the system auto-extracts and stores the skill.",
  "feat.skills.step2": "Open the sidebar \"Skill Library\" to confirm (rename, delete).",
  "feat.skills.step3": "Next time reference the skill directly, or let the agent auto-match.",
  "feat.skills.tech0": "Skill extraction shares the same node/step model with the workflow engine.",
  "feat.skills.tech1": "Skills are stored as local files for easy backup and migration.",
  "feat.skills.tech2": "Separated from L1/L2 memory to avoid skill text crowding the resident budget.",
  "feat.skills.shot": "Skill library: crystallized on success",

  "feat.workflow.title": "Node-Based Workflow Canvas",
  "feat.workflow.tag": "Workflow Canvas",
  "feat.workflow.sub": "Chain AI like building blocks: drag nodes, connect, run. Each step previews, re-runs and edits its prompt individually — prompts you can write yourself or let AI write for you.",
  "feat.workflow.fact0": "10 node types",
  "feat.workflow.fact1": "Drag + auto-connect + auto-layout",
  "feat.workflow.fact2": "Single-node rerun",
  "feat.workflow.fact3": "Prompt DIY or AI-written",
  "feat.workflow.grid": "10 node types · drag + auto-connect + auto-layout",
  "feat.workflow.what0t": "10 nodes, full coverage",
  "feat.workflow.what0d": "LLM text, storyboard, AI image, AI video, AI music, video compose, tool node, text card, local image, local music.",
  "feat.workflow.what1t": "Drag + connect",
  "feat.workflow.what1d": "Drag from the left library onto the canvas, hold a node's right edge to its target to connect; or \"⚡ Auto Connect\" wires by type logic at once.",
  "feat.workflow.what2t": "Auto layout",
  "feat.workflow.what2d": "\"⌗ Auto Layout\" arranges by dependency into layers; one click reorders scattered nodes.",
  "feat.workflow.what3t": "Preview every step",
  "feat.workflow.what3d": "Click any node and the right panel shows its text / image / video / audio artifact with a player.",
  "feat.workflow.what4t": "Prompts fully DIY",
  "feat.workflow.what4d": "Every text param is a multi-line editor; supports {{node}} placeholders referencing upstream artifacts.",
  "feat.workflow.what5t": "🪄 AI writes prompts for you",
  "feat.workflow.what5d": "Give one-line intent, AI writes a pro prompt by node type (storyboard artist / art director / music producer each has a template); still editable after.",
  "feat.workflow.what6t": "Templates run instantly",
  "feat.workflow.what6d": "Built-in AI shorts, music singles, concept-art flows — change a theme and run.",
  "feat.workflow.what7t": "Reliability analysis",
  "feat.workflow.what7d": "\"🛡 Reliability\" checks missing params, missing keys, broken links, cycles, with a score and fix tips.",
  "feat.workflow.step0": "Open sidebar \"Workflow\", drag nodes in (or \"Load Template\").",
  "feat.workflow.step1": "Connect: hold a node's right edge to the target; lazy users click \"⚡ Auto Connect\".",
  "feat.workflow.step2": "Click a node, set its prompt to this task (write or 🪄 AI write).",
  "feat.workflow.step3": "\"▶ Run Workflow\" runs the full flow; a failed node won't block other branches.",
  "feat.workflow.step4": "Save canvas as JSON; \"Save / Open JSON\" for reuse and sharing.",
  "feat.workflow.tech0": "Nodes are flat dict + deps; engine runs topologically in series, failed branches auto-skip downstream.",
  "feat.workflow.tech1": "Placeholders reference upstream artifacts, support nth item of a list (e.g. storyboard shot 1).",
  "feat.workflow.tech2": "Params normalized by type (duration→int, instrumental→bool) to avoid cloud type errors.",
  "feat.workflow.tech3": "LLM node return values get error-flag detection, preventing error text flowing downstream as script.",
  "feat.workflow.shot": "Node canvas: drag, connect, per-node preview",

  "feat.media.title": "AI Media Factory",
  "feat.media.tag": "AI Media Studio",
  "feat.media.sub": "From one theme to a finished clip: script → storyboard → AI video shots → background music → subtitles → compose, all built into the client — no hopping between sites.",
  "feat.media.fact0": "Script / storyboard / video / music",
  "feat.media.fact1": "Subtitles + GIF",
  "feat.media.fact2": "Vertical 9:16",
  "feat.media.fact3": "Auto-archived",
  "feat.media.grid": "Script / storyboard / video / music · subtitles + GIF",
  "feat.media.what0t": "Script generation",
  "feat.media.what0d": "Give a theme, get a 60s three-shot micro-drama script with auto-cut image prompts per shot.",
  "feat.media.what1t": "Storyboard split",
  "feat.media.what1d": "Auto-extract each shot description into a structured list, fed one by one to video nodes.",
  "feat.media.what2t": "AI video shots",
  "feat.media.what2d": "Call text-to-video to generate each shot, vertical 9:16, adjustable duration, single-shot rerun.",
  "feat.media.what3t": "Background music",
  "feat.media.what3d": "Generate an instrumental theme by script mood, or let AI write a full song with lyrics.",
  "feat.media.what4t": "AI image",
  "feat.media.what4d": "Cinematic concept art, cover images, storyboard refs, selectable ratios.",
  "feat.media.what5t": "Subtitles & GIF",
  "feat.media.what5d": "Auto subtitle files, or export clips as GIFs.",
  "feat.media.what6t": "Video compose",
  "feat.media.what6d": "Compose multiple shots in order into one finished clip.",
  "feat.media.what7t": "Local assets insertable",
  "feat.media.what7d": "Your own images and music can drop into the workflow as refs or score, mixed with AI output.",
  "feat.media.step0": "Workflow → Load \"🎬 AI Short (3 shots + music)\" template.",
  "feat.media.step1": "Change the theme to this task (e.g. \"daily life of a working dragon\").",
  "feat.media.step2": "Click the script node, write or 🪄 AI write; confirm then run.",
  "feat.media.step3": "Preview per node: script & storyboard first, then generated shot video & music.",
  "feat.media.step4": "Compose node outputs the clip; artifacts auto-land in the task archive folder.",
  "feat.media.tech0": "Video / music / image connect to Kling, Suno, image models via a unified tool registry.",
  "feat.media.tech1": "Media nodes bill per use; UI shows cost clearly (free tier can practice flows with local).",
  "feat.media.tech2": "Shot count, ratio, duration all editable; shot prompt supports hard override of upstream.",
  "feat.media.tech3": "Artifact paths auto-backfill to nodes; next rerun reuses directly.",
  "feat.media.shot": "Script → storyboard → shots → music",

  "feat.modules.title": "Six Industry Scenario Modules",
  "feat.modules.tag": "Scenarios",
  "feat.modules.sub": "Research, video, image, finance, software, growth — six ready-to-use scenario entries, each preset with experts, tools and quick cards; click in and go.",
  "feat.modules.fact0": "6 scenarios",
  "feat.modules.fact1": "Preset quick cards",
  "feat.modules.fact2": "Multi-language",
  "feat.modules.fact3": "Local / cloud",
  "feat.modules.grid": "6 scenarios · preset quick-start cards",
  "feat.modules.what0t": "Research",
  "feat.modules.what0d": "Paper search, material整理, structured summary & comparison — great for reviews and proposals.",
  "feat.modules.what1t": "Video & image creation",
  "feat.modules.what1d": "Short-script to clip, concept & cover design, wired to creation experts.",
  "feat.modules.what2t": "Finance & investment",
  "feat.modules.what2d": "Market data, company info, long/short thesis & risk — wired to trader / actuary.",
  "feat.modules.what3t": "Software & code",
  "feat.modules.what3d": "Requirement breakdown, code gen, debugging, quick script runs — wired to architect / full-stack Codex.",
  "feat.modules.what4t": "Growth & marketing",
  "feat.modules.what4d": "Topics, copy, campaign planning, growth experiment design.",
  "feat.modules.what5t": "Every module has quick cards",
  "feat.modules.what5d": "No prompt from scratch; click a card to use a ready task template.",
  "feat.modules.step0": "Sidebar \"NAVIGATION\" pick a scenario (research / video / image / finance / software / growth).",
  "feat.modules.step1": "Click a quick card in the scenario, or just describe the need.",
  "feat.modules.step2": "For cross-scenario, a project space gathers artifacts from several scenarios.",
  "feat.modules.tech0": "Scenario cards are just \"task template + expert + tool\" combos, all defined locally, editable.",
  "feat.modules.tech1": "Scenarios share one tool registry and memory system; artifacts interoperate.",
  "feat.modules.tech2": "UI supports 10 languages; scenario card copy follows the switch.",
  "feat.modules.shot": "Scenario cards: click and start working",

  "feat.spaces.title": "Project Spaces & Task Center",
  "feat.spaces.tag": "Projects & Tasks",
  "feat.spaces.sub": "One goal, one space; multiple tasks in parallel without mixing; all artifacts, logs and context archived in the space, resume anytime.",
  "feat.spaces.fact0": "Parallel tasks",
  "feat.spaces.fact1": "Space-level context isolation",
  "feat.spaces.fact2": "Auto-archived",
  "feat.spaces.fact3": "Kanban progress",
  "feat.spaces.grid": "Parallel tasks · space-level context isolation",
  "feat.spaces.what0t": "Project space",
  "feat.spaces.what0d": "Open a space per project; its goals, attachments, artifacts and chat history are stored separately, never polluted by others.",
  "feat.spaces.what1t": "Parallel tasks",
  "feat.spaces.what1d": "Run multiple subtasks in one space, each on its own progress.",
  "feat.spaces.what2t": "Task center kanban",
  "feat.spaces.what2d": "All tasks in one board: status, time, artifacts, failure reasons at a glance.",
  "feat.spaces.what3t": "Context bus",
  "feat.spaces.what3d": "Spaces can reference each other's artifacts within limits; call caps prevent circular dependency.",
  "feat.spaces.what4t": "Artifact archive",
  "feat.spaces.what4d": "Generated files, images, video, tables auto-land in the space folder — no hunting.",
  "feat.spaces.what5t": "Resume anytime",
  "feat.spaces.what5d": "Close and reopen the client; the space and progress remain.",
  "feat.spaces.step0": "Sidebar \"Project Spaces\" → New space, state the goal and attach reference files.",
  "feat.spaces.step1": "Hand the goal to the agent; it splits into parallel subtasks.",
  "feat.spaces.step2": "\"Task Center\" shows overall progress and each task's artifacts.",
  "feat.spaces.step3": "When done, grab all artifacts from the space folder; iterate in the same space.",
  "feat.spaces.tech0": "Spaces pass artifact refs via a context bus; cross-space calls capped to prevent loops.",
  "feat.spaces.tech1": "Task state and artifact paths persist; restart doesn't lose them.",
  "feat.spaces.tech2": "Each space's execution log is kept separately for easy step tracing.",
  "feat.spaces.shot": "Project space: goal, tasks, artifacts in one place",

  "feat.task_center.title": "Task Center",
  "feat.task_center.tag": "Task Center",
  "feat.task_center.sub": "All tasks in one kanban: who's running, which step, how long, what it produced, why it failed — clear at a glance.",
  "feat.task_center.fact0": "Central board",
  "feat.task_center.fact1": "Real-time status",
  "feat.task_center.fact2": "Failure traceable",
  "feat.task_center.fact3": "One-click open",
  "feat.task_center.grid": "Central board · real-time status refresh",
  "feat.task_center.what0t": "One screen, all",
  "feat.task_center.what0d": "Whether triggered by chat, split by agent, or run on schedule — all funnel into one list.",
  "feat.task_center.what1t": "Real-time status",
  "feat.task_center.what1d": "Queued / running / done / failed / skipped — status changes refresh instantly.",
  "feat.task_center.what2t": "Failures make sense",
  "feat.task_center.what2d": "Failure isn't just \"error\" — it gives the specific step and reason (missing key, rate-limit, file not found…).",
  "feat.task_center.what3t": "Artifact direct",
  "feat.task_center.what3d": "Open a task to open its file, image, video, or table.",
  "feat.task_center.what4t": "Pairs with workflow",
  "feat.task_center.what4d": "Each workflow node's result also lands in the task log for easy step tracing.",
  "feat.task_center.step0": "Sidebar \"Task Center\" to view all tasks.",
  "feat.task_center.step1": "Click a task for details: steps, time, artifacts, log.",
  "feat.task_center.step2": "Failed tasks can be traced then rerun that step.",
  "feat.task_center.tech0": "Two-level task/step structure; step-level logs tool name, params, time, result.",
  "feat.task_center.tech1": "Execution and UI threads separated; long tasks don't freeze the UI; thread crash auto-resets button state.",
  "feat.task_center.shot": "Task center: status, time, artifacts",

  "feat.automation.title": "Automation & Scheduled Tasks",
  "feat.automation.tag": "Automation",
  "feat.automation.sub": "Let AI work on your rhythm: tidy news each morning, summarize data weekly, remind you on time — it runs even when you're not watching.",
  "feat.automation.fact0": "Scheduled / periodic",
  "feat.automation.fact1": "Local scheduler",
  "feat.automation.fact2": "History logged",
  "feat.automation.fact3": "Failures visible",
  "feat.automation.grid": "Scheduled / periodic · local scheduler",
  "feat.automation.what0t": "One sentence to create",
  "feat.automation.what0d": "\"Tidy yesterday's industry news into a summary at 9am daily\" — said, and an automation exists.",
  "feat.automation.what1t": "Periodic & one-shot",
  "feat.automation.what1d": "Daily, weekly, monthly, or run once at a set time.",
  "feat.automation.what2t": "Local scheduler",
  "feat.automation.what2d": "Scheduling and data stay on-device, not uploaded.",
  "feat.automation.what3t": "Execution history",
  "feat.automation.what3d": "How many runs, each result, any failure — all recorded.",
  "feat.automation.what4t": "Pausable & deletable",
  "feat.automation.what4d": "Pause or delete anytime you don't want it.",
  "feat.automation.step0": "Sidebar \"Automation\" → New, write what to do.",
  "feat.automation.step1": "Set time & frequency (daily / weekly / once at a time).",
  "feat.automation.step2": "Save, then view next run time and history in the list.",
  "feat.automation.tech0": "Automation def and run state persist separately; scheduling survives restart.",
  "feat.automation.tech1": "Each run logged independently to judge content vs environment issues.",
  "feat.automation.shot": "Work automatically on your rhythm",

  "feat.gui.title": "GUI Automation",
  "feat.gui.tag": "Computer Control",
  "feat.gui.sub": "Let AI drive other programs on your machine: click buttons, fill forms, open menus — even old software with no API gets automated.",
  "feat.gui.fact0": "Mouse & keyboard sim",
  "feat.gui.fact1": "Capability check first",
  "feat.gui.fact2": "Confirm per action",
  "feat.gui.fact3": "Toggle anytime",
  "feat.gui.grid": "Mouse & keyboard sim · capability check first",
  "feat.gui.what0t": "Operate UI like a human",
  "feat.gui.what0d": "AI \"sees\" the current window, then decides where to click and what to type, advancing step by step.",
  "feat.gui.what1t": "Capability check before start",
  "feat.gui.what1d": "The system checks if the environment supports it first; if not, tells you why instead of failing silently.",
  "feat.gui.what2t": "Confirm before acting",
  "feat.gui.what2d": "By default every key action asks; only auto-confirm mode skips the prompts.",
  "feat.gui.what3t": "Risky actions still blocked",
  "feat.gui.what3d": "Destructive ops like delete/overwrite aren't released by auto-confirm.",
  "feat.gui.what4t": "Toggle anytime",
  "feat.gui.what4d": "One click off; AI immediately loses mouse/keyboard control.",
  "feat.gui.step0": "Settings → Enable \"GUI Automation\", pass the capability check first.",
  "feat.gui.step1": "Describe the operation (the more specific, the better).",
  "feat.gui.step2": "Confirm each key action as prompted.",
  "feat.gui.step3": "Turn the switch off when done.",
  "feat.gui.tech0": "Capability check runs and caches on enable, avoiding mid-run \"environment unsupported.\"",
  "feat.gui.tech1": "Operation granularity configurable; default per-action confirm.",
  "feat.gui.tech2": "Wired to auto-confirm: only explicit auto-confirm skips the prompt.",
  "feat.gui.shot": "Old software with no API gets automated too",

  "feat.safety.title": "Safety Guardrails: Auto-Confirm & Emergency Stop",
  "feat.safety.tag": "Safety",
  "feat.safety.sub": "Grant the power that should be granted, block what must be blocked. Writes can confirm per step or auto-confirm for speed — but risky actions are always blocked, deletes always go to recycle bin.",
  "feat.safety.fact0": "Levels: WARNING / BLOCKED",
  "feat.safety.fact1": "Auto-confirm mode",
  "feat.safety.fact2": "One-click stop",
  "feat.safety.fact3": "Deletes → recycle bin",
  "feat.safety.grid": "Levels: WARNING / BLOCKED · auto-confirm mode",
  "feat.safety.what0t": "Per-step confirm by default",
  "feat.safety.what0d": "Every write, data change or command first pops a window; executes only on your yes.",
  "feat.safety.what1t": "Auto-confirm (speed mode)",
  "feat.safety.what1d": "After trust, enable it; routine writes stop prompting, run straight through — good for verified repeat flows.",
  "feat.safety.what2t": "Risky still blocked",
  "feat.safety.what2d": "BLOCKED-level destructive actions aren't released by auto-confirm; always need your nod.",
  "feat.safety.what3t": "Deletes → recycle bin",
  "feat.safety.what3d": "AI deletes go to recycle bin by default, not wiped — recoverable if mistaken.",
  "feat.safety.what4t": "One-click emergency stop",
  "feat.safety.what4d": "Spot something wrong mid-chain? Emergency stop ends the running task immediately.",
  "feat.safety.what5t": "Tool allow/deny lists",
  "feat.safety.what5d": "Callable tools limited to the allowlist; denylist tools are unreachable in any case.",
  "feat.safety.step0": "Default is \"confirm every action\" — nothing to set.",
  "feat.safety.step1": "Enable \"Auto-Confirm\" once trust is enough; it asks once on enable.",
  "feat.safety.step2": "Disable anytime from the top bar, back to per-step confirm.",
  "feat.safety.step3": "Mid-run, click \"Stop\" to emergency-stop the current task.",
  "feat.safety.tech0": "Actions graded by risk: WARNING can be auto-confirmed, BLOCKED always blocked.",
  "feat.safety.tech1": "Tool calls use allow + deny lists; ≤10 calls per subtask.",
  "feat.safety.tech2": "Deletes uniformly go through recycle-bin backup path for recoverability.",
  "feat.safety.shot": "Grant the power, block what must be blocked",

  "feat.files.title": "Real File Work",
  "feat.files.tag": "Real File Work",
  "feat.files.sub": "It doesn't just chat: read your docs and sheets, edit content, generate new files, run scripts, batch process — then hand you the file.",
  "feat.files.fact0": "Read/write Office / sheets",
  "feat.files.fact1": "Run scripts",
  "feat.files.fact2": "Batch process",
  "feat.files.fact3": "Drag / paste images",
  "feat.files.grid": "Read/write Office / sheets · run scripts",
  "feat.files.what0t": "Understands your files",
  "feat.files.what0d": "Drop in Word, Excel, PPT, PDF, images; it reads and works on the content.",
  "feat.files.what1t": "Same format after edit",
  "feat.files.what1d": "Edits in-place and saves as the original format — not text you copy back yourself.",
  "feat.files.what2t": "Generate new files",
  "feat.files.what2d": "Sheets, reports, lists, charts — directly produce openable files.",
  "feat.files.what3t": "Run scripts",
  "feat.files.what3d": "Run scripts for batch when needed; output flows back into chat.",
  "feat.files.what4t": "Drag & paste",
  "feat.files.what4d": "Drop a file into the input to become context; clipboard images Ctrl+V become attachments.",
  "feat.files.what5t": "Artifact archive",
  "feat.files.what5d": "Generated files land in the task folder for easy pickup.",
  "feat.files.step0": "Drop a file into the input (or Ctrl+V paste an image).",
  "feat.files.step1": "Say what to do: \"summarize this sheet by month and chart the trend.\"",
  "feat.files.step2": "AI hands you a new file when done; open and use.",
  "feat.files.tech0": "File read/write goes through a unified tool layer, shared with workflow nodes.",
  "feat.files.tech1": "Large files are structurally parsed before processing, avoiding stuffing the whole doc into context.",
  "feat.files.tech2": "Generated artifact paths backfill for later reference and reprocessing.",
  "feat.files.shot": "Drop in, edited, hand you back a file",

  "feat.i18n.title": "Multi-Language Interface",
  "feat.i18n.tag": "i18n",
  "feat.i18n.sub": "The UI supports 10 languages with real-time switching — instant, no restart. Handy for overseas users or team collaboration.",
  "feat.i18n.fact0": "10 languages",
  "feat.i18n.fact1": "Real-time switch",
  "feat.i18n.fact2": "UI + scenario cards",
  "feat.i18n.fact3": "Extensible",
  "feat.i18n.grid": "10 languages · real-time switch",
  "feat.i18n.what0t": "10 languages",
  "feat.i18n.what0d": "简体中文, English, 日本語, 한국어, Deutsch, Français, Español, Português, Русский, العربية.",
  "feat.i18n.what1t": "Switch takes effect instantly",
  "feat.i18n.what1d": "Change language in Settings; UI text updates immediately, no client restart.",
  "feat.i18n.what2t": "Full coverage",
  "feat.i18n.what2d": "Main UI, settings, workflow canvas, scenario card copy all share one multilingual layer.",
  "feat.i18n.what3t": "Translations extensible",
  "feat.i18n.what3d": "Language resources live in separate files; adding a language is just one more copy.",
  "feat.i18n.step0": "Settings → UI Language, pick a language.",
  "feat.i18n.step1": "If prompted to restart, restart once for full effect.",
  "feat.i18n.tech0": "All UI text is fetched via a runtime translation function, avoiding hard-coding Chinese at import.",
  "feat.i18n.tech1": "Language resources are separate files for easy review and addition.",
  "feat.i18n.shot": "",

  "feat.privacy.title": "Local-First & Privacy",
  "feat.privacy.tag": "Local First",
  "feat.privacy.sub": "Conversations, memory, knowledge base, skills and artifacts all default to your own computer. Works fully offline; cloud is only for models you actively choose.",
  "feat.privacy.fact0": "0 data out (local mode)",
  "feat.privacy.fact1": "Offline usable",
  "feat.privacy.fact2": "All on-device",
  "feat.privacy.fact3": "Local DB",
  "feat.privacy.grid": "0 data out (local) · offline usable",
  "feat.privacy.what0t": "Data stays on-device",
  "feat.privacy.what0d": "Chat history, four-layer memory, skill library, project artifacts all stored as local files / local DB.",
  "feat.privacy.what1t": "Offline usable",
  "feat.privacy.what1d": "With local models, chat, file ops and workflow orchestration need no network at all.",
  "feat.privacy.what2t": "Cloud is your choice",
  "feat.privacy.what2d": "Only when you choose cloud models or cloud generation does related content go to the provider.",
  "feat.privacy.what3t": "One-click cleanup",
  "feat.privacy.what3d": "\"Memory Cleanup\" can clear a memory layer or delete a session — gone for real.",
  "feat.privacy.what4t": "No account needed",
  "feat.privacy.what4d": "Free tier doesn't force registration; local features work out of the box.",
  "feat.privacy.step0": "For full offline, just use local models.",
  "feat.privacy.step1": "To clear records: sidebar \"Memory Cleanup\".",
  "feat.privacy.step2": "Worried a chat is sensitive? Just don't pick a cloud model.",
  "feat.privacy.tech0": "Local storage uses SQLite and local dirs, no self-built cloud service.",
  "feat.privacy.tech1": "Cloud calls only go through your configured provider key, directly to the API.",
  "feat.privacy.tech2": "Memory layers are each clearable, avoiding \"clear one wipes all.\"",
  "feat.privacy.shot": "All on-device, runs offline"
};
