/* Working Mate — Português */
window.I18N = window.I18N || {};
window.I18N.pt = {
  /* ───────── 首页 HOME ───────── */
  "home.nav.capability": "Capacidades",
  "home.nav.features": "Todas as funções",
  "home.nav.workflow": "Fluxo de trabalho",
  "home.nav.models": "Modelos",
  "home.nav.pricing": "Preços",
  "home.nav.console": "Console",
  "home.nav.login": "Entrar",

  "home.hero1.eyebrow": "v1.4 lançado · Agente de IA multi-modelo local-first",
  "home.hero1.h1": "Faça a IA <span class=\"glow\">trabalhar de verdade</span><br>em vez de só conversar",
  "home.hero1.sub": "Ollama local e LLMs na nuvem sob um mesmo agendador; fluxos por nós encadeiam scripts, storyboards, vídeo e música num único pipeline. A memória de quatro camadas aprende com você com o tempo, seus dados ficam no dispositivo e roda offline.",
  "home.hero1.stat1": "Modelos suportados",
  "home.hero1.stat2": "Dados compartilhados",
  "home.hero1.stat3": "Memória autoevolutiva",
  "home.hero1.cta1": "Baixar grátis · Nível gratuito",
  "home.hero1.cta2": "Ver demo do fluxo",

  "home.hero2.eyebrow": "Fluxo de trabalho · Tela de nós",
  "home.hero2.h1": "Arraste e solte<br>para construir um <span class=\"glow\">pipeline de IA</span>",
  "home.hero2.sub": "Roteiro → storyboard → planos de vídeo → música de fundo, tudo numa execução. Pré-visualize cada passo, reexecute um nó só e insira cartões ou assets locais personalizados.",
  "home.hero2.stat1": "Especialistas de domínio",
  "home.hero2.stat2": "Modelos prontos",
  "home.hero2.stat3": "Arraste e use",
  "home.hero2.cta1": "Abrir fluxo",
  "home.hero2.cta2": "Ver demo de 60s",

  "home.hero3.eyebrow": "v1.4 · Oferta limitada de lançamento",
  "home.hero3.h1": "Promo de meio de ano<br>use <span class=\"glow\">para sempre</span> por $0",
  "home.hero3.sub": "O nível gratuito é seu para sempre com modelos locais ilimitados. Os níveis pagos destravam memória mais longa, modelos estrela e cota de geração na nuvem.",
  "home.hero3.stat1": "Início · Grátis",
  "home.hero3.stat2": "Padrão",
  "home.hero3.stat3": "Equipe · Previsto",
  "home.hero3.cta1": "Baixar agora",
  "home.hero3.cta2": "Ver registro de mudanças",

  "home.float.assist": "Assistente IA",
  "home.float.service": "Suporte humano",
  "home.float.sales": "Vendas",

  "home.cap.tag": "Capacidade",
  "home.cap.h2": "Um só cliente, todo o seu espaço de trabalho IA",
  "home.cap.c1t": "Roteamento híbrido local + nuvem",
  "home.cap.c1d": "Use Ollama local offline, troque automaticamente para modelos estrela na nuvem quando online. Troque de modelo no meio da conversa.",
  "home.cap.c2t": "17 especialistas de domínio colaboram",
  "home.cap.c2d": "Dê um objetivo e o AdminAgent divide as subtarefas, atribui o especialista certo e funde os resultados.",
  "home.cap.c3t": "Memória de quatro camadas",
  "home.cap.c3d": "Fatos residentes, arquivo de sessão, biblioteca de habilidades e perfil do usuário.",
  "home.cap.c4t": "As habilidades se cristalizam sozinhas",
  "home.cap.c4d": "Os fluxos que funcionam são extraídos automaticamente em habilidades reutilizáveis.",
  "home.cap.c5t": "Trabalho real com arquivos",
  "home.cap.c5d": "Lê/escreve documentos e planilhas, executa scripts, controla o Windows.",

  "home.feat.tag": "Todas as funções",
  "home.feat.h2": "Todas as funções, clique para ver detalhes",
  "home.feat.p": "Cada cartão abre uma página completa: o que faz, como usar e os pontos técnicos.",

  "home.wf.tag": "Fluxo de trabalho",
  "home.wf.h2": "Transforme fluxos repetitivos num pipeline",
  "home.wf.i1t": "Arraste e conecte livremente",
  "home.wf.i1d": "Organize fluxos como blocos; mude um passo sem refazer o resto.",
  "home.wf.i2t": "Pré-visualize cada passo",
  "home.wf.i2d": "Texto, imagens, vídeo, áudio — clique num nó para ver.",
  "home.wf.i3t": "Modelos num clique",
  "home.wf.i3d": "Shorts de IA / singles musicais / arte conceitual — fluxos prontos integrados.",
  "home.wf.memtag": "Memória",
  "home.wf.memh2": "Não recomeça do zero toda vez",
  "home.wf.mem.i1t": "Sem perda de contexto ao trocar de assunto",
  "home.wf.mem.i1d": "Retome nesta semana as solicitações da semana passada.",
  "home.wf.mem.i2t": "Os fluxos viram habilidades",
  "home.wf.mem.i2d": "A mesma tarefa na segunda vez leva uma única frase.",

  "home.mem.l1t": "Memória residente",
  "home.mem.l1d": "Os fatos e preferências mais críticos, injetados a cada turno.",
  "home.mem.l2t": "Arquivo de sessão",
  "home.mem.l2d": "Todo o histórico, recuperado por número de acertos de palavras-chave.",
  "home.mem.l3t": "Biblioteca de habilidades",
  "home.mem.l3d": "Os fluxos comprovados se cristalizam automaticamente para reuso.",
  "home.mem.l4t": "Perfil do usuário",
  "home.mem.l4d": "O estilo de comunicação e os conhecimentos de domínio se acumulam com o tempo.",

  "home.models.tag": "Modelos",
  "home.models.h2": "Praticamente qualquer modelo que você queira",
  "home.models.m1": "Ollama local",
  "home.models.m2": "DeepSeek V4",
  "home.models.m3": "Qwen3.8 Max",
  "home.models.m4": "GLM 5.3",
  "home.models.m5": "Kimi K3",
  "home.models.m6": "Doubao Seed",
  "home.models.m7": "Claude Opus / Sonnet",
  "home.models.m8": "GPT-5.6",
  "home.models.m9": "Gemini",
  "home.models.m10": "Kling",
  "home.models.m11": "Suno music",
  "home.models.m12": "OpenRouter todos",

  "home.price.tag": "Preços",
  "home.price.h2": "Comece grátis, melhore quando precisar de mais",
  "home.price.free.name": "Grátis",
  "home.price.free.li1": "Modelos locais ilimitados",
  "home.price.free.li2": "Chat e ops de arquivos básicas",
  "home.price.free.li3": "Inclui anúncios",
  "home.price.free.li4": "Suporte da comunidade",
  "home.price.free.cta": "Baixar grátis",
  "home.price.std.flag": "Mais popular",
  "home.price.std.name": "Padrão",
  "home.price.std.li1": "Contexto e memória mais longos",
  "home.price.std.li2": "Modelos na nuvem econômicos",
  "home.price.std.li3": "Sem anúncios",
  "home.price.std.li4": "Funções de fluxo completas",
  "home.price.std.cta": "Ir para Padrão",
  "home.price.pro.name": "Pro",
  "home.price.pro.li1": "Todos os modelos estrela",
  "home.price.pro.li2": "Geração de vídeo / música IA",
  "home.price.pro.li3": "Colaboração multi-especialista",
  "home.price.pro.li4": "Suporte prioritário",
  "home.price.pro.cta": "Ir para Pro",
  "home.price.ult.flag": "Em breve",
  "home.price.ult.name": "Ultimate",
  "home.price.ult.li1": "Contexto enorme",
  "home.price.ult.li2": "Modelos top exclusivos",
  "home.price.ult.li3": "Colab de equipe (previsto)",
  "home.price.ult.li4": "—",
  "home.price.ult.cta": "Em breve",

  "home.faq.h2": "Perguntas frequentes",
  "home.faq.q1": "Funciona offline?",
  "home.faq.a1": "Sim. Os modelos locais do Ollama rodam totalmente offline — chat, ops de arquivos e orquestração de fluxos não precisam de rede.",
  "home.faq.q2": "Meus dados são enviados?",
  "home.faq.a2": "Não. O histórico de chat, a base de conhecimento e a memória ficam na sua máquina.",
  "home.faq.q3": "Quais os limites do nível grátis?",
  "home.faq.a3": "O grátis dá todas as capacidades locais e ferramentas básicas com um espaço de anúncio; os modelos estrela na nuvem e a geração de vídeo/música IA são pagos.",
  "home.faq.q4": "Quais sistemas são suportados?",
  "home.faq.a4": "Windows e macOS. Mobile (Android / iOS / HarmonyOS) está previsto.",

  "home.cta.h2": "Deixe a IA começar a trabalhar agora",
  "home.cta.p": "O nível grátis é para sempre, instala em um minuto, sem cartão de crédito.",
  "home.cta.btn": "Baixe o Working Mate grátis",

  "home.foot.copy": "© 2026 Working Mate · Espaço de trabalho IA local-first",
  "home.foot.privacy": "Privacidade",
  "home.foot.terms": "Termos",
  "home.foot.refunds": "Reembolsos",

  /* ───────── 功能页共享 UI (FEAT-UI) ───────── */
  "feat.nav.features": "Funções",
  "feat.nav.workflow": "Fluxo de trabalho",
  "feat.nav.models": "Modelos",
  "feat.nav.pricing": "Preços",
  "feat.nav.download": "Baixar grátis",
  "feat.foot.copy": "© 2026 Working Mate · Espaço de trabalho IA local-first",
  "feat.foot.features": "Funções",
  "feat.foot.privacy": "Privacidade",
  "feat.foot.terms": "Termos",
  "feat.foot.refunds": "Reembolsos",
  "feat.tpl.back": "Voltar a todas as funções",
  "feat.tpl.what": "O que faz",
  "feat.tpl.how": "Como usar",
  "feat.tpl.tech": "Destaques técnicos",
  "feat.tpl.shot": "Dê uma olhada",
  "feat.tpl.related": "Funções relacionadas",
  "feat.tpl.end": "Experimente",
  "feat.tpl.endP": "O nível grátis é para sempre; as funções locais funcionam de fábrica, sem cartão de crédito.",
  "feat.tpl.endBtn": "Baixe o Working Mate grátis",
  "feat.tpl.view": "Ver detalhes →",
  "feat.tpl.heroCta1": "Testar download grátis",
  "feat.tpl.heroCta2": "Ver outras funções",

  /* ───────── 功能数据 (FEAT-DATA) ───────── */
  "feat.models.title": "Roteamento híbrido multi-modelo",
  "feat.models.tag": "Roteador multi-modelo",
  "feat.models.sub": "Ollama local e modelos estrela na nuvem numa só caixa de chat: troca automática para local offline, automática para nuvem online; troque de modelo no meio da conversa sem reiniciar nem reconfigurar.",
  "feat.models.fact0": "60+ modelos",
  "feat.models.fact1": "Local / nuvem unificado",
  "feat.models.fact2": "Fallback auto",
  "feat.models.fact3": "0 dados fora (local)",
  "feat.models.grid": "60+ modelos · entrada unificada local / nuvem",
  "feat.models.what0t": "Uma entrada, todos os modelos",
  "feat.models.what0d": "Sem biruta de APIs, sem abas espalhadas. DeepSeek, Qwen, GLM, Kimi, Doubao, GPT, Claude, Gemini, OpenRouter — tudo num menu suspenso.",
  "feat.models.what1t": "Local primeiro, roda offline",
  "feat.models.what1d": "Plugue o Ollama e fique totalmente offline: chat, ops de arquivos e orquestração de fluxos não precisam de rede, os dados nunca saem da máquina.",
  "feat.models.what2t": "Estratégia de modelos em três níveis",
  "feat.models.what2d": "Padrão / Pro / Estrela num clique; o sistema escolhe automaticamente o melhor custo-benefício por tarefa, ou você escolhe manualmente.",
  "feat.models.what3t": "Degradação automática multi-modelo",
  "feat.models.what3d": "Ante limite de taxa ou 5xx, pula automaticamente para o próximo candidato; só para e erra claramente com saldo insuficiente ou falha de auth — nunca em silêncio.",
  "feat.models.what4t": "Os especialistas trazem grupos de modelos",
  "feat.models.what4d": "Os 17 especialistas de domínio ligam cada um um grupo de modelos raciocínio / geral / código, assim coders usam modelos de código e redatores modelos de escrita.",
  "feat.models.what5t": "Troque ao vivo numa sessão",
  "feat.models.what5d": "Troque de modelo no meio do chat sem perder contexto — verdadeiramente «troca de cérebro em voo».",
  "feat.models.step0": "Ajustes → Modelos e runtime, escolha um nível (Padrão / Pro / Estrela).",
  "feat.models.step1": "Para uso offline, ligue o Ollama local; o cliente descobre os modelos locais automaticamente.",
  "feat.models.step2": "Escolha um modelo no menu superior, ou simplesmente use «Roteador auto».",
  "feat.models.step3": "Offline cai para local; online restaura a nuvem — sem intervenção manual.",
  "feat.models.tech0": "Abstração cloud_client unificada; local / nuvem compartilham uma mesma assinatura de chamada.",
  "feat.models.tech1": "429 distingue «limite» vs «saldo insuficiente»: retry uma vez no limite, para e pede recarga no saldo.",
  "feat.models.tech2": "Cadeia de fallback multi-modelo: troca só em limite / 5xx; nunca em erros de auth (evita retries inúteis).",
  "feat.models.tech3": "Modelos indexados por nível × propósito; os especialistas referenciam grupos de modelos diretamente.",
  "feat.models.shot": "Uma entrada, local e nuvem conectados",

  "feat.experts.title": "17 especialistas de domínio colaboram",
  "feat.experts.tag": "Equipe de especialistas",
  "feat.experts.sub": "Dê um objetivo, o AdminAgent o divide em subtarefas, atribui o especialista certo e funde num único resultado. Sem escrever prompts, sem divisão manual.",
  "feat.experts.fact0": "17 especialistas de domínio",
  "feat.experts.fact1": "Divisão / atribuição auto",
  "feat.experts.fact2": "≤10 chamadas ferramenta / subtarefa",
  "feat.experts.fact3": "Resultados fundidos auto",
  "feat.experts.grid": "17 especialistas de domínio · divisão / atribuição auto",
  "feat.experts.what0t": "Descreva numa frase",
  "feat.experts.what0d": "Diga «transforme as vendas de 3 meses deste Excel num gráfico de tendência e escreva uma análise» — divide em ler → limpar → gráfico → analisar e atribui.",
  "feat.experts.what1t": "17 especialistas de domínio",
  "feat.experts.what1d": "Pesquisa, shorts de vídeo, design de imagem, música, trading, atuária, negócio-solo, arquitetura de software, IA, prompting, Codex full-stack, escritório, código, redação, ciência de dados, ops, geral.",
  "feat.experts.what2t": "O AdminAgent faz a divisão",
  "feat.experts.what2d": "O agente principal lê seu objetivo → constrói uma lista de subtarefas (com dependências) → despacha cada uma ao especialista certo.",
  "feat.experts.what3t": "Os especialistas trazem grupos de modelos",
  "feat.experts.what3d": "Cada especialista liga um grupo de modelos raciocínio / geral / código, e liga modelos de geração em imagem / vídeo / música.",
  "feat.experts.what4t": "As chamadas ferramenta ficam limitadas",
  "feat.experts.what4d": "Até 10 chamadas ferramenta por subtarefa, com listas permitir/negar, evitando chamadas descontroladas ou perigosas.",
  "feat.experts.what5t": "Fundido numa entrega",
  "feat.experts.what5d": "Quando todas as subtarefas terminam, os resultados se fundem automaticamente numa saída útil, não fragmentos espalhados.",
  "feat.experts.step0": "Ative «Modo Agente» acima.",
  "feat.experts.step1": "Descreva seu objetivo (quanto mais específico, melhor); sem divisão manual.",
  "feat.experts.step2": "O agente mostra primeiro uma lista de subtarefas; confirme para iniciar.",
  "feat.experts.step3": "Você pode parar de emergência a qualquer momento e ver o status e artefatos de cada subtarefa.",
  "feat.experts.tech0": "Divisão e execução compartilham uma mesma cadeia de degradação multi-modelo; limites não derrubam a tarefa toda.",
  "feat.experts.tech1": "Uma subtarefa falha só pula seu downstream; os outros ramos continuam.",
  "feat.experts.tech2": "As chamadas cross-space têm teto (evita loops) para os especialistas não se rebaterem para sempre.",
  "feat.experts.tech3": "A falha ao parsear a divisão lança o erro real em vez de devolver vazio em silêncio.",
  "feat.experts.shot": "Objetivo → subtarefas → execução especialista",

  "feat.memory.title": "Sistema de memória de quatro camadas",
  "feat.memory.tag": "Memória",
  "feat.memory.sub": "Não recomeça do zero toda vez. Fatos-chave, sessões passadas, fluxos comprovados, suas preferências e estilo se assentam em quatro camadas de memória — quanto mais usa, mais ele o conhece.",
  "feat.memory.fact0": "4 camadas de memória",
  "feat.memory.fact1": "Busca n-gram chinês",
  "feat.memory.fact2": "SQLite local",
  "feat.memory.fact3": "Com teto de capacidade",
  "feat.memory.grid": "4 camadas de memória · busca n-gram chinês",
  "feat.memory.what0t": "L1 Memória residente",
  "feat.memory.what0d": "Os fatos e preferências mais importantes injetados a cada turno. Um teto de capacidade força a guardar só os mais valiosos.",
  "feat.memory.what1t": "L2 Arquivo de sessão",
  "feat.memory.what1d": "Todas as sessões passadas armazenadas localmente, recuperadas por número de acertos de palavras-chave, injetadas só quando necessário — sem gastar orçamento residente.",
  "feat.memory.what2t": "L3 Biblioteca de habilidades",
  "feat.memory.what2d": "Os fluxos comprovados se extraem sozinhos em habilidades reutilizáveis — na segunda vez, uma frase reproduz toda a ação.",
  "feat.memory.what3t": "L4 Perfil do usuário",
  "feat.memory.what3d": "O estilo de comunicação, os conhecimentos de domínio e os hábitos se acumulam para as respostas parecerem mais com você.",
  "feat.memory.what4t": "Troque de assunto sem perder o fio",
  "feat.memory.what4d": "As necessidades da semana passada persistem; saia e volte, ainda lembra do contexto.",
  "feat.memory.what5t": "Memória visível e apagável",
  "feat.memory.what5d": "O painel lateral «Arquivos de memória» está sempre inspecionável; entradas erradas podem ser apagadas ou corrigidas.",
  "feat.memory.step0": "Só converse normalmente; sem «lembre» manual.",
  "feat.memory.step1": "O painel «Arquivos de memória» mostra o residente L1 e o perfil L4 atuais.",
  "feat.memory.step2": "«Limpeza de memória» apaga uma camada ou deleta uma sessão.",
  "feat.memory.step3": "Para memorizar uma regra rígida, basta enunciá-la no chat — julgada como fato de longo prazo.",
  "feat.memory.tech0": "O chinês usa n-gram de 2-4 chars com tokenização em inglês para corrigir a baixa taxa de acerto LIKE sobre string completa.",
  "feat.memory.tech1": "L2 pontua por acertos; degrada para tabela simples + LIKE se SQLite FTS5 indisponível.",
  "feat.memory.tech2": "Os resumos leves pulam o LLM, concatenando primeiros/últimos turnos para controlar custo.",
  "feat.memory.tech3": "Cada camada tem teto de caracteres, protegendo a memória de estouro obsoleto.",
  "feat.memory.shot": "Arquivos de memória, sempre inspecionáveis e apagáveis",

  "feat.skills.title": "As habilidades se cristalizam sozinhas",
  "feat.skills.tag": "Habilidades autoevolutivas",
  "feat.skills.sub": "Um fluxo que você executou é extraído sozinho numa habilidade reutilizável da biblioteca. Na próxima vez, uma frase reproduz toda a ação.",
  "feat.skills.fact0": "Extração auto de fluxos",
  "feat.skills.fact1": "Biblioteca central de habilidades",
  "feat.skills.fact2": "Armazenamento local",
  "feat.skills.fact3": "Reutilizável e compartilhável",
  "feat.skills.grid": "Extração auto de fluxos · biblioteca central",
  "feat.skills.what0t": "Execute uma vez, vira habilidade",
  "feat.skills.what0d": "Um fluxo completo (ler → processar → sair) que funciona é extraído sozinho numa habilidade estruturada reutilizável.",
  "feat.skills.what1t": "Na próxima vez, uma frase",
  "feat.skills.what1d": "Diga simplesmente «faça como da última vez»; ele casa pela biblioteca e executa, sem reescrever os passos.",
  "feat.skills.what2t": "Biblioteca de habilidades visualizada",
  "feat.skills.what2d": "Painel lateral «Biblioteca de habilidades» para navegar, buscar, ativar ou apagar.",
  "feat.skills.what3t": "Conectada à memória de quatro camadas",
  "feat.skills.what3d": "As habilidades pertencem a L3, compartilhando o mesmo sistema de memória com fluxos e especialistas.",
  "feat.skills.what4t": "Falhas não poluem a biblioteca",
  "feat.skills.what4d": "Só fluxos que realmente funcionam se cristalizam; os pela metade não são salvos como habilidades.",
  "feat.skills.what5t": "Armazenamento local",
  "feat.skills.what5d": "A biblioteca de habilidades vive na sua máquina, não é enviada à nuvem.",
  "feat.skills.step0": "Deixe o agente terminar um trabalho multi-passo como de costume.",
  "feat.skills.step1": "Ao ter sucesso, o sistema extrai e salva a habilidade automaticamente.",
  "feat.skills.step2": "Abra o painel «Biblioteca de habilidades» para confirmar (renomear, apagar).",
  "feat.skills.step3": "Na próxima vez referencie a habilidade diretamente, ou deixe o agente casar sozinho.",
  "feat.skills.tech0": "A extração de habilidades compartilha o mesmo modelo nó/passo com o motor de fluxos.",
  "feat.skills.tech1": "As habilidades são salvas como arquivos locais para fácil backup e migração.",
  "feat.skills.tech2": "Separadas da memória L1/L2 para o texto de habilidade não ocupar o orçamento residente.",
  "feat.skills.shot": "Biblioteca de habilidades: cristalizada ao sucesso",

  "feat.workflow.title": "Tela de fluxo por nós",
  "feat.workflow.tag": "Tela de fluxo",
  "feat.workflow.sub": "Encadeie a IA como blocos: arraste nós, conecte, execute. Cada passo pré-visualiza, reexecuta e edita seu prompt individualmente — prompts que você escreve ou deixa a IA escrever.",
  "feat.workflow.fact0": "10 tipos de nós",
  "feat.workflow.fact1": "Arrastar + auto-conectar + auto-layout",
  "feat.workflow.fact2": "Reexecutar um nó só",
  "feat.workflow.fact3": "Prompt DIY ou escrito por IA",
  "feat.workflow.grid": "10 tipos de nós · arrastar + auto-conectar + auto-layout",
  "feat.workflow.what0t": "10 nós, cobertura total",
  "feat.workflow.what0d": "Texto LLM, storyboard, imagem IA, vídeo IA, música IA, composição vídeo, nó ferramenta, cartão texto, imagem local, música local.",
  "feat.workflow.what1t": "Arrastar + conectar",
  "feat.workflow.what1d": "Arraste da biblioteca esquerda para a tela, segure a borda direita de um nó até o destino para conectar; ou «⚡ Auto Connect» cabea de uma vez por lógica de tipo.",
  "feat.workflow.what2t": "Auto-layout",
  "feat.workflow.what2d": "«⌗ Auto Layout» organiza por dependência em camadas; um clique reordena nós espalhados.",
  "feat.workflow.what3t": "Pré-visualize cada passo",
  "feat.workflow.what3d": "Clique em qualquer nó e o painel direito mostra seu artefato texto / imagem / vídeo / áudio com player.",
  "feat.workflow.what4t": "Prompts totalmente DIY",
  "feat.workflow.what4d": "Cada parâmetro de texto é um editor multilinha; suporta marcadores {{node}} que referenciam artefatos a montante.",
  "feat.workflow.what5t": "🪄 A IA escreve os prompts para você",
  "feat.workflow.what5d": "Dê uma intenção de uma linha, a IA escreve um prompt pro por tipo de nó (artista storyboard / diretor de arte / produtor musical cada um tem modelo); ainda editável depois.",
  "feat.workflow.what6t": "Modelos rodam instantaneamente",
  "feat.workflow.what6d": "Shorts de IA, singles musicais, fluxos de arte conceitual integrados — mude um tema e execute.",
  "feat.workflow.what7t": "Análise de confiabilidade",
  "feat.workflow.what7d": "«🛡 Confiabilidade» checa parâmetros faltantes, chaves faltantes, links quebrados, ciclos, com pontuação e dicas de correção.",
  "feat.workflow.step0": "Abra o painel «Fluxo», arraste nós (ou «Carregar modelo»).",
  "feat.workflow.step1": "Conecte: segure a borda direita de um nó até o destino; os vagarosos clicam «⚡ Auto Connect».",
  "feat.workflow.step2": "Clique num nó, defina seu prompt para esta tarefa (escreva ou 🪄 IA escreve).",
  "feat.workflow.step3": "«▶ Executar fluxo» roda o fluxo todo; um nó falho não bloqueia outros ramos.",
  "feat.workflow.step4": "Salve a tela como JSON; «Salvar / Abrir JSON» para reuso e compartilhamento.",
  "feat.workflow.tech0": "Os nós são dict plano + deps; o motor executa topologicamente em série, ramos falhos pulam seu downstream sozinhos.",
  "feat.workflow.tech1": "Os marcadores referenciam artefatos a montante, suportam o enésimo item de uma lista (ex. plano de storyboard 1).",
  "feat.workflow.tech2": "Parâmetros normalizados por tipo (duração→int, instrumental→bool) contra erros de tipo na nuvem.",
  "feat.workflow.tech3": "Os valores de retorno do nó LLM têm detecção de erro, evitando que o texto de erro flua a jusante como roteiro.",
  "feat.workflow.shot": "Tela de nós: arraste, conecte, pré-visualize por nó",

  "feat.media.title": "Fábrica de mídia IA",
  "feat.media.tag": "Estúdio de mídia IA",
  "feat.media.sub": "De um tema a um clipe pronto: roteiro → storyboard → planos de vídeo IA → música de fundo → legendas → composição, tudo integrado no cliente — sem pular de site em site.",
  "feat.media.fact0": "Roteiro / storyboard / vídeo / música",
  "feat.media.fact1": "Legendas + GIF",
  "feat.media.fact2": "Vertical 9:16",
  "feat.media.fact3": "Auto-arquivado",
  "feat.media.grid": "Roteiro / storyboard / vídeo / música · legendas + GIF",
  "feat.media.what0t": "Geração de roteiro",
  "feat.media.what0d": "Dê um tema, obtenha um roteiro de micro-drama 60s com 3 planos e prompts de imagem recortados auto por plano.",
  "feat.media.what1t": "Divisão de storyboard",
  "feat.media.what1d": "Extrai auto cada descrição de plano numa lista estruturada, alimentada uma a uma aos nós de vídeo.",
  "feat.media.what2t": "Planos de vídeo IA",
  "feat.media.what2d": "Chame texto-para-vídeo para gerar cada plano, vertical 9:16, duração ajustável, reexecução de um plano só.",
  "feat.media.what3t": "Música de fundo",
  "feat.media.what3d": "Gere um tema instrumental conforme o clima do roteiro, ou deixe a IA escrever uma música completa com letra.",
  "feat.media.what4t": "Imagem IA",
  "feat.media.what4d": "Arte conceitual cinematográfico, capas, refs de storyboard, ratios selecionáveis.",
  "feat.media.what5t": "Legendas e GIF",
  "feat.media.what5d": "Arquivos de legenda auto, ou exporte clips como GIF.",
  "feat.media.what6t": "Composição de vídeo",
  "feat.media.what6d": "Componha vários planos em ordem num clipe terminado.",
  "feat.media.what7t": "Assets locais inseríveis",
  "feat.media.what7d": "Suas próprias imagens e músicas podem cair no fluxo como refs ou trilha, misturadas com a saída IA.",
  "feat.media.step0": "Fluxo → Carregue modelo «🎬 Short IA (3 planos + música)».",
  "feat.media.step1": "Mude o tema para esta tarefa (ex. «o dia a dia de um dragão trabalhador»).",
  "feat.media.step2": "Clique no nó roteiro, escreva ou 🪄 IA escreve; confirme e execute.",
  "feat.media.step3": "Pré-visualize por nó: roteiro e storyboard primeiro, depois planos de vídeo e música.",
  "feat.media.step4": "O nó composição solta o clipe; os artefatos caem auto na pasta de arquivo de tarefa.",
  "feat.media.tech0": "Vídeo / música / imagem conectados a Kling, Suno, modelos de imagem via um registro de ferramentas unificado.",
  "feat.media.tech1": "Os nós de mídia faturam por uso; a UI mostra o custo claro (o grátis pode praticar fluxos localmente).",
  "feat.media.tech2": "Número de planos, ratio, duração todos editáveis; o prompt de plano suporta override duro a montante.",
  "feat.media.tech3": "Caminhos de artefatos auto-preenchidos nos nós; a próxima execução reusa direto.",
  "feat.media.shot": "Roteiro → storyboard → planos → música",

  "feat.modules.title": "Seis módulos de cenários industriais",
  "feat.modules.tag": "Cenários",
  "feat.modules.sub": "Pesquisa, vídeo, imagem, finanças, software, growth — seis entradas de cenário prontas, cada uma pré-configurada com especialistas, ferramentas e cartões rápidos; entre e trabalhe.",
  "feat.modules.fact0": "6 cenários",
  "feat.modules.fact1": "Cartões rápidos pré-configurados",
  "feat.modules.fact2": "Multilíngue",
  "feat.modules.fact3": "Local / nuvem",
  "feat.modules.grid": "6 cenários · cartões de início rápido pré-configurados",
  "feat.modules.what0t": "Pesquisa",
  "feat.modules.what0d": "Busca de papers, organização de material, resumo estruturado e comparação — ótimo para revisões e propostas.",
  "feat.modules.what1t": "Criação de vídeo e imagem",
  "feat.modules.what1d": "Roteiro curto para clipe, design de conceito e capa, conectado a especialistas de criação.",
  "feat.modules.what2t": "Finanças e investimento",
  "feat.modules.what2d": "Dados de mercado, info de empresas, tese long/short e risco — conectado a trader / atuário.",
  "feat.modules.what3t": "Software e código",
  "feat.modules.what3d": "Divisão de requisitos, gen de código, debug, execução de scripts rápidos — conectado a arquiteto / Codex full-stack.",
  "feat.modules.what4t": "Growth e marketing",
  "feat.modules.what4d": "Temas, copy, planejamento de campanhas, design de experimentos growth.",
  "feat.modules.what5t": "Cada módulo tem cartões rápidos",
  "feat.modules.what5d": "Sem prompt from scratch; clique um cartão para usar um modelo de tarefa pronto.",
  "feat.modules.step0": "Painel «NAVEGAÇÃO» escolha um cenário (pesquisa / vídeo / imagem / finanças / software / growth).",
  "feat.modules.step1": "Clique um cartão rápido do cenário, ou simplesmente descreva a necessidade.",
  "feat.modules.step2": "Para cross-cenário, um espaço de projeto reúne artefatos de vários cenários.",
  "feat.modules.tech0": "Os cartões de cenário são só combos «modelo de tarefa + especialista + ferramenta», definidos localmente, editáveis.",
  "feat.modules.tech1": "Os cenários compartilham um registro de ferramentas e um sistema de memória; os artefatos interoperam.",
  "feat.modules.tech2": "A UI suporta 10 idiomas; o copy dos cartões de cenário segue o switch.",
  "feat.modules.shot": "Cartões de cenário: clique e comece a trabalhar",

  "feat.spaces.title": "Espaços de projeto e centro de tarefas",
  "feat.spaces.tag": "Projetos e tarefas",
  "feat.spaces.sub": "Um objetivo, um espaço; várias tarefas em paralelo sem misturar; todos os artefatos, logs e contexto arquivados no espaço, retome quando quiser.",
  "feat.spaces.fact0": "Tarefas em paralelo",
  "feat.spaces.fact1": "Isolamento de contexto a nível de espaço",
  "feat.spaces.fact2": "Auto-arquivado",
  "feat.spaces.fact3": "Progresso kanban",
  "feat.spaces.grid": "Tarefas em paralelo · isolamento de contexto a nível de espaço",
  "feat.spaces.what0t": "Espaço de projeto",
  "feat.spaces.what0d": "Abra um espaço por projeto; seus objetivos, anexos, artefatos e histórico de chat são guardados separadamente, nunca contaminados por outros.",
  "feat.spaces.what1t": "Tarefas em paralelo",
  "feat.spaces.what1d": "Execute várias subtarefas num espaço, cada uma com seu próprio progresso.",
  "feat.spaces.what2t": "Centro de tarefas kanban",
  "feat.spaces.what2d": "Todas as tarefas num quadro: status, tempo, artefatos, razões de falha num relance.",
  "feat.spaces.what3t": "Barramento de contexto",
  "feat.spaces.what3d": "Os espaços podem referenciar os artefatos de outros dentro de um limite; os tetos de chamada evitam dependência circular.",
  "feat.spaces.what4t": "Arquivo de artefatos",
  "feat.spaces.what4d": "Arquivos, imagens, vídeo, planilhas gerados caem auto na pasta do espaço — sem caçar.",
  "feat.spaces.what5t": "Retome quando quiser",
  "feat.spaces.what5d": "Feche e reabra o cliente; o espaço e o progresso permanecem.",
  "feat.spaces.step0": "Painel «Espaços de projeto» → Novo espaço, enuncie o objetivo e anexe arquivos de referência.",
  "feat.spaces.step1": "Entregue o objetivo ao agente; ele divide em subtarefas em paralelo.",
  "feat.spaces.step2": "«Centro de tarefas» mostra o progresso global e os artefatos de cada tarefa.",
  "feat.spaces.step3": "Quando acabar, pegue todos os artefatos da pasta do espaço; itere no mesmo espaço.",
  "feat.spaces.tech0": "Os espaços passam refs de artefatos via um barramento de contexto; chamadas cross-space com teto para evitar loops.",
  "feat.spaces.tech1": "O estado de tarefa e os caminhos de artefatos persistem; o reinício não os perde.",
  "feat.spaces.tech2": "O log de execução de cada espaço é guardado separadamente para rastrear passos facilmente.",
  "feat.spaces.shot": "Espaço de projeto: objetivo, tarefas, artefatos num lugar",

  "feat.task_center.title": "Centro de tarefas",
  "feat.task_center.tag": "Centro de tarefas",
  "feat.task_center.sub": "Todas as tarefas num kanban: quem roda, que passo, quanto tempo, o que produziu, por que falhou — claro num relance.",
  "feat.task_center.fact0": "Quadro central",
  "feat.task_center.fact1": "Status em tempo real",
  "feat.task_center.fact2": "Falha rastreável",
  "feat.task_center.fact3": "Abrir num clique",
  "feat.task_center.grid": "Quadro central · refresco de status em tempo real",
  "feat.task_center.what0t": "Uma tela, tudo",
  "feat.task_center.what0d": "Disparado por chat, dividido por agente ou por agenda — tudo converge numa lista.",
  "feat.task_center.what1t": "Status em tempo real",
  "feat.task_center.what1d": "Em fila / rodando / feito / falhou / pulado — a mudança de status atualiza instantaneamente.",
  "feat.task_center.what2t": "As falhas fazem sentido",
  "feat.task_center.what2d": "A falha não é só «erro» — dá o passo e motivo específico (chave faltante, limite, arquivo não encontrado…).",
  "feat.task_center.what3t": "Artefato direto",
  "feat.task_center.what3d": "Abra uma tarefa para abrir seu arquivo, imagem, vídeo ou planilha.",
  "feat.task_center.what4t": "Emparelhado com fluxo",
  "feat.task_center.what4d": "O resultado de cada nó de fluxo também cai no log de tarefa para rastrear passos.",
  "feat.task_center.step0": "Painel «Centro de tarefas» para ver todas as tarefas.",
  "feat.task_center.step1": "Clique uma tarefa para detalhes: passos, tempo, artefatos, log.",
  "feat.task_center.step2": "Tarefas falhas podem ser rastreadas e depois reexecutar aquele passo.",
  "feat.task_center.tech0": "Estrutura de dois níveis tarefa/passo; o log de passo nomeia ferramenta, parâmetros, tempo, resultado.",
  "feat.task_center.tech1": "Thread de execução e UI separados; tarefas longas não congelam a UI; queda de thread reseta estado de botão auto.",
  "feat.task_center.shot": "Centro de tarefas: status, tempo, artefatos",

  "feat.automation.title": "Automação e tarefas agendadas",
  "feat.automation.tag": "Automação",
  "feat.automation.sub": "Deixe a IA trabalhar no seu ritmo: organize notícias cada manhã, resuma dados semanalmente, lembre na hora — roda mesmo quando você não olha.",
  "feat.automation.fact0": "Agendado / periódico",
  "feat.automation.fact1": "Agendador local",
  "feat.automation.fact2": "Histórico registrado",
  "feat.automation.fact3": "Falhas visíveis",
  "feat.automation.grid": "Agendado / periódico · agendador local",
  "feat.automation.what0t": "Crie numa frase",
  "feat.automation.what0d": "«Organize as notícias do setor de ontem num resumo às 9h diário» — dito, existe uma automação.",
  "feat.automation.what1t": "Periódico e único",
  "feat.automation.what1d": "Diário, semanal, mensal, ou executar uma vez num horário fixo.",
  "feat.automation.what2t": "Agendador local",
  "feat.automation.what2d": "O agendamento e os dados ficam no dispositivo, não são enviados.",
  "feat.automation.what3t": "Histórico de execução",
  "feat.automation.what3d": "Quantas execuções, cada resultado, qualquer falha — tudo registrado.",
  "feat.automation.what4t": "Pausável e apagável",
  "feat.automation.what4d": "Pause ou apague quando não quiser mais.",
  "feat.automation.step0": "Painel «Automação» → Novo, escreva o que fazer.",
  "feat.automation.step1": "Defina hora e frequência (diário / semanal / uma vez num horário).",
  "feat.automation.step2": "Salve, depois veja próxima execução e histórico na lista.",
  "feat.automation.tech0": "Def de automação e estado de execução persistem separados; o agendamento sobrevive ao reinício.",
  "feat.automation.tech1": "Cada execução registrada independentemente para julgar conteúdo vs ambiente.",
  "feat.automation.shot": "Trabalhe automaticamente no seu ritmo",

  "feat.gui.title": "Automação GUI",
  "feat.gui.tag": "Controle de computador",
  "feat.gui.sub": "Deixe a IA conduzir outros programas na sua máquina: clicar botões, preencher formulários, abrir menus — até um software antigo sem API é automatizado.",
  "feat.gui.fact0": "Simulação de mouse e teclado",
  "feat.gui.fact1": "Checagem de capacidade primeiro",
  "feat.gui.fact2": "Confirmar por ação",
  "feat.gui.fact3": "Alternável a qualquer momento",
  "feat.gui.grid": "Simulação de mouse e teclado · checagem de capacidade primeiro",
  "feat.gui.what0t": "Opere a UI como um humano",
  "feat.gui.what0d": "A IA «vê» a janela atual, então decide onde clicar e o que digitar, avançando passo a passo.",
  "feat.gui.what1t": "Checagem de capacidade antes de começar",
  "feat.gui.what1d": "O sistema checa primeiro se o ambiente suporta; senão, diz por que em vez de falhar em silêncio.",
  "feat.gui.what2t": "Confirmar antes de agir",
  "feat.gui.what2d": "Por padrão cada ação-chave pergunta; só o modo auto-confirm pula os avisos.",
  "feat.gui.what3t": "Ações arriscadas seguem bloqueadas",
  "feat.gui.what3d": "Operações destrutivas como apagar/sobrescrever não são liberadas por auto-confirm.",
  "feat.gui.what4t": "Alternável a qualquer momento",
  "feat.gui.what4d": "Um clique para desligar; a IA perde instantaneamente o controle de mouse/teclado.",
  "feat.gui.step0": "Ajustes → Ative «Automação GUI», passe a checagem de capacidade primeiro.",
  "feat.gui.step1": "Descreva a operação (quanto mais específico, melhor).",
  "feat.gui.step2": "Confirme cada ação-chave como pedido.",
  "feat.gui.step3": "Desligue o interruptor ao terminar.",
  "feat.gui.tech0": "A checagem de capacidade roda e cacheia ao ativar, evitando «ambiente não suportado» no meio.",
  "feat.gui.tech1": "Granularidade de operação configurável; confirmar por ação por padrão.",
  "feat.gui.tech2": "Conectado a auto-confirm: só auto-confirm explícito pula o aviso.",
  "feat.gui.shot": "Um software antigo sem API também é automatizado",

  "feat.safety.title": "Barreiras de segurança: auto-confirm e parada de emergência",
  "feat.safety.tag": "Segurança",
  "feat.safety.sub": "Conceda o poder que deve ser concedido, bloqueie o que deve ser bloqueado. As escritas podem confirmar por passo ou auto-confirmar por velocidade — mas ações arriscadas sempre bloqueadas, deletes sempre vão para a lixeira.",
  "feat.safety.fact0": "Níveis: WARNING / BLOCKED",
  "feat.safety.fact1": "Modo auto-confirm",
  "feat.safety.fact2": "Parada num clique",
  "feat.safety.fact3": "Deletes → lixeira",
  "feat.safety.grid": "Níveis: WARNING / BLOCKED · modo auto-confirm",
  "feat.safety.what0t": "Confirmar por passo por padrão",
  "feat.safety.what0d": "Cada escrita, mudança de dado ou comando abre janela primeiro; executa só com seu sim.",
  "feat.safety.what1t": "Auto-confirm (modo velocidade)",
  "feat.safety.what1d": "Após confiança, ative; escritas rotineiras param de perguntar, passam direto — bom para fluxos repetidos verificados.",
  "feat.safety.what2t": "Risco segue bloqueado",
  "feat.safety.what2d": "Ações destrutivas de nível BLOCKED não são liberadas por auto-confirm; sempre precisam do seu aval.",
  "feat.safety.what3t": "Deletes → lixeira",
  "feat.safety.what3d": "Os deletes de IA vão para a lixeira por padrão, não apagados — recuperáveis se errar.",
  "feat.safety.what4t": "Parada de emergência num clique",
  "feat.safety.what4d": "Viu algo errado no meio da cadeia? A parada de emergência encerra a tarefa atual imediatamente.",
  "feat.safety.what5t": "Listas permitir/negar de ferramentas",
  "feat.safety.what5d": "As ferramentas chamáveis limitadas à lista branca; as da lista negra são inalcançáveis em todo caso.",
  "feat.safety.step0": "Por padrão «confirmar cada ação» — nada a ajustar.",
  "feat.safety.step1": "Ative «Auto-Confirm» quando houver confiança suficiente; pergunta uma vez ao ativar.",
  "feat.safety.step2": "Desative a qualquer momento pela barra superior, volte a confirmar por passo.",
  "feat.safety.step3": "Em curso, clique «Stop» para parada de emergência da tarefa atual.",
  "feat.safety.tech0": "Ações graduadas por risco: WARNING auto-confirmável, BLOCKED sempre bloqueado.",
  "feat.safety.tech1": "Chamadas ferramenta usam listas permitir + negar; ≤10 chamadas por subtarefa.",
  "feat.safety.tech2": "Deletes uniformes via caminho de backup de lixeira para recuperabilidade.",
  "feat.safety.shot": "Conceda o poder, bloqueie o que deve ser bloqueado",

  "feat.files.title": "Trabalho real com arquivos",
  "feat.files.tag": "Trabalho real com arquivos",
  "feat.files.sub": "Não só conversa: lê seus documentos e planilhas, edita conteúdo, gera novos arquivos, executa scripts, processa em lote — então entrega o arquivo.",
  "feat.files.fact0": "Lê/escreve Office / planilhas",
  "feat.files.fact1": "Executa scripts",
  "feat.files.fact2": "Processo em lote",
  "feat.files.fact3": "Arraste / cole imagens",
  "feat.files.grid": "Lê/escreve Office / planilhas · executa scripts",
  "feat.files.what0t": "Entende seus arquivos",
  "feat.files.what0d": "Solte Word, Excel, PPT, PDF, imagens; lê e trabalha sobre o conteúdo.",
  "feat.files.what1t": "Mesmo formato após editar",
  "feat.files.what1d": "Edita no local e salva no formato original — não um texto que você copia de volta.",
  "feat.files.what2t": "Gera novos arquivos",
  "feat.files.what2d": "Planilhas, relatórios, listas, gráficos — produz diretamente arquivos abríveis.",
  "feat.files.what3t": "Executa scripts",
  "feat.files.what3d": "Execute scripts para lote quando preciso; a saída volta ao chat.",
  "feat.files.what4t": "Arraste e cole",
  "feat.files.what4d": "Solte um arquivo no input para ser contexto; imagens da área de transferência Ctrl+V viram anexos.",
  "feat.files.what5t": "Arquivo de artefatos",
  "feat.files.what5d": "Os arquivos gerados caem na pasta de tarefa para fácil recolha.",
  "feat.files.step0": "Solte um arquivo no input (ou Ctrl+V cole imagem).",
  "feat.files.step1": "Diga o que fazer: «resuma esta planilha por mês e grafique a tendência».",
  "feat.files.step2": "A IA entrega um arquivo novo ao terminar; abra e use.",
  "feat.files.tech0": "Leitura/escrita de arquivos via uma camada de ferramentas unificada, compartilhada com nós de fluxo.",
  "feat.files.tech1": "Arquivos grandes são parseados estruturalmente antes de processar, evitando enfiar o doc todo no contexto.",
  "feat.files.tech2": "Caminhos de artefatos gerados são repreenchidos para referência e reprocessamento.",
  "feat.files.shot": "Solte, editado, entrega um arquivo",

  "feat.i18n.title": "Interface multilíngue",
  "feat.i18n.tag": "i18n",
  "feat.i18n.sub": "A UI suporta 10 idiomas com troca em tempo real — instantâneo, sem reiniciar. Útil para usuários no exterior ou trabalho em equipe.",
  "feat.i18n.fact0": "10 idiomas",
  "feat.i18n.fact1": "Troca em tempo real",
  "feat.i18n.fact2": "UI + cartões de cenário",
  "feat.i18n.fact3": "Extensível",
  "feat.i18n.grid": "10 idiomas · troca em tempo real",
  "feat.i18n.what0t": "10 idiomas",
  "feat.i18n.what0d": "简体中文, English, 日本語, 한국어, Deutsch, Français, Español, Português, Русский, العربية.",
  "feat.i18n.what1t": "A troca surte efeito na hora",
  "feat.i18n.what1d": "Mude o idioma em Ajustes; o texto da UI atualiza imediatamente, sem reiniciar o cliente.",
  "feat.i18n.what2t": "Cobertura total",
  "feat.i18n.what2d": "UI principal, ajustes, tela de fluxo, copy dos cartões de cenário compartilham uma mesma camada multilíngue.",
  "feat.i18n.what3t": "Traduções extensíveis",
  "feat.i18n.what3d": "Os recursos de idioma vivem em arquivos separados; adicionar um idioma é só mais uma cópia.",
  "feat.i18n.step0": "Ajustes → Idioma da UI, escolha um idioma.",
  "feat.i18n.step1": "Se pedir reinício, reinicie uma vez para efeito completo.",
  "feat.i18n.tech0": "Todo o texto da UI é obtido via uma função de tradução em runtime, evitando hardcodar chinês ao importar.",
  "feat.i18n.tech1": "Os recursos de idioma são arquivos separados para fácil revisão e adição.",
  "feat.i18n.shot": "",

  "feat.privacy.title": "Local-first e privacidade",
  "feat.privacy.tag": "Local First",
  "feat.privacy.sub": "Conversas, memória, base de conhecimento, habilidades e artefatos por padrão no seu próprio computador. Funciona totalmente offline; a nuvem só para modelos que você escolhe ativamente.",
  "feat.privacy.fact0": "0 dados fora (modo local)",
  "feat.privacy.fact1": "Usável offline",
  "feat.privacy.fact2": "Tudo no dispositivo",
  "feat.privacy.fact3": "DB local",
  "feat.privacy.grid": "0 dados fora (local) · usável offline",
  "feat.privacy.what0t": "Os dados ficam no dispositivo",
  "feat.privacy.what0d": "Histórico de chat, memória de quatro camadas, biblioteca de habilidades, artefatos de projeto todos como arquivos locais / DB local.",
  "feat.privacy.what1t": "Usável offline",
  "feat.privacy.what1d": "Com modelos locais, chat, ops de arquivos e orquestração de fluxos não precisam de rede.",
  "feat.privacy.what2t": "A nuvem é sua escolha",
  "feat.privacy.what2d": "Só quando você escolhe modelos na nuvem ou geração na nuvem o conteúdo vai ao provedor.",
  "feat.privacy.what3t": "Limpeza num clique",
  "feat.privacy.what3d": "«Limpeza de memória» pode apagar uma camada de memória ou deletar uma sessão — apagado de verdade.",
  "feat.privacy.what4t": "Não exige conta",
  "feat.privacy.what4d": "O grátis não força registro; as funções locais funcionam de fábrica.",
  "feat.privacy.step0": "Para tudo offline, simplesmente use modelos locais.",
  "feat.privacy.step1": "Para apagar registros: painel «Limpeza de memória».",
  "feat.privacy.step2": "Um chat parece sensível? Simplesmente não escolha modelo na nuvem.",
  "feat.privacy.tech0": "O armazenamento local usa SQLite e pastas locais, sem serviço na nuvem próprio.",
  "feat.privacy.tech1": "As chamadas na nuvem só vão via sua chave de provedor configurada, direto à API.",
  "feat.privacy.tech2": "As camadas de memória são cada uma apagáveis, evitando «apagar uma apaga todas».",
  "feat.privacy.shot": "Tudo no dispositivo, roda offline"
};
